"""I publish native products through a staged NanoISA-to-C tool pipeline."""
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
DRIVER = '''from "src_nano/compiler/native_product.nano" import publish_native_module
extern fn get_argc() -> int
extern fn get_argv(index: int) -> string
fn main() -> int {
    if (!= (get_argc) 5) { return 0 }
    if (and (!= (get_argv 4) "native") (!= (get_argv 4) "c")) { return 0 }
    return (publish_native_module (get_argv 1) (get_argv 2) (get_argv 3)
        (getenv "CC") "-O0" "" (== (get_argv 4) "c")
        (== (getenv "KEEP_C") "1") false false)
}
shadow main { assert (== (main) 0) }
'''


class NativeProductPipeline(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.temporary = tempfile.TemporaryDirectory(prefix="nano-native-product-")
        cls.addClassCleanup(cls.temporary.cleanup)
        cls.work = Path(cls.temporary.name)
        cls.cc = os.environ.get("NANO_NATIVE_TEST_CC") or shutil.which("cc")
        cls.env = {**os.environ, "CC": shlex.quote(cls.cc), "KEEP_C": "0",
                   "ASAN_OPTIONS": "detect_leaks=1"}
        cls.env.pop("NANO_NVM2C", None)
        source = cls.work / "driver.nano"
        source.write_text(DRIVER)
        cls.module = cls.work / "driver.nvm"
        generated = cls.work / "driver.c"
        cls.native = cls.work / "driver"
        producer = os.environ.get("NANO_PIPELINE_PRODUCER", "nano_virt")
        cls.checked([ROOT / "bin" / producer, source, "--emit-nvm", "-o", cls.module])
        cls.checked([ROOT / "bin/nvm2c", cls.module, "-o", generated])
        cls.checked([cls.cc, "-std=c11", "-O0", "-Wall", "-Wextra", "-Werror",
                     "-fsanitize=address,undefined", "-fno-sanitize-recover=all",
                     generated, ROOT / "bin/nano_aot_runtime.o", "-lm", "-o", cls.native])
        program = cls.work / "program.nano"
        program.write_text('fn main() -> int { assert (== (+ 19 23) 42) '
                           '(println "native product") return 0 }\n'
                           'shadow main { assert (== (+ 19 23) 42) }\n')
        cls.product_module = cls.work / "program.nvm"
        cls.checked([ROOT / "bin/nano_virt", program, "--emit-nvm", "-o", cls.product_module])

    @classmethod
    def checked(cls, args, **kwargs):
        result = subprocess.run(list(map(str, args)), cwd=ROOT,
                                capture_output=True, text=True, timeout=90,
                                env=kwargs.pop("env", cls.env), **kwargs)
        if result.returncode:
            raise AssertionError(result.stdout + result.stderr)
        return result

    def invoke(self, route, output, mode="native", env=None, module=None):
        command = ([ROOT / "bin/nano_vm", self.module, "--"] if route == "vm"
                   else [self.native])
        return subprocess.run(list(map(str, command + [module or self.product_module,
                              output, ROOT, mode])), cwd=ROOT, capture_output=True,
                              text=True, timeout=90, env=env or self.env)

    def test_native_and_source_outputs_from_vm_and_native_drivers(self):
        for route in ("vm", "native"):
            with self.subTest(route=route), tempfile.TemporaryDirectory(dir=self.work) as tmp:
                directory = Path(tmp)
                output = directory / "program ' with spaces"
                output.write_text("prior")
                result = self.invoke(route, output)
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                self.assertEqual(self.checked([output], env={**self.env, "NANO_VM": "/absent"}).stdout,
                                 "native product\n")
                source = directory / "source ' with spaces.c"
                result = self.invoke(route, source, "c", env={**self.env, "CC": "false"})
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                self.assertIn("Generated by nvm2c", source.read_text())
                self.assertEqual(list(directory.glob(".nano-native.*")), [])

    def test_declared_host_import_executes_in_native_product(self):
        with tempfile.TemporaryDirectory(dir=self.work) as tmp:
            directory = Path(tmp)
            data = directory / "host ' input"
            data.write_text("declared host")
            source = directory / "host.nano"
            source.write_text('module "std/fs.nano" as fs\n'
                              'fn main() -> int { (println (fs.read ' + json.dumps(str(data)) +
                              ')) return 0 }\nshadow main { assert (== (fs.read ' +
                              json.dumps(str(data)) + ') "declared host") }\n')
            module = directory / "host.nvm"
            self.checked([ROOT / "bin/nano_virt", source, "--emit-nvm", "-o", module])
            for route in ("vm", "native"):
                with self.subTest(route=route):
                    output = directory / route
                    result = self.invoke(route, output, module=module)
                    self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                    self.assertEqual(self.checked([output], env={**self.env, "NANO_VM": "/absent"}).stdout,
                                     "declared host\n")
            self.assertEqual(list(directory.glob(".nano-native.*")), [])

    def test_failed_tools_preserve_output_and_remove_staging(self):
        for route in ("vm", "native"):
            for tool in ("translator", "compiler"):
                with self.subTest(route=route, tool=tool), tempfile.TemporaryDirectory(dir=self.work) as tmp:
                    directory = Path(tmp)
                    output = directory / "prior ' output"
                    output.write_bytes(b"prior output\x00")
                    failed = directory / "failed ' tool"
                    body = ('printf bad > "$3"\n' if tool == "translator" else
                            'for last; do :; done\nprintf bad > "$last"\n')
                    failed.write_text("#!/bin/sh\n" + body + "exit 9\n")
                    failed.chmod(0o755)
                    env = {**self.env}
                    env["NANO_NVM2C" if tool == "translator" else "CC"] = (
                        str(failed) if tool == "translator" else shlex.quote(str(failed)))
                    result = self.invoke(route, output, env=env)
                    self.assertNotEqual(result.returncode, 0)
                    self.assertEqual(output.read_bytes(), b"prior output\x00")
                    self.assertEqual(list(directory.glob(".nano-native.*")), [])

    def test_invalid_module_and_directory_destination_preserve_prior_state(self):
        for route in ("vm", "native"):
            with self.subTest(route=route), tempfile.TemporaryDirectory(dir=self.work) as tmp:
                directory = Path(tmp)
                invalid = directory / "invalid.nvm"
                invalid.write_bytes(b"not a module")
                output = directory / "output"
                output.write_text("prior")
                self.assertNotEqual(self.invoke(route, output, module=invalid).returncode, 0)
                self.assertEqual(output.read_text(), "prior")
                destination = directory / "destination"
                destination.mkdir()
                (destination / "sentinel").write_text("prior")
                self.assertNotEqual(self.invoke(route, destination).returncode, 0)
                self.assertEqual([p.name for p in destination.iterdir()], ["sentinel"])
                self.assertEqual(list(directory.glob(".nano-native.*")), [])

    def test_keep_c_retains_only_source_after_native_publication(self):
        with tempfile.TemporaryDirectory(dir=self.work) as tmp:
            directory = Path(tmp)
            output = directory / "output"
            result = self.invoke("native", output, env={**self.env, "KEEP_C": "1"})
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            stages = list(directory.glob(".nano-native.*"))
            self.assertEqual(len(stages), 1)
            self.assertEqual([p.name for p in stages[0].iterdir()], ["program.c"])
            self.assertIn("Generated by nvm2c", (stages[0] / "program.c").read_text())
            self.assertEqual(self.checked([output]).stdout, "native product\n")


if __name__ == "__main__":
    unittest.main()
