"""I retain actual byte conversion programs and each backend execution."""
import json
import os
from pathlib import Path
import shlex
import shutil
import signal
import sys
import tempfile
import unittest

from tests import test_file_cyclic

ROOT = Path(__file__).resolve().parents[1]


class CastU8Backends(unittest.TestCase):
    command = test_file_cyclic.FileCyclic.command

    def setUp(self):
        self.artifacts = Path(tempfile.mkdtemp(prefix='nano-cast-u8-backends-'))
        print(f'I retain generated byte conversion artifacts at {self.artifacts}', flush=True)
        self.cc = shlex.split(os.environ.get('NANO_NATIVE_TEST_CC', 'cc'))
        self.flags = shlex.split(os.environ.get('NANO_CAST_U8_NATIVE_FLAGS', ''))
        for tool in ('llvm-as', 'lli', 'opt', 'llc', 'wasm-ld', 'wasmtime', 'node', self.cc[0]):
            self.assertIsNotNone(shutil.which(tool), tool + ' is required')
        (self.artifacts / 'selection.json').write_text(json.dumps({
            'cc': self.cc, 'flags': self.flags,
        }, indent=2) + '\n')
        self.serial = 0

    def run_actual(self, args):
        self.serial += 1
        return self.command(f'{self.serial:03d}', list(map(str, args)))

    def run_trap(self, args, expected_code=None):
        """I retain the actual child result; my supervisor owns its process group."""
        result = self.artifacts / f'trap-{self.serial + 1:03d}.json'
        wrapper = ('import json,subprocess,sys\n'
            'p=subprocess.run(sys.argv[2:],capture_output=True,timeout=120)\n'
            'open(sys.argv[1],"w").write(json.dumps({"returncode":p.returncode,'
            '"stdout":p.stdout.decode("utf-8","replace"),'
            '"stderr":p.stderr.decode("utf-8","replace")}))\n'
            'sys.exit(0 if p.returncode else 1)\n')
        self.run_actual([sys.executable, '-c', wrapper, result, *args])
        observed = json.loads(result.read_text())
        if expected_code is not None:
            self.assertEqual(observed['returncode'], expected_code, observed)
        self.assertNotIn('Sanitizer', observed['stderr'])
        self.assertNotIn('runtime error:', observed['stderr'])
        return observed

    @staticmethod
    def exact_byte(expected):
        return (f'DUP\nTYPE_CHECK 2\nASSERT\nDUP\nTYPE_CHECK 1\nBOOL_NOT\nASSERT\n'
                f'CAST_INT\nPUSH_I64 {expected}\nI64_EQ\nASSERT\n')

    @staticmethod
    def program(body, suffix=''):
        return ('.entry main\n.function main 0 2 0 int 1\n' + body +
                'PUSH_I64 0\nRET\n.end\n' + suffix)

    def compare(self, text):
        asm, module = self.artifacts / 'input.nasm', self.artifacts / 'input.nvm'
        asm.write_text(text)
        self.run_actual([ROOT / 'bin/nanoisa', 'asm', asm, '-o', module])
        self.run_actual([ROOT / 'bin/nano_vm', '--verify-only', module])
        self.run_actual([ROOT / 'bin/nano_vm', module])
        source, ir = self.artifacts / 'program.c', self.artifacts / 'program.ll'
        self.run_actual([ROOT / 'bin/nvm2c', module, '-o', source])
        self.run_actual([ROOT / 'bin/nvm2llvm', module, '-o', ir])
        self.run_actual(['llvm-as', ir, '-o', self.artifacts / 'original.bc'])
        self.run_actual(['lli', ir])
        for optimization in ('O0', 'O2'):
            executable = self.artifacts / ('native-' + optimization)
            self.run_actual([*self.cc, *self.flags, '-std=c11', '-' + optimization,
                             '-Wall', '-Wextra', '-Werror', source, '-o', executable])
            self.run_actual([executable])
            optimized = self.artifacts / (optimization + '.bc')
            self.run_actual(['opt', '-passes=default<' + optimization + '>', ir, '-o', optimized])
            self.run_actual(['opt', '-passes=verify', '-disable-output', optimized])
            self.run_actual(['lli', optimized])
            obj = self.artifacts / (optimization + '.o')
            machine = self.artifacts / ('llvm-native-' + optimization)
            self.run_actual(['llc', '-filetype=obj', '-relocation-model=pic', optimized, '-o', obj])
            self.run_actual([*self.cc, obj, '-o', machine])
            self.run_actual([machine])
        wasm = self.artifacts / 'program.wasm'
        self.run_actual([ROOT / 'bin/nvm2wasm', module, '-o', wasm])
        self.assertEqual(self.run_actual(['wasmtime', 'run', '--invoke', 'nano_entry', wasm]), b'0\n')
        script = self.artifacts / 'run.js'
        script.write_text('const fs=require("fs");\n'
            'const m=new WebAssembly.Module(fs.readFileSync(process.argv[2]));\n'
            'if(WebAssembly.Module.imports(m).length) throw Error("imports");\n'
            'if(new WebAssembly.Instance(m).exports.nano_entry()!==0) throw Error("result");\n')
        self.run_actual(['node', script, wasm])

    def test_integer_extrema_without_byte_literal(self):
        body = ''
        for value in (0, 1, 127, 128, 200, 201, 255, 256, 257, -1, -256,
                      -9223372036854775808, 9223372036854775807):
            body += f'PUSH_I64 {value}\nCAST_U8\n' + self.exact_byte(value % 256)
        self.compare(self.program(body))

    def test_all_byte_identities(self):
        body = ''.join(f'PUSH_U8 {value}\nCAST_U8\n' + self.exact_byte(value)
                       for value in range(256))
        self.compare(self.program(body))

    def test_calls_locals_globals_and_once_only_operand(self):
        body = ('PUSH_I64 0\nSTORE_GLOBAL 0\nCALL tick\nCAST_U8\nSTORE_LOCAL 0\n'
                'LOAD_LOCAL 0\nCALL relay\nSTORE_GLOBAL 1\nLOAD_GLOBAL 1\n' +
                self.exact_byte(1) + 'LOAD_GLOBAL 0\nPUSH_I64 1\nI64_EQ\nASSERT\n'
                'PUSH_I64 -1\nCAST_U8\nSTORE_LOCAL 0\nLOAD_LOCAL 0\n' + self.exact_byte(255))
        suffix = ('.function tick 0 0 0 int 1\nLOAD_GLOBAL 0\nPUSH_I64 1\nI64_ADD\n'
                  'DUP\nSTORE_GLOBAL 0\nPUSH_I64 256\nI64_ADD\nRET\n.end\n'
                  '.function relay 1 1 0 u8 1\n.parameters relay u8\nLOAD_LOCAL 0\nCAST_U8\nRET\n.end\n')
        self.compare(self.program(body, suffix))

    def test_integer_byte_branch_join_before_conversion(self):
        suffix = ('.function choose 1 1 0 u8 1\n.parameters choose bool\n'
                  'LOAD_LOCAL 0\nJMP_FALSE byte\nPUSH_I64 -1\nJMP joined\n'
                  'byte:\nPUSH_U8 128\njoined:\nCAST_U8\nRET\n.end\n')
        body = ('PUSH_BOOL 1\nCALL choose\n' + self.exact_byte(255) +
                'PUSH_BOOL 0\nCALL choose\n' + self.exact_byte(128))
        self.compare(self.program(body, suffix))

    def test_verified_wrong_tags_and_managed_cleanup(self):
        base = self.artifacts
        for name, operand in (
            ('bool', 'PUSH_BOOL 1'), ('float', 'PUSH_F64 1.5'),
            ('void', 'PUSH_VOID'), ('enum', 'ENUM_VAL 0 1'),
            ('string', 'LOAD_LOCAL 0'), ('array', 'ARR_NEW 1'),
        ):
            with self.subTest(tag=name):
                self.artifacts = base / name
                self.artifacts.mkdir()
                # I retain one independent global alias while a callee consumes
                # its argument. The operand type is unknown to verification.
                text = ('.types 0 1 0\n.string a "a\\x00z"\n' + self.program(
                    'PUSH_STR a\nPUSH_STR a\nSTR_CONCAT\nDUP\nSTORE_LOCAL 0\n'
                    'STORE_GLOBAL 0\n' + operand + '\nCALL fail\nPOP\n',
                    '.function fail 1 1 0 u8 1\nLOAD_LOCAL 0\nCAST_U8\nRET\n.end\n'))
                asm, module = self.artifacts / 'input.nasm', self.artifacts / 'input.nvm'
                asm.write_text(text)
                self.run_actual([ROOT / 'bin/nanoisa', 'asm', asm, '-o', module])
                self.run_actual([ROOT / 'bin/nano_vm', '--verify-only', module])
                self.run_trap([ROOT / 'bin/nano_vm', module])
                source = self.artifacts / 'native.c'
                self.run_actual([ROOT / 'bin/nvm2c', module, '-o', source])
                for optimization in ('O0', 'O2'):
                    exe = self.artifacts / ('native-' + optimization)
                    self.run_actual([*self.cc, *self.flags, '-' + optimization, '-std=c11',
                        '-Wall', '-Wextra', '-Werror', source, '-o', exe])
                    observed = self.run_trap([exe], -signal.SIGABRT)
                    self.assertIn('I stopped at a native invariant', observed['stderr'])
                harness = self.artifacts / 'harness.c'
                harness.write_text('#include <stdint.h>\n'
                    'extern uint64_t nano_try_entry(void),nms_module_live_objects(void),nms_module_live_bytes(void);\n'
                    'extern int nano_dispose(void);\n'
                    'int main(void){for(int i=0;i<16;i++){'
                    'if(nano_try_entry()!=((uint64_t)1<<32)||nms_module_live_objects()!=1||'
                    'nms_module_live_bytes()!=6)return 1;}'
                    'if(nano_dispose()||nms_module_live_objects()||nms_module_live_bytes())return 2;return 0;}\n')
                for target in ('native', 'wasm32'):
                    original = self.artifacts / (target + '.ll')
                    self.run_actual([ROOT / 'bin/nvm2llvm', module, '--entry-name', 'nano_entry',
                        '--runtime-target', target, '-o', original])
                    for optimization in ('O0', 'O2'):
                        ir = self.artifacts / (target + '-' + optimization + '.ll')
                        self.run_actual(['opt', '-S', '-passes=default<' + optimization + '>', original, '-o', ir])
                        self.run_actual(['opt', '-passes=verify', '-disable-output', ir])
                        if target == 'native':
                            obj = ir.with_suffix('.o')
                            exe = ir.with_suffix('.exe')
                            self.run_actual(['llc', '-filetype=obj', '-relocation-model=pic', ir, '-o', obj])
                            self.run_actual([*self.cc, *self.flags, harness, obj, '-o', exe])
                            self.run_actual([exe])
                        else:
                            wasm = ir.with_suffix('.wasm')
                            self.run_actual(['clang', '--target=wasm32-unknown-unknown', '-nostdlib', ir,
                                '-Wl,--no-entry', '-Wl,--export=nano_try_entry', '-Wl,--export=nano_dispose',
                                '-Wl,--export=nms_module_live_objects', '-Wl,--export=nms_module_live_bytes',
                                '-o', wasm])
                            self.assertEqual(self.run_actual(['wasmtime', 'run', '--invoke', 'nano_try_entry', wasm]),
                                             b'4294967296\n')
                            script = self.artifacts / ('managed-' + optimization + '.js')
                            script.write_text('const fs=require("fs");'
                                'const m=new WebAssembly.Module(fs.readFileSync(process.argv[2]));'
                                'function check(v){if(!v)throw Error("ownership");}'
                                'check(WebAssembly.Module.imports(m).length===0);'
                                'const e=new WebAssembly.Instance(m).exports;'
                                'for(let i=0;i<16;i++){check(e.nano_try_entry()===(1n<<32n));'
                                'check(e.nms_module_live_objects()===1n);check(e.nms_module_live_bytes()===6n);}'
                                'check(e.nano_dispose()===0);check(e.nms_module_live_objects()===0n);'
                                'check(e.nms_module_live_bytes()===0n);')
                            self.run_actual(['node', script, wasm])
                self.artifacts = base


if __name__ == '__main__':
    unittest.main()
