"""I check issue lifecycle and offline behavior without touching real issues."""
import argparse
import contextlib
import importlib.util
import io
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('nanolang_autogithub', ROOT / 'scripts/autogithub.py')
tracker = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = tracker
spec.loader.exec_module(tracker)


class GitHubTracking(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.log = Path(self.tmp.name) / 'failure.log'
        self.log.write_text('literal `command` and $(never-run)\nsecond line\n')
        self.failure = tracker.Failure('test_runtime', 'scope', (self.log,), 'abc123', 'Runtime failed')
        self.args = argparse.Namespace(mode='per', max_new=10, job_name='unit', close_on_success=True)
        self.calls = []
        self.pages = [[]]
        self.patch = patch.object(tracker, '_run', side_effect=self.run_cli)
        self.patch.start()
        self.addCleanup(self.patch.stop)

    def run_cli(self, cmd, **kwargs):
        self.assertNotIn('mac', cmd)
        body = Path(cmd[cmd.index('--body-file') + 1]).read_text() if '--body-file' in cmd else None
        self.calls.append((cmd, body))
        if cmd[:2] == ['git', 'rev-parse']:
            output = 'branch\n' if '--abbrev-ref' in cmd else 'abcde\n'
        elif cmd[1] == 'api':
            self.assertIn('--paginate', cmd)
            self.assertIn('--slurp', cmd)
            output = json.dumps(self.pages)
        elif cmd[1:3] == ['issue', 'create']:
            output = 'https://github.com/jordanhubbard/nanolang/issues/123\n'
        else:
            self.assertEqual(cmd[1], 'issue')
            self.assertIn('--repo', cmd)
            output = ''
        return subprocess.CompletedProcess(cmd, 0, output, '')

    def managed(self, state='open', summary=False):
        title = '[autotest][summary] make test (branch=branch, job=unit)' if summary else '[autotest] Runtime failed: scope'
        return {'number': 22, 'title': title, 'state': state,
                'body': 'Autogenerated by scripts/autogithub.py\nFingerprint: abc123'}

    def mutations(self):
        return [(cmd[2], body) for cmd, body in self.calls if cmd[1:2] == ['issue']]

    def test_paginated_issues_exclude_pull_requests(self):
        self.pages = [[self.managed()], [{'number': 23, 'state': 'open', 'pull_request': {}}]]
        self.assertEqual([i['number'] for i in tracker._load_issues()], [22])
        self.pages = {'unexpected': []}
        with self.assertRaises(ValueError):
            tracker._load_issues()

    def test_create_preserves_literal_multiline_body_and_deduplicates_run(self):
        tracker._report('make test', 2, [self.failure, self.failure], self.log, self.args)
        self.assertEqual([v for v, _ in self.mutations()], ['create', 'comment'])
        self.assertIn(self.log.read_text(), self.mutations()[0][1])
        self.assertIn('Fingerprint: abc123', self.mutations()[0][1])

    def test_recurrence_reopens_closed_issue_without_creating_duplicate(self):
        self.pages = [[self.managed('closed')]]
        tracker._report('make test', 2, [self.failure], self.log, self.args)
        self.assertEqual([v for v, _ in self.mutations()], ['reopen', 'comment'])

    def test_fingerprint_finds_issue_after_title_change(self):
        issue = self.managed(); issue['title'] = 'renamed by maintainer'
        self.pages = [[issue]]
        tracker._report('make test', 2, [self.failure], self.log, self.args)
        self.assertEqual([v for v, _ in self.mutations()], ['comment'])

    def test_success_never_creates_summary_and_closes_only_managed_issue(self):
        self.args.mode = 'summary'
        tracker._report('make test', 0, [], self.log, self.args)
        self.assertEqual(self.mutations(), [])
        issue = self.managed(summary=True); issue['body'] = 'Human tracking'
        self.pages = [[issue]]
        tracker._report('make test', 0, [], self.log, self.args)
        self.assertEqual(self.mutations(), [])
        self.pages = [[self.managed(summary=True)]]
        tracker._report('make test', 0, [], self.log, self.args)
        self.assertEqual([v for v, _ in self.mutations()], ['comment', 'close'])

    def test_summary_failure_reopens_and_records_nonzero_exit(self):
        self.args.mode = 'summary'; self.pages = [[self.managed('closed', summary=True)]]
        tracker._report('make test', 7, [self.failure], self.log, self.args)
        self.assertEqual([v for v, _ in self.mutations()], ['reopen', 'comment'])
        self.assertIn('Exit: 7', self.mutations()[-1][1])

    def test_new_issue_limit_does_not_suppress_existing_updates(self):
        self.args.max_new = 0
        with contextlib.redirect_stderr(io.StringIO()):
            tracker._report('make test', 2, [self.failure], self.log, self.args)
        self.assertEqual(self.mutations(), [])
        self.pages = [[self.managed()]]
        tracker._report('make test', 2, [self.failure], self.log, self.args)
        self.assertEqual([v for v, _ in self.mutations()], ['comment'])

    def test_summary_zero_limit_leaves_failure_unfiled(self):
        self.args.mode = 'summary'; self.args.max_new = 0
        with contextlib.redirect_stderr(io.StringIO()) as stderr:
            tracker._report('make test', 2, [self.failure], self.log, self.args)
        self.assertEqual(self.mutations(), [])
        self.assertIn('unfiled failure', stderr.getvalue())

    def test_offline_preserves_failure_and_still_runs_examples(self):
        for error in [FileNotFoundError('gh'), RuntimeError('offline'), ValueError('bad JSON')]:
            with self.subTest(error=error), patch.object(tracker, '_run_tests', return_value=7), \
                 patch.object(tracker, '_run_examples', return_value=0) as examples, \
                 patch.object(tracker, '_collect_test_failures', return_value=[]), \
                 patch.object(tracker, '_load_issues', side_effect=error), \
                 contextlib.redirect_stderr(io.StringIO()) as stderr:
                self.assertEqual(tracker.main(['--tests', '--examples']), 7)
                examples.assert_called_once()
                self.assertIn('retain test exit 7', stderr.getvalue())

    def test_dry_run_never_contacts_github(self):
        with patch.object(tracker, '_load_issues', side_effect=AssertionError('network')), \
             patch.object(tracker, 'TEST_OUTPUT_DIR', Path(self.tmp.name)), \
             contextlib.redirect_stdout(io.StringIO()):
            self.assertEqual(tracker.main(['--tests', '--examples', '--mode', 'summary', '--dry-run']), 0)
        self.assertEqual(self.calls, [])

    def test_legacy_entry_point_routes_to_github_without_network_in_dry_run(self):
        result = subprocess.run([sys.executable, ROOT / 'scripts/automac.py', '--tests', '--dry-run'],
                                cwd=ROOT, text=True, capture_output=True, timeout=10)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn('make test-impl', result.stdout)


if __name__ == '__main__':
    unittest.main()
