"""I make the unqualified compiler product a verified NanoISA module."""
import os
from pathlib import Path
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
DRIVER = Path(os.environ.get('NANOLANG_SELFHOST_COMPILER', ROOT / 'bin/nanoc_stage2'))

class DefaultNanoisaProduct(unittest.TestCase):
    def run_driver(self, work, *args, success=True):
        env = {**os.environ, 'NANO_VM': str(ROOT / 'bin/nano_vm'),
               'NANO_NVM2C': str(ROOT / 'bin/nvm2c'),
               'NANO_AOT_RUNTIME': str(ROOT / 'bin/nano_aot_runtime.o')}
        result = subprocess.run([str(DRIVER), *map(str,args)], cwd=work, env=env,
                                capture_output=True, timeout=120)
        self.assertEqual(result.returncode == 0, success, result.stdout + result.stderr)
        return result

    def source(self, work, name='program.nano'):
        source = work / name
        source.write_text('fn main() -> int { (println "default-bytecode") return 0 }\n'
                          'shadow main { assert true }\n')
        return source

    def test_default_and_explicit_bytecode_derive_sibling(self):
        with tempfile.TemporaryDirectory(prefix='nano default ') as tmp:
            work = Path(tmp)
            for name, options in [('program.nano', ()), ('.hidden', ()),
                                  ('plain', ('--emit-nvm',))]:
                with self.subTest(name=name):
                    source = self.source(work, name)
                    before = source.read_bytes()
                    self.run_driver(work, source, *options)
                    output = source.with_suffix('.nvm') if source.suffix else work / (name + '.nvm')
                    self.assertEqual(output.read_bytes()[:4], b'NVM\x02')
                    result = subprocess.run([ROOT / 'bin/nano_vm', output], capture_output=True)
                    self.assertEqual(result.returncode, 0, result.stderr)
                    self.assertEqual(result.stdout, b'default-bytecode\n')
                    self.assertEqual(source.read_bytes(), before)
                    self.assertFalse((work / 'a.out').exists())

    def test_explicit_native_and_c_products(self):
        with tempfile.TemporaryDirectory(prefix='nano explicit ') as tmp:
            work = Path(tmp); source = self.source(work)
            self.run_driver(work, source, '--target', 'native')
            self.assertEqual(subprocess.check_output([work / 'a.out']), b'default-bytecode\n')
            binary = work / 'named'
            self.run_driver(work, source, '-o', binary)
            self.assertEqual(subprocess.check_output([binary]), b'default-bytecode\n')
            self.run_driver(work, source, '--target', 'c')
            self.assertIn('Generated by nvm2c', source.with_suffix('.c').read_text())

    def test_conflicting_target_preserves_previous_output(self):
        with tempfile.TemporaryDirectory(prefix='nano option-conflict-') as tmp:
            work=Path(tmp); source=self.source(work); output=work/'prior'
            output.write_bytes(b'previous artifact')
            for target in ('c', 'native'):
                self.run_driver(work, source, '--emit-nvm', '--target', target, '-o', output, success=False)
                self.assertEqual(output.read_bytes(), b'previous artifact')

    def test_derived_output_cannot_replace_source(self):
        with tempfile.TemporaryDirectory(prefix='nano source-preservation-') as tmp:
            work=Path(tmp); source=self.source(work, 'program.nvm'); before=source.read_bytes()
            self.run_driver(work, source, success=False)
            self.assertEqual(source.read_bytes(), before)

if __name__ == '__main__': unittest.main()
