"""I keep the self-hosted product driver on one verified NanoISA path."""
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
COMPILER = Path(os.environ.get("NANOLANG_SELFHOST_COMPILER", ROOT / "bin/nanoc_stage2")).resolve()
SOURCE = 'fn main() -> int { (println "one module") return 0 }\nshadow main { assert (== (+ 19 23) 42) }\n'


class SelfhostNanoisaProduct(unittest.TestCase):
    def invoke(self, args, **kwargs):
        env = {**os.environ, "NANOLANG_ROOT": str(ROOT), "NANO_CC": "/bin/false"}
        env.update(kwargs.pop("env", {}))
        return subprocess.run([str(COMPILER), *map(str, args)], cwd=ROOT, env=env,
                              capture_output=True, text=True, timeout=90, **kwargs)

    def test_default_output_is_verified_executable_module(self):
        with tempfile.TemporaryDirectory(prefix="nano-default-module-") as tmp:
            source = Path(tmp) / "input.nano"
            source.write_text(SOURCE)
            result = self.invoke([source])
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            module = source.with_suffix(".nvm")
            verified = subprocess.run([ROOT / "bin/nano_vm", "--verify-only", module],
                                      capture_output=True, text=True, timeout=10)
            self.assertEqual(verified.returncode, 0, verified.stderr)
            executed = subprocess.run([ROOT / "bin/nano_vm", module],
                                      capture_output=True, text=True, timeout=10)
            self.assertEqual(executed.returncode, 0, executed.stderr)
            self.assertEqual(executed.stdout, "one module\n")
            self.assertEqual(source.read_text(), SOURCE)
            self.assertEqual(sorted(p.name for p in Path(tmp).iterdir()), ["input.nano", "input.nvm"])

    def test_failed_shadows_precede_translation_and_preserve_output(self):
        for mode in ([], ["--emit-nvm"]):
            with self.subTest(mode=mode), tempfile.TemporaryDirectory(prefix="nano-shadow-product-") as tmp:
                directory = Path(tmp)
                source = directory / "input.nano"
                source.write_text(SOURCE.replace('assert (== (+ 19 23) 42)', 'assert false'))
                output = directory / "prior"
                output.write_bytes(b"prior output\x00")
                marker = directory / "translated"
                tool = directory / "translator"
                tool.write_text('#!/bin/sh\nprintf called > "' + str(marker) + '"\nexit 9\n')
                tool.chmod(0o755)
                result = self.invoke([source, "-o", output, *mode], env={"NANO_NVM2C": str(tool)})
                self.assertNotEqual(result.returncode, 0)
                self.assertIn("failed shadows", result.stdout + result.stderr)
                self.assertEqual(output.read_bytes(), b"prior output\x00")
                self.assertFalse(marker.exists())
                self.assertFalse(list(directory.glob(".nano-native.*")))

    def test_source_only_translation_does_not_execute_shadows(self):
        with tempfile.TemporaryDirectory(prefix="nano-source-product-") as tmp:
            source = Path(tmp) / "input.nano"
            source.write_text(SOURCE.replace('assert (== (+ 19 23) 42)', 'assert false'))
            output = source.with_suffix(".c")
            result = self.invoke([source, "--target", "c"])
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertIn("Generated by nvm2c", output.read_text())

    def test_installed_driver_discovers_tools_outside_checkout(self):
        with tempfile.TemporaryDirectory(prefix="nano-installed-", dir=ROOT / "bin") as installed:
            executable = Path(installed) / "nanoc-probe"
            shutil.copyfile(COMPILER, executable)
            executable.chmod(0o755)
            for via_path in (False, True):
                with self.subTest(via_path=via_path), tempfile.TemporaryDirectory(prefix="nano-client-") as tmp:
                    source = Path(tmp) / "input.nano"
                    source.write_text(SOURCE)
                    env = {**os.environ, "PATH": installed + os.pathsep + os.environ["PATH"],
                           "NANO_CC": "/bin/false"}
                    env.pop("NANOLANG_ROOT", None)
                    env.pop("NANO_NVM2C", None)
                    command = "nanoc-probe" if via_path else str(executable)
                    result = subprocess.run([command, str(source), "--target", "c"],
                                            cwd=tmp, env=env, capture_output=True, text=True, timeout=90)
                    self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                    self.assertIn("Generated by nvm2c", source.with_suffix(".c").read_text())


if __name__ == "__main__":
    unittest.main()
