#ifndef _GNU_SOURCE
#define _GNU_SOURCE 1
#endif
#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE 1
#endif
/* Generated by nvm2c from NanoISA. Not a VM wrapper. */
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
/* I preserve invariant termination while naming its generated source. */
#define NVM2C_ABORT() do { fprintf(stderr, "I stopped at a native invariant in %s at generated C line %d.\n", __func__, __LINE__); abort(); } while (0)
/* I reconstruct wrapped bits without an out-of-range signed cast. */
static inline int64_t ni64_from_bits(uint64_t bits) {
    return bits <= INT64_MAX ? (int64_t)bits : -INT64_C(1) - (int64_t)(UINT64_MAX - bits);
}
#include <stdio.h>
static inline int64_t nf64_to_i64(double value) {
    if (!(value >= -0x1p63 && value < 0x1p63)) {
        fputs("I cannot convert this float to int: I require a finite value in [-2^63, 2^63).\n", stderr);
        exit(EXIT_FAILURE);
    }
    return (int64_t)value;
}
#include <string.h>
static inline double nf64_from_bits(uint64_t bits) {
    double value; memcpy(&value, &bits, sizeof value); return value;
}
#include <stdio.h>
#ifndef NANOLANG_BINARY64_FORMAT_H
#define NANOLANG_BINARY64_FORMAT_H
#include <float.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#if FLT_RADIX != 2 || DBL_MANT_DIG != 53 || DBL_MAX_EXP != 1024 || DBL_MIN_EXP != -1021
#error "I require binary64 formatting storage."
#endif
typedef char nano_rt_f64_format_storage[(sizeof(double) == 8 && sizeof(uint64_t) == 8) ? 1 : -1]; static inline const char *nano_rt_f64_nonfinite(double value) { uint64_t bits; __builtin___memcpy_chk (&bits, &value, sizeof bits, __builtin_object_size (&bits, 0)); if ((bits & (0x7ff0000000000000ULL)) != (0x7ff0000000000000ULL)) return ((void*)0); if (bits & (0x000fffffffffffffULL)) return bits >> 63 ? "-nan" : "nan"; return bits >> 63 ? "-inf" : "inf"; } static inline int nano_rt_f64_format(char *out, size_t size, double value) { const char *special = nano_rt_f64_nonfinite(value); return special ? __builtin___snprintf_chk (out, size, 0, __builtin_object_size (out, 2 > 1 ? 1 : 0), "%s", special) : __builtin___snprintf_chk (out, size, 0, __builtin_object_size (out, 2 > 1 ? 1 : 0), "%g", value); } static inline int nano_rt_f64_print(FILE *out, double value) { const char *special = nano_rt_f64_nonfinite(value); return special ? fprintf(out, "%s", special) : fprintf(out, "%g", value); }
#endif
static inline void nf64_print(double value) {
    const char *special = nano_rt_f64_nonfinite(value);
    if (special) fputs(special, stdout);
    else if (value >= -1e15 && value <= 1e15 && value == (int64_t)value) printf("%.1f", value);
    else printf("%g", value);
}
#include <stdlib.h>
#include <string.h>

typedef struct nmap_s *nmap_t;
typedef struct { int64_t *data; size_t len; struct narr_owner *owner; } narr_s;
typedef narr_s *narr_t;
typedef struct { const char **data; size_t len; struct nsarr_owner *owner; } nsarr_s;
typedef nsarr_s *nsarr_t;
/* I canonicalize only scalar binary arithmetic results, never transported bits. */
#ifndef NANOLANG_BINARY64_ARITHMETIC_H
#define NANOLANG_BINARY64_ARITHMETIC_H
#include <float.h>
#include <stdint.h>
#include <string.h>

#if defined(__FAST_MATH__) || (defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__)
#error "I require ordinary IEEE arithmetic without fast-math."
#endif
#if FLT_RADIX != 2 || DBL_MANT_DIG != 53 || DBL_MAX_EXP != 1024 || DBL_MIN_EXP != -1021
#error "I require binary64 double arithmetic."
#endif
#if !defined(FLT_EVAL_METHOD) || FLT_EVAL_METHOD != 0
#error "I require operations evaluated in their binary64 type."
#endif
/* I retain a compile-time storage check in both C99 and C11 output. */
typedef char nano_rt_binary64_storage_guard[
    sizeof(double) == 8 && sizeof(uint64_t) == 8 ? 1 : -1];

/* I inspect a rounded result with integer operations, not another FP operation. */
static inline double nano_rt_f64_arithmetic_result(double value) {
    uint64_t bits;
    memcpy(&bits, &value, sizeof(bits));
    if ((bits & UINT64_C(0x7ff0000000000000)) == UINT64_C(0x7ff0000000000000) &&
        (bits & UINT64_C(0x000fffffffffffff)) != 0) {
        bits = UINT64_C(0x7ff8000000000000);
        memcpy(&value, &bits, sizeof(value));
    }
    return value;
}

/* Each volatile store/load is a binary64 rounding and noncontraction boundary. */
static inline double nano_rt_f64_add(double a, double b) {
    volatile double rounded = a + b;
    return nano_rt_f64_arithmetic_result(rounded);
}
static inline double nano_rt_f64_sub(double a, double b) {
    volatile double rounded = a - b;
    return nano_rt_f64_arithmetic_result(rounded);
}
static inline double nano_rt_f64_mul(double a, double b) {
    volatile double rounded = a * b;
    return nano_rt_f64_arithmetic_result(rounded);
}
static inline double nano_rt_f64_div(double a, double b) {
    uint64_t divisor;
    memcpy(&divisor, &b, sizeof(divisor));
    /* Either signed zero takes precedence even over a signaling NaN numerator. */
    if ((divisor & UINT64_C(0x7fffffffffffffff)) == 0) return 0.0;
    volatile double rounded = a / b;
    return nano_rt_f64_arithmetic_result(rounded);
}
#endif
typedef struct nrarr_s nrarr_s;
typedef nrarr_s *nrarr_t;
typedef struct nrec_s nrec_t;
struct nrec_s { int64_t f[1]; const char *s[1]; narr_t a[1]; nsarr_t sa[1]; nrarr_t ra[1]; const nrec_t *rec[1]; uint8_t k[1], vk[1]; uint16_t n, tag; uint8_t kind; };
struct nrarr_s { nrec_t *data; size_t len; struct nrarr_owner *owner; };

static int64_t nl_square(int64_t a0);
static int64_t nl_diamond(int64_t a0);
static double nl_scalars(int64_t a0, const char * a1, double a2);
static int64_t nl_multiple(void);
static int64_t nl_shadowed(int64_t a0);
static int64_t nl_inferred(void);
static int64_t nl_main(void);

static int64_t nl_square(int64_t a0) {
    (void)ni64_from_bits;
    int64_t l0 = a0;
    (void)l0;
    int64_t t[3] = {0}; (void)t;
    double f[1] = {0}; (void)f;
    const char *s[1] = {0}; (void)s;
    narr_t a[1] = {0}; (void)a;
    nsarr_t sa[1] = {0}; (void)sa;
    nrec_t *r = 0 ? calloc(0, sizeof *r) : NULL;
    if (0 && !r) NVM2C_ABORT();
    nrarr_t ra[1] = {0}; (void)ra;
    nmap_t m[1] = {0}; (void)m;
    int64_t nresult = {0};
    if (0) goto L_return;
    t[0] = l0;
    t[1] = l0;
    t[2] = ni64_from_bits((uint64_t)t[0] * (uint64_t)t[1]);
    nresult = t[2];
    goto L_return;
L_return:
    free(r);
    return nresult;
}

static int64_t nl_diamond(int64_t a0) {
    (void)ni64_from_bits;
    int64_t l0 = a0;
    (void)l0;
    int64_t l1 = 0;
    (void)l1;
    int64_t l2 = 0;
    (void)l2;
    int64_t l3 = 0;
    (void)l3;
    int64_t l4 = 0;
    (void)l4;
    int64_t t[14] = {0}; (void)t;
    double f[1] = {0}; (void)f;
    const char *s[1] = {0}; (void)s;
    narr_t a[1] = {0}; (void)a;
    nsarr_t sa[1] = {0}; (void)sa;
    nrec_t *r = 0 ? calloc(0, sizeof *r) : NULL;
    if (0 && !r) NVM2C_ABORT();
    nrarr_t ra[1] = {0}; (void)ra;
    nmap_t m[1] = {0}; (void)m;
    int64_t nresult = {0};
    if (0) goto L_return;
    t[0] = l0;
    t[1] = 1;
    if (!t[1]) NVM2C_ABORT();
    t[2] = l0;
    t[3] = 1LL;
    t[4] = ni64_from_bits((uint64_t)t[2] + (uint64_t)t[3]);
    l1 = t[4];
    t[5] = l1;
    t[6] = nl_square(t[5]);
    l2 = t[6];
    t[7] = l1;
    t[8] = l1;
    t[9] = ni64_from_bits((uint64_t)t[7] + (uint64_t)t[8]);
    l3 = t[9];
    t[10] = l2;
    t[11] = l3;
    t[12] = ni64_from_bits((uint64_t)t[10] + (uint64_t)t[11]);
    l4 = t[12];
    t[13] = l4;
    nresult = t[13];
    goto L_return;
L_return:
    free(r);
    return nresult;
}

static double nl_scalars(int64_t a0, const char * a1, double a2) {
    (void)ni64_from_bits;
    int64_t l0 = a0;
    (void)l0;
    const char * l1 = a1;
    (void)l1;
    double l2 = a2;
    (void)l2;
    double l3 = 0.0;
    (void)l3;
    double l4 = 0.0;
    (void)l4;
    int64_t l5 = 0;
    (void)l5;
    const char *l6 = "";
    (void)l6;
    int64_t l7 = 0;
    (void)l7;
    int64_t t[9] = {0}; (void)t;
    double f[6] = {0}; (void)f;
    const char *s[4] = {0}; (void)s;
    narr_t a[1] = {0}; (void)a;
    nsarr_t sa[1] = {0}; (void)sa;
    nrec_t *r = 0 ? calloc(0, sizeof *r) : NULL;
    if (0 && !r) NVM2C_ABORT();
    nrarr_t ra[1] = {0}; (void)ra;
    nmap_t m[1] = {0}; (void)m;
    double nresult = {0};
    if (0) goto L_return;
    t[0] = l0;
    t[1] = 1;
    if (!t[1]) NVM2C_ABORT();
    s[0] = l1;
    t[2] = 1;
    if (!t[2]) NVM2C_ABORT();
    f[0] = l2;
    t[3] = 1;
    if (!t[3]) NVM2C_ABORT();
    f[1] = l2;
    l3 = f[1];
    f[2] = l3;
    f[3] = nf64_from_bits(UINT64_C(0x3fe0000000000000));
    f[4] = nano_rt_f64_add(f[2], f[3]);
    l4 = f[4];
    t[4] = l0;
    l5 = t[4];
    s[1] = l1;
    l6 = s[1];
    t[5] = l5;
    t[6] = t[5];
    if (!t[6]) {
    goto L_69;
    }
    s[2] = l6;
    s[3] = l1;
    t[7] = (int64_t)(strcmp(s[2] ? s[2] : "", s[3] ? s[3] : "") == 0);
    {
    int64_t j0 = t[7];
    t[5] = j0;
    }
L_69: ;
    l7 = t[5];
    t[8] = l7;
    if (!t[8]) NVM2C_ABORT();
    f[5] = l4;
    nresult = f[5];
    goto L_return;
L_return:
    free(r);
    return nresult;
}

static int64_t nl_multiple(void) {
    (void)ni64_from_bits;
    int64_t l0 = 0;
    (void)l0;
    int64_t l1 = 0;
    (void)l1;
    int64_t l2 = 0;
    (void)l2;
    int64_t l3 = 0;
    (void)l3;
    int64_t t[17] = {0}; (void)t;
    double f[1] = {0}; (void)f;
    const char *s[1] = {0}; (void)s;
    narr_t a[1] = {0}; (void)a;
    nsarr_t sa[1] = {0}; (void)sa;
    nrec_t *r = 0 ? calloc(0, sizeof *r) : NULL;
    if (0 && !r) NVM2C_ABORT();
    nrarr_t ra[1] = {0}; (void)ra;
    nmap_t m[1] = {0}; (void)m;
    int64_t nresult = {0};
    if (0) goto L_return;
    t[0] = 4LL;
    l0 = t[0];
    t[1] = l0;
    t[2] = 1LL;
    t[3] = ni64_from_bits((uint64_t)t[1] + (uint64_t)t[2]);
    l1 = t[3];
    t[4] = 7LL;
    l2 = t[4];
    t[5] = l2;
    t[6] = 1LL;
    t[7] = ni64_from_bits((uint64_t)t[5] + (uint64_t)t[6]);
    l3 = t[7];
    t[8] = l1;
    t[9] = 5LL;
    t[10] = (t[8] == t[9]);
    if (!t[10]) NVM2C_ABORT();
    t[11] = l3;
    t[12] = 8LL;
    t[13] = (t[11] == t[12]);
    if (!t[13]) NVM2C_ABORT();
    t[14] = l1;
    t[15] = l3;
    t[16] = ni64_from_bits((uint64_t)t[14] + (uint64_t)t[15]);
    nresult = t[16];
    goto L_return;
L_return:
    free(r);
    return nresult;
}

static int64_t nl_shadowed(int64_t a0) {
    (void)ni64_from_bits;
    int64_t l0 = a0;
    (void)l0;
    int64_t l1 = 0;
    (void)l1;
    int64_t l2 = 0;
    (void)l2;
    int64_t l3 = 0;
    (void)l3;
    int64_t t[17] = {0}; (void)t;
    double f[1] = {0}; (void)f;
    const char *s[1] = {0}; (void)s;
    narr_t a[1] = {0}; (void)a;
    nsarr_t sa[1] = {0}; (void)sa;
    nrec_t *r = 0 ? calloc(0, sizeof *r) : NULL;
    if (0 && !r) NVM2C_ABORT();
    nrarr_t ra[1] = {0}; (void)ra;
    nmap_t m[1] = {0}; (void)m;
    int64_t nresult = {0};
    if (0) goto L_return;
    t[0] = l0;
    t[1] = 1;
    if (!t[1]) NVM2C_ABORT();
    t[2] = 99LL;
    l1 = t[2];
    t[3] = 1LL;
    if (!t[3]) {
    goto L_71;
    }
    t[4] = l0;
    t[5] = 1LL;
    t[6] = ni64_from_bits((uint64_t)t[4] + (uint64_t)t[5]);
    l2 = t[6];
    t[7] = l2;
    t[8] = 1LL;
    t[9] = ni64_from_bits((uint64_t)t[7] + (uint64_t)t[8]);
    l3 = t[9];
    t[10] = l3;
    t[11] = 4LL;
    t[12] = (t[10] == t[11]);
    if (!t[12]) NVM2C_ABORT();
    {
    }
L_71: ;
    t[13] = l1;
    t[14] = 99LL;
    t[15] = (t[13] == t[14]);
    if (!t[15]) NVM2C_ABORT();
    t[16] = 0LL;
    nresult = t[16];
    goto L_return;
L_return:
    free(r);
    return nresult;
}

static int64_t nl_inferred(void) {
    (void)ni64_from_bits;
    int64_t l0 = 0;
    (void)l0;
    int64_t l1 = 0;
    (void)l1;
    int64_t t[5] = {0}; (void)t;
    double f[1] = {0}; (void)f;
    const char *s[1] = {0}; (void)s;
    narr_t a[1] = {0}; (void)a;
    nsarr_t sa[1] = {0}; (void)sa;
    nrec_t *r = 0 ? calloc(0, sizeof *r) : NULL;
    if (0 && !r) NVM2C_ABORT();
    nrarr_t ra[1] = {0}; (void)ra;
    nmap_t m[1] = {0}; (void)m;
    int64_t nresult = {0};
    if (0) goto L_return;
    t[0] = 6LL;
    l0 = t[0];
    t[1] = l0;
    t[2] = 1LL;
    t[3] = ni64_from_bits((uint64_t)t[1] + (uint64_t)t[2]);
    l1 = t[3];
    t[4] = l1;
    nresult = t[4];
    goto L_return;
L_return:
    free(r);
    return nresult;
}

static int64_t nl_main(void) {
    (void)ni64_from_bits;
    int64_t t[15] = {0}; (void)t;
    double f[3] = {0}; (void)f;
    const char *s[1] = {0}; (void)s;
    narr_t a[1] = {0}; (void)a;
    nsarr_t sa[1] = {0}; (void)sa;
    nrec_t *r = 0 ? calloc(0, sizeof *r) : NULL;
    if (0 && !r) NVM2C_ABORT();
    nrarr_t ra[1] = {0}; (void)ra;
    nmap_t m[1] = {0}; (void)m;
    int64_t nresult = {0};
    if (0) goto L_return;
    t[0] = 2LL;
    t[1] = nl_shadowed(t[0]);
    t[2] = 0LL;
    t[3] = (t[1] == t[2]);
    if (!t[3]) NVM2C_ABORT();
    t[4] = nl_inferred();
    t[5] = 7LL;
    t[6] = (t[4] == t[5]);
    if (!t[6]) NVM2C_ABORT();
    t[7] = nl_multiple();
    t[8] = 13LL;
    t[9] = (t[7] == t[8]);
    if (!t[9]) NVM2C_ABORT();
    t[10] = 1LL;
    s[0] = "flow";
    f[0] = nf64_from_bits(UINT64_C(0x3ff8000000000000));
    f[1] = nl_scalars(t[10], s[0], f[0]);
    f[2] = nf64_from_bits(UINT64_C(0x4000000000000000));
    t[11] = f[1] == f[2];
    if (!t[11]) NVM2C_ABORT();
    t[12] = 2LL;
    t[13] = nl_diamond(t[12]);
    printf("%lld\n", (long long)t[13]);
    fflush(stdout);
    t[14] = 0LL;
    nresult = t[14];
    goto L_return;
L_return:
    free(r);
    return nresult;
}

int main(void) {
    (void)nf64_to_i64;
    (void)nano_rt_f64_format; (void)nano_rt_f64_print;
    (void)nano_rt_f64_add; (void)nano_rt_f64_sub; (void)nano_rt_f64_mul; (void)nano_rt_f64_div;
    (void)nl_square;
    (void)nl_diamond;
    (void)nl_scalars;
    (void)nl_multiple;
    (void)nl_shadowed;
    (void)nl_inferred;
    (void)nl_main;
    (void)nf64_print;
    int result = (int)nl_main();
    return result;
}
