#ifndef _GNU_SOURCE
#define _GNU_SOURCE 1
#endif
#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE 1
#endif
/* Generated by nvm2c from NanoISA. Not a VM wrapper. */
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
/* I preserve invariant termination while naming its generated source. */
#define NVM2C_ABORT() do { fprintf(stderr, "I stopped at a native invariant in %s at generated C line %d.\n", __func__, __LINE__); abort(); } while (0)
/* I reconstruct wrapped bits without an out-of-range signed cast. */
static inline int64_t ni64_from_bits(uint64_t bits) {
    return bits <= INT64_MAX ? (int64_t)bits : -INT64_C(1) - (int64_t)(UINT64_MAX - bits);
}
#include <stdio.h>
static inline int64_t nf64_to_i64(double value) {
    if (!(value >= -0x1p63 && value < 0x1p63)) {
        fputs("I cannot convert this float to int: I require a finite value in [-2^63, 2^63).\n", stderr);
        exit(EXIT_FAILURE);
    }
    return (int64_t)value;
}

typedef struct nmap_s *nmap_t;
typedef struct { int64_t *data; size_t len; struct narr_owner *owner; } narr_s;
typedef narr_s *narr_t;
typedef struct { const char **data; size_t len; struct nsarr_owner *owner; } nsarr_s;
typedef nsarr_s *nsarr_t;
typedef struct nrarr_s nrarr_s;
typedef nrarr_s *nrarr_t;
typedef struct nrec_s nrec_t;
struct nrec_s { int64_t f[1]; const char *s[1]; narr_t a[1]; nsarr_t sa[1]; nrarr_t ra[1]; const nrec_t *rec[1]; uint8_t k[1], vk[1]; uint16_t n, tag; uint8_t kind; uint32_t callable_target; };
struct nrarr_s { nrec_t *data; size_t len; struct nrarr_owner *owner; };

static int64_t nl_main(void);

static int64_t nl_main(void) {
    (void)ni64_from_bits;
    int64_t t[1] = {0}; (void)t;
    double f[1] = {0}; (void)f;
    const char *s[1] = {0}; (void)s;
    narr_t a[1] = {0}; (void)a;
    nsarr_t sa[1] = {0}; (void)sa;
    nrec_t *r = 0 ? calloc(0, sizeof *r) : NULL;
    if (0 && !r) NVM2C_ABORT();
    nrarr_t ra[1] = {0}; (void)ra;
    nmap_t m[1] = {0}; (void)m;
    int64_t nresult = {0};
    if (0) goto L_return;
    t[0] = 0LL;
    nresult = t[0];
    goto L_return;
L_return:
    free(r);
    return nresult;
}

int main(void) {
    (void)nf64_to_i64;
    (void)nl_main;
    int result = (int)nl_main();
    return result;
}
