/* nanolang OpenCL C output: gpu/matmul.nano */
/* Generated by nanoc --target opencl */
/* Load: clCreateProgramWithSource + clBuildProgram */

#pragma OPENCL EXTENSION cl_khr_int64_base_atomics    : enable
#pragma OPENCL EXTENSION cl_khr_byte_addressable_store : enable
#pragma OPENCL EXTENSION cl_khr_fp64                   : enable


__kernel void matrix_scale(long a,
    __global char* mat_a,
    __global char* mat_c,
    long n)
{
    long _t0 = a;
    long _t1 = (long)(ulong)mat_a;
    long _t2 = (long)(ulong)mat_c;
    long _t3 = n;
    long _t4 = (long)get_global_id(1);
    long _t5 = (long)get_global_id(0);
    long _t6 = (_t4 < _t3) ? 1LL : 0LL;
    long _t7 = (_t5 < _t3) ? 1LL : 0LL;
    long _t8 = (_t6 != 0LL) ? 1LL : 0LL;
    long _t9 = (_t7 != 0LL) ? 1LL : 0LL;
    long _t10 = (_t8 && _t9) ? 1LL : 0LL;
    long _t11 = 0LL;
    if (_t10) {
    long _t12 = _t4 * _t3;
    long _t13 = _t12 + _t5;
    long _t14 = 8LL;
    long _t15 = _t13 * _t14;
    long _t16 = _t1 + _t15;
    long _t17 = *((__global long*)((ulong)_t16));
    long _t18 = _t0 * _t17;
    long _t19 = _t2 + _t15;
    *((__global long*)((ulong)_t19)) = _t18;
    long _t20 = 0LL;
    return;
    }
}

__kernel void matrix_hadamard(__global char* mat_a,
    __global char* mat_b,
    __global char* mat_c,
    long n)
{
    long _t0 = (long)(ulong)mat_a;
    long _t1 = (long)(ulong)mat_b;
    long _t2 = (long)(ulong)mat_c;
    long _t3 = n;
    long _t4 = (long)get_global_id(1);
    long _t5 = (long)get_global_id(0);
    long _t6 = (_t4 < _t3) ? 1LL : 0LL;
    long _t7 = (_t5 < _t3) ? 1LL : 0LL;
    long _t8 = (_t6 != 0LL) ? 1LL : 0LL;
    long _t9 = (_t7 != 0LL) ? 1LL : 0LL;
    long _t10 = (_t8 && _t9) ? 1LL : 0LL;
    long _t11 = 0LL;
    if (_t10) {
    long _t12 = _t4 * _t3;
    long _t13 = _t12 + _t5;
    long _t14 = 8LL;
    long _t15 = _t13 * _t14;
    long _t16 = _t0 + _t15;
    long _t17 = *((__global long*)((ulong)_t16));
    long _t18 = _t1 + _t15;
    long _t19 = *((__global long*)((ulong)_t18));
    long _t20 = _t17 * _t19;
    long _t21 = _t2 + _t15;
    *((__global long*)((ulong)_t21)) = _t20;
    long _t22 = 0LL;
    return;
    }
}
