/* nanolang OpenCL C output: gpu/ocean.nano */
/* Generated by nanoc --target opencl */
/* Load: clCreateProgramWithSource + clBuildProgram */

#pragma OPENCL EXTENSION cl_khr_int64_base_atomics    : enable
#pragma OPENCL EXTENSION cl_khr_byte_addressable_store : enable
#pragma OPENCL EXTENSION cl_khr_fp64                   : enable


__kernel void compute_ocean(__global char* d_sin,
    __global char* d_h,
    long width,
    long t)
{
    long _t0 = (long)(ulong)d_sin;
    long _t1 = (long)(ulong)d_h;
    long _t2 = width;
    long _t3 = t;
    long _t4 = (long)get_global_id(0);
    long _t5 = (_t4 < _t2) ? 1LL : 0LL;
    long _t6 = 0LL;
    if (_t5) {
    long _t7 = 5120000LL;
    long _t8 = 3LL;
    long _t9 = _t8 * _t4;
    long _t10 = 0LL;
    long _t11 = 3LL;
    long _t12 = _t10 - _t11;
    long _t13 = _t12 * _t3;
    long _t14 = _t9 + _t13;
    long _t15 = _t14 + _t7;
    long _t16 = 512LL;
    long _t17 = _t15 % _t16;
    long _t18 = 25LL;
    long _t19 = 8LL;
    long _t20 = _t17 * _t19;
    long _t21 = _t0 + _t20;
    long _t22 = *((__global long*)((ulong)_t21));
    long _t23 = _t18 * _t22;
    long _t24 = 1000LL;
    long _t25 = _t23 / _t24;
    long _t26 = 0LL;
    long _t27 = 7LL;
    long _t28 = _t26 - _t27;
    long _t29 = _t28 * _t4;
    long _t30 = 0LL;
    long _t31 = 6LL;
    long _t32 = _t30 - _t31;
    long _t33 = _t32 * _t3;
    long _t34 = _t29 + _t33;
    long _t35 = _t34 + _t7;
    long _t36 = 512LL;
    long _t37 = _t35 % _t36;
    long _t38 = 12LL;
    long _t39 = 8LL;
    long _t40 = _t37 * _t39;
    long _t41 = _t0 + _t40;
    long _t42 = *((__global long*)((ulong)_t41));
    long _t43 = _t38 * _t42;
    long _t44 = 1000LL;
    long _t45 = _t43 / _t44;
    long _t46 = 2LL;
    long _t47 = _t46 * _t4;
    long _t48 = 0LL;
    long _t49 = 2LL;
    long _t50 = _t48 - _t49;
    long _t51 = _t50 * _t3;
    long _t52 = _t47 + _t51;
    long _t53 = _t52 + _t7;
    long _t54 = 512LL;
    long _t55 = _t53 % _t54;
    long _t56 = 20LL;
    long _t57 = 8LL;
    long _t58 = _t55 * _t57;
    long _t59 = _t0 + _t58;
    long _t60 = *((__global long*)((ulong)_t59));
    long _t61 = _t56 * _t60;
    long _t62 = 1000LL;
    long _t63 = _t61 / _t62;
    long _t64 = 11LL;
    long _t65 = _t64 * _t4;
    long _t66 = 0LL;
    long _t67 = 8LL;
    long _t68 = _t66 - _t67;
    long _t69 = _t68 * _t3;
    long _t70 = _t65 + _t69;
    long _t71 = _t70 + _t7;
    long _t72 = 512LL;
    long _t73 = _t71 % _t72;
    long _t74 = 8LL;
    long _t75 = 8LL;
    long _t76 = _t73 * _t75;
    long _t77 = _t0 + _t76;
    long _t78 = *((__global long*)((ulong)_t77));
    long _t79 = _t74 * _t78;
    long _t80 = 1000LL;
    long _t81 = _t79 / _t80;
    long _t82 = 8LL;
    long _t83 = _t4 * _t82;
    long _t84 = _t1 + _t83;
    long _t85 = _t25 + _t45;
    long _t86 = _t63 + _t81;
    long _t87 = _t85 + _t86;
    *((__global long*)((ulong)_t84)) = _t87;
    long _t88 = 0LL;
    return;
    }
}
