/* nanolang OpenCL C output: examples/gpu/ocean.nano */
/* Generated by nanoc --target opencl */
/* Load: clCreateProgramWithSource + clBuildProgram */

#pragma OPENCL EXTENSION cl_khr_int64_base_atomics    : enable
#pragma OPENCL EXTENSION cl_khr_byte_addressable_store : enable
#pragma OPENCL EXTENSION cl_khr_fp64                   : enable


__kernel void compute_ocean(__global char* d_sin,
    __global char* d_heights,
    long cols,
    long tick)
{
    long _t0 = (long)(ulong)d_sin;
    long _t1 = (long)(ulong)d_heights;
    long _t2 = cols;
    long _t3 = tick;
    long _t4 = (long)get_global_id(0);
    long _t5 = (long)get_global_id(1);
    long _t6 = (_t4 < _t2) ? 1LL : 0LL;
    long _t7 = 52LL;
    long _t8 = (_t5 < _t7) ? 1LL : 0LL;
    long _t9 = (_t6 != 0LL) ? 1LL : 0LL;
    long _t10 = (_t8 != 0LL) ? 1LL : 0LL;
    long _t11 = (_t9 && _t10) ? 1LL : 0LL;
    long _t12 = 0LL;
    if (_t11) {
    long _t13 = 102400000LL;
    long _t14 = 17LL;
    long _t15 = _t14 * _t4;
    long _t16 = 7LL;
    long _t17 = _t16 * _t5;
    long _t18 = _t15 + _t17;
    long _t19 = 0LL;
    long _t20 = 4LL;
    long _t21 = _t19 - _t20;
    long _t22 = _t21 * _t3;
    long _t23 = _t18 + _t22;
    long _t24 = _t23 + _t13;
    long _t25 = 1024LL;
    long _t26 = _t24 % _t25;
    long _t27 = 0LL;
    long _t28 = 9LL;
    long _t29 = _t27 - _t28;
    long _t30 = _t29 * _t4;
    long _t31 = 21LL;
    long _t32 = _t31 * _t5;
    long _t33 = _t30 + _t32;
    long _t34 = 0LL;
    long _t35 = 7LL;
    long _t36 = _t34 - _t35;
    long _t37 = _t36 * _t3;
    long _t38 = _t33 + _t37;
    long _t39 = _t38 + _t13;
    long _t40 = 1024LL;
    long _t41 = _t39 % _t40;
    long _t42 = 5LL;
    long _t43 = _t42 * _t4;
    long _t44 = 4LL;
    long _t45 = _t44 * _t5;
    long _t46 = _t43 + _t45;
    long _t47 = 0LL;
    long _t48 = 2LL;
    long _t49 = _t47 - _t48;
    long _t50 = _t49 * _t3;
    long _t51 = _t46 + _t50;
    long _t52 = _t51 + _t13;
    long _t53 = 1024LL;
    long _t54 = _t52 % _t53;
    long _t55 = 31LL;
    long _t56 = _t55 * _t4;
    long _t57 = 0LL;
    long _t58 = 13LL;
    long _t59 = _t57 - _t58;
    long _t60 = _t59 * _t5;
    long _t61 = _t56 + _t60;
    long _t62 = 0LL;
    long _t63 = 11LL;
    long _t64 = _t62 - _t63;
    long _t65 = _t64 * _t3;
    long _t66 = _t61 + _t65;
    long _t67 = _t66 + _t13;
    long _t68 = 1024LL;
    long _t69 = _t67 % _t68;
    long _t70 = 2800LL;
    long _t71 = 8LL;
    long _t72 = _t26 * _t71;
    long _t73 = _t0 + _t72;
    long _t74 = *((__global long*)((ulong)_t73));
    long _t75 = _t70 * _t74;
    long _t76 = 1350LL;
    long _t77 = 8LL;
    long _t78 = _t41 * _t77;
    long _t79 = _t0 + _t78;
    long _t80 = *((__global long*)((ulong)_t79));
    long _t81 = _t76 * _t80;
    long _t82 = 2200LL;
    long _t83 = 8LL;
    long _t84 = _t54 * _t83;
    long _t85 = _t0 + _t84;
    long _t86 = *((__global long*)((ulong)_t85));
    long _t87 = _t82 * _t86;
    long _t88 = 650LL;
    long _t89 = 8LL;
    long _t90 = _t69 * _t89;
    long _t91 = _t0 + _t90;
    long _t92 = *((__global long*)((ulong)_t91));
    long _t93 = _t88 * _t92;
    long _t94 = _t75 + _t81;
    long _t95 = _t87 + _t93;
    long _t96 = _t94 + _t95;
    long _t97 = 1000LL;
    long _t98 = _t96 / _t97;
    long _t99 = _t5 * _t2;
    long _t100 = _t99 + _t4;
    long _t101 = 8LL;
    long _t102 = _t100 * _t101;
    long _t103 = _t1 + _t102;
    *((__global long*)((ulong)_t103)) = _t98;
    long _t104 = 0LL;
    return;
    }
}
