/* Generated by scripts/gen_ffi_dispatch.py. Do not edit.
 *
 * Mixed integer/floating FFI dispatch: correctly-typed function-pointer stubs
 * for every general-purpose (i) / floating-point (f) argument-class pattern up
 * to arity 6. See scripts/gen_ffi_dispatch.py for the rationale (ABI register
 * classes for int vs. float arguments).
 */
#ifndef NANOVM_FFI_DISPATCH_GENERATED_H
#define NANOVM_FFI_DISPATCH_GENERATED_H

#include <stdint.h>

#define FFI_DISPATCH_MAX_ARITY 6

/* A classified argument: either a general-purpose (long/pointer) slot or a
 * floating-point (double) slot. The dispatcher fills these from NanoValues. */
typedef struct {
    int is_float;   /* 1 => use .f (double); 0 => use .i (long/pointer) */
    long   i;
    double f;
} FfiArgSlot;

/* ffi_dispatch_gp: dispatch a call whose return is int64_t. Returns 1 on success, 0 if the (arity, pattern) is unsupported. */
static inline int ffi_dispatch_gp(void *fn, const FfiArgSlot *a, int argc, int64_t *out) {
    switch (argc) {
    case 0: {
        *out = (int64_t)(((int64_t (*)(void))fn)()); return 1;
    }
    case 1: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        switch (sel) {
        case 0: *out = (int64_t)(((int64_t (*)(long))fn)(a[0].i)); return 1;
        case 1: *out = (int64_t)(((int64_t (*)(double))fn)(a[0].f)); return 1;
        default: return 0;
        }
    }
    case 2: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        switch (sel) {
        case 0: *out = (int64_t)(((int64_t (*)(long, long))fn)(a[0].i, a[1].i)); return 1;
        case 2: *out = (int64_t)(((int64_t (*)(long, double))fn)(a[0].i, a[1].f)); return 1;
        case 1: *out = (int64_t)(((int64_t (*)(double, long))fn)(a[0].f, a[1].i)); return 1;
        case 3: *out = (int64_t)(((int64_t (*)(double, double))fn)(a[0].f, a[1].f)); return 1;
        default: return 0;
        }
    }
    case 3: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        sel |= (a[2].is_float ? 1 : 0) << 2;
        switch (sel) {
        case 0: *out = (int64_t)(((int64_t (*)(long, long, long))fn)(a[0].i, a[1].i, a[2].i)); return 1;
        case 4: *out = (int64_t)(((int64_t (*)(long, long, double))fn)(a[0].i, a[1].i, a[2].f)); return 1;
        case 2: *out = (int64_t)(((int64_t (*)(long, double, long))fn)(a[0].i, a[1].f, a[2].i)); return 1;
        case 6: *out = (int64_t)(((int64_t (*)(long, double, double))fn)(a[0].i, a[1].f, a[2].f)); return 1;
        case 1: *out = (int64_t)(((int64_t (*)(double, long, long))fn)(a[0].f, a[1].i, a[2].i)); return 1;
        case 5: *out = (int64_t)(((int64_t (*)(double, long, double))fn)(a[0].f, a[1].i, a[2].f)); return 1;
        case 3: *out = (int64_t)(((int64_t (*)(double, double, long))fn)(a[0].f, a[1].f, a[2].i)); return 1;
        case 7: *out = (int64_t)(((int64_t (*)(double, double, double))fn)(a[0].f, a[1].f, a[2].f)); return 1;
        default: return 0;
        }
    }
    case 4: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        sel |= (a[2].is_float ? 1 : 0) << 2;
        sel |= (a[3].is_float ? 1 : 0) << 3;
        switch (sel) {
        case 0: *out = (int64_t)(((int64_t (*)(long, long, long, long))fn)(a[0].i, a[1].i, a[2].i, a[3].i)); return 1;
        case 8: *out = (int64_t)(((int64_t (*)(long, long, long, double))fn)(a[0].i, a[1].i, a[2].i, a[3].f)); return 1;
        case 4: *out = (int64_t)(((int64_t (*)(long, long, double, long))fn)(a[0].i, a[1].i, a[2].f, a[3].i)); return 1;
        case 12: *out = (int64_t)(((int64_t (*)(long, long, double, double))fn)(a[0].i, a[1].i, a[2].f, a[3].f)); return 1;
        case 2: *out = (int64_t)(((int64_t (*)(long, double, long, long))fn)(a[0].i, a[1].f, a[2].i, a[3].i)); return 1;
        case 10: *out = (int64_t)(((int64_t (*)(long, double, long, double))fn)(a[0].i, a[1].f, a[2].i, a[3].f)); return 1;
        case 6: *out = (int64_t)(((int64_t (*)(long, double, double, long))fn)(a[0].i, a[1].f, a[2].f, a[3].i)); return 1;
        case 14: *out = (int64_t)(((int64_t (*)(long, double, double, double))fn)(a[0].i, a[1].f, a[2].f, a[3].f)); return 1;
        case 1: *out = (int64_t)(((int64_t (*)(double, long, long, long))fn)(a[0].f, a[1].i, a[2].i, a[3].i)); return 1;
        case 9: *out = (int64_t)(((int64_t (*)(double, long, long, double))fn)(a[0].f, a[1].i, a[2].i, a[3].f)); return 1;
        case 5: *out = (int64_t)(((int64_t (*)(double, long, double, long))fn)(a[0].f, a[1].i, a[2].f, a[3].i)); return 1;
        case 13: *out = (int64_t)(((int64_t (*)(double, long, double, double))fn)(a[0].f, a[1].i, a[2].f, a[3].f)); return 1;
        case 3: *out = (int64_t)(((int64_t (*)(double, double, long, long))fn)(a[0].f, a[1].f, a[2].i, a[3].i)); return 1;
        case 11: *out = (int64_t)(((int64_t (*)(double, double, long, double))fn)(a[0].f, a[1].f, a[2].i, a[3].f)); return 1;
        case 7: *out = (int64_t)(((int64_t (*)(double, double, double, long))fn)(a[0].f, a[1].f, a[2].f, a[3].i)); return 1;
        case 15: *out = (int64_t)(((int64_t (*)(double, double, double, double))fn)(a[0].f, a[1].f, a[2].f, a[3].f)); return 1;
        default: return 0;
        }
    }
    case 5: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        sel |= (a[2].is_float ? 1 : 0) << 2;
        sel |= (a[3].is_float ? 1 : 0) << 3;
        sel |= (a[4].is_float ? 1 : 0) << 4;
        switch (sel) {
        case 0: *out = (int64_t)(((int64_t (*)(long, long, long, long, long))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].i)); return 1;
        case 16: *out = (int64_t)(((int64_t (*)(long, long, long, long, double))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].f)); return 1;
        case 8: *out = (int64_t)(((int64_t (*)(long, long, long, double, long))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].i)); return 1;
        case 24: *out = (int64_t)(((int64_t (*)(long, long, long, double, double))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].f)); return 1;
        case 4: *out = (int64_t)(((int64_t (*)(long, long, double, long, long))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].i)); return 1;
        case 20: *out = (int64_t)(((int64_t (*)(long, long, double, long, double))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].f)); return 1;
        case 12: *out = (int64_t)(((int64_t (*)(long, long, double, double, long))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].i)); return 1;
        case 28: *out = (int64_t)(((int64_t (*)(long, long, double, double, double))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].f)); return 1;
        case 2: *out = (int64_t)(((int64_t (*)(long, double, long, long, long))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].i)); return 1;
        case 18: *out = (int64_t)(((int64_t (*)(long, double, long, long, double))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].f)); return 1;
        case 10: *out = (int64_t)(((int64_t (*)(long, double, long, double, long))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].i)); return 1;
        case 26: *out = (int64_t)(((int64_t (*)(long, double, long, double, double))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].f)); return 1;
        case 6: *out = (int64_t)(((int64_t (*)(long, double, double, long, long))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].i)); return 1;
        case 22: *out = (int64_t)(((int64_t (*)(long, double, double, long, double))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].f)); return 1;
        case 14: *out = (int64_t)(((int64_t (*)(long, double, double, double, long))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].i)); return 1;
        case 30: *out = (int64_t)(((int64_t (*)(long, double, double, double, double))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].f)); return 1;
        case 1: *out = (int64_t)(((int64_t (*)(double, long, long, long, long))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].i)); return 1;
        case 17: *out = (int64_t)(((int64_t (*)(double, long, long, long, double))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].f)); return 1;
        case 9: *out = (int64_t)(((int64_t (*)(double, long, long, double, long))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].i)); return 1;
        case 25: *out = (int64_t)(((int64_t (*)(double, long, long, double, double))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].f)); return 1;
        case 5: *out = (int64_t)(((int64_t (*)(double, long, double, long, long))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].i)); return 1;
        case 21: *out = (int64_t)(((int64_t (*)(double, long, double, long, double))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].f)); return 1;
        case 13: *out = (int64_t)(((int64_t (*)(double, long, double, double, long))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].i)); return 1;
        case 29: *out = (int64_t)(((int64_t (*)(double, long, double, double, double))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].f)); return 1;
        case 3: *out = (int64_t)(((int64_t (*)(double, double, long, long, long))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].i)); return 1;
        case 19: *out = (int64_t)(((int64_t (*)(double, double, long, long, double))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].f)); return 1;
        case 11: *out = (int64_t)(((int64_t (*)(double, double, long, double, long))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].i)); return 1;
        case 27: *out = (int64_t)(((int64_t (*)(double, double, long, double, double))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].f)); return 1;
        case 7: *out = (int64_t)(((int64_t (*)(double, double, double, long, long))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].i)); return 1;
        case 23: *out = (int64_t)(((int64_t (*)(double, double, double, long, double))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].f)); return 1;
        case 15: *out = (int64_t)(((int64_t (*)(double, double, double, double, long))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].i)); return 1;
        case 31: *out = (int64_t)(((int64_t (*)(double, double, double, double, double))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].f)); return 1;
        default: return 0;
        }
    }
    case 6: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        sel |= (a[2].is_float ? 1 : 0) << 2;
        sel |= (a[3].is_float ? 1 : 0) << 3;
        sel |= (a[4].is_float ? 1 : 0) << 4;
        sel |= (a[5].is_float ? 1 : 0) << 5;
        switch (sel) {
        case 0: *out = (int64_t)(((int64_t (*)(long, long, long, long, long, long))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].i, a[5].i)); return 1;
        case 32: *out = (int64_t)(((int64_t (*)(long, long, long, long, long, double))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].i, a[5].f)); return 1;
        case 16: *out = (int64_t)(((int64_t (*)(long, long, long, long, double, long))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].f, a[5].i)); return 1;
        case 48: *out = (int64_t)(((int64_t (*)(long, long, long, long, double, double))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].f, a[5].f)); return 1;
        case 8: *out = (int64_t)(((int64_t (*)(long, long, long, double, long, long))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].i, a[5].i)); return 1;
        case 40: *out = (int64_t)(((int64_t (*)(long, long, long, double, long, double))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].i, a[5].f)); return 1;
        case 24: *out = (int64_t)(((int64_t (*)(long, long, long, double, double, long))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].f, a[5].i)); return 1;
        case 56: *out = (int64_t)(((int64_t (*)(long, long, long, double, double, double))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].f, a[5].f)); return 1;
        case 4: *out = (int64_t)(((int64_t (*)(long, long, double, long, long, long))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].i, a[5].i)); return 1;
        case 36: *out = (int64_t)(((int64_t (*)(long, long, double, long, long, double))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].i, a[5].f)); return 1;
        case 20: *out = (int64_t)(((int64_t (*)(long, long, double, long, double, long))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].f, a[5].i)); return 1;
        case 52: *out = (int64_t)(((int64_t (*)(long, long, double, long, double, double))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].f, a[5].f)); return 1;
        case 12: *out = (int64_t)(((int64_t (*)(long, long, double, double, long, long))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].i, a[5].i)); return 1;
        case 44: *out = (int64_t)(((int64_t (*)(long, long, double, double, long, double))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].i, a[5].f)); return 1;
        case 28: *out = (int64_t)(((int64_t (*)(long, long, double, double, double, long))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].f, a[5].i)); return 1;
        case 60: *out = (int64_t)(((int64_t (*)(long, long, double, double, double, double))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].f, a[5].f)); return 1;
        case 2: *out = (int64_t)(((int64_t (*)(long, double, long, long, long, long))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].i, a[5].i)); return 1;
        case 34: *out = (int64_t)(((int64_t (*)(long, double, long, long, long, double))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].i, a[5].f)); return 1;
        case 18: *out = (int64_t)(((int64_t (*)(long, double, long, long, double, long))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].f, a[5].i)); return 1;
        case 50: *out = (int64_t)(((int64_t (*)(long, double, long, long, double, double))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].f, a[5].f)); return 1;
        case 10: *out = (int64_t)(((int64_t (*)(long, double, long, double, long, long))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].i, a[5].i)); return 1;
        case 42: *out = (int64_t)(((int64_t (*)(long, double, long, double, long, double))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].i, a[5].f)); return 1;
        case 26: *out = (int64_t)(((int64_t (*)(long, double, long, double, double, long))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].f, a[5].i)); return 1;
        case 58: *out = (int64_t)(((int64_t (*)(long, double, long, double, double, double))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].f, a[5].f)); return 1;
        case 6: *out = (int64_t)(((int64_t (*)(long, double, double, long, long, long))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].i, a[5].i)); return 1;
        case 38: *out = (int64_t)(((int64_t (*)(long, double, double, long, long, double))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].i, a[5].f)); return 1;
        case 22: *out = (int64_t)(((int64_t (*)(long, double, double, long, double, long))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].f, a[5].i)); return 1;
        case 54: *out = (int64_t)(((int64_t (*)(long, double, double, long, double, double))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].f, a[5].f)); return 1;
        case 14: *out = (int64_t)(((int64_t (*)(long, double, double, double, long, long))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].i, a[5].i)); return 1;
        case 46: *out = (int64_t)(((int64_t (*)(long, double, double, double, long, double))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].i, a[5].f)); return 1;
        case 30: *out = (int64_t)(((int64_t (*)(long, double, double, double, double, long))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].f, a[5].i)); return 1;
        case 62: *out = (int64_t)(((int64_t (*)(long, double, double, double, double, double))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].f, a[5].f)); return 1;
        case 1: *out = (int64_t)(((int64_t (*)(double, long, long, long, long, long))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].i, a[5].i)); return 1;
        case 33: *out = (int64_t)(((int64_t (*)(double, long, long, long, long, double))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].i, a[5].f)); return 1;
        case 17: *out = (int64_t)(((int64_t (*)(double, long, long, long, double, long))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].f, a[5].i)); return 1;
        case 49: *out = (int64_t)(((int64_t (*)(double, long, long, long, double, double))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].f, a[5].f)); return 1;
        case 9: *out = (int64_t)(((int64_t (*)(double, long, long, double, long, long))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].i, a[5].i)); return 1;
        case 41: *out = (int64_t)(((int64_t (*)(double, long, long, double, long, double))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].i, a[5].f)); return 1;
        case 25: *out = (int64_t)(((int64_t (*)(double, long, long, double, double, long))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].f, a[5].i)); return 1;
        case 57: *out = (int64_t)(((int64_t (*)(double, long, long, double, double, double))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].f, a[5].f)); return 1;
        case 5: *out = (int64_t)(((int64_t (*)(double, long, double, long, long, long))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].i, a[5].i)); return 1;
        case 37: *out = (int64_t)(((int64_t (*)(double, long, double, long, long, double))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].i, a[5].f)); return 1;
        case 21: *out = (int64_t)(((int64_t (*)(double, long, double, long, double, long))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].f, a[5].i)); return 1;
        case 53: *out = (int64_t)(((int64_t (*)(double, long, double, long, double, double))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].f, a[5].f)); return 1;
        case 13: *out = (int64_t)(((int64_t (*)(double, long, double, double, long, long))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].i, a[5].i)); return 1;
        case 45: *out = (int64_t)(((int64_t (*)(double, long, double, double, long, double))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].i, a[5].f)); return 1;
        case 29: *out = (int64_t)(((int64_t (*)(double, long, double, double, double, long))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].f, a[5].i)); return 1;
        case 61: *out = (int64_t)(((int64_t (*)(double, long, double, double, double, double))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].f, a[5].f)); return 1;
        case 3: *out = (int64_t)(((int64_t (*)(double, double, long, long, long, long))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].i, a[5].i)); return 1;
        case 35: *out = (int64_t)(((int64_t (*)(double, double, long, long, long, double))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].i, a[5].f)); return 1;
        case 19: *out = (int64_t)(((int64_t (*)(double, double, long, long, double, long))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].f, a[5].i)); return 1;
        case 51: *out = (int64_t)(((int64_t (*)(double, double, long, long, double, double))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].f, a[5].f)); return 1;
        case 11: *out = (int64_t)(((int64_t (*)(double, double, long, double, long, long))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].i, a[5].i)); return 1;
        case 43: *out = (int64_t)(((int64_t (*)(double, double, long, double, long, double))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].i, a[5].f)); return 1;
        case 27: *out = (int64_t)(((int64_t (*)(double, double, long, double, double, long))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].f, a[5].i)); return 1;
        case 59: *out = (int64_t)(((int64_t (*)(double, double, long, double, double, double))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].f, a[5].f)); return 1;
        case 7: *out = (int64_t)(((int64_t (*)(double, double, double, long, long, long))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].i, a[5].i)); return 1;
        case 39: *out = (int64_t)(((int64_t (*)(double, double, double, long, long, double))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].i, a[5].f)); return 1;
        case 23: *out = (int64_t)(((int64_t (*)(double, double, double, long, double, long))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].f, a[5].i)); return 1;
        case 55: *out = (int64_t)(((int64_t (*)(double, double, double, long, double, double))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].f, a[5].f)); return 1;
        case 15: *out = (int64_t)(((int64_t (*)(double, double, double, double, long, long))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].i, a[5].i)); return 1;
        case 47: *out = (int64_t)(((int64_t (*)(double, double, double, double, long, double))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].i, a[5].f)); return 1;
        case 31: *out = (int64_t)(((int64_t (*)(double, double, double, double, double, long))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].f, a[5].i)); return 1;
        case 63: *out = (int64_t)(((int64_t (*)(double, double, double, double, double, double))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].f, a[5].f)); return 1;
        default: return 0;
        }
    }
    default: return 0;
    }
}

/* ffi_dispatch_fp: dispatch a call whose return is double. Returns 1 on success, 0 if the (arity, pattern) is unsupported. */
static inline int ffi_dispatch_fp(void *fn, const FfiArgSlot *a, int argc, double *out) {
    switch (argc) {
    case 0: {
        *out = (double)(((double (*)(void))fn)()); return 1;
    }
    case 1: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        switch (sel) {
        case 0: *out = (double)(((double (*)(long))fn)(a[0].i)); return 1;
        case 1: *out = (double)(((double (*)(double))fn)(a[0].f)); return 1;
        default: return 0;
        }
    }
    case 2: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        switch (sel) {
        case 0: *out = (double)(((double (*)(long, long))fn)(a[0].i, a[1].i)); return 1;
        case 2: *out = (double)(((double (*)(long, double))fn)(a[0].i, a[1].f)); return 1;
        case 1: *out = (double)(((double (*)(double, long))fn)(a[0].f, a[1].i)); return 1;
        case 3: *out = (double)(((double (*)(double, double))fn)(a[0].f, a[1].f)); return 1;
        default: return 0;
        }
    }
    case 3: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        sel |= (a[2].is_float ? 1 : 0) << 2;
        switch (sel) {
        case 0: *out = (double)(((double (*)(long, long, long))fn)(a[0].i, a[1].i, a[2].i)); return 1;
        case 4: *out = (double)(((double (*)(long, long, double))fn)(a[0].i, a[1].i, a[2].f)); return 1;
        case 2: *out = (double)(((double (*)(long, double, long))fn)(a[0].i, a[1].f, a[2].i)); return 1;
        case 6: *out = (double)(((double (*)(long, double, double))fn)(a[0].i, a[1].f, a[2].f)); return 1;
        case 1: *out = (double)(((double (*)(double, long, long))fn)(a[0].f, a[1].i, a[2].i)); return 1;
        case 5: *out = (double)(((double (*)(double, long, double))fn)(a[0].f, a[1].i, a[2].f)); return 1;
        case 3: *out = (double)(((double (*)(double, double, long))fn)(a[0].f, a[1].f, a[2].i)); return 1;
        case 7: *out = (double)(((double (*)(double, double, double))fn)(a[0].f, a[1].f, a[2].f)); return 1;
        default: return 0;
        }
    }
    case 4: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        sel |= (a[2].is_float ? 1 : 0) << 2;
        sel |= (a[3].is_float ? 1 : 0) << 3;
        switch (sel) {
        case 0: *out = (double)(((double (*)(long, long, long, long))fn)(a[0].i, a[1].i, a[2].i, a[3].i)); return 1;
        case 8: *out = (double)(((double (*)(long, long, long, double))fn)(a[0].i, a[1].i, a[2].i, a[3].f)); return 1;
        case 4: *out = (double)(((double (*)(long, long, double, long))fn)(a[0].i, a[1].i, a[2].f, a[3].i)); return 1;
        case 12: *out = (double)(((double (*)(long, long, double, double))fn)(a[0].i, a[1].i, a[2].f, a[3].f)); return 1;
        case 2: *out = (double)(((double (*)(long, double, long, long))fn)(a[0].i, a[1].f, a[2].i, a[3].i)); return 1;
        case 10: *out = (double)(((double (*)(long, double, long, double))fn)(a[0].i, a[1].f, a[2].i, a[3].f)); return 1;
        case 6: *out = (double)(((double (*)(long, double, double, long))fn)(a[0].i, a[1].f, a[2].f, a[3].i)); return 1;
        case 14: *out = (double)(((double (*)(long, double, double, double))fn)(a[0].i, a[1].f, a[2].f, a[3].f)); return 1;
        case 1: *out = (double)(((double (*)(double, long, long, long))fn)(a[0].f, a[1].i, a[2].i, a[3].i)); return 1;
        case 9: *out = (double)(((double (*)(double, long, long, double))fn)(a[0].f, a[1].i, a[2].i, a[3].f)); return 1;
        case 5: *out = (double)(((double (*)(double, long, double, long))fn)(a[0].f, a[1].i, a[2].f, a[3].i)); return 1;
        case 13: *out = (double)(((double (*)(double, long, double, double))fn)(a[0].f, a[1].i, a[2].f, a[3].f)); return 1;
        case 3: *out = (double)(((double (*)(double, double, long, long))fn)(a[0].f, a[1].f, a[2].i, a[3].i)); return 1;
        case 11: *out = (double)(((double (*)(double, double, long, double))fn)(a[0].f, a[1].f, a[2].i, a[3].f)); return 1;
        case 7: *out = (double)(((double (*)(double, double, double, long))fn)(a[0].f, a[1].f, a[2].f, a[3].i)); return 1;
        case 15: *out = (double)(((double (*)(double, double, double, double))fn)(a[0].f, a[1].f, a[2].f, a[3].f)); return 1;
        default: return 0;
        }
    }
    case 5: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        sel |= (a[2].is_float ? 1 : 0) << 2;
        sel |= (a[3].is_float ? 1 : 0) << 3;
        sel |= (a[4].is_float ? 1 : 0) << 4;
        switch (sel) {
        case 0: *out = (double)(((double (*)(long, long, long, long, long))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].i)); return 1;
        case 16: *out = (double)(((double (*)(long, long, long, long, double))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].f)); return 1;
        case 8: *out = (double)(((double (*)(long, long, long, double, long))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].i)); return 1;
        case 24: *out = (double)(((double (*)(long, long, long, double, double))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].f)); return 1;
        case 4: *out = (double)(((double (*)(long, long, double, long, long))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].i)); return 1;
        case 20: *out = (double)(((double (*)(long, long, double, long, double))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].f)); return 1;
        case 12: *out = (double)(((double (*)(long, long, double, double, long))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].i)); return 1;
        case 28: *out = (double)(((double (*)(long, long, double, double, double))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].f)); return 1;
        case 2: *out = (double)(((double (*)(long, double, long, long, long))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].i)); return 1;
        case 18: *out = (double)(((double (*)(long, double, long, long, double))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].f)); return 1;
        case 10: *out = (double)(((double (*)(long, double, long, double, long))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].i)); return 1;
        case 26: *out = (double)(((double (*)(long, double, long, double, double))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].f)); return 1;
        case 6: *out = (double)(((double (*)(long, double, double, long, long))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].i)); return 1;
        case 22: *out = (double)(((double (*)(long, double, double, long, double))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].f)); return 1;
        case 14: *out = (double)(((double (*)(long, double, double, double, long))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].i)); return 1;
        case 30: *out = (double)(((double (*)(long, double, double, double, double))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].f)); return 1;
        case 1: *out = (double)(((double (*)(double, long, long, long, long))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].i)); return 1;
        case 17: *out = (double)(((double (*)(double, long, long, long, double))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].f)); return 1;
        case 9: *out = (double)(((double (*)(double, long, long, double, long))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].i)); return 1;
        case 25: *out = (double)(((double (*)(double, long, long, double, double))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].f)); return 1;
        case 5: *out = (double)(((double (*)(double, long, double, long, long))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].i)); return 1;
        case 21: *out = (double)(((double (*)(double, long, double, long, double))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].f)); return 1;
        case 13: *out = (double)(((double (*)(double, long, double, double, long))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].i)); return 1;
        case 29: *out = (double)(((double (*)(double, long, double, double, double))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].f)); return 1;
        case 3: *out = (double)(((double (*)(double, double, long, long, long))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].i)); return 1;
        case 19: *out = (double)(((double (*)(double, double, long, long, double))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].f)); return 1;
        case 11: *out = (double)(((double (*)(double, double, long, double, long))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].i)); return 1;
        case 27: *out = (double)(((double (*)(double, double, long, double, double))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].f)); return 1;
        case 7: *out = (double)(((double (*)(double, double, double, long, long))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].i)); return 1;
        case 23: *out = (double)(((double (*)(double, double, double, long, double))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].f)); return 1;
        case 15: *out = (double)(((double (*)(double, double, double, double, long))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].i)); return 1;
        case 31: *out = (double)(((double (*)(double, double, double, double, double))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].f)); return 1;
        default: return 0;
        }
    }
    case 6: {
        int sel = 0;
        sel |= (a[0].is_float ? 1 : 0) << 0;
        sel |= (a[1].is_float ? 1 : 0) << 1;
        sel |= (a[2].is_float ? 1 : 0) << 2;
        sel |= (a[3].is_float ? 1 : 0) << 3;
        sel |= (a[4].is_float ? 1 : 0) << 4;
        sel |= (a[5].is_float ? 1 : 0) << 5;
        switch (sel) {
        case 0: *out = (double)(((double (*)(long, long, long, long, long, long))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].i, a[5].i)); return 1;
        case 32: *out = (double)(((double (*)(long, long, long, long, long, double))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].i, a[5].f)); return 1;
        case 16: *out = (double)(((double (*)(long, long, long, long, double, long))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].f, a[5].i)); return 1;
        case 48: *out = (double)(((double (*)(long, long, long, long, double, double))fn)(a[0].i, a[1].i, a[2].i, a[3].i, a[4].f, a[5].f)); return 1;
        case 8: *out = (double)(((double (*)(long, long, long, double, long, long))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].i, a[5].i)); return 1;
        case 40: *out = (double)(((double (*)(long, long, long, double, long, double))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].i, a[5].f)); return 1;
        case 24: *out = (double)(((double (*)(long, long, long, double, double, long))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].f, a[5].i)); return 1;
        case 56: *out = (double)(((double (*)(long, long, long, double, double, double))fn)(a[0].i, a[1].i, a[2].i, a[3].f, a[4].f, a[5].f)); return 1;
        case 4: *out = (double)(((double (*)(long, long, double, long, long, long))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].i, a[5].i)); return 1;
        case 36: *out = (double)(((double (*)(long, long, double, long, long, double))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].i, a[5].f)); return 1;
        case 20: *out = (double)(((double (*)(long, long, double, long, double, long))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].f, a[5].i)); return 1;
        case 52: *out = (double)(((double (*)(long, long, double, long, double, double))fn)(a[0].i, a[1].i, a[2].f, a[3].i, a[4].f, a[5].f)); return 1;
        case 12: *out = (double)(((double (*)(long, long, double, double, long, long))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].i, a[5].i)); return 1;
        case 44: *out = (double)(((double (*)(long, long, double, double, long, double))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].i, a[5].f)); return 1;
        case 28: *out = (double)(((double (*)(long, long, double, double, double, long))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].f, a[5].i)); return 1;
        case 60: *out = (double)(((double (*)(long, long, double, double, double, double))fn)(a[0].i, a[1].i, a[2].f, a[3].f, a[4].f, a[5].f)); return 1;
        case 2: *out = (double)(((double (*)(long, double, long, long, long, long))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].i, a[5].i)); return 1;
        case 34: *out = (double)(((double (*)(long, double, long, long, long, double))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].i, a[5].f)); return 1;
        case 18: *out = (double)(((double (*)(long, double, long, long, double, long))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].f, a[5].i)); return 1;
        case 50: *out = (double)(((double (*)(long, double, long, long, double, double))fn)(a[0].i, a[1].f, a[2].i, a[3].i, a[4].f, a[5].f)); return 1;
        case 10: *out = (double)(((double (*)(long, double, long, double, long, long))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].i, a[5].i)); return 1;
        case 42: *out = (double)(((double (*)(long, double, long, double, long, double))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].i, a[5].f)); return 1;
        case 26: *out = (double)(((double (*)(long, double, long, double, double, long))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].f, a[5].i)); return 1;
        case 58: *out = (double)(((double (*)(long, double, long, double, double, double))fn)(a[0].i, a[1].f, a[2].i, a[3].f, a[4].f, a[5].f)); return 1;
        case 6: *out = (double)(((double (*)(long, double, double, long, long, long))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].i, a[5].i)); return 1;
        case 38: *out = (double)(((double (*)(long, double, double, long, long, double))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].i, a[5].f)); return 1;
        case 22: *out = (double)(((double (*)(long, double, double, long, double, long))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].f, a[5].i)); return 1;
        case 54: *out = (double)(((double (*)(long, double, double, long, double, double))fn)(a[0].i, a[1].f, a[2].f, a[3].i, a[4].f, a[5].f)); return 1;
        case 14: *out = (double)(((double (*)(long, double, double, double, long, long))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].i, a[5].i)); return 1;
        case 46: *out = (double)(((double (*)(long, double, double, double, long, double))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].i, a[5].f)); return 1;
        case 30: *out = (double)(((double (*)(long, double, double, double, double, long))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].f, a[5].i)); return 1;
        case 62: *out = (double)(((double (*)(long, double, double, double, double, double))fn)(a[0].i, a[1].f, a[2].f, a[3].f, a[4].f, a[5].f)); return 1;
        case 1: *out = (double)(((double (*)(double, long, long, long, long, long))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].i, a[5].i)); return 1;
        case 33: *out = (double)(((double (*)(double, long, long, long, long, double))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].i, a[5].f)); return 1;
        case 17: *out = (double)(((double (*)(double, long, long, long, double, long))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].f, a[5].i)); return 1;
        case 49: *out = (double)(((double (*)(double, long, long, long, double, double))fn)(a[0].f, a[1].i, a[2].i, a[3].i, a[4].f, a[5].f)); return 1;
        case 9: *out = (double)(((double (*)(double, long, long, double, long, long))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].i, a[5].i)); return 1;
        case 41: *out = (double)(((double (*)(double, long, long, double, long, double))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].i, a[5].f)); return 1;
        case 25: *out = (double)(((double (*)(double, long, long, double, double, long))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].f, a[5].i)); return 1;
        case 57: *out = (double)(((double (*)(double, long, long, double, double, double))fn)(a[0].f, a[1].i, a[2].i, a[3].f, a[4].f, a[5].f)); return 1;
        case 5: *out = (double)(((double (*)(double, long, double, long, long, long))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].i, a[5].i)); return 1;
        case 37: *out = (double)(((double (*)(double, long, double, long, long, double))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].i, a[5].f)); return 1;
        case 21: *out = (double)(((double (*)(double, long, double, long, double, long))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].f, a[5].i)); return 1;
        case 53: *out = (double)(((double (*)(double, long, double, long, double, double))fn)(a[0].f, a[1].i, a[2].f, a[3].i, a[4].f, a[5].f)); return 1;
        case 13: *out = (double)(((double (*)(double, long, double, double, long, long))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].i, a[5].i)); return 1;
        case 45: *out = (double)(((double (*)(double, long, double, double, long, double))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].i, a[5].f)); return 1;
        case 29: *out = (double)(((double (*)(double, long, double, double, double, long))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].f, a[5].i)); return 1;
        case 61: *out = (double)(((double (*)(double, long, double, double, double, double))fn)(a[0].f, a[1].i, a[2].f, a[3].f, a[4].f, a[5].f)); return 1;
        case 3: *out = (double)(((double (*)(double, double, long, long, long, long))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].i, a[5].i)); return 1;
        case 35: *out = (double)(((double (*)(double, double, long, long, long, double))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].i, a[5].f)); return 1;
        case 19: *out = (double)(((double (*)(double, double, long, long, double, long))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].f, a[5].i)); return 1;
        case 51: *out = (double)(((double (*)(double, double, long, long, double, double))fn)(a[0].f, a[1].f, a[2].i, a[3].i, a[4].f, a[5].f)); return 1;
        case 11: *out = (double)(((double (*)(double, double, long, double, long, long))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].i, a[5].i)); return 1;
        case 43: *out = (double)(((double (*)(double, double, long, double, long, double))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].i, a[5].f)); return 1;
        case 27: *out = (double)(((double (*)(double, double, long, double, double, long))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].f, a[5].i)); return 1;
        case 59: *out = (double)(((double (*)(double, double, long, double, double, double))fn)(a[0].f, a[1].f, a[2].i, a[3].f, a[4].f, a[5].f)); return 1;
        case 7: *out = (double)(((double (*)(double, double, double, long, long, long))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].i, a[5].i)); return 1;
        case 39: *out = (double)(((double (*)(double, double, double, long, long, double))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].i, a[5].f)); return 1;
        case 23: *out = (double)(((double (*)(double, double, double, long, double, long))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].f, a[5].i)); return 1;
        case 55: *out = (double)(((double (*)(double, double, double, long, double, double))fn)(a[0].f, a[1].f, a[2].f, a[3].i, a[4].f, a[5].f)); return 1;
        case 15: *out = (double)(((double (*)(double, double, double, double, long, long))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].i, a[5].i)); return 1;
        case 47: *out = (double)(((double (*)(double, double, double, double, long, double))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].i, a[5].f)); return 1;
        case 31: *out = (double)(((double (*)(double, double, double, double, double, long))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].f, a[5].i)); return 1;
        case 63: *out = (double)(((double (*)(double, double, double, double, double, double))fn)(a[0].f, a[1].f, a[2].f, a[3].f, a[4].f, a[5].f)); return 1;
        default: return 0;
        }
    }
    default: return 0;
    }
}

#endif /* NANOVM_FFI_DISPATCH_GENERATED_H */
