/* I generate this from binary64_parse.h; do not edit. SHA256 e019a8709ba3381300a135d32cb478504762aa916d2f3c899be601dc2f557e63 */
static const char nbp_parser_source[] =
"#ifndef NANOISA_BINARY64_PARSE_H\n"
"#define NANOISA_BINARY64_PARSE_H\n"
"#include <stdint.h>\n"
"/* I parse closed C-locale binary64 values with fixed-capacity integer math.\n"
" * My input is a valid byte view; NUL terminates its numeric prefix. */\n"
"typedef struct {\n"
"    uint32_t limb[128];\n"
"    unsigned used;\n"
"} NbpBig;\n"
"static inline void nbp_zero(NbpBig *a) { *a = (NbpBig){{0}, 0}; }\n"
"static inline void nbp_normalize(NbpBig *a) {\n"
"    while (a->used && !a->limb[a->used - 1])\n"
"        a->used--;\n"
"}\n"
"static inline int nbp_multiply(NbpBig *a, unsigned base, unsigned add) {\n"
"    uint64_t carry = add;\n"
"    for (unsigned i = 0; i < a->used; i++) {\n"
"        uint64_t value = (uint64_t)a->limb[i] * base + carry;\n"
"        a->limb[i] = (uint32_t)value;\n"
"        carry = value >> 32;\n"
"    }\n"
"    if (carry) {\n"
"        if (a->used == 128)\n"
"            return 0;\n"
"        a->limb[a->used++] = (uint32_t)carry;\n"
"    }\n"
"    return 1;\n"
"}\n"
"static inline unsigned nbp_bits(const NbpBig *a) {\n"
"    if (!a->used)\n"
"        return 0;\n"
"    uint32_t top = a->limb[a->used - 1];\n"
"    unsigned n = 0;\n"
"    while (top) {\n"
"        top >>= 1;\n"
"        n++;\n"
"    }\n"
"    return (a->used - 1) * 32 + n;\n"
"}\n"
"static inline int nbp_shift(NbpBig *a, unsigned shift) {\n"
"    if (!a->used || !shift)\n"
"        return 1;\n"
"    unsigned words = shift / 32, bits = shift % 32;\n"
"    unsigned carry = bits && (a->limb[a->used - 1] >> (32 - bits));\n"
"    if (words >= 128 || a->used + words + carry > 128)\n"
"        return 0;\n"
"    NbpBig result;\n"
"    nbp_zero(&result);\n"
"    result.used = a->used + words + carry;\n"
"    for (unsigned i = 0; i < a->used; i++) {\n"
"        uint64_t value = (uint64_t)a->limb[i] << bits;\n"
"        result.limb[i + words] |= (uint32_t)value;\n"
"        if (value >> 32)\n"
"            result.limb[i + words + 1] |= (uint32_t)(value >> 32);\n"
"    }\n"
"    *a = result;\n"
"    return 1;\n"
"}\n"
"static inline int nbp_compare(const NbpBig *a, const NbpBig *b) {\n"
"    if (a->used != b->used)\n"
"        return a->used > b->used ? 1 : -1;\n"
"    for (unsigned i = a->used; i > 0; i--)\n"
"        if (a->limb[i - 1] != b->limb[i - 1])\n"
"            return a->limb[i - 1] > b->limb[i - 1] ? 1 : -1;\n"
"    return 0;\n"
"}\n"
"static inline void nbp_subtract(NbpBig *a, const NbpBig *b) {\n"
"    uint64_t borrow = 0;\n"
"    for (unsigned i = 0; i < a->used; i++) {\n"
"        uint64_t sub = (i < b->used ? b->limb[i] : 0) + borrow, value = a->limb[i];\n"
"        a->limb[i] = (uint32_t)(value - sub);\n"
"        borrow = value < sub;\n"
"    }\n"
"    nbp_normalize(a);\n"
"}\n"
"static inline int nbp_rational(NbpBig numerator, NbpBig denominator, int sticky, uint64_t *out) {\n"
"    int exponent = (int)nbp_bits(&numerator) - (int)nbp_bits(&denominator);\n"
"    NbpBig probe = exponent < 0 ? numerator : denominator;\n"
"    if (!nbp_shift(&probe, (unsigned)(exponent < 0 ? -exponent : exponent)))\n"
"        return 0;\n"
"    if ((exponent < 0 ? nbp_compare(&probe, &denominator) : nbp_compare(&numerator, &probe)) < 0)\n"
"        exponent--;\n"
"    if (exponent > 1023) {\n"
"        *out = UINT64_C(0x7ff0000000000000);\n"
"        return 1;\n"
"    }\n"
"    int normal = exponent >= -1022, shift = normal ? 52 - exponent : 1074;\n"
"    if (!nbp_shift(shift >= 0 ? &numerator : &denominator, (unsigned)(shift >= 0 ? shift : -shift)))\n"
"        return 0;\n"
"    int bit = (int)nbp_bits(&numerator) - (int)nbp_bits(&denominator);\n"
"    if (bit >= 64)\n"
"        return 0;\n"
"    uint64_t quotient = 0;\n"
"    for (; bit >= 0; bit--) {\n"
"        probe = denominator;\n"
"        if (!nbp_shift(&probe, (unsigned)bit))\n"
"            return 0;\n"
"        if (nbp_compare(&numerator, &probe) >= 0) {\n"
"            nbp_subtract(&numerator, &probe);\n"
"            quotient |= UINT64_C(1) << bit;\n"
"        }\n"
"    }\n"
"    if (!nbp_shift(&numerator, 1))\n"
"        return 0;\n"
"    int half = nbp_compare(&numerator, &denominator);\n"
"    if (half > 0 || (half == 0 && (sticky || (quotient & 1))))\n"
"        quotient++;\n"
"    if (normal) {\n"
"        if (quotient == (UINT64_C(1) << 53)) {\n"
"            quotient >>= 1;\n"
"            exponent++;\n"
"        }\n"
"        if (exponent > 1023) {\n"
"            *out = UINT64_C(0x7ff0000000000000);\n"
"            return 1;\n"
"        }\n"
"        if (quotient < (UINT64_C(1) << 52) || quotient >= (UINT64_C(1) << 53))\n"
"            return 0;\n"
"        *out = ((uint64_t)(exponent + 1023) << 52) | (quotient - (UINT64_C(1) << 52));\n"
"    } else {\n"
"        if (quotient > (UINT64_C(1) << 52))\n"
"            return 0;\n"
"        *out = quotient;\n"
"    }\n"
"    return 1;\n"
"}\n"
"static inline unsigned char nbp_lower(unsigned char c) {\n"
"    return c >= 'A' && c <= 'Z' ? (unsigned char)(c + 32) : c;\n"
"}\n"
"static inline int nbp_digit(unsigned char c) {\n"
"    if (c >= '0' && c <= '9')\n"
"        return c - '0';\n"
"    c = nbp_lower(c);\n"
"    return c >= 'a' && c <= 'f' ? c - 'a' + 10 : -1;\n"
"}\n"
"static inline int nbp_word(const unsigned char *text, uint32_t length, uint32_t start,\n"
"                           const char *word, unsigned count) {\n"
"    if (start > length || length - start < count)\n"
"        return 0;\n"
"    for (unsigned i = 0; i < count; i++)\n"
"        if (nbp_lower(text[start + i]) != (unsigned char)word[i])\n"
"            return 0;\n"
"    return 1;\n"
"}\n"
"static inline uint64_t nbp_nan_payload(const unsigned char *text, uint32_t length, uint32_t start) {\n"
"    if (start >= length || text[start] != '(')\n"
"        return 0;\n"
"    uint32_t end = start + 1;\n"
"    while (end < length) {\n"
"        unsigned char c = nbp_lower(text[end]);\n"
"        if (!((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_'))\n"
"            break;\n"
"        end++;\n"
"    }\n"
"    if (end == length || text[end] != ')')\n"
"        return 0;\n"
"    uint32_t i = start + 1;\n"
"    unsigned base = 10;\n"
"    if (end - i >= 2 && text[i] == '0' && nbp_lower(text[i + 1]) == 'x') {\n"
"        base = 16;\n"
"        i += 2;\n"
"    } else if (end - i > 1 && text[i] == '0')\n"
"        base = 8;\n"
"    if (i == end)\n"
"        return 0;\n"
"    uint64_t value = 0;\n"
"    for (; i < end; i++) {\n"
"        int digit = nbp_digit(text[i]);\n"
"        if (digit < 0 || (unsigned)digit >= base)\n"
"            return 0;\n"
"        if (value > (UINT64_MAX - (unsigned)digit) / base)\n"
"            value = UINT64_MAX;\n"
"        else\n"
"            value = value * base + (unsigned)digit;\n"
"    }\n"
"    return value;\n"
"}\n"
"static inline int nbp_parse(const unsigned char *text, uint32_t length, uint64_t *out) {\n"
"    if (!out || (!text && length))\n"
"        return 0;\n"
"    uint32_t i = 0;\n"
"    while (i < length && (text[i] == ' ' || text[i] == '\\t' || text[i] == '\\n' || text[i] == '\\r' ||\n"
"                          text[i] == '\\v' || text[i] == '\\f'))\n"
"        i++;\n"
"    uint64_t sign = 0;\n"
"    if (i < length && (text[i] == '-' || text[i] == '+')) {\n"
"        if (text[i] == '-')\n"
"            sign = UINT64_C(1) << 63;\n"
"        i++;\n"
"    }\n"
"    if (nbp_word(text, length, i, \"inf\", 3)) {\n"
"        *out = sign | UINT64_C(0x7ff0000000000000);\n"
"        return 1;\n"
"    }\n"
"    if (nbp_word(text, length, i, \"nan\", 3)) {\n"
"        *out = sign | UINT64_C(0x7ff8000000000000) |\n"
"               (nbp_nan_payload(text, length, i + 3) & UINT64_C(0xfffffffffffff));\n"
"        return 1;\n"
"    }\n"
"    unsigned radix = 10, cap = 800;\n"
"    if (length - i >= 3 && text[i] == '0' && nbp_lower(text[i + 1]) == 'x' &&\n"
"        (nbp_digit(text[i + 2]) >= 0 ||\n"
"         (length - i >= 4 && text[i + 2] == '.' && nbp_digit(text[i + 3]) >= 0))) {\n"
"        radix = 16;\n"
"        cap = 32;\n"
"        i += 2;\n"
"    }\n"
"    NbpBig numerator;\n"
"    nbp_zero(&numerator);\n"
"    unsigned kept = 0;\n"
"    int point = 0, saw_digit = 0, started = 0, sticky = 0;\n"
"    int64_t fractional = 0, omitted = 0;\n"
"    while (i < length) {\n"
"        int digit = nbp_digit(text[i]);\n"
"        if (digit >= 0 && (unsigned)digit < radix) {\n"
"            saw_digit = 1;\n"
"            if (point)\n"
"                fractional++;\n"
"            if (digit)\n"
"                started = 1;\n"
"            if (started) {\n"
"                if (kept < cap) {\n"
"                    if (!nbp_multiply(&numerator, radix, (unsigned)digit))\n"
"                        return 0;\n"
"                    kept++;\n"
"                } else {\n"
"                    omitted++;\n"
"                    sticky |= digit != 0;\n"
"                }\n"
"            }\n"
"            i++;\n"
"            continue;\n"
"        }\n"
"        if (text[i] == '.' && !point) {\n"
"            point = 1;\n"
"            i++;\n"
"            continue;\n"
"        }\n"
"        break;\n"
"    }\n"
"    if (!saw_digit) {\n"
"        *out = 0;\n"
"        return 1;\n"
"    }\n"
"    if (!started) {\n"
"        *out = sign;\n"
"        return 1;\n"
"    }\n"
"    int64_t exponent = 0;\n"
"    if (i < length && nbp_lower(text[i]) == (radix == 16 ? 'p' : 'e')) {\n"
"        uint32_t next = i + 1;\n"
"        int minus = 0;\n"
"        if (next < length && (text[next] == '+' || text[next] == '-')) {\n"
"            minus = text[next] == '-';\n"
"            next++;\n"
"        }\n"
"        if (next < length && text[next] >= '0' && text[next] <= '9') {\n"
"            const int64_t cap_exponent = INT64_C(1) << 40;\n"
"            for (; next < length && text[next] >= '0' && text[next] <= '9'; next++) {\n"
"                if (exponent < cap_exponent) {\n"
"                    exponent = exponent * 10 + (text[next] - '0');\n"
"                    if (exponent > cap_exponent)\n"
"                        exponent = cap_exponent;\n"
"                }\n"
"            }\n"
"            if (minus)\n"
"                exponent = -exponent;\n"
"        }\n"
"    }\n"
"    int64_t scale = exponent + (omitted - fractional) * (radix == 16 ? 4 : 1);\n"
"    int64_t order = (radix == 16 ? (int64_t)nbp_bits(&numerator) - 1 : (int64_t)kept - 1) + scale;\n"
"    if (order > (radix == 16 ? 1023 : 308)) {\n"
"        *out = sign | UINT64_C(0x7ff0000000000000);\n"
"        return 1;\n"
"    }\n"
"    if (order < (radix == 16 ? -1075 : -324)) {\n"
"        *out = sign;\n"
"        return 1;\n"
"    }\n"
"    NbpBig denominator;\n"
"    nbp_zero(&denominator);\n"
"    denominator.used = 1;\n"
"    denominator.limb[0] = 1;\n"
"    NbpBig *scaled = scale < 0 ? &denominator : &numerator;\n"
"    unsigned power = (unsigned)(scale < 0 ? -scale : scale);\n"
"    if (radix == 16) {\n"
"        if (!nbp_shift(scaled, power))\n"
"            return 0;\n"
"    } else\n"
"        for (unsigned step = 0; step < power; step++)\n"
"            if (!nbp_multiply(scaled, 10, 0))\n"
"                return 0;\n"
"    uint64_t result;\n"
"    if (!nbp_rational(numerator, denominator, sticky, &result))\n"
"        return 0;\n"
"    *out = sign | result;\n"
"    return 1;\n"
"}\n"
"#endif\n"
;
