#ifndef NANOISA_FILE_INDIRECT_NATIVE_ABI_H
#define NANOISA_FILE_INDIRECT_NATIVE_ABI_H
#include "file_indirect_runtime.h"
#define NVM_FILE_INDIRECT_NATIVE_ABI 1u
#define NVM_FILE_INDIRECT_NATIVE_OUTPUT_BYTES (128u*1024u*1024u)
#endif
