/* I generate exact managed native source; do not edit.
 * managed_strings.h SHA256 487f184a0005172f39d66a167a587e61f81442ffd46d3251c9a448067fe7e699
 * binary64_parse.h SHA256 bc66ca560c1cbde3a075043174d165f56d3f85ee6026578b7b0cf8dd9ccf08c5
 * managed_strings.c SHA256 24c5d151d101a1b32ffcd34725e15814fb8bb8576cb5f255e2220564db368dc7
 * I remove only the two named local includes from managed_strings.c.
 * Assembled SHA256 82f4f199044f7247148da245e22279276cea04ab560258b6a132b00239ff8cd2
 */
#ifndef NANOISA_MANAGED_NATIVE_SOURCE_H
#define NANOISA_MANAGED_NATIVE_SOURCE_H
static const char nms_native_source[] =
"#ifndef NANOISA_MANAGED_STRINGS_H\n"
"#define NANOISA_MANAGED_STRINGS_H\n"
"#include <stddef.h>\n"
"#include <stdint.h>\n"
"\n"
"/* My private runtime API does not itself grant bytecode/profile admission. */\n"
"typedef enum {\n"
"    NMS_OK = 0, NMS_TYPE = 1, NMS_ASSERT = 2, NMS_MEMORY = 3,\n"
"    NMS_BUSY = 4, NMS_DISPOSED = 5, NMS_STATE = 6, NMS_BOUNDS = 7\n"
"} NmsStatus;\n"
"typedef uint64_t NmsHandle;\n"
"/* I share this value tag with the ISA; the emitter asserts its ABI. */\n"
"#define NMS_ARRAY_TAG 7\n"
"#define NMS_RECORD_TAG 8\n"
"#define NMS_DYNAMIC (UINT64_C(1) << 63)\n"
"typedef struct { const unsigned char *data; uint32_t length; } NmsView;\n"
"typedef enum { NMS_SLOT_FREE = 0, NMS_SLOT_STRING = 1, NMS_SLOT_STRING_ARRAY = 2, NMS_SLOT_BOXED_ARRAY = 3, NMS_SLOT_BOXED_LEAF_ARRAY = NMS_SLOT_BOXED_ARRAY, NMS_SLOT_PACKED_SCALAR_ARRAY = 4, NMS_SLOT_RECORD = 5 } NmsSlotKind;\n"
"typedef struct {\n"
"    unsigned char *data;\n"
"    uint64_t references;\n"
"    uint32_t length, next_free, capacity, kind, element_tag, vm_array_policy, record_ordinal;\n"
"} NmsSlot;\n"
"typedef struct { uint32_t global_layout_index, field_count; } NmsRecordDescriptor;\n"
"typedef struct {\n"
"    const NmsRecordDescriptor *record_descriptors; /* Immutable through disposal. */\n"
"    uint32_t record_count;\n"
"    unsigned records_bound;\n"
"    const NmsView *literals; /* Borrowed immutable storage, alive until disposal. */\n"
"    NmsSlot *slots;\n"
"    void *collection_workspace;\n"
"    uint32_t collection_capacity;\n"
"    unsigned collection_prepared;\n"
"    uint64_t live_bytes, live_objects;\n"
"    uint32_t literal_count, capacity, free_head;\n"
"    unsigned active, disposed;\n"
"#ifdef NMS_TESTING\n"
"    uint64_t fail_after;\n"
"#endif\n"
"} NmsRuntime;\n"
"\n"
"/* init requires fresh storage or a previously disposed instance. Handles and\n"
" * views never cross runtime instances; a view borrows its handle's lifetime. */\n"
"void nms_init(NmsRuntime *, const NmsView *, uint32_t);\n"
"NmsStatus nms_create(NmsRuntime *, const unsigned char *, uint64_t, NmsHandle *);\n"
"/* My arrays own string children only. Append borrows both arguments and\n"
" * retains one child on success; get returns an owner, or zero for a missing\n"
" * unsigned index. Outputs and array contents change only on success. */\n"
"/* I consume both string owners and publish a complete split array only on success. */\n"
"NmsStatus nms_split_owned(NmsRuntime *, NmsHandle, NmsHandle, NmsHandle *);\n"
"NmsStatus nms_string_array_create(NmsRuntime *, NmsHandle *);\n"
"NmsStatus nms_string_array_append(NmsRuntime *, NmsHandle, NmsHandle);\n"
"NmsStatus nms_string_array_get(NmsRuntime *, NmsHandle, uint64_t, NmsHandle *);\n"
"NmsStatus nms_string_array_length(const NmsRuntime *, NmsHandle, uint32_t *);\n"
"/* My boxed-value API preserves scalar bits and owns string/array/record handles.\n"
" * Other heap/callable tags remain outside this private graph foundation. */\n"
"typedef struct { uint64_t payload; uint32_t tag; } NmsValue;\n"
"NmsStatus nms_value_retain(NmsRuntime *, NmsValue);\n"
"NmsStatus nms_value_release(NmsRuntime *, NmsValue);\n"
"/* Private description only: binding supplies no ordinary/resource authority.\n"
" * I bind once before dynamic allocations. The descriptor table stays alive and\n"
" * immutable through disposal; construction borrows ordered values. Failure\n"
" * leaves output and owners unchanged. GET retains; SET borrows both inputs. */\n"
"NmsStatus nms_bind_records(NmsRuntime *, const NmsRecordDescriptor *, uint32_t);\n"
"NmsStatus nms_record_create(NmsRuntime *, uint32_t, const NmsValue *, uint32_t, NmsHandle *);\n"
"NmsStatus nms_record_identity(const NmsRuntime *, NmsHandle, uint32_t *, uint32_t *);\n"
"NmsStatus nms_record_get(NmsRuntime *, NmsHandle, uint64_t, NmsValue *);\n"
"NmsStatus nms_record_set(NmsRuntime *, NmsHandle, uint64_t, NmsValue);\n"
"\n"
"/* I retain a declared int/U8/float/bool kind; this API grants no opcode admission. */\n"
"NmsStatus nms_packed_array_create(NmsRuntime *, uint32_t, NmsHandle *);\n"
"NmsStatus nms_value_array_create(NmsRuntime *, NmsHandle *);\n"
"/* I prepare capacity8 and VM checked-doubling semantics before publication. */\n"
"NmsStatus nms_vm_array_create(NmsRuntime *, uint32_t, NmsHandle *);\n"
"/* I borrow input roots and publish only a complete fresh VM-policy array.\n"
" * Literal count is uint16-bounded; slice endpoints are already uint32 values.\n"
" * Input vectors remain valid for the call (outside relocating slot storage).\n"
" * Failure leaves inputs and output unchanged. These APIs grant no admission. */\n"
"NmsStatus nms_vm_array_literal(NmsRuntime *, uint32_t, const uint64_t *, const uint32_t *, uint32_t, NmsHandle *);\n"
"NmsStatus nms_vm_array_slice(NmsRuntime *, NmsHandle, uint32_t, uint32_t, NmsHandle *);\n"
"/* I consume both strings and build boxed tagged children before publication. */\n"
"NmsStatus nms_split_values_owned(NmsRuntime *, NmsHandle, NmsHandle, NmsHandle *);\n"
"NmsStatus nms_value_array_append(NmsRuntime *, NmsHandle, NmsValue);\n"
"NmsStatus nms_value_array_set(NmsRuntime *, NmsHandle, uint64_t, NmsValue);\n"
"NmsStatus nms_value_array_get(NmsRuntime *, NmsHandle, uint64_t, NmsValue *);\n"
"NmsStatus nms_value_array_pop(NmsRuntime *, NmsHandle, NmsValue *);\n"
"NmsStatus nms_value_array_length(const NmsRuntime *, NmsHandle, uint32_t *);\n"
"/* I consume one owner and publish a fresh ASCII-mapped result; upper is 0/1.\n"
" * Output changes only on success. */\n"
"NmsStatus nms_case_owned(NmsRuntime *, NmsHandle, uint32_t, NmsHandle *);\n"
"/* I consume one source owner on every path; output changes only on success.\n"
" * Trim also allocates a fresh result when no bytes change. */\n"
"NmsStatus nms_trim_owned(NmsRuntime *, NmsHandle, NmsHandle *);\n"
"NmsStatus nms_substr_owned(NmsRuntime *, NmsHandle, uint32_t, uint32_t, NmsHandle *);\n"
"/* I consume three owners, including one per equal handle; failed output is unchanged. */\n"
"NmsStatus nms_replace_owned(NmsRuntime *, NmsHandle, NmsHandle, NmsHandle, NmsHandle *);\n"
"/* I consume one owned reference per input on success or failure. Equal inputs\n"
" * require two references. Other aliases survive; out is unchanged on failure. */\n"
"NmsStatus nms_concat_owned(NmsRuntime *, NmsHandle, NmsHandle, NmsHandle *);\n"
"/* I create one owner from scalar bits; strings transfer in lowering. */\n"
"NmsStatus nms_format_scalar(NmsRuntime *, uint64_t, uint32_t, NmsHandle *);\n"
"/* I borrow the handle, parse C-locale decimal bytes, and allocate nothing. */\n"
"NmsStatus nms_parse_f64(const NmsRuntime *, NmsHandle, uint64_t *);\n"
"NmsStatus nms_parse_i64(const NmsRuntime *, NmsHandle, int64_t *);\n"
"typedef enum { NMS_CONTAINS = 0, NMS_STARTS_WITH = 1, NMS_ENDS_WITH = 2 } NmsPredicate;\n"
"/* I borrow the source, allocate nothing, and publish only on success.\n"
" * Non-integer indices use zero; signed negative/out-of-range returns -1. */\n"
"NmsStatus nms_char_at(const NmsRuntime *, NmsHandle, uint64_t, uint32_t, int64_t *);\n"
"/* I borrow both handles and allocate nothing; output changes only on success. */\n"
"NmsStatus nms_predicate(const NmsRuntime *, NmsHandle, NmsHandle, uint32_t, uint32_t *);\n"
"NmsStatus nms_view(const NmsRuntime *, NmsHandle, NmsView *);\n"
"NmsStatus nms_retain(NmsRuntime *, NmsHandle);\n"
"NmsStatus nms_release(NmsRuntime *, NmsHandle);\n"
"/* I reclaim unreachable array graphs explicitly; failure leaves owners intact.\n"
" * This synchronous private operation grants no emitted collection safe point. */\n"
"NmsStatus nms_collect(NmsRuntime *);\n"
"/* I reserve reusable workspace transactionally; prepared collection allocates\n"
" * nothing. These private operations do not admit generated graph execution. */\n"
"NmsStatus nms_prepare_collection(NmsRuntime *);\n"
"NmsStatus nms_collect_prepared(NmsRuntime *);\n"
"/* These guard exported entry; generated frames own their separate cleanup. */\n"
"NmsStatus nms_begin(NmsRuntime *);\n"
"uint64_t nms_finish(NmsRuntime *, NmsStatus, int32_t);\n"
"NmsStatus nms_dispose(NmsRuntime *);\n"
"int nms_reserved_entry(const char *);\n"
"#ifdef NMS_TESTING\n"
"void nms_test_fail_after(NmsRuntime *, uint64_t);\n"
"uint64_t nms_test_live_allocations(void);\n"
"uint64_t nms_test_memory_pages(void);\n"
"#endif\n"
"#endif\n"
"#ifndef NANOISA_BINARY64_PARSE_H\n"
"#define NANOISA_BINARY64_PARSE_H\n"
"#include <stdint.h>\n"
"/* I parse closed C-locale binary64 values with fixed-capacity integer math.\n"
" * My input is a valid byte view; NUL terminates its numeric prefix. */\n"
"typedef struct {\n"
"    uint32_t limb[128];\n"
"    unsigned used;\n"
"} NbpBig;\n"
"static inline void nbp_zero(NbpBig *a) { *a = (NbpBig){{0}, 0}; }\n"
"static inline void nbp_normalize(NbpBig *a) {\n"
"    while (a->used && !a->limb[a->used - 1])\n"
"        a->used--;\n"
"}\n"
"static inline int nbp_multiply(NbpBig *a, unsigned base, unsigned add) {\n"
"    uint64_t carry = add;\n"
"    for (unsigned i = 0; i < a->used; i++) {\n"
"        uint64_t value = (uint64_t)a->limb[i] * base + carry;\n"
"        a->limb[i] = (uint32_t)value;\n"
"        carry = value >> 32;\n"
"    }\n"
"    if (carry) {\n"
"        if (a->used == 128)\n"
"            return 0;\n"
"        a->limb[a->used++] = (uint32_t)carry;\n"
"    }\n"
"    return 1;\n"
"}\n"
"static inline unsigned nbp_bits(const NbpBig *a) {\n"
"    if (!a->used)\n"
"        return 0;\n"
"    uint32_t top = a->limb[a->used - 1];\n"
"    unsigned n = 0;\n"
"    while (top) {\n"
"        top >>= 1;\n"
"        n++;\n"
"    }\n"
"    return (a->used - 1) * 32 + n;\n"
"}\n"
"static inline int nbp_shift(NbpBig *a, unsigned shift) {\n"
"    if (!a->used || !shift)\n"
"        return 1;\n"
"    unsigned words = shift / 32, bits = shift % 32;\n"
"    unsigned carry = bits && (a->limb[a->used - 1] >> (32 - bits));\n"
"    if (words >= 128 || a->used + words + carry > 128)\n"
"        return 0;\n"
"    NbpBig result;\n"
"    nbp_zero(&result);\n"
"    result.used = a->used + words + carry;\n"
"    for (unsigned i = 0; i < a->used; i++) {\n"
"        uint64_t value = (uint64_t)a->limb[i] << bits;\n"
"        result.limb[i + words] |= (uint32_t)value;\n"
"        if (value >> 32)\n"
"            result.limb[i + words + 1] |= (uint32_t)(value >> 32);\n"
"    }\n"
"    *a = result;\n"
"    return 1;\n"
"}\n"
"static inline int nbp_compare(const NbpBig *a, const NbpBig *b) {\n"
"    if (a->used != b->used)\n"
"        return a->used > b->used ? 1 : -1;\n"
"    for (unsigned i = a->used; i > 0; i--)\n"
"        if (a->limb[i - 1] != b->limb[i - 1])\n"
"            return a->limb[i - 1] > b->limb[i - 1] ? 1 : -1;\n"
"    return 0;\n"
"}\n"
"static inline void nbp_subtract(NbpBig *a, const NbpBig *b) {\n"
"    uint64_t borrow = 0;\n"
"    for (unsigned i = 0; i < a->used; i++) {\n"
"        uint64_t sub = (i < b->used ? b->limb[i] : 0) + borrow, value = a->limb[i];\n"
"        a->limb[i] = (uint32_t)(value - sub);\n"
"        borrow = value < sub;\n"
"    }\n"
"    nbp_normalize(a);\n"
"}\n"
"static inline int nbp_rational(NbpBig numerator, NbpBig denominator, int sticky, uint64_t *out) {\n"
"    int exponent = (int)nbp_bits(&numerator) - (int)nbp_bits(&denominator);\n"
"    NbpBig probe = exponent < 0 ? numerator : denominator;\n"
"    if (!nbp_shift(&probe, (unsigned)(exponent < 0 ? -exponent : exponent)))\n"
"        return 0;\n"
"    if ((exponent < 0 ? nbp_compare(&probe, &denominator) : nbp_compare(&numerator, &probe)) < 0)\n"
"        exponent--;\n"
"    if (exponent > 1023) {\n"
"        *out = UINT64_C(0x7ff0000000000000);\n"
"        return 1;\n"
"    }\n"
"    int normal = exponent >= -1022, shift = normal ? 52 - exponent : 1074;\n"
"    if (!nbp_shift(shift >= 0 ? &numerator : &denominator, (unsigned)(shift >= 0 ? shift : -shift)))\n"
"        return 0;\n"
"    int bit = (int)nbp_bits(&numerator) - (int)nbp_bits(&denominator);\n"
"    if (bit >= 64)\n"
"        return 0;\n"
"    uint64_t quotient = 0;\n"
"    for (; bit >= 0; bit--) {\n"
"        probe = denominator;\n"
"        if (!nbp_shift(&probe, (unsigned)bit))\n"
"            return 0;\n"
"        if (nbp_compare(&numerator, &probe) >= 0) {\n"
"            nbp_subtract(&numerator, &probe);\n"
"            quotient |= UINT64_C(1) << bit;\n"
"        }\n"
"    }\n"
"    if (!nbp_shift(&numerator, 1))\n"
"        return 0;\n"
"    int half = nbp_compare(&numerator, &denominator);\n"
"    if (half > 0 || (half == 0 && (sticky || (quotient & 1))))\n"
"        quotient++;\n"
"    if (normal) {\n"
"        if (quotient == (UINT64_C(1) << 53)) {\n"
"            quotient >>= 1;\n"
"            exponent++;\n"
"        }\n"
"        if (exponent > 1023) {\n"
"            *out = UINT64_C(0x7ff0000000000000);\n"
"            return 1;\n"
"        }\n"
"        if (quotient < (UINT64_C(1) << 52) || quotient >= (UINT64_C(1) << 53))\n"
"            return 0;\n"
"        *out = ((uint64_t)(exponent + 1023) << 52) | (quotient - (UINT64_C(1) << 52));\n"
"    } else {\n"
"        if (quotient > (UINT64_C(1) << 52))\n"
"            return 0;\n"
"        *out = quotient;\n"
"    }\n"
"    return 1;\n"
"}\n"
"static inline unsigned char nbp_lower(unsigned char c) {\n"
"    return c >= 'A' && c <= 'Z' ? (unsigned char)(c + 32) : c;\n"
"}\n"
"static inline int nbp_digit(unsigned char c) {\n"
"    if (c >= '0' && c <= '9')\n"
"        return c - '0';\n"
"    c = nbp_lower(c);\n"
"    return c >= 'a' && c <= 'f' ? c - 'a' + 10 : -1;\n"
"}\n"
"static inline int nbp_word(const unsigned char *text, uint32_t length, uint32_t start,\n"
"                           const char *word, unsigned count) {\n"
"    if (start > length || length - start < count)\n"
"        return 0;\n"
"    for (unsigned i = 0; i < count; i++)\n"
"        if (nbp_lower(text[start + i]) != (unsigned char)word[i])\n"
"            return 0;\n"
"    return 1;\n"
"}\n"
"static inline uint64_t nbp_nan_payload(const unsigned char *text, uint32_t length, uint32_t start,\n"
"                                       uint32_t *consumed) {\n"
"    if (start >= length || text[start] != '(')\n"
"        return 0;\n"
"    uint32_t end = start + 1;\n"
"    while (end < length) {\n"
"        unsigned char c = nbp_lower(text[end]);\n"
"        if (!((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_'))\n"
"            break;\n"
"        end++;\n"
"    }\n"
"    if (end == length || text[end] != ')')\n"
"        return 0;\n"
"    *consumed = end + 1;\n"
"    uint32_t i = start + 1;\n"
"    unsigned base = 10;\n"
"    if (end - i >= 2 && text[i] == '0' && nbp_lower(text[i + 1]) == 'x') {\n"
"        base = 16;\n"
"        i += 2;\n"
"    } else if (end - i > 1 && text[i] == '0')\n"
"        base = 8;\n"
"    if (i == end)\n"
"        return 0;\n"
"    uint64_t value = 0;\n"
"    for (; i < end; i++) {\n"
"        int digit = nbp_digit(text[i]);\n"
"        if (digit < 0 || (unsigned)digit >= base)\n"
"            return 0;\n"
"        if (value > (UINT64_MAX - (unsigned)digit) / base)\n"
"            value = UINT64_MAX;\n"
"        else\n"
"            value = value * base + (unsigned)digit;\n"
"    }\n"
"    return value;\n"
"}\n"
"static inline int nbp_parse_impl(const unsigned char *text, uint32_t length, uint64_t *out,\n"
"                                 uint32_t *consumed) {\n"
"    if (!out || (!text && length))\n"
"        return 0;\n"
"    *consumed = 0;\n"
"    uint32_t i = 0;\n"
"    while (i < length && (text[i] == ' ' || text[i] == '\\t' || text[i] == '\\n' || text[i] == '\\r' ||\n"
"                          text[i] == '\\v' || text[i] == '\\f'))\n"
"        i++;\n"
"    uint64_t sign = 0;\n"
"    if (i < length && (text[i] == '-' || text[i] == '+')) {\n"
"        if (text[i] == '-')\n"
"            sign = UINT64_C(1) << 63;\n"
"        i++;\n"
"    }\n"
"    if (nbp_word(text, length, i, \"inf\", 3)) {\n"
"        *consumed = i + (nbp_word(text, length, i, \"infinity\", 8) ? 8 : 3);\n"
"        *out = sign | UINT64_C(0x7ff0000000000000);\n"
"        return 1;\n"
"    }\n"
"    if (nbp_word(text, length, i, \"nan\", 3)) {\n"
"        *consumed = i + 3;\n"
"        *out = sign | UINT64_C(0x7ff8000000000000) |\n"
"               (nbp_nan_payload(text, length, i + 3, consumed) & UINT64_C(0xfffffffffffff));\n"
"        return 1;\n"
"    }\n"
"    unsigned radix = 10, cap = 800;\n"
"    if (length - i >= 3 && text[i] == '0' && nbp_lower(text[i + 1]) == 'x' &&\n"
"        (nbp_digit(text[i + 2]) >= 0 ||\n"
"         (length - i >= 4 && text[i + 2] == '.' && nbp_digit(text[i + 3]) >= 0))) {\n"
"        radix = 16;\n"
"        cap = 32;\n"
"        i += 2;\n"
"    }\n"
"    NbpBig numerator;\n"
"    nbp_zero(&numerator);\n"
"    unsigned kept = 0;\n"
"    int point = 0, saw_digit = 0, started = 0, sticky = 0;\n"
"    int64_t fractional = 0, omitted = 0;\n"
"    while (i < length) {\n"
"        int digit = nbp_digit(text[i]);\n"
"        if (digit >= 0 && (unsigned)digit < radix) {\n"
"            saw_digit = 1;\n"
"            if (point)\n"
"                fractional++;\n"
"            if (digit)\n"
"                started = 1;\n"
"            if (started) {\n"
"                if (kept < cap) {\n"
"                    if (!nbp_multiply(&numerator, radix, (unsigned)digit))\n"
"                        return 0;\n"
"                    kept++;\n"
"                } else {\n"
"                    omitted++;\n"
"                    sticky |= digit != 0;\n"
"                }\n"
"            }\n"
"            i++;\n"
"            continue;\n"
"        }\n"
"        if (text[i] == '.' && !point) {\n"
"            point = 1;\n"
"            i++;\n"
"            continue;\n"
"        }\n"
"        break;\n"
"    }\n"
"    if (!saw_digit) {\n"
"        *out = 0;\n"
"        return 1;\n"
"    }\n"
"    int64_t exponent = 0;\n"
"    if (i < length && nbp_lower(text[i]) == (radix == 16 ? 'p' : 'e')) {\n"
"        uint32_t next = i + 1;\n"
"        int minus = 0;\n"
"        if (next < length && (text[next] == '+' || text[next] == '-')) {\n"
"            minus = text[next] == '-';\n"
"            next++;\n"
"        }\n"
"        if (next < length && text[next] >= '0' && text[next] <= '9') {\n"
"            const int64_t cap_exponent = INT64_C(1) << 40;\n"
"            for (; next < length && text[next] >= '0' && text[next] <= '9'; next++) {\n"
"                if (exponent < cap_exponent) {\n"
"                    exponent = exponent * 10 + (text[next] - '0');\n"
"                    if (exponent > cap_exponent)\n"
"                        exponent = cap_exponent;\n"
"                }\n"
"            }\n"
"            i = next;\n"
"            if (minus)\n"
"                exponent = -exponent;\n"
"        }\n"
"    }\n"
"    *consumed = i;\n"
"    if (!started) {\n"
"        *out = sign;\n"
"        return 1;\n"
"    }\n"
"    int64_t scale = exponent + (omitted - fractional) * (radix == 16 ? 4 : 1);\n"
"    int64_t order = (radix == 16 ? (int64_t)nbp_bits(&numerator) - 1 : (int64_t)kept - 1) + scale;\n"
"    if (order > (radix == 16 ? 1023 : 308)) {\n"
"        *out = sign | UINT64_C(0x7ff0000000000000);\n"
"        return 1;\n"
"    }\n"
"    if (order < (radix == 16 ? -1075 : -324)) {\n"
"        *out = sign;\n"
"        return 1;\n"
"    }\n"
"    NbpBig denominator;\n"
"    nbp_zero(&denominator);\n"
"    denominator.used = 1;\n"
"    denominator.limb[0] = 1;\n"
"    NbpBig *scaled = scale < 0 ? &denominator : &numerator;\n"
"    unsigned power = (unsigned)(scale < 0 ? -scale : scale);\n"
"    if (radix == 16) {\n"
"        if (!nbp_shift(scaled, power))\n"
"            return 0;\n"
"    } else\n"
"        for (unsigned step = 0; step < power; step++)\n"
"            if (!nbp_multiply(scaled, 10, 0))\n"
"                return 0;\n"
"    uint64_t result;\n"
"    if (!nbp_rational(numerator, denominator, sticky, &result))\n"
"        return 0;\n"
"    *out = sign | result;\n"
"    return 1;\n"
"}\n"
"/* I publish both outputs only after checked parsing succeeds. An input with\n"
" * no numeric prefix has endpoint zero; optional endpoints preserve values. */\n"
"static inline int nbp_parse_end(const unsigned char *text, uint32_t length, uint64_t *out,\n"
"                                uint32_t *consumed) {\n"
"    if (!out || (!text && length))\n"
"        return 0;\n"
"    uint64_t bits;\n"
"    uint32_t end;\n"
"    if (!nbp_parse_impl(text, length, &bits, &end))\n"
"        return 0;\n"
"    *out = bits;\n"
"    if (consumed)\n"
"        *consumed = end;\n"
"    return 1;\n"
"}\n"
"static inline int nbp_parse(const unsigned char *text, uint32_t length, uint64_t *out) {\n"
"    return nbp_parse_end(text, length, out, 0);\n"
"}\n"
"#endif\n"
"/* I retain byte strings with context-local handles. My managed lowering\n"
" * supplies frame/global ownership and cleanup around this allocator core. */\n"
"#include <limits.h>\n"
"#ifndef __wasm32__\n"
"#include <stdlib.h>\n"
"_Static_assert(sizeof(void *) == 8 && sizeof(size_t) == 8,\n"
"               \"I require the declared native 64-bit allocator ABI\");\n"
"#endif\n"
"\n"
"#ifdef NMS_TESTING\n"
"static uint64_t live_allocations;\n"
"#endif\n"
"#ifdef NMS_TEST_ALLOC_HOOKS\n"
"#ifndef NMS_TESTING\n"
"#error \"I require NMS_TESTING for allocator observation hooks\"\n"
"#endif\n"
"/* My fixture owns these nonallocating callbacks; production has no hooks. */\n"
"extern int nms_test_allocation_permitted(uint64_t bytes);\n"
"extern void nms_test_allocation_created(void *memory, uint64_t bytes);\n"
"extern void nms_test_allocation_destroyed(void *memory);\n"
"#endif\n"
"static void copy_bytes(unsigned char *to, const unsigned char *from, uint64_t n) {\n"
"    /* Volatile byte accesses keep the freestanding Wasm core independent of\n"
"     * compiler-created memcpy/memmove imports, including optimized builds. */\n"
"    volatile unsigned char *dst = to;\n"
"    const volatile unsigned char *src = from;\n"
"    for (uint64_t i = 0; i < n; i++) dst[i] = src[i];\n"
"}\n"
"\n"
"#ifdef __wasm32__\n"
"/* Free-block headers live inside memory owned by this allocator. The sole\n"
" * external boundary is wasm-ld's heap base, after data and reserved stack. */\n"
"extern unsigned char __heap_base;\n"
"typedef struct FreeBlock { uint64_t size; struct FreeBlock *next; } FreeBlock;\n"
"_Static_assert(sizeof(FreeBlock) <= 16, \"I reserve a 16-byte block header\");\n"
"static FreeBlock *free_blocks;\n"
"static unsigned pool_initialized;\n"
"\n"
"static void pool_insert(FreeBlock *block) {\n"
"    FreeBlock *previous = NULL, *next = free_blocks;\n"
"    while (next && (uintptr_t)next < (uintptr_t)block) {\n"
"        previous = next; next = next->next;\n"
"    }\n"
"    block->next = next;\n"
"    if (next && (uint64_t)(uintptr_t)block + block->size == (uintptr_t)next) {\n"
"        block->size += next->size;\n"
"        block->next = next->next;\n"
"    }\n"
"    if (previous) {\n"
"        if ((uint64_t)(uintptr_t)previous + previous->size == (uintptr_t)block) {\n"
"            previous->size += block->size;\n"
"            previous->next = block->next;\n"
"        } else previous->next = block;\n"
"    } else free_blocks = block;\n"
"}\n"
"static void pool_init(void) {\n"
"    if (pool_initialized) return;\n"
"    pool_initialized = 1;\n"
"    uint64_t start = ((uint64_t)(uintptr_t)&__heap_base + 15) & ~UINT64_C(15);\n"
"    uint64_t end = (uint64_t)__builtin_wasm_memory_size(0) * 65536;\n"
"    if (start < end && end - start >= 32) {\n"
"        FreeBlock *block = (FreeBlock *)(uintptr_t)start;\n"
"        block->size = end - start;\n"
"        block->next = NULL;\n"
"        free_blocks = block;\n"
"    }\n"
"}\n"
"static void *backend_allocate(uint64_t bytes) {\n"
"    /* Widen before header/alignment arithmetic; no wrapped request reaches\n"
"     * the free list or memory.grow. All published block sizes are aligned. */\n"
"    if (bytes > UINT32_MAX - UINT64_C(31)) return NULL;\n"
"    uint64_t need = (bytes + 16 + 15) & ~UINT64_C(15);\n"
"    pool_init();\n"
"    for (unsigned attempt = 0; attempt < 2; attempt++) {\n"
"        FreeBlock **link = &free_blocks;\n"
"        for (FreeBlock *block = *link; block; link = &block->next, block = *link) {\n"
"            if (block->size < need) continue;\n"
"            uint64_t remaining = block->size - need;\n"
"            if (remaining >= 32) {\n"
"                FreeBlock *tail = (FreeBlock *)((unsigned char *)block + (size_t)need);\n"
"                tail->size = remaining; tail->next = block->next;\n"
"                *link = tail; block->size = need;\n"
"            } else *link = block->next;\n"
"            block->next = NULL;\n"
"            return (unsigned char *)block + 16;\n"
"        }\n"
"        if (attempt) break;\n"
"        uint64_t current = __builtin_wasm_memory_size(0);\n"
"        uint64_t missing = need;\n"
"        FreeBlock *tail = free_blocks;\n"
"        while (tail && tail->next) tail = tail->next;\n"
"        if (tail && (uint64_t)(uintptr_t)tail + tail->size == current * 65536)\n"
"            missing -= tail->size; /* No free block fitted, so this is positive. */\n"
"        uint64_t pages = (missing + 65535) / 65536;\n"
"        if (current > 65536 || pages > 65536 - current) return NULL;\n"
"        size_t old = __builtin_wasm_memory_grow(0, (size_t)pages);\n"
"        if (old == (size_t)-1) return NULL;\n"
"        FreeBlock *added = (FreeBlock *)(uintptr_t)((uint64_t)old * 65536);\n"
"        added->size = pages * 65536; added->next = NULL;\n"
"        pool_insert(added);\n"
"    }\n"
"    return NULL;\n"
"}\n"
"static void backend_free(void *memory) {\n"
"    if (memory) pool_insert((FreeBlock *)((unsigned char *)memory - 16));\n"
"}\n"
"#else\n"
"static void *backend_allocate(uint64_t bytes) {\n"
"    if (bytes > SIZE_MAX) return NULL;\n"
"    return malloc((size_t)bytes);\n"
"}\n"
"static void backend_free(void *memory) { free(memory); }\n"
"#endif\n"
"\n"
"static void *allocate(NmsRuntime *runtime, uint64_t bytes) {\n"
"#ifdef NMS_TEST_ALLOC_HOOKS\n"
"    if (!nms_test_allocation_permitted(bytes)) return NULL;\n"
"#endif\n"
"#ifdef NMS_TESTING\n"
"    if (!runtime->fail_after) return NULL;\n"
"    if (runtime->fail_after != UINT64_MAX) runtime->fail_after--;\n"
"#else\n"
"    (void)runtime;\n"
"#endif\n"
"    void *memory = backend_allocate(bytes);\n"
"#ifdef NMS_TEST_ALLOC_HOOKS\n"
"    if (memory) nms_test_allocation_created(memory, bytes);\n"
"#endif\n"
"#ifdef NMS_TESTING\n"
"    if (memory) live_allocations++;\n"
"#endif\n"
"    return memory;\n"
"}\n"
"static void deallocate(void *memory) {\n"
"    if (!memory) return;\n"
"#ifdef NMS_TEST_ALLOC_HOOKS\n"
"    nms_test_allocation_destroyed(memory);\n"
"#endif\n"
"#ifdef NMS_TESTING\n"
"    live_allocations--;\n"
"#endif\n"
"    backend_free(memory);\n"
"}\n"
"void nms_init(NmsRuntime *runtime, const NmsView *literals, uint32_t count) {\n"
"    runtime->record_descriptors = NULL;\n"
"    runtime->record_count = runtime->records_bound = 0;\n"
"    runtime->literals = literals;\n"
"    runtime->literal_count = count;\n"
"    runtime->slots = NULL;\n"
"    runtime->collection_workspace = NULL;\n"
"    runtime->collection_capacity = runtime->collection_prepared = 0;\n"
"    runtime->capacity = runtime->free_head = 0;\n"
"    runtime->live_bytes = runtime->live_objects = 0;\n"
"    runtime->active = runtime->disposed = 0;\n"
"#ifdef NMS_TESTING\n"
"    runtime->fail_after = UINT64_MAX;\n"
"#endif\n"
"}\n"
"static NmsStatus slot_for(const NmsRuntime *runtime, NmsHandle handle, uint32_t *index) {\n"
"    if (!runtime) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    uint64_t raw = handle & ~NMS_DYNAMIC;\n"
"    if (!(handle & NMS_DYNAMIC) || !raw || raw > runtime->capacity ||\n"
"        !runtime->slots || !runtime->slots[raw].references) return NMS_STATE;\n"
"    *index = (uint32_t)raw;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_view(const NmsRuntime *runtime, NmsHandle handle, NmsView *out) {\n"
"    if (!runtime || !out) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (handle & NMS_DYNAMIC) {\n"
"        uint32_t index;\n"
"        NmsStatus status = slot_for(runtime, handle, &index);\n"
"        if (status != NMS_OK) return status;\n"
"        if (runtime->slots[index].kind != NMS_SLOT_STRING) return NMS_TYPE;\n"
"        out->data = runtime->slots[index].data;\n"
"        out->length = runtime->slots[index].length;\n"
"    } else {\n"
"        if (!handle || handle > runtime->literal_count || !runtime->literals)\n"
"            return NMS_STATE;\n"
"        const NmsView *literal = &runtime->literals[handle - 1];\n"
"        if (!literal->data) return NMS_STATE;\n"
"        out->data = literal->data; out->length = literal->length;\n"
"    }\n"
"    return NMS_OK;\n"
"}\n"
"/* uint64 trial counts, byte marks, then aligned uint32 queue. All arithmetic\n"
" * is widened before checking the target size_t limit. */\n"
"static int collection_layout(uint32_t capacity, uint64_t *mark_offset,\n"
"                             uint64_t *queue_offset, uint64_t *bytes) {\n"
"    uint64_t count = (uint64_t)capacity + 1;\n"
"    uint64_t marks = count * sizeof(uint64_t);\n"
"    uint64_t queue = (marks + count + 3) & ~UINT64_C(3);\n"
"    uint64_t total = queue + count * sizeof(uint32_t);\n"
"    if (total > SIZE_MAX) return 0;\n"
"    *mark_offset = marks; *queue_offset = queue; *bytes = total;\n"
"    return 1;\n"
"}\n"
"static void *collection_allocate(NmsRuntime *runtime, uint32_t capacity) {\n"
"    uint64_t marks, queue, bytes;\n"
"    if (!collection_layout(capacity, &marks, &queue, &bytes)) return NULL;\n"
"    return allocate(runtime, bytes);\n"
"}\n"
"NmsStatus nms_prepare_collection(NmsRuntime *runtime) {\n"
"    if (!runtime) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (runtime->collection_prepared) return NMS_OK;\n"
"    void *workspace = collection_allocate(runtime, runtime->capacity);\n"
"    if (!workspace) return NMS_MEMORY;\n"
"    runtime->collection_workspace = workspace;\n"
"    runtime->collection_capacity = runtime->capacity;\n"
"    runtime->collection_prepared = 1;\n"
"    return NMS_OK;\n"
"}\n"
"/* Publication borrows prepared storage until success; I never publish a\n"
" * partial table or consume that storage on allocation failure. */\n"
"static NmsStatus publish_slot(NmsRuntime *runtime, unsigned char *bytes,\n"
"                              uint32_t length, uint32_t capacity, uint32_t kind,\n"
"                              uint64_t storage_bytes, NmsHandle *out) {\n"
"    if (storage_bytes > UINT64_MAX - runtime->live_bytes) return NMS_MEMORY;\n"
"    uint32_t new_capacity = runtime->capacity;\n"
"    if (!runtime->free_head) {\n"
"        if (runtime->capacity >= UINT32_MAX - 1) return NMS_MEMORY;\n"
"        new_capacity = runtime->capacity ?\n"
"            (runtime->capacity > (UINT32_MAX - 1) / 2 ? UINT32_MAX - 1 : runtime->capacity * 2) : 8;\n"
"        if ((uint64_t)new_capacity + 1 > SIZE_MAX / sizeof(NmsSlot)) return NMS_MEMORY;\n"
"    }\n"
"    NmsSlot *slots = runtime->slots;\n"
"    if (new_capacity != runtime->capacity) {\n"
"        slots = allocate(runtime, ((uint64_t)new_capacity + 1) * sizeof(NmsSlot));\n"
"        if (!slots) return NMS_MEMORY;\n"
"        void *workspace = NULL;\n"
"        if (runtime->collection_prepared) {\n"
"            workspace = collection_allocate(runtime, new_capacity);\n"
"            if (!workspace) { deallocate(slots); return NMS_MEMORY; }\n"
"        }\n"
"        for (uint64_t i = 0; i <= new_capacity; i++) {\n"
"            if (runtime->slots && i <= runtime->capacity) {\n"
"                slots[i].data = runtime->slots[i].data;\n"
"                slots[i].references = runtime->slots[i].references;\n"
"                slots[i].length = runtime->slots[i].length;\n"
"                slots[i].next_free = runtime->slots[i].next_free;\n"
"                slots[i].element_tag = runtime->slots[i].element_tag;\n"
"                slots[i].vm_array_policy = runtime->slots[i].vm_array_policy;\n"
"                slots[i].record_ordinal = runtime->slots[i].record_ordinal;\n"
"                slots[i].kind = runtime->slots[i].kind;\n"
"                slots[i].capacity = runtime->slots[i].capacity;\n"
"            } else {\n"
"                slots[i].data = NULL; slots[i].references = 0; slots[i].length = 0;\n"
"                slots[i].kind = NMS_SLOT_FREE; slots[i].capacity = 0; slots[i].element_tag = 0; slots[i].vm_array_policy = 0; slots[i].record_ordinal = 0;\n"
"                slots[i].next_free = i < new_capacity ? (uint32_t)i + 1 : 0;\n"
"            }\n"
"        }\n"
"        NmsSlot *old = runtime->slots;\n"
"        if (runtime->collection_prepared) {\n"
"            void *old_workspace = runtime->collection_workspace;\n"
"            runtime->collection_workspace = workspace;\n"
"            runtime->collection_capacity = new_capacity;\n"
"            deallocate(old_workspace);\n"
"        }\n"
"        runtime->slots = slots;\n"
"        runtime->free_head = runtime->capacity + 1;\n"
"        runtime->capacity = new_capacity;\n"
"        deallocate(old);\n"
"    }\n"
"    uint32_t index = runtime->free_head;\n"
"    runtime->free_head = slots[index].next_free;\n"
"    slots[index].data = bytes; slots[index].length = (uint32_t)length;\n"
"    slots[index].element_tag = 0; slots[index].vm_array_policy = 0; slots[index].record_ordinal = 0;\n"
"    slots[index].kind = kind; slots[index].capacity = capacity;\n"
"    slots[index].references = 1; slots[index].next_free = 0;\n"
"    runtime->live_bytes += storage_bytes; runtime->live_objects++;\n"
"    *out = NMS_DYNAMIC | index;\n"
"    return NMS_OK;\n"
"}\n"
"static NmsStatus create_parts(NmsRuntime *runtime,\n"
"                              const unsigned char *data, uint64_t first_length,\n"
"                              const unsigned char *second, uint64_t second_length,\n"
"                              NmsHandle *out) {\n"
"    if (!runtime || !out || (!data && first_length) || (!second && second_length))\n"
"        return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (first_length > UINT32_MAX || second_length > UINT32_MAX) return NMS_MEMORY;\n"
"    uint64_t length = first_length + second_length;\n"
"    if (length > UINT32_MAX || length == SIZE_MAX ||\n"
"        length > UINT64_MAX - runtime->live_bytes) return NMS_MEMORY;\n"
"    unsigned char *bytes = allocate(runtime, length + 1);\n"
"    if (!bytes) return NMS_MEMORY;\n"
"    copy_bytes(bytes, data, first_length);\n"
"    copy_bytes(bytes + first_length, second, second_length);\n"
"    bytes[length] = 0;\n"
"    NmsStatus status = publish_slot(runtime, bytes, (uint32_t)length, 0,\n"
"                                   NMS_SLOT_STRING, length, out);\n"
"    if (status != NMS_OK) deallocate(bytes);\n"
"    return status;\n"
"}\n"
"static NmsStatus string_array_slot(const NmsRuntime *runtime, NmsHandle handle,\n"
"                                   uint32_t *index) {\n"
"    if (!(handle & NMS_DYNAMIC)) {\n"
"        NmsView view;\n"
"        NmsStatus status = nms_view(runtime, handle, &view);\n"
"        return status == NMS_OK ? NMS_TYPE : status;\n"
"    }\n"
"    NmsStatus status = slot_for(runtime, handle, index);\n"
"    if (status != NMS_OK) return status;\n"
"    return runtime->slots[*index].kind == NMS_SLOT_STRING_ARRAY ? NMS_OK : NMS_TYPE;\n"
"}\n"
"NmsStatus nms_string_array_create(NmsRuntime *runtime, NmsHandle *out) {\n"
"    if (!runtime || !out) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    return publish_slot(runtime, NULL, 0, 0, NMS_SLOT_STRING_ARRAY, 0, out);\n"
"}\n"
"NmsStatus nms_string_array_append(NmsRuntime *runtime, NmsHandle array, NmsHandle child) {\n"
"    uint32_t index;\n"
"    NmsStatus status = string_array_slot(runtime, array, &index);\n"
"    if (status != NMS_OK) return status;\n"
"    NmsView view;\n"
"    status = nms_view(runtime, child, &view);\n"
"    if (status != NMS_OK) return status;\n"
"    NmsSlot *slot = &runtime->slots[index];\n"
"    if (slot->length == UINT32_MAX) return NMS_MEMORY;\n"
"    uint32_t capacity = slot->capacity;\n"
"    NmsHandle *buffer = (NmsHandle *)slot->data;\n"
"    if (slot->length == capacity) {\n"
"        capacity = capacity ? (capacity > UINT32_MAX / 2 ? UINT32_MAX : capacity * 2) : 4;\n"
"        uint64_t bytes = (uint64_t)capacity * sizeof(NmsHandle);\n"
"        uint64_t added = (uint64_t)(capacity - slot->capacity) * sizeof(NmsHandle);\n"
"        if (bytes > SIZE_MAX || added > UINT64_MAX - runtime->live_bytes) return NMS_MEMORY;\n"
"        buffer = allocate(runtime, bytes);\n"
"        if (!buffer) return NMS_MEMORY;\n"
"        copy_bytes((unsigned char *)buffer, slot->data, (uint64_t)slot->length * sizeof(NmsHandle));\n"
"    }\n"
"    status = nms_retain(runtime, child);\n"
"    if (status != NMS_OK) {\n"
"        if ((unsigned char *)buffer != slot->data) deallocate(buffer);\n"
"        return status;\n"
"    }\n"
"    if ((unsigned char *)buffer != slot->data) {\n"
"        runtime->live_bytes += (uint64_t)(capacity - slot->capacity) * sizeof(NmsHandle);\n"
"        deallocate(slot->data);\n"
"        slot->data = (unsigned char *)buffer;\n"
"        slot->capacity = capacity;\n"
"    }\n"
"    buffer[slot->length++] = child;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_string_array_get(NmsRuntime *runtime, NmsHandle array, uint64_t index,\n"
"                              NmsHandle *out) {\n"
"    if (!out) return NMS_STATE;\n"
"    uint32_t slot_index;\n"
"    NmsStatus status = string_array_slot(runtime, array, &slot_index);\n"
"    if (status != NMS_OK) return status;\n"
"    NmsSlot *slot = &runtime->slots[slot_index];\n"
"    if (index >= slot->length) { *out = 0; return NMS_OK; }\n"
"    NmsHandle child = ((NmsHandle *)slot->data)[index];\n"
"    status = nms_retain(runtime, child);\n"
"    if (status == NMS_OK) *out = child;\n"
"    return status;\n"
"}\n"
"NmsStatus nms_string_array_length(const NmsRuntime *runtime, NmsHandle array, uint32_t *out) {\n"
"    if (!out) return NMS_STATE;\n"
"    uint32_t index;\n"
"    NmsStatus status = string_array_slot(runtime, array, &index);\n"
"    if (status == NMS_OK) *out = runtime->slots[index].length;\n"
"    return status;\n"
"}\n"
"NmsStatus nms_create(NmsRuntime *runtime, const unsigned char *data, uint64_t length,\n"
"                     NmsHandle *out) {\n"
"    return create_parts(runtime, data, length, NULL, 0, out);\n"
"}\n"
"_Static_assert(offsetof(NmsValue, payload) == 0 && offsetof(NmsValue, tag) == 8 &&\n"
"               sizeof(NmsValue) == 16, \"I require the private boxed leaf-value ABI\");\n"
"static NmsStatus value_array_slot(const NmsRuntime *, NmsHandle, uint32_t *);\n"
"static NmsStatus record_slot(const NmsRuntime *runtime, NmsHandle handle, uint32_t *index) {\n"
"    NmsStatus status = slot_for(runtime, handle, index);\n"
"    if (status != NMS_OK) return status;\n"
"    const NmsSlot *slot = &runtime->slots[*index];\n"
"    if (slot->kind != NMS_SLOT_RECORD) return NMS_TYPE;\n"
"    if (!runtime->records_bound || !runtime->record_descriptors ||\n"
"        slot->record_ordinal >= runtime->record_count) return NMS_STATE;\n"
"    uint32_t fields = runtime->record_descriptors[slot->record_ordinal].field_count;\n"
"    return slot->length == fields && slot->capacity == fields &&\n"
"        (!fields || slot->data) ? NMS_OK : NMS_STATE;\n"
"}\n"
"static int value_is_reference(NmsValue value) {\n"
"    return value.tag == 5 || value.tag == NMS_ARRAY_TAG || value.tag == NMS_RECORD_TAG;\n"
"}\n"
"static int slot_has_children(const NmsSlot *slot) {\n"
"    return slot->kind == NMS_SLOT_STRING_ARRAY || slot->kind == NMS_SLOT_BOXED_ARRAY ||\n"
"        slot->kind == NMS_SLOT_RECORD;\n"
"}\n"
"\n"
"static NmsStatus value_valid(const NmsRuntime *runtime, NmsValue value) {\n"
"    if (!runtime) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (value.tag == 5) {\n"
"        NmsView view;\n"
"        return nms_view(runtime, value.payload, &view);\n"
"    }\n"
"    if (value.tag == NMS_ARRAY_TAG) {\n"
"        uint32_t index;\n"
"        return value_array_slot(runtime, value.payload, &index);\n"
"    }\n"
"    if (value.tag == NMS_RECORD_TAG) {\n"
"        uint32_t index;\n"
"        return record_slot(runtime, value.payload, &index);\n"
"    }\n"
"    return value.tag < 5 || value.tag == 9 ? NMS_OK : NMS_TYPE;\n"
"}\n"
"NmsStatus nms_value_retain(NmsRuntime *runtime, NmsValue value) {\n"
"    NmsStatus status = value_valid(runtime, value);\n"
"    if (status != NMS_OK) return status;\n"
"    return value_is_reference(value) ? nms_retain(runtime, value.payload) : NMS_OK;\n"
"}\n"
"NmsStatus nms_value_release(NmsRuntime *runtime, NmsValue value) {\n"
"    NmsStatus status = value_valid(runtime, value);\n"
"    if (status != NMS_OK) return status;\n"
"    return value_is_reference(value) ? nms_release(runtime, value.payload) : NMS_OK;\n"
"}\n"
"static NmsStatus value_array_slot(const NmsRuntime *runtime, NmsHandle array,\n"
"                                  uint32_t *index) {\n"
"    if (!(array & NMS_DYNAMIC)) {\n"
"        NmsView view;\n"
"        NmsStatus status = nms_view(runtime, array, &view);\n"
"        return status == NMS_OK ? NMS_TYPE : status;\n"
"    }\n"
"    NmsStatus status = slot_for(runtime, array, index);\n"
"    if (status != NMS_OK) return status;\n"
"    uint32_t kind = runtime->slots[*index].kind;\n"
"    return kind == NMS_SLOT_STRING_ARRAY || kind == NMS_SLOT_BOXED_ARRAY || kind == NMS_SLOT_PACKED_SCALAR_ARRAY ? NMS_OK : NMS_TYPE;\n"
"}\n"
"static uint32_t packed_width(uint32_t tag) {\n"
"    return tag == 1 || tag == 3 ? 8 : tag == 2 || tag == 4 ? 1 : 0;\n"
"}\n"
"/* I distinguish VM logical growth from older private empty-buffer factories. */\n"
"static NmsStatus array_next_capacity(uint32_t old, uint32_t width, uint32_t vm_policy,\n"
"                                     uint32_t *out) {\n"
"    uint64_t next = old ? (uint64_t)old * 2 : 4;\n"
"    if (vm_policy) {\n"
"        if (!width || next <= old || next > UINT32_MAX / width) return NMS_MEMORY;\n"
"    } else if (next > UINT32_MAX) next = UINT32_MAX;\n"
"    *out = (uint32_t)next;\n"
"    return NMS_OK;\n"
"}\n"
"static NmsStatus vm_array_create_capacity(NmsRuntime *runtime, uint32_t tag,\n"
"                                           uint32_t capacity, NmsHandle *out) {\n"
"    if (!runtime || !out) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (!(tag <= 5 || tag == NMS_ARRAY_TAG || tag == 9)) return NMS_TYPE;\n"
"    uint32_t width = packed_width(tag);\n"
"    uint32_t kind = width ? NMS_SLOT_PACKED_SCALAR_ARRAY : NMS_SLOT_BOXED_ARRAY;\n"
"    if (!width) width = sizeof(NmsValue);\n"
"    if (capacity < 8) capacity = 8;\n"
"    uint64_t bytes = (uint64_t)capacity * width;\n"
"    if (bytes > SIZE_MAX || bytes > UINT64_MAX - runtime->live_bytes) return NMS_MEMORY;\n"
"    unsigned char *buffer = allocate(runtime, bytes);\n"
"    if (!buffer) return NMS_MEMORY;\n"
"    NmsHandle result = 0;\n"
"    NmsStatus status = publish_slot(runtime, buffer, 0, capacity, kind, bytes, &result);\n"
"    if (status != NMS_OK) { deallocate(buffer); return status; }\n"
"    NmsSlot *slot = &runtime->slots[(uint32_t)result];\n"
"    slot->element_tag = tag; slot->vm_array_policy = 1;\n"
"    *out = result;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_vm_array_create(NmsRuntime *runtime, uint32_t tag, NmsHandle *out) {\n"
"    return vm_array_create_capacity(runtime, tag, 8, out);\n"
"}\n"
"static NmsValue packed_value(const NmsSlot *slot, uint32_t index) {\n"
"    uint32_t width = packed_width(slot->element_tag);\n"
"    uint64_t offset = (uint64_t)index * width;\n"
"    NmsValue value = {0, slot->element_tag};\n"
"    for (uint32_t i = 0; i < width; i++) value.payload |= (uint64_t)slot->data[offset + i] << (8 * i);\n"
"    return value;\n"
"}\n"
"static void packed_publish(NmsSlot *slot, uint32_t index, uint64_t bits) {\n"
"    uint32_t width = packed_width(slot->element_tag);\n"
"    uint64_t offset = (uint64_t)index * width;\n"
"    for (uint32_t i = 0; i < width; i++) slot->data[offset + i] = (unsigned char)(bits >> (8 * i));\n"
"}\n"
"static NmsStatus packed_prepare(uint32_t tag, NmsValue value, uint64_t *bits) {\n"
"    if ((value.tag == 2 && value.payload > 255) || (value.tag == 4 && value.payload > 1)) return NMS_TYPE;\n"
"    if (tag == value.tag && packed_width(tag)) { *bits = value.payload; return NMS_OK; }\n"
"    if (tag == 1 && value.tag == 2) { *bits = value.payload; return NMS_OK; }\n"
"    if (tag == 2 && value.tag == 1) { *bits = value.payload & 255; return NMS_OK; }\n"
"    if (tag == 3 && value.tag == 1) {\n"
"        /* I avoid an implementation-defined unsigned-to-signed conversion. */\n"
"        int64_t integer = value.payload <= INT64_MAX ? (int64_t)value.payload :\n"
"                          -1 - (int64_t)(UINT64_MAX - value.payload);\n"
"        double converted = (double)integer;\n"
"        _Static_assert(sizeof(double) == sizeof(uint64_t), \"I require binary64 scalar storage\");\n"
"        copy_bytes((unsigned char *)bits, (const unsigned char *)&converted, sizeof converted);\n"
"        return NMS_OK;\n"
"    }\n"
"    return NMS_TYPE;\n"
"}\n"
"NmsStatus nms_packed_array_create(NmsRuntime *runtime, uint32_t tag, NmsHandle *out) {\n"
"    if (!runtime || !out) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (!packed_width(tag)) return NMS_TYPE;\n"
"    NmsHandle result = 0;\n"
"    NmsStatus status = publish_slot(runtime, NULL, 0, 0, NMS_SLOT_PACKED_SCALAR_ARRAY, 0, &result);\n"
"    if (status != NMS_OK) return status;\n"
"    runtime->slots[(uint32_t)result].element_tag = tag;\n"
"    *out = result;\n"
"    return NMS_OK;\n"
"}\n"
"static NmsStatus packed_write(NmsRuntime *runtime, NmsSlot *slot, uint64_t index,\n"
"                               NmsValue value, int append) {\n"
"    uint64_t bits = 0;\n"
"    NmsStatus status = packed_prepare(slot->element_tag, value, &bits);\n"
"    if (status != NMS_OK) return status;\n"
"    if (!append && index >= slot->length) return NMS_STATE;\n"
"    if (append && slot->length == UINT32_MAX) return NMS_MEMORY;\n"
"    uint32_t width = packed_width(slot->element_tag);\n"
"    if (!width) return NMS_STATE;\n"
"    uint32_t target = append ? slot->length : (uint32_t)index;\n"
"    if (append && slot->length == slot->capacity) {\n"
"        uint32_t capacity = 0;\n"
"        status = array_next_capacity(slot->capacity, width, slot->vm_array_policy, &capacity);\n"
"        if (status != NMS_OK) return status;\n"
"        uint64_t bytes = (uint64_t)capacity * width;\n"
"        uint64_t delta = (uint64_t)(capacity - slot->capacity) * width;\n"
"        if (bytes > SIZE_MAX || delta > UINT64_MAX - runtime->live_bytes) return NMS_MEMORY;\n"
"        unsigned char *buffer = allocate(runtime, bytes);\n"
"        if (!buffer) return NMS_MEMORY;\n"
"        copy_bytes(buffer, slot->data, (uint64_t)slot->length * width);\n"
"        unsigned char *old = slot->data;\n"
"        slot->data = buffer; slot->capacity = capacity;\n"
"        runtime->live_bytes += delta;\n"
"        deallocate(old);\n"
"    }\n"
"    packed_publish(slot, target, bits);\n"
"    if (append) slot->length++;\n"
"    return NMS_OK;\n"
"}\n"
"static NmsValue slot_value(const NmsSlot *slot, uint32_t index) {\n"
"    if (slot->kind == NMS_SLOT_PACKED_SCALAR_ARRAY) return packed_value(slot, index);\n"
"    if (slot->kind == NMS_SLOT_STRING_ARRAY) {\n"
"        NmsValue value = {((const NmsHandle *)slot->data)[index], 5};\n"
"        return value;\n"
"    }\n"
"    return ((const NmsValue *)slot->data)[index];\n"
"}\n"
"static uint64_t slot_storage_bytes(const NmsSlot *slot) {\n"
"    return (uint64_t)slot->capacity *\n"
"        (slot->kind == NMS_SLOT_STRING_ARRAY ? sizeof(NmsHandle) :\n"
"         slot->kind == NMS_SLOT_PACKED_SCALAR_ARRAY ? packed_width(slot->element_tag) : sizeof(NmsValue));\n"
"}\n"
"NmsStatus nms_bind_records(NmsRuntime *runtime, const NmsRecordDescriptor *descriptors,\n"
"                            uint32_t count) {\n"
"    if (!runtime) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (runtime->active) return NMS_BUSY;\n"
"    if (runtime->records_bound || runtime->capacity || runtime->live_objects ||\n"
"        runtime->live_bytes || (count && !descriptors)) return NMS_STATE;\n"
"    if (count > 256) return NMS_TYPE;\n"
"    uint32_t total = 0;\n"
"    for (uint32_t i = 0; i < count; i++) {\n"
"        if (descriptors[i].global_layout_index >= 256 ||\n"
"            (i && descriptors[i].global_layout_index <= descriptors[i-1].global_layout_index) ||\n"
"            descriptors[i].field_count > UINT16_MAX ||\n"
"            descriptors[i].field_count > 65536u - total) return NMS_TYPE;\n"
"        total += descriptors[i].field_count;\n"
"    }\n"
"    runtime->record_descriptors = descriptors;\n"
"    runtime->record_count = count;\n"
"    runtime->records_bound = 1;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_record_create(NmsRuntime *runtime, uint32_t ordinal, const NmsValue *values,\n"
"                             uint32_t count, NmsHandle *out) {\n"
"    if (!runtime || !out) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (!runtime->records_bound || !runtime->record_descriptors ||\n"
"        ordinal >= runtime->record_count) return NMS_TYPE;\n"
"    if (count != runtime->record_descriptors[ordinal].field_count) return NMS_TYPE;\n"
"    if (count && !values) return NMS_STATE;\n"
"    uint64_t bytes = (uint64_t)count * sizeof(NmsValue);\n"
"    if (bytes > SIZE_MAX || bytes > UINT64_MAX - runtime->live_bytes) return NMS_MEMORY;\n"
"    for (uint32_t i = 0; i < count; i++) {\n"
"        NmsStatus status = value_valid(runtime, values[i]);\n"
"        if (status != NMS_OK) return status;\n"
"    }\n"
"    NmsValue *fields = bytes ? allocate(runtime, bytes) : NULL;\n"
"    if (bytes && !fields) return NMS_MEMORY;\n"
"    uint32_t retained = 0;\n"
"    NmsStatus status = NMS_OK;\n"
"    for (; retained < count; retained++) {\n"
"        fields[retained] = values[retained];\n"
"        status = nms_value_retain(runtime, fields[retained]);\n"
"        if (status != NMS_OK) break;\n"
"    }\n"
"    NmsHandle result;\n"
"    if (status == NMS_OK)\n"
"        status = publish_slot(runtime, (unsigned char *)fields, count, count,\n"
"                              NMS_SLOT_RECORD, bytes, &result);\n"
"    if (status != NMS_OK) {\n"
"        while (retained) nms_value_release(runtime, fields[--retained]);\n"
"        deallocate(fields);\n"
"        return status;\n"
"    }\n"
"    runtime->slots[(uint32_t)result].record_ordinal = ordinal;\n"
"    *out = result;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_record_identity(const NmsRuntime *runtime, NmsHandle record,\n"
"                               uint32_t *ordinal, uint32_t *global_layout) {\n"
"    if (!ordinal || !global_layout) return NMS_STATE;\n"
"    uint32_t index;\n"
"    NmsStatus status = record_slot(runtime, record, &index);\n"
"    if (status != NMS_OK) return status;\n"
"    uint32_t definition = runtime->slots[index].record_ordinal;\n"
"    *ordinal = definition;\n"
"    *global_layout = runtime->record_descriptors[definition].global_layout_index;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_record_get(NmsRuntime *runtime, NmsHandle record, uint64_t field, NmsValue *out) {\n"
"    if (!out) return NMS_STATE;\n"
"    uint32_t index;\n"
"    NmsStatus status = record_slot(runtime, record, &index);\n"
"    if (status != NMS_OK) return status;\n"
"    if (field >= runtime->slots[index].length) return NMS_BOUNDS;\n"
"    NmsValue value = slot_value(&runtime->slots[index], (uint32_t)field);\n"
"    status = nms_value_retain(runtime, value);\n"
"    if (status == NMS_OK) *out = value;\n"
"    return status;\n"
"}\n"
"NmsStatus nms_record_set(NmsRuntime *runtime, NmsHandle record, uint64_t field, NmsValue value) {\n"
"    uint32_t index;\n"
"    NmsStatus status = record_slot(runtime, record, &index);\n"
"    if (status != NMS_OK) return status;\n"
"    NmsSlot *slot = &runtime->slots[index];\n"
"    if (field >= slot->length) return NMS_BOUNDS;\n"
"    status = nms_value_retain(runtime, value);\n"
"    if (status != NMS_OK) return status;\n"
"    NmsValue *fields = (NmsValue *)slot->data;\n"
"    NmsValue previous = fields[field];\n"
"    fields[field] = value;\n"
"    return nms_value_release(runtime, previous);\n"
"}\n"
"NmsStatus nms_value_array_create(NmsRuntime *runtime, NmsHandle *out) {\n"
"    if (!runtime || !out) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    return publish_slot(runtime, NULL, 0, 0, NMS_SLOT_BOXED_ARRAY, 0, out);\n"
"}\n"
"static NmsStatus value_array_write(NmsRuntime *runtime, NmsHandle array,\n"
"                                    uint64_t requested_index, NmsValue value, int append) {\n"
"    uint32_t index;\n"
"    NmsStatus status = value_array_slot(runtime, array, &index);\n"
"    if (status != NMS_OK) return status;\n"
"    NmsSlot *slot = &runtime->slots[index];\n"
"    if (slot->kind == NMS_SLOT_PACKED_SCALAR_ARRAY)\n"
"        return packed_write(runtime, slot, requested_index, value, append);\n"
"    status = value_valid(runtime, value);\n"
"    if (status != NMS_OK) return status;\n"
"    if (!append && requested_index >= slot->length) return NMS_STATE;\n"
"    if (append && slot->length == UINT32_MAX) return NMS_MEMORY;\n"
"    uint32_t target = append ? slot->length : (uint32_t)requested_index;\n"
"    uint32_t capacity = slot->capacity;\n"
"    if (append && slot->length == capacity) {\n"
"        status = array_next_capacity(slot->capacity, sizeof(NmsValue), slot->vm_array_policy, &capacity);\n"
"        if (status != NMS_OK) return status;\n"
"    }\n"
"    uint64_t bytes = (uint64_t)capacity * sizeof(NmsValue);\n"
"    uint64_t old_bytes = slot_storage_bytes(slot);\n"
"    if (bytes > SIZE_MAX || bytes - old_bytes > UINT64_MAX - runtime->live_bytes) return NMS_MEMORY;\n"
"    NmsValue *buffer = (NmsValue *)slot->data;\n"
"    int replacement = slot->kind == NMS_SLOT_STRING_ARRAY || capacity != slot->capacity;\n"
"    if (replacement) {\n"
"        buffer = allocate(runtime, bytes);\n"
"        if (!buffer) return NMS_MEMORY;\n"
"        /* I move existing edge ownership without changing reference counts. */\n"
"        for (uint32_t i = 0; i < slot->length; i++) buffer[i] = slot_value(slot, i);\n"
"    }\n"
"    status = nms_value_retain(runtime, value);\n"
"    if (status != NMS_OK) {\n"
"        if (replacement) deallocate(buffer);\n"
"        return status;\n"
"    }\n"
"    NmsValue previous = {0, 0};\n"
"    if (!append) previous = slot_value(slot, target);\n"
"    if (replacement) {\n"
"        unsigned char *old = slot->data;\n"
"        slot->data = (unsigned char *)buffer;\n"
"        slot->capacity = capacity;\n"
"        slot->kind = NMS_SLOT_BOXED_ARRAY;\n"
"        runtime->live_bytes += bytes - old_bytes;\n"
"        deallocate(old);\n"
"    }\n"
"    buffer[target] = value;\n"
"    if (append) slot->length++;\n"
"    /* My new edge is visible before I drop the old child's owner. */\n"
"    return append ? NMS_OK : nms_value_release(runtime, previous);\n"
"}\n"
"NmsStatus nms_value_array_append(NmsRuntime *runtime, NmsHandle array, NmsValue value) {\n"
"    return value_array_write(runtime, array, 0, value, 1);\n"
"}\n"
"NmsStatus nms_value_array_set(NmsRuntime *runtime, NmsHandle array, uint64_t index, NmsValue value) {\n"
"    return value_array_write(runtime, array, index, value, 0);\n"
"}\n"
"NmsStatus nms_value_array_get(NmsRuntime *runtime, NmsHandle array, uint64_t index, NmsValue *out) {\n"
"    if (!out) return NMS_STATE;\n"
"    uint32_t slot_index;\n"
"    NmsStatus status = value_array_slot(runtime, array, &slot_index);\n"
"    if (status != NMS_OK) return status;\n"
"    NmsSlot *slot = &runtime->slots[slot_index];\n"
"    if (index >= slot->length) { *out = (NmsValue){0, 0}; return NMS_OK; }\n"
"    NmsValue value = slot_value(slot, (uint32_t)index);\n"
"    status = nms_value_retain(runtime, value);\n"
"    if (status == NMS_OK) *out = value;\n"
"    return status;\n"
"}\n"
"NmsStatus nms_value_array_pop(NmsRuntime *runtime, NmsHandle array, NmsValue *out) {\n"
"    if (!out) return NMS_STATE;\n"
"    uint32_t index;\n"
"    NmsStatus status = value_array_slot(runtime, array, &index);\n"
"    if (status != NMS_OK) return status;\n"
"    NmsSlot *slot = &runtime->slots[index];\n"
"    if (!slot->length) { *out = (NmsValue){0, 0}; return NMS_OK; }\n"
"    NmsValue value = slot_value(slot, slot->length - 1);\n"
"    slot->length--;\n"
"    if (slot->kind == NMS_SLOT_PACKED_SCALAR_ARRAY) packed_publish(slot, slot->length, 0);\n"
"    else if (slot->kind == NMS_SLOT_STRING_ARRAY) ((NmsHandle *)slot->data)[slot->length] = 0;\n"
"    else ((NmsValue *)slot->data)[slot->length] = (NmsValue){0, 0};\n"
"    *out = value;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_value_array_length(const NmsRuntime *runtime, NmsHandle array, uint32_t *out) {\n"
"    if (!out) return NMS_STATE;\n"
"    uint32_t index;\n"
"    NmsStatus status = value_array_slot(runtime, array, &index);\n"
"    if (status == NMS_OK) *out = runtime->slots[index].length;\n"
"    return status;\n"
"}\n"
"/* I borrow complete input arrays; my result remains private until all edges exist. */\n"
"NmsStatus nms_vm_array_literal(NmsRuntime *runtime, uint32_t tag,\n"
"                                const uint64_t *payloads, const uint32_t *tags,\n"
"                                uint32_t count, NmsHandle *out) {\n"
"    if (!runtime || !out || count > UINT16_MAX || (count && (!payloads || !tags))) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (!(tag <= 5 || tag == NMS_ARRAY_TAG || tag == 9)) return NMS_TYPE;\n"
"    for (uint32_t i = 0; i < count; i++) {\n"
"        NmsValue value = {payloads[i], tags[i]};\n"
"        uint64_t ignored;\n"
"        NmsStatus status = packed_width(tag) ? packed_prepare(tag, value, &ignored) : value_valid(runtime, value);\n"
"        if (status != NMS_OK) return status;\n"
"    }\n"
"    NmsHandle result = 0;\n"
"    NmsStatus status = vm_array_create_capacity(runtime, tag, count, &result);\n"
"    if (status != NMS_OK) return status;\n"
"    for (uint32_t i = 0; i < count; i++) {\n"
"        status = nms_value_array_append(runtime, result, (NmsValue){payloads[i], tags[i]});\n"
"        if (status != NMS_OK) { nms_release(runtime, result); return status; }\n"
"    }\n"
"    *out = result;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_vm_array_slice(NmsRuntime *runtime, NmsHandle source,\n"
"                              uint32_t start, uint32_t end, NmsHandle *out) {\n"
"    if (!out) return NMS_STATE;\n"
"    uint32_t source_index;\n"
"    NmsStatus status = value_array_slot(runtime, source, &source_index);\n"
"    if (status != NMS_OK) return status;\n"
"    const NmsSlot *input = &runtime->slots[source_index];\n"
"    uint32_t length = input->length;\n"
"    uint32_t tag = input->kind == NMS_SLOT_STRING_ARRAY ? 5 : input->element_tag;\n"
"    if (start > length) start = length;\n"
"    if (end > length) end = length;\n"
"    uint32_t count = end > start ? end - start : 0;\n"
"    NmsHandle result = 0;\n"
"    status = vm_array_create_capacity(runtime, tag, count, &result);\n"
"    if (status != NMS_OK) return status;\n"
"    /* Descriptor growth may relocate the source slot; its immutable buffer\n"
"     * remains owned by the borrowed source handle. Reacquire both slots. */\n"
"    input = &runtime->slots[source_index];\n"
"    NmsSlot *output = &runtime->slots[(uint32_t)result];\n"
"    if (input->kind == NMS_SLOT_PACKED_SCALAR_ARRAY) {\n"
"        uint32_t width = packed_width(tag);\n"
"        if (count) copy_bytes(output->data, input->data + (uint64_t)start * width,\n"
"                              (uint64_t)count * width);\n"
"        output->length = count;\n"
"    } else {\n"
"        for (uint32_t i = 0; i < count; i++) {\n"
"            NmsValue value = slot_value(input, start + i);\n"
"            status = nms_value_array_append(runtime, result, value);\n"
"            if (status != NMS_OK) { nms_release(runtime, result); return status; }\n"
"        }\n"
"    }\n"
"    *out = result;\n"
"    return NMS_OK;\n"
"}\n"
"\n"
"/* I format the exact binary64 rational with decimal integer arithmetic. The\n"
" * largest coefficient needs fewer than 800 digits; 1100 is an explicit cap. */\n"
"static NmsStatus nms_format_binary64(NmsRuntime *runtime, uint64_t bits, NmsHandle *out) {\n"
"    unsigned char output[32];\n"
"    unsigned used = 0;\n"
"    int negative = (int)(bits >> 63);\n"
"    if (negative) output[used++] = '-';\n"
"    uint32_t exponent_bits = (uint32_t)((bits >> 52) & 2047);\n"
"    uint64_t significand = bits & ((UINT64_C(1) << 52) - 1);\n"
"    if (exponent_bits == 2047) {\n"
"        const char *word = significand ? \"nan\" : \"inf\";\n"
"        for (unsigned i = 0; i < 3; i++) output[used++] = (unsigned char)word[i];\n"
"        return nms_create(runtime, output, used, out);\n"
"    }\n"
"    if (!exponent_bits && !significand) {\n"
"        output[used++] = '0';\n"
"        return nms_create(runtime, output, used, out);\n"
"    }\n"
"    int binary_exponent = exponent_bits ? (int)exponent_bits - 1023 - 52 : -1074;\n"
"    if (exponent_bits) significand |= UINT64_C(1) << 52;\n"
"    unsigned char digits[1100]; /* Little endian, one decimal digit per byte. */\n"
"    unsigned count = 0;\n"
"    do { digits[count++] = (unsigned char)(significand % 10); significand /= 10; }\n"
"    while (significand);\n"
"    unsigned steps = (unsigned)(binary_exponent < 0 ? -binary_exponent : binary_exponent);\n"
"    unsigned multiplier = binary_exponent < 0 ? 5 : 2;\n"
"    for (unsigned step = 0; step < steps; step++) {\n"
"        unsigned carry = 0;\n"
"        for (unsigned i = 0; i < count; i++) {\n"
"            unsigned value = digits[i] * multiplier + carry;\n"
"            digits[i] = (unsigned char)(value % 10);\n"
"            carry = value / 10;\n"
"        }\n"
"        if (carry) {\n"
"            if (count == sizeof digits) return NMS_STATE;\n"
"            digits[count++] = (unsigned char)carry;\n"
"        }\n"
"    }\n"
"    int exponent = (int)count - 1 + (binary_exponent < 0 ? binary_exponent : 0);\n"
"    uint32_t rounded = 0;\n"
"    for (unsigned i = 0; i < 6; i++)\n"
"        rounded = rounded * 10 + (i < count ? digits[count - 1 - i] : 0);\n"
"    if (count > 6) {\n"
"        unsigned next = digits[count - 7];\n"
"        int lower_nonzero = 0;\n"
"        for (unsigned i = 0; i + 7 < count; i++) lower_nonzero |= digits[i] != 0;\n"
"        if (next > 5 || (next == 5 && (lower_nonzero || (rounded & 1)))) rounded++;\n"
"        if (rounded == 1000000) { rounded = 100000; exponent++; }\n"
"    }\n"
"    unsigned char leading[6];\n"
"    for (unsigned i = 6; i > 0; i--) { leading[i-1] = (unsigned char)('0' + rounded % 10); rounded /= 10; }\n"
"    unsigned length = 6;\n"
"    while (length > 1 && leading[length - 1] == '0') length--;\n"
"    /* At most 14 bytes: sign + six digits + point + e + sign + three exponent\n"
"     * digits. Fixed notation is smaller because its exponent lies in [-4,5]. */\n"
"    if (exponent < -4 || exponent >= 6) {\n"
"        output[used++] = leading[0];\n"
"        if (length > 1) {\n"
"            output[used++] = '.';\n"
"            for (unsigned i = 1; i < length; i++) output[used++] = leading[i];\n"
"        }\n"
"        output[used++] = 'e';\n"
"        output[used++] = exponent < 0 ? '-' : '+';\n"
"        unsigned magnitude = (unsigned)(exponent < 0 ? -exponent : exponent);\n"
"        if (magnitude >= 100) output[used++] = (unsigned char)('0' + magnitude / 100);\n"
"        output[used++] = (unsigned char)('0' + (magnitude / 10) % 10);\n"
"        output[used++] = (unsigned char)('0' + magnitude % 10);\n"
"    } else if (exponent < 0) {\n"
"        output[used++] = '0'; output[used++] = '.';\n"
"        for (int i = -1; i > exponent; i--) output[used++] = '0';\n"
"        for (unsigned i = 0; i < length; i++) output[used++] = leading[i];\n"
"    } else {\n"
"        unsigned integer_length = (unsigned)exponent + 1;\n"
"        for (unsigned i = 0; i < integer_length; i++) output[used++] = leading[i];\n"
"        if (length > integer_length) {\n"
"            output[used++] = '.';\n"
"            for (unsigned i = integer_length; i < length; i++) output[used++] = leading[i];\n"
"        }\n"
"    }\n"
"    return nms_create(runtime, output, used, out);\n"
"}\n"
"NmsStatus nms_format_scalar(NmsRuntime *runtime, uint64_t bits, uint32_t tag, NmsHandle *out) {\n"
"    if (tag == 3) return nms_format_binary64(runtime, bits, out);\n"
"    if (tag == 0 || tag == NMS_ARRAY_TAG || tag == 9) return nms_create(runtime, NULL, 0, out);\n"
"    if (tag == 4) return nms_create(runtime,\n"
"        (const unsigned char *)(bits ? \"true\" : \"false\"), bits ? 4 : 5, out);\n"
"    if (tag != 1 && tag != 2) return NMS_TYPE;\n"
"    int negative = tag == 1 && (bits >> 63);\n"
"    uint64_t magnitude = tag == 2 ? bits & 255 : negative ? UINT64_C(0) - bits : bits;\n"
"    unsigned char digits[20];\n"
"    unsigned position = sizeof digits;\n"
"    do { digits[--position] = (unsigned char)('0' + magnitude % 10); magnitude /= 10; }\n"
"    while (magnitude);\n"
"    if (negative) digits[--position] = '-';\n"
"    return nms_create(runtime, digits + position, sizeof digits - position, out);\n"
"}\n"
"NmsStatus nms_parse_f64(const NmsRuntime *runtime, NmsHandle source, uint64_t *out) {\n"
"    NmsView view;\n"
"    NmsStatus status = nms_view(runtime, source, &view);\n"
"    if (status != NMS_OK) return status;\n"
"    return nbp_parse(view.data, view.length, out) ? NMS_OK : NMS_STATE;\n"
"}\n"
"NmsStatus nms_parse_i64(const NmsRuntime *runtime, NmsHandle source, int64_t *out) {\n"
"    NmsView view;\n"
"    NmsStatus status = nms_view(runtime, source, &view);\n"
"    if (status != NMS_OK) return status;\n"
"    if (!out) return NMS_STATE;\n"
"    uint32_t i = 0;\n"
"    while (i < view.length) {\n"
"        unsigned char c = view.data[i];\n"
"        if (c != ' ' && c != '\\t' && c != '\\n' && c != '\\r' && c != '\\v' && c != '\\f') break;\n"
"        i++;\n"
"    }\n"
"    int negative = 0;\n"
"    if (i < view.length && (view.data[i] == '-' || view.data[i] == '+')) {\n"
"        negative = view.data[i] == '-';\n"
"        i++;\n"
"    }\n"
"    uint64_t limit = negative ? (UINT64_C(1) << 63) : INT64_MAX;\n"
"    uint64_t value = 0;\n"
"    while (i < view.length) {\n"
"        unsigned char c = view.data[i++];\n"
"        if (c < '0' || c > '9') break;\n"
"        uint64_t digit = c - '0';\n"
"        if (value > (limit - digit) / 10) { value = limit; break; }\n"
"        value = value * 10 + digit;\n"
"    }\n"
"    /* I never cast 2^63 to signed or negate INT64_MIN. */\n"
"    *out = negative ? (value == (UINT64_C(1) << 63) ? INT64_MIN : -(int64_t)value)\n"
"                    : (int64_t)value;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_case_owned(NmsRuntime *runtime, NmsHandle source, uint32_t upper,\n"
"                         NmsHandle *out) {\n"
"    NmsView view;\n"
"    NmsHandle result = 0;\n"
"    NmsStatus status = (!out || upper > 1) ? NMS_STATE : nms_view(runtime, source, &view);\n"
"    if (status == NMS_OK) status = nms_create(runtime, view.data, view.length, &result);\n"
"    if (status == NMS_OK) {\n"
"        /* Creation can move the descriptor table. This new owner is private;\n"
"         * I reacquire its slot after allocation and transform before publish. */\n"
"        NmsSlot *slot = &runtime->slots[(uint32_t)(result & ~NMS_DYNAMIC)];\n"
"        for (uint32_t i = 0; i < slot->length; i++) {\n"
"            unsigned char byte = slot->data[i];\n"
"            slot->data[i] = upper ? (byte >= 'a' && byte <= 'z' ? byte - 32 : byte)\n"
"                                  : (byte >= 'A' && byte <= 'Z' ? byte + 32 : byte);\n"
"        }\n"
"    }\n"
"    NmsStatus released = nms_release(runtime, source);\n"
"    if (status != NMS_OK) return status;\n"
"    if (released != NMS_OK) { nms_release(runtime, result); return released; }\n"
"    *out = result;\n"
"    return NMS_OK;\n"
"}\n"
"static int trim_space(unsigned char byte) {\n"
"    return byte == ' ' || byte == '\\t' || byte == '\\n' || byte == '\\r';\n"
"}\n"
"NmsStatus nms_trim_owned(NmsRuntime *runtime, NmsHandle source, NmsHandle *out) {\n"
"    NmsView view;\n"
"    NmsStatus status = nms_view(runtime, source, &view);\n"
"    if (status != NMS_OK) { nms_release(runtime, source); return status; }\n"
"    uint32_t start = 0, end = view.length;\n"
"    while (start < end && trim_space(view.data[start])) start++;\n"
"    while (end > start && trim_space(view.data[end - 1])) end--;\n"
"    return nms_substr_owned(runtime, source, start, end - start, out);\n"
"}\n"
"NmsStatus nms_substr_owned(NmsRuntime *runtime, NmsHandle source,\n"
"                           uint32_t start, uint32_t length, NmsHandle *out) {\n"
"    NmsView view;\n"
"    NmsHandle result = 0;\n"
"    NmsStatus status = nms_view(runtime, source, &view);\n"
"    if (status == NMS_OK) {\n"
"        if (start >= view.length) { start = 0; length = 0; }\n"
"        else if (length > view.length - start) length = view.length - start;\n"
"        status = out ? nms_create(runtime, length ? view.data + start : NULL, length, &result) : NMS_STATE;\n"
"    }\n"
"    NmsStatus released = nms_release(runtime, source);\n"
"    if (status != NMS_OK) return status;\n"
"    if (released != NMS_OK) { nms_release(runtime, result); return released; }\n"
"    *out = result;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_concat_owned(NmsRuntime *runtime, NmsHandle left, NmsHandle right,\n"
"                           NmsHandle *out) {\n"
"    NmsView a, b;\n"
"    NmsHandle result = 0;\n"
"    NmsStatus status = nms_view(runtime, left, &a);\n"
"    if (status == NMS_OK) status = nms_view(runtime, right, &b);\n"
"    if (status == NMS_OK)\n"
"        status = out ? create_parts(runtime, a.data, a.length, b.data, b.length, &result) : NMS_STATE;\n"
"    /* Each input represents a transferred owner, including equal handles.\n"
"     * Copying finishes before release or descriptor-table replacement. */\n"
"    NmsStatus left_status = nms_release(runtime, left);\n"
"    NmsStatus right_status = nms_release(runtime, right);\n"
"    if (status != NMS_OK) return status;\n"
"    /* Ownership-correct callers cannot fail these releases. */\n"
"    if (left_status != NMS_OK || right_status != NMS_OK) {\n"
"        nms_release(runtime, result);\n"
"        return left_status != NMS_OK ? left_status : right_status;\n"
"    }\n"
"    *out = result;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_retain(NmsRuntime *runtime, NmsHandle handle) {\n"
"    if (!(handle & NMS_DYNAMIC)) { NmsView view; return nms_view(runtime, handle, &view); }\n"
"    uint32_t index;\n"
"    NmsStatus status = slot_for(runtime, handle, &index);\n"
"    if (status != NMS_OK) return status;\n"
"    if (runtime->slots[index].references == UINT64_MAX) return NMS_MEMORY;\n"
"    runtime->slots[index].references++;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_release(NmsRuntime *runtime, NmsHandle handle) {\n"
"    if (!(handle & NMS_DYNAMIC)) { NmsView view; return nms_view(runtime, handle, &view); }\n"
"    uint32_t index;\n"
"    NmsStatus status = slot_for(runtime, handle, &index);\n"
"    if (status != NMS_OK) return status;\n"
"    if (--runtime->slots[index].references) return NMS_OK;\n"
"    /* Zero-count slots are unavailable to live-handle lookup. I use their\n"
"     * next_free field as a private worklist until all outgoing edges are gone.\n"
"     * No allocation or table relocation occurs in this loop. */\n"
"    uint32_t pending = index;\n"
"    runtime->slots[index].next_free = 0;\n"
"    NmsStatus first_error = NMS_OK;\n"
"    while (pending) {\n"
"        index = pending;\n"
"        NmsSlot *slot = &runtime->slots[index];\n"
"        pending = slot->next_free;\n"
"        if (slot_has_children(slot)) {\n"
"            for (uint32_t i = 0; i < slot->length; i++) {\n"
"                NmsValue child = slot_value(slot, i);\n"
"                if (!value_is_reference(child) || !(child.payload & NMS_DYNAMIC)) continue;\n"
"                uint32_t child_index;\n"
"                NmsStatus child_status = slot_for(runtime, child.payload, &child_index);\n"
"                if (child_status != NMS_OK) {\n"
"                    if (first_error == NMS_OK) first_error = child_status;\n"
"                    continue;\n"
"                }\n"
"                NmsSlot *child_slot = &runtime->slots[child_index];\n"
"                if (!--child_slot->references) {\n"
"                    child_slot->next_free = pending;\n"
"                    pending = child_index;\n"
"                }\n"
"            }\n"
"        }\n"
"        runtime->live_bytes -= slot->kind == NMS_SLOT_STRING ? slot->length : slot_storage_bytes(slot);\n"
"        runtime->live_objects--;\n"
"        deallocate(slot->data);\n"
"        slot->data = NULL; slot->length = 0; slot->capacity = 0;\n"
"        slot->kind = NMS_SLOT_FREE; slot->element_tag = 0; slot->vm_array_policy = 0; slot->record_ordinal = 0;\n"
"        slot->next_free = runtime->free_head; runtime->free_head = index;\n"
"    }\n"
"    return first_error;\n"
"}\n"
"/* I complete validation and scratch allocation before changing any owner.\n"
" * Trial counts identify external roots; graph edges do not become roots. */\n"
"static NmsStatus collect_with_workspace(NmsRuntime *runtime, uint64_t *trial,\n"
"                                        unsigned char *marked, uint32_t *queue) {\n"
"    uint64_t count = (uint64_t)runtime->capacity + 1;\n"
"    uint64_t bytes = 0, objects = 0;\n"
"    NmsStatus status = NMS_STATE;\n"
"    for (uint64_t i = 0; i < count; i++) {\n"
"        const NmsSlot *slot = &runtime->slots[i];\n"
"        trial[i] = slot->references; marked[i] = 0;\n"
"        if (!slot->references) {\n"
"            if (slot->kind != NMS_SLOT_FREE || slot->data || slot->length || slot->capacity) goto done;\n"
"            continue;\n"
"        }\n"
"        if (!i || slot->kind < NMS_SLOT_STRING || slot->kind > NMS_SLOT_RECORD) goto done;\n"
"        uint64_t storage;\n"
"        if (slot->kind == NMS_SLOT_STRING) {\n"
"            if (!slot->data) goto done;\n"
"            storage = slot->length;\n"
"        } else {\n"
"            if (slot->length > slot->capacity || (slot->capacity && !slot->data)) goto done;\n"
"            if (slot->kind == NMS_SLOT_PACKED_SCALAR_ARRAY && !packed_width(slot->element_tag)) goto done;\n"
"            if (slot->kind == NMS_SLOT_RECORD) {\n"
"                uint32_t index;\n"
"                if (record_slot(runtime, NMS_DYNAMIC | i, &index) != NMS_OK) goto done;\n"
"            }\n"
"            storage = slot_storage_bytes(slot);\n"
"            if (storage > SIZE_MAX) goto done;\n"
"        }\n"
"        if (storage > UINT64_MAX - bytes) goto done;\n"
"        bytes += storage; objects++;\n"
"    }\n"
"    if (objects != runtime->live_objects || bytes != runtime->live_bytes) goto done;\n"
"    for (uint64_t i = 1; i < count; i++) {\n"
"        const NmsSlot *slot = &runtime->slots[i];\n"
"        if (!slot_has_children(slot)) continue;\n"
"        for (uint32_t j = 0; j < slot->length; j++) {\n"
"            NmsValue child = slot_value(slot, j);\n"
"            if (value_valid(runtime, child) != NMS_OK) goto done;\n"
"            if (value_is_reference(child) && (child.payload & NMS_DYNAMIC)) {\n"
"                uint32_t index = (uint32_t)child.payload;\n"
"                if (!trial[index]) goto done;\n"
"                trial[index]--;\n"
"            }\n"
"        }\n"
"    }\n"
"    uint64_t head = 0, tail = 0;\n"
"    for (uint64_t i = 1; i < count; i++) if (trial[i]) {\n"
"        marked[i] = 1; queue[tail++] = (uint32_t)i;\n"
"    }\n"
"    while (head < tail) {\n"
"        const NmsSlot *slot = &runtime->slots[queue[head++]];\n"
"        if (!slot_has_children(slot)) continue;\n"
"        for (uint32_t j = 0; j < slot->length; j++) {\n"
"            NmsValue child = slot_value(slot, j);\n"
"            if (!value_is_reference(child) || !(child.payload & NMS_DYNAMIC)) continue;\n"
"            uint32_t index = (uint32_t)child.payload;\n"
"            if (!marked[index]) { marked[index] = 1; queue[tail++] = index; }\n"
"        }\n"
"    }\n"
"    /* Every marked slot is reached from an external owner. Removing only\n"
"     * dead-to-live edges therefore cannot remove its final live owner. */\n"
"    for (uint64_t i = 1; i < count; i++) {\n"
"        const NmsSlot *slot = &runtime->slots[i];\n"
"        if (marked[i] || !slot->references ||\n"
"            !slot_has_children(slot)) continue;\n"
"        for (uint32_t j = 0; j < slot->length; j++) {\n"
"            NmsValue child = slot_value(slot, j);\n"
"            if (value_is_reference(child) && (child.payload & NMS_DYNAMIC)) {\n"
"                uint32_t index = (uint32_t)child.payload;\n"
"                if (marked[index]) runtime->slots[index].references--;\n"
"            }\n"
"        }\n"
"    }\n"
"    for (uint64_t i = 1; i < count; i++) {\n"
"        NmsSlot *slot = &runtime->slots[i];\n"
"        if (marked[i] || !slot->references) continue;\n"
"        runtime->live_bytes -= slot->kind == NMS_SLOT_STRING ? slot->length : slot_storage_bytes(slot);\n"
"        runtime->live_objects--; deallocate(slot->data);\n"
"        slot->data = NULL; slot->references = 0; slot->length = 0; slot->capacity = 0;\n"
"        slot->kind = NMS_SLOT_FREE; slot->element_tag = 0; slot->vm_array_policy = 0; slot->record_ordinal = 0;\n"
"        slot->next_free = runtime->free_head; runtime->free_head = (uint32_t)i;\n"
"    }\n"
"    status = NMS_OK;\n"
" done:\n"
"    return status;\n"
"}\n"
"static NmsStatus collection_ready(const NmsRuntime *runtime) {\n"
"    if (!runtime) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (!runtime->capacity)\n"
"        return !runtime->slots && !runtime->live_objects && !runtime->live_bytes ? NMS_OK : NMS_STATE;\n"
"    return runtime->slots ? NMS_OK : NMS_STATE;\n"
"}\n"
"NmsStatus nms_collect(NmsRuntime *runtime) {\n"
"    NmsStatus status = collection_ready(runtime);\n"
"    if (status != NMS_OK || !runtime->capacity) return status;\n"
"    uint64_t count = (uint64_t)runtime->capacity + 1;\n"
"    if (count > SIZE_MAX / sizeof(uint64_t) || count > SIZE_MAX / sizeof(uint32_t)) return NMS_MEMORY;\n"
"    uint64_t *trial = allocate(runtime, count * sizeof(uint64_t));\n"
"    unsigned char *marked = allocate(runtime, count);\n"
"    uint32_t *queue = allocate(runtime, count * sizeof(uint32_t));\n"
"    status = trial && marked && queue ? collect_with_workspace(runtime, trial, marked, queue) : NMS_MEMORY;\n"
"    deallocate(queue); deallocate(marked); deallocate(trial);\n"
"    return status;\n"
"}\n"
"NmsStatus nms_collect_prepared(NmsRuntime *runtime) {\n"
"    NmsStatus status = collection_ready(runtime);\n"
"    if (status != NMS_OK) return status;\n"
"    if (!runtime->collection_prepared || !runtime->collection_workspace ||\n"
"        runtime->collection_capacity < runtime->capacity) return NMS_STATE;\n"
"    if (!runtime->capacity) return NMS_OK;\n"
"    uint64_t marks, queue, bytes;\n"
"    if (!collection_layout(runtime->collection_capacity, &marks, &queue, &bytes)) return NMS_STATE;\n"
"    unsigned char *workspace = runtime->collection_workspace;\n"
"    return collect_with_workspace(runtime, (uint64_t *)workspace, workspace + marks,\n"
"                                  (uint32_t *)(workspace + queue));\n"
"}\n"
"NmsStatus nms_begin(NmsRuntime *runtime) {\n"
"    if (!runtime) return NMS_STATE;\n"
"    if (runtime->disposed) return NMS_DISPOSED;\n"
"    if (runtime->active) return NMS_BUSY;\n"
"    runtime->active = 1;\n"
"    return NMS_OK;\n"
"}\n"
"uint64_t nms_finish(NmsRuntime *runtime, NmsStatus status, int32_t result) {\n"
"    if (!runtime || !runtime->active) return (uint64_t)NMS_STATE << 32;\n"
"    runtime->active = 0;\n"
"    if ((unsigned)status > NMS_BOUNDS) status = NMS_STATE;\n"
"    return ((uint64_t)status << 32) | (status == NMS_OK ? (uint32_t)result : 0);\n"
"}\n"
"NmsStatus nms_dispose(NmsRuntime *runtime) {\n"
"    if (!runtime) return NMS_STATE;\n"
"    if (runtime->active) return NMS_BUSY;\n"
"    if (runtime->disposed) return NMS_OK;\n"
"    /* Terminal instance disposal invalidates all context-local handles.\n"
"     * Later lowering must first release frame/global roots normally. */\n"
"    for (uint64_t i = 1; i <= runtime->capacity; i++)\n"
"        if (runtime->slots[i].references) deallocate(runtime->slots[i].data);\n"
"    deallocate(runtime->slots);\n"
"    deallocate(runtime->collection_workspace);\n"
"    runtime->collection_workspace = NULL;\n"
"    runtime->collection_capacity = runtime->collection_prepared = 0;\n"
"    runtime->slots = NULL; runtime->capacity = runtime->free_head = 0;\n"
"    runtime->live_bytes = runtime->live_objects = 0;\n"
"    runtime->record_descriptors = NULL;\n"
"    runtime->record_count = runtime->records_bound = 0;\n"
"    runtime->disposed = 1;\n"
"    return NMS_OK;\n"
"}\n"
"int nms_reserved_entry(const char *name) {\n"
"    if (!name) return 0;\n"
"    const char *reserved[] = {\"nano_try_entry\", \"nano_dispose\", \"nano_runtime_\", \"nms_\"};\n"
"    for (unsigned i = 0; i < sizeof reserved / sizeof reserved[0]; i++) {\n"
"        unsigned n = 0;\n"
"        while (reserved[i][n] && name[n] == reserved[i][n]) n++;\n"
"        if (!reserved[i][n] && (i >= 2 || !name[n])) return 1;\n"
"    }\n"
"    return 0;\n"
"}\n"
"#ifdef NMS_TESTING\n"
"void nms_test_fail_after(NmsRuntime *runtime, uint64_t count) { runtime->fail_after = count; }\n"
"uint64_t nms_test_live_allocations(void) { return live_allocations; }\n"
"uint64_t nms_test_memory_pages(void) {\n"
"#ifdef __wasm32__\n"
"    return __builtin_wasm_memory_size(0);\n"
"#else\n"
"    return 0;\n"
"#endif\n"
"}\n"
"#endif\n"
"\n"
"/* I compare complete byte views, including embedded zero bytes. */\n"
"static int equal_bytes(const unsigned char *left, const unsigned char *right, uint32_t length) {\n"
"    for (uint32_t i = 0; i < length; i++)\n"
"        if (left[i] != right[i]) return 0;\n"
"    return 1;\n"
"}\n"
"static int find_bytes(NmsView source, NmsView needle, uint32_t start, uint32_t *found) {\n"
"    if (!needle.length || start > source.length || needle.length > source.length - start)\n"
"        return 0;\n"
"    uint32_t last = source.length - needle.length;\n"
"    for (uint32_t position = start; position <= last; position++) {\n"
"        if (equal_bytes(source.data + position, needle.data, needle.length)) {\n"
"            *found = position;\n"
"            return 1;\n"
"        }\n"
"    }\n"
"    return 0;\n"
"}\n"
"static NmsStatus append_segment(NmsRuntime *runtime, NmsHandle array,\n"
"                                 const unsigned char *bytes, uint32_t length, int values) {\n"
"    NmsHandle child = 0;\n"
"    NmsStatus status = nms_create(runtime, bytes, length, &child);\n"
"    if (status != NMS_OK) return status;\n"
"    status = values ? nms_value_array_append(runtime, array, (NmsValue){child, 5}) :\n"
"                      nms_string_array_append(runtime, array, child);\n"
"    NmsStatus released = nms_release(runtime, child);\n"
"    return status != NMS_OK ? status : released;\n"
"}\n"
"static NmsStatus split_owned(NmsRuntime *runtime, NmsHandle source, NmsHandle delimiter,\n"
"                               NmsHandle *out, int values) {\n"
"    NmsView a, b;\n"
"    NmsHandle array = 0;\n"
"    NmsStatus status = out ? nms_view(runtime, source, &a) : NMS_STATE;\n"
"    if (status == NMS_OK) status = nms_view(runtime, delimiter, &b);\n"
"    if (status == NMS_OK) status = values ? nms_vm_array_create(runtime, 5, &array) :\n"
"                                          nms_string_array_create(runtime, &array);\n"
"    if (status == NMS_OK && !b.length) {\n"
"        for (uint32_t i = 0; i < a.length && status == NMS_OK; i++)\n"
"            status = append_segment(runtime, array, a.data + i, 1, values);\n"
"    } else if (status == NMS_OK) {\n"
"        uint32_t position = 0, found = 0;\n"
"        while (status == NMS_OK && find_bytes(a, b, position, &found)) {\n"
"            status = append_segment(runtime, array, a.data + position, found - position, values);\n"
"            position = found + b.length;\n"
"        }\n"
"        if (status == NMS_OK)\n"
"            status = append_segment(runtime, array, a.data + position, a.length - position, values);\n"
"    }\n"
"    /* Views point at retained byte buffers, never relocated slot-table cells.\n"
"     * I finish every read before consuming either input owner. */\n"
"    NmsStatus left = nms_release(runtime, source);\n"
"    NmsStatus right = nms_release(runtime, delimiter);\n"
"    if (status == NMS_OK) status = left != NMS_OK ? left : right;\n"
"    if (status != NMS_OK) {\n"
"        if (array) nms_release(runtime, array);\n"
"        return status;\n"
"    }\n"
"    *out = array;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_split_owned(NmsRuntime *runtime, NmsHandle source, NmsHandle delimiter,\n"
"                          NmsHandle *out) {\n"
"    return split_owned(runtime, source, delimiter, out, 0);\n"
"}\n"
"NmsStatus nms_split_values_owned(NmsRuntime *runtime, NmsHandle source, NmsHandle delimiter,\n"
"                                 NmsHandle *out) {\n"
"    return split_owned(runtime, source, delimiter, out, 1);\n"
"}\n"
"NmsStatus nms_replace_owned(NmsRuntime *runtime, NmsHandle source, NmsHandle needle,\n"
"                            NmsHandle replacement, NmsHandle *out) {\n"
"    NmsView a, b, c;\n"
"    NmsHandle result = 0;\n"
"    unsigned char *scratch = NULL;\n"
"    NmsStatus status = out ? nms_view(runtime, source, &a) : NMS_STATE;\n"
"    if (status == NMS_OK) status = nms_view(runtime, needle, &b);\n"
"    if (status == NMS_OK) status = nms_view(runtime, replacement, &c);\n"
"    if (status == NMS_OK && !b.length) {\n"
"        status = nms_create(runtime, a.data, a.length, &result);\n"
"    } else if (status == NMS_OK) {\n"
"        uint64_t count = 0;\n"
"        uint32_t position = 0, found;\n"
"        while (find_bytes(a, b, position, &found)) {\n"
"            count++;\n"
"            position = found + b.length;\n"
"        }\n"
"        uint32_t length = 0;\n"
"        if (count > a.length / b.length) status = NMS_STATE;\n"
"        else {\n"
"            uint32_t remaining = a.length - (uint32_t)count * b.length;\n"
"            if (c.length && count > (UINT32_MAX - remaining) / c.length) status = NMS_MEMORY;\n"
"            else length = remaining + (uint32_t)count * c.length;\n"
"        }\n"
"        if (status == NMS_OK && (uint64_t)length + 1 > SIZE_MAX) status = NMS_MEMORY;\n"
"        if (status == NMS_OK) {\n"
"            scratch = allocate(runtime, (uint64_t)length + 1);\n"
"            if (!scratch) status = NMS_MEMORY;\n"
"        }\n"
"        if (status == NMS_OK) {\n"
"            uint32_t written = 0;\n"
"            position = 0;\n"
"            while (find_bytes(a, b, position, &found)) {\n"
"                uint32_t segment = found - position;\n"
"                copy_bytes(scratch + written, a.data + position, segment);\n"
"                written += segment;\n"
"                copy_bytes(scratch + written, c.data, c.length);\n"
"                written += c.length;\n"
"                position = found + b.length;\n"
"            }\n"
"            copy_bytes(scratch + written, a.data + position, a.length - position);\n"
"            scratch[length] = 0;\n"
"            /* All three immutable byte views remain owned through this copy;\n"
"             * descriptor-table relocation cannot invalidate their storage. */\n"
"            status = nms_create(runtime, scratch, length, &result);\n"
"        }\n"
"    }\n"
"    deallocate(scratch);\n"
"    NmsStatus sa = nms_release(runtime, source);\n"
"    NmsStatus sb = nms_release(runtime, needle);\n"
"    NmsStatus sc = nms_release(runtime, replacement);\n"
"    if (status != NMS_OK) return status;\n"
"    if (sa != NMS_OK || sb != NMS_OK || sc != NMS_OK) {\n"
"        nms_release(runtime, result);\n"
"        return sa != NMS_OK ? sa : sb != NMS_OK ? sb : sc;\n"
"    }\n"
"    *out = result;\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_char_at(const NmsRuntime *runtime, NmsHandle source,\n"
"                      uint64_t index_bits, uint32_t is_integer, int64_t *out) {\n"
"    if (!out || is_integer > 1) return NMS_STATE;\n"
"    NmsView view;\n"
"    NmsStatus status = nms_view(runtime, source, &view);\n"
"    if (status != NMS_OK) return status;\n"
"    uint64_t index = is_integer ? index_bits : 0;\n"
"    *out = (index & (UINT64_C(1) << 63)) || index >= view.length\n"
"         ? -1 : (int64_t)view.data[(uint32_t)index];\n"
"    return NMS_OK;\n"
"}\n"
"NmsStatus nms_predicate(const NmsRuntime *runtime, NmsHandle source, NmsHandle affix,\n"
"                        uint32_t operation, uint32_t *out) {\n"
"    if (!out || operation > NMS_ENDS_WITH) return NMS_STATE;\n"
"    NmsView haystack, needle;\n"
"    NmsStatus status = nms_view(runtime, source, &haystack);\n"
"    if (status != NMS_OK) return status;\n"
"    status = nms_view(runtime, affix, &needle);\n"
"    if (status != NMS_OK) return status;\n"
"    uint32_t answer = 0;\n"
"    if (needle.length == 0) answer = 1;\n"
"    else if (needle.length <= haystack.length) {\n"
"        uint32_t last = haystack.length - needle.length;\n"
"        if (operation == NMS_STARTS_WITH)\n"
"            answer = equal_bytes(haystack.data, needle.data, needle.length);\n"
"        else if (operation == NMS_ENDS_WITH)\n"
"            answer = equal_bytes(haystack.data + last, needle.data, needle.length);\n"
"        else {\n"
"            /* A nonempty needle makes last < UINT32_MAX; increment cannot wrap. */\n"
"            for (uint32_t position = 0; position <= last; position++) {\n"
"                if (equal_bytes(haystack.data + position, needle.data, needle.length)) {\n"
"                    answer = 1;\n"
"                    break;\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"    *out = answer;\n"
"    return NMS_OK;\n"
"}\n"
;
#endif
