#ifndef NANOISA_SERVICES_INDIRECT_NATIVE_ABI_H
#define NANOISA_SERVICES_INDIRECT_NATIVE_ABI_H
#include "services_indirect_runtime.h"
#define NVM_SERVICES_INDIRECT_NATIVE_ABI 1u
#define NVM_SERVICES_INDIRECT_NATIVE_OUTPUT_BYTES (128u*1024u*1024u)
#endif
