#include "socket_runtime.h"
#include "socket_runtime_frames.h"
#include "socket_cyclic_runtime.h"
#include "socket_indirect_runtime.h"
#include "../nsi_socket_values.h"
#include "nvm_v2_sections.h"
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include "socket_runtime_config.h"
#include "service_runtime.inc"
