#ifndef NANOISA_SOCKET_INDIRECT_NATIVE_ABI_H
#define NANOISA_SOCKET_INDIRECT_NATIVE_ABI_H
#include "socket_indirect_runtime.h"
#define NVM_SOCKET_INDIRECT_NATIVE_ABI 1u
#define NVM_SOCKET_INDIRECT_NATIVE_OUTPUT_BYTES (128u*1024u*1024u)
#endif
