#ifndef NANOISA_WEBSOCKET_INDIRECT_NATIVE_ABI_H
#define NANOISA_WEBSOCKET_INDIRECT_NATIVE_ABI_H
#include "websocket_indirect_runtime.h"
#define NVM_WEBSOCKET_INDIRECT_NATIVE_ABI 1u
#define NVM_WEBSOCKET_INDIRECT_NATIVE_OUTPUT_BYTES (128u*1024u*1024u)
#endif
