#include "websocket_codec.h"
#define HOSTED_DESERIALIZE nvm_websocket_deserialize
#define HOSTED_TO_MODULE nvm_websocket_to_module
#include "websocket_flow_config.h"
#include "service_flow.inc"
#include "websocket_code.h"
#include "service_code.inc"
#include "websocket_body.h"
#include "service_body.inc"
#include "websocket_hosted.h"
#include "service_hosted.inc"
#include "websocket_cyclic.h"
#include "service_cyclic.inc"
#include "websocket_cyclic_hosted.h"
#include "service_cyclic_hosted.inc"
#include "websocket_indirect_targets.h"
#include "service_indirect_targets.inc"
#include "websocket_indirect_flow.h"
#include "service_indirect_flow.inc"
#include "websocket_indirect_hosted.h"
#include "service_indirect_hosted.inc"
