#!/usr/bin/env python3
"""Generate the NanoVM FFI mixed-signature dispatch table.

Roadmap 4.0, Phase 12 (FFI and traps): "use generated typed stubs or a general
ABI layer for mixed integer and floating signatures."

The problem this solves: the C ABI (SysV x86-64, AArch64 AAPCS, ...) passes
integer/pointer arguments in general-purpose registers and floating-point
arguments in a *separate* bank of FP/SIMD registers. A dispatcher that casts
every argument to ``void*`` therefore places ``double`` values in the wrong
register class, silently corrupting any imported C function whose signature
mixes integer and floating parameters.

Rather than depend on libffi (an external build dependency that is not always
present), we generate correctly-typed function-pointer stubs for every
combination of argument classes up to ``MAX_ARITY``. Each argument is either

  * a general-purpose slot ('i'): passed as ``long`` (covers int, bool,
    string/char*, opaque pointer, array pointer), or
  * a floating-point slot ('f'): passed as ``double``.

The compiler then emits the ABI-correct calling sequence for each stub, so the
host C function receives every argument in the register class its real
signature expects. Return values are likewise dispatched by class (``int64_t``
for GP returns, ``double`` for FP returns).

Run manually or via the Makefile; the output is checked in so builds do not
require Python at compile time. Use ``--check`` to verify the committed file is
up to date.
"""

import argparse
import io
import itertools
import os
import sys

# Highest arity for which we emit fully-typed mixed stubs. Arities above this
# fall back to the all-GP or all-FP fast paths (which remain ABI-correct for
# homogeneous signatures). Six covers essentially all real FFI signatures while
# keeping the generated table small.
MAX_ARITY = 6

HEADER = """/* Generated by scripts/gen_ffi_dispatch.py. Do not edit.
 *
 * Mixed integer/floating FFI dispatch: correctly-typed function-pointer stubs
 * for every general-purpose (i) / floating-point (f) argument-class pattern up
 * to arity %d. See scripts/gen_ffi_dispatch.py for the rationale (ABI register
 * classes for int vs. float arguments).
 */
#ifndef NANOVM_FFI_DISPATCH_GENERATED_H
#define NANOVM_FFI_DISPATCH_GENERATED_H

#include <stdint.h>

#define FFI_DISPATCH_MAX_ARITY %d

/* A classified argument: either a general-purpose (long/pointer) slot or a
 * floating-point (double) slot. The dispatcher fills these from NanoValues. */
typedef struct {
    int is_float;   /* 1 => use .f (double); 0 => use .i (long/pointer) */
    long   i;
    double f;
} FfiArgSlot;
"""

FOOTER = """
#endif /* NANOVM_FFI_DISPATCH_GENERATED_H */
"""


def ctype(cls):
    return "double" if cls == "f" else "long"


def emit(out):
    out.write(HEADER % (MAX_ARITY, MAX_ARITY))

    # For each return class (i = int64_t, f = double) and each argument-class
    # pattern, emit one dispatch case behind a single entry point.
    #
    # ffi_dispatch_gp(): GP (int64_t) return.
    # ffi_dispatch_fp(): FP (double)  return.
    for ret_cls, ret_c, fn_name in (("i", "int64_t", "ffi_dispatch_gp"),
                                    ("f", "double", "ffi_dispatch_fp")):
        out.write("\n/* %s: dispatch a call whose return is %s. "
                  "Returns 1 on success, 0 if the (arity, pattern) is "
                  "unsupported. */\n" % (fn_name, ret_c))
        out.write("static inline int %s(void *fn, const FfiArgSlot *a, "
                  "int argc, %s *out) {\n" % (fn_name, ret_c))
        out.write("    switch (argc) {\n")
        for arity in range(0, MAX_ARITY + 1):
            out.write("    case %d: {\n" % arity)
            # Build a selector integer from the per-arg classes so we can switch.
            if arity == 0:
                patterns = [()]
            else:
                patterns = list(itertools.product("if", repeat=arity))
            if arity > 0:
                out.write("        int sel = 0;\n")
                for i in range(arity):
                    out.write("        sel |= (a[%d].is_float ? 1 : 0) << %d;\n"
                              % (i, i))
                out.write("        switch (sel) {\n")
            for pat in patterns:
                sel = 0
                for i, c in enumerate(pat):
                    if c == "f":
                        sel |= (1 << i)
                params = ", ".join(ctype(c) for c in pat) if pat else "void"
                cast = "(%s (*)(%s))fn" % (ret_c, params)
                call_args = ", ".join(
                    ("a[%d].f" % i) if c == "f" else ("a[%d].i" % i)
                    for i, c in enumerate(pat))
                body = "*out = (%s)((%s)(%s)); return 1;" % (
                    ret_c, cast, call_args)
                if arity == 0:
                    out.write("        %s\n" % body)
                else:
                    out.write("        case %d: %s\n" % (sel, body))
            if arity > 0:
                out.write("        default: return 0;\n")
                out.write("        }\n")
            out.write("    }\n")
        out.write("    default: return 0;\n")
        out.write("    }\n")
        out.write("}\n")

    out.write(FOOTER)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify the checked-in file matches; exit 1 if stale")
    ap.add_argument("--output",
                    default=os.path.join(os.path.dirname(__file__), "..",
                                         "src", "nanovm",
                                         "ffi_dispatch_generated.h"))
    args = ap.parse_args()

    buf = io.StringIO()
    emit(buf)
    generated = buf.getvalue()

    out_path = os.path.abspath(args.output)
    if args.check:
        try:
            with open(out_path, "r", encoding="utf-8") as f:
                current = f.read()
        except FileNotFoundError:
            current = None
        if current != generated:
            sys.stderr.write(
                "%s is out of date; run scripts/gen_ffi_dispatch.py\n"
                % out_path)
            return 1
        return 0

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(generated)
    return 0


if __name__ == "__main__":
    sys.exit(main())
