#!/usr/bin/env python3
"""Generate active NanoISA metadata from the normative v2 design schema."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "spec/nanoisa.yaml"
OUTPUT = ROOT / "src/nanoisa/generated_schema.h"

# Paired operations must name identical operand forms so that reading and
# writing an addressable slot decode the same way (symmetric operand forms).
SYMMETRIC_PAIRS = (
    ("local.get", "local.set"),
    ("global.get", "global.set"),
    ("upvalue.get", "upvalue.set"),
    ("aggregate.get", "aggregate.set"),
    ("mem.load8", "mem.store8"),
    ("mem.load16", "mem.store16"),
    ("mem.load32", "mem.store32"),
    ("mem.load64", "mem.store64"),
)


def c_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).upper().strip("_")


def c_string(text: str) -> str:
    """Escape a Python string for safe inclusion in a C string literal."""
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def families_of(schema: dict) -> list:
    return [item for group in schema["instruction_families"].values() for item in group]


def validate(schema: dict) -> None:
    """Enforce the portable-ISA contract: one comprehensible meaning per
    instruction and symmetric operand forms drawn from declared operand kinds."""
    kinds = {kind["name"] for kind in schema["operand_kinds"]}
    families = families_of(schema)

    names = [family["name"] for family in families]
    if len(names) != len(set(names)):
        raise ValueError("instruction family names are not unique")

    meanings: dict[str, str] = {}
    by_name = {}
    for family in families:
        name = family["name"]
        by_name[name] = family

        meaning = family.get("meaning")
        if not isinstance(meaning, str) or not meaning.strip():
            raise ValueError(f"{name} is missing a comprehensible meaning")
        if meaning in meanings:
            raise ValueError(
                f"{name} shares its meaning with {meanings[meaning]}; "
                "each instruction needs one distinct meaning"
            )
        meanings[meaning] = name

        for operand in family.get("operands", []):
            if operand not in kinds:
                raise ValueError(
                    f"{name} uses operand '{operand}' that is not a declared "
                    "operand kind; operand forms must be symmetric and named"
                )

    for load_like, store_like in SYMMETRIC_PAIRS:
        if load_like not in by_name or store_like not in by_name:
            raise ValueError(
                f"symmetric pair {load_like}/{store_like} is incomplete"
            )
        left = by_name[load_like].get("operands", [])
        right = by_name[store_like].get("operands", [])
        if left != right:
            raise ValueError(
                f"{load_like} and {store_like} must share operand forms, "
                f"got {left} vs {right}"
            )


def generate(schema: dict) -> str:
    validate(schema)
    tags = schema["value_tags"]
    opcodes = schema["legacy_opcodes"]
    families = families_of(schema)
    lines = [
        "/* Generated by scripts/gen_nanoisa_schema.py. Do not edit. */",
        "#ifndef NANOISA_GENERATED_SCHEMA_H",
        "#define NANOISA_GENERATED_SCHEMA_H",
        "",
        f"#define NANOISA_SCHEMA_VERSION {schema['version']}",
        f"#define NANOISA_LEGACY_OPCODE_COUNT {len(opcodes)}",
        f"#define NANOISA_V2_FAMILY_COUNT {len(families)}",
        "",
        "static const NanoisaSchemaTag nanoisa_schema_tags[] = {",
    ]
    lines.extend(f'    {{"{tag["name"]}", 0x{tag["code"]:02x}}},' for tag in tags)
    lines.extend(["};", "", "static const NanoisaSchemaOpcode nanoisa_schema_opcodes[] = {"])
    for opcode in opcodes:
        operands = opcode.get("operands", [])
        padded = operands + ["NONE"] * (4 - len(operands))
        rendered = ", ".join(f"OPERAND_{operand}" for operand in padded)
        lines.append(
            f'    {{"{opcode["name"]}", 0x{opcode["code"]:02x}, '
            f'{len(operands)}, {{{rendered}}}}},'
        )
    lines.extend(["};", "", "static const NanoisaV2Family nanoisa_v2_families[] = {"])
    for item in families:
        lines.append(
            f'    {{{c_string(item["name"])}, {c_string(item["meaning"])}, '
            f'{c_string(item["ownership"])}, '
            f'{len(item.get("operands", []))}, {len(item.get("pops", []))}, '
            f'{len(item.get("pushes", []))}}},'
        )
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(yaml.safe_load(SCHEMA.read_text()))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date")
            return 1
        return 0
    OUTPUT.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
