#!/usr/bin/env python3
"""Generate active NanoISA metadata from the normative v2 design schema."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "spec/nanoisa.yaml"
OUTPUT = ROOT / "src/nanoisa/generated_schema.h"


def c_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).upper().strip("_")


def c_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def generate(schema: dict) -> str:
    tags = schema["value_tags"]
    opcodes = schema["legacy_opcodes"]
    operand_kinds = schema["operand_kinds"]
    families = [item for group in schema["instruction_families"].values() for item in group]
    lines = [
        "/* Generated by scripts/gen_nanoisa_schema.py. Do not edit. */",
        "#ifndef NANOISA_GENERATED_SCHEMA_H",
        "#define NANOISA_GENERATED_SCHEMA_H",
        "",
        f"#define NANOISA_SCHEMA_VERSION {schema['version']}",
        f"#define NANOISA_LEGACY_OPCODE_COUNT {len(opcodes)}",
        f"#define NANOISA_OPERAND_KIND_COUNT {len(operand_kinds)}",
        f"#define NANOISA_V2_FAMILY_COUNT {len(families)}",
        "",
        "static const NanoisaSchemaTag nanoisa_schema_tags[] = {",
    ]
    lines.extend(f'    {{"{tag["name"]}", 0x{tag["code"]:02x}}},' for tag in tags)
    lines.extend(["};", "", "static const NanoisaSchemaOpcode nanoisa_schema_opcodes[] = {"])
    for opcode in opcodes:
        operands = opcode.get("operands", [])
        padded = operands + ["NONE"] * (4 - len(operands))
        rendered = ", ".join(f"OPERAND_{operand}" for operand in padded)
        lines.append(
            f'    {{"{opcode["name"]}", 0x{opcode["code"]:02x}, '
            f'{len(operands)}, {{{rendered}}}}},'
        )
    lines.extend(["};", "", "static const NanoisaOperandKind nanoisa_operand_kinds[] = {"])
    for kind in operand_kinds:
        lines.append(
            f'    {{{c_string(kind["name"])}, {c_string(kind["encoding"])}, '
            f'{c_string(kind["meaning"])}}},'
        )
    lines.extend(["};", "", "static const NanoisaV2Family nanoisa_v2_families[] = {"])
    for item in families:
        lines.append(
            f'    {{{c_string(item["name"])}, {c_string(item["ownership"])}, '
            f'{c_string(item["meaning"])}, '
            f'{len(item.get("operands", []))}, {len(item.get("pops", []))}, '
            f'{len(item.get("pushes", []))}}},'
        )
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(yaml.safe_load(SCHEMA.read_text()))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date")
            return 1
        return 0
    OUTPUT.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
