#!/usr/bin/env python3
"""Generate active NanoISA metadata from the normative v2 design schema."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "spec/nanoisa.yaml"
OUTPUT = ROOT / "src/nanoisa/generated_schema.h"


def c_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).upper().strip("_")


def generate(schema: dict) -> str:
    tags = schema["value_tags"]
    opcodes = schema["legacy_opcodes"]
    effects = schema.get("legacy_stack_effects", {})
    families = [item for group in schema["instruction_families"].values() for item in group]
    lines = [
        "/* Generated by scripts/gen_nanoisa_schema.py. Do not edit. */",
        "#ifndef NANOISA_GENERATED_SCHEMA_H",
        "#define NANOISA_GENERATED_SCHEMA_H",
        "",
        f"#define NANOISA_SCHEMA_VERSION {schema['version']}",
        f"#define NANOISA_LEGACY_OPCODE_COUNT {len(opcodes)}",
        f"#define NANOISA_V2_FAMILY_COUNT {len(families)}",
        "",
        "static const NanoisaSchemaTag nanoisa_schema_tags[] = {",
    ]
    lines.extend(f'    {{"{tag["name"]}", 0x{tag["code"]:02x}}},' for tag in tags)
    lines.extend(["};", "", "static const NanoisaSchemaOpcode nanoisa_schema_opcodes[] = {"])
    for opcode in opcodes:
        operands = opcode.get("operands", [])
        padded = operands + ["NONE"] * (4 - len(operands))
        rendered = ", ".join(f"OPERAND_{operand}" for operand in padded)
        lines.append(
            f'    {{"{opcode["name"]}", 0x{opcode["code"]:02x}, '
            f'{len(operands)}, {{{rendered}}}}},'
        )
    lines.extend(["};", "", "static const NanoisaStackEffect nanoisa_legacy_stack_effects[256] = {"])
    by_code = {opcode["code"]: effects.get(opcode["name"], {"pops": -1, "pushes": -1})
               for opcode in opcodes}
    for code in range(256):
        effect = by_code.get(code, {"pops": -1, "pushes": -1})
        lines.append(f'    {{{effect["pops"]}, {effect["pushes"]}}},')
    lines.extend(["};", "", "static const NanoisaV2Family nanoisa_v2_families[] = {"])
    for item in families:
        lines.append(
            f'    {{"{item["name"]}", "{item["ownership"]}", '
            f'{len(item.get("operands", []))}, {len(item.get("pops", []))}, '
            f'{len(item.get("pushes", []))}}},'
        )
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(yaml.safe_load(SCHEMA.read_text()))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date")
            return 1
        return 0
    OUTPUT.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
