# I derive this list from scripts/native_sdk_objects.json.
NATIVE_SDK_OBJECTS = \
  $(OBJ_DIR)/builtins_registry.o \
  $(OBJ_DIR)/cJSON.o \
  $(OBJ_DIR)/coroutine.o \
  $(OBJ_DIR)/effects.o \
  $(OBJ_DIR)/env.o \
  $(OBJ_DIR)/eval.o \
  $(OBJ_DIR)/eval/eval_hashmap.o \
  $(OBJ_DIR)/eval/eval_io.o \
  $(OBJ_DIR)/eval/eval_math.o \
  $(OBJ_DIR)/eval/eval_string.o \
  $(OBJ_DIR)/interpreter_ffi.o \
  $(OBJ_DIR)/json_diagnostics.o \
  $(OBJ_DIR)/lexer.o \
  $(OBJ_DIR)/module.o \
  $(OBJ_DIR)/module_builder.o \
  $(OBJ_DIR)/module_metadata.o \
  $(OBJ_DIR)/nanoisa/affine_bytecode.o \
  $(OBJ_DIR)/nanoisa/affine_state.o \
  $(OBJ_DIR)/nanoisa/assembler.o \
  $(OBJ_DIR)/nanoisa/capture_bindings.o \
  $(OBJ_DIR)/nanoisa/disassembler.o \
  $(OBJ_DIR)/nanoisa/file_flow.o \
  $(OBJ_DIR)/nanoisa/isa.o \
  $(OBJ_DIR)/nanoisa/local_bindings.o \
  $(OBJ_DIR)/nanoisa/managed_array_shapes.o \
  $(OBJ_DIR)/nanoisa/mixed_float_proof.o \
  $(OBJ_DIR)/nanoisa/nanoisa_facade.o \
  $(OBJ_DIR)/nanoisa/nvm_format.o \
  $(OBJ_DIR)/nanoisa/nvm_format_v2.o \
  $(OBJ_DIR)/nanoisa/nvm_v2_constants.o \
  $(OBJ_DIR)/nanoisa/nvm_v2_convert.o \
  $(OBJ_DIR)/nanoisa/nvm_v2_cursor.o \
  $(OBJ_DIR)/nanoisa/nvm_v2_functions.o \
  $(OBJ_DIR)/nanoisa/nvm_v2_imports.o \
  $(OBJ_DIR)/nanoisa/nvm_v2_layouts.o \
  $(OBJ_DIR)/nanoisa/nvm_v2_module.o \
  $(OBJ_DIR)/nanoisa/nvm_v2_signatures.o \
  $(OBJ_DIR)/nanoisa/ownership_contracts.o \
  $(OBJ_DIR)/nanoisa/passive.o \
  $(OBJ_DIR)/nanoisa/reference_places.o \
  $(OBJ_DIR)/nanoisa/retained_layouts.o \
  $(OBJ_DIR)/nanoisa/service_bindings.o \
  $(OBJ_DIR)/nanoisa/service_bindings_module.o \
  $(OBJ_DIR)/nanoisa/service_file_nominal.o \
  $(OBJ_DIR)/nanoisa/service_file_nominal_plan.o \
  $(OBJ_DIR)/nanoisa/verifier.o \
  $(OBJ_DIR)/nanoisa/verifier_types.o \
  $(OBJ_DIR)/nanovm/binding_state.o \
  $(OBJ_DIR)/nanovm/cop_opaque.o \
  $(OBJ_DIR)/nanovm/cop_protocol.o \
  $(OBJ_DIR)/nanovm/heap.o \
  $(OBJ_DIR)/nanovm/heap_cycles.o \
  $(OBJ_DIR)/nanovm/value.o \
  $(OBJ_DIR)/nanovm/vm.o \
  $(OBJ_DIR)/nanovm/vm_builtins.o \
  $(OBJ_DIR)/nanovm/vm_callback.o \
  $(OBJ_DIR)/nanovm/vm_decode.o \
  $(OBJ_DIR)/nanovm/vm_dispatch.o \
  $(OBJ_DIR)/nanovm/vm_ffi.o \
  $(OBJ_DIR)/nanovm/vm_ffi_arrays.o \
  $(OBJ_DIR)/nanovm/vmd_client.o \
  $(OBJ_DIR)/nanovm/vmd_protocol.o \
  $(OBJ_DIR)/nominal_types.o \
  $(OBJ_DIR)/nsi_file_plan.o \
  $(OBJ_DIR)/parser.o \
  $(OBJ_DIR)/reflection.o \
  $(OBJ_DIR)/resource_flow.o \
  $(OBJ_DIR)/resource_tracking.o \
  $(OBJ_DIR)/runtime/callback_runtime.o \
  $(OBJ_DIR)/runtime/cli.o \
  $(OBJ_DIR)/runtime/dyn_array.o \
  $(OBJ_DIR)/runtime/effect_runtime.o \
  $(OBJ_DIR)/runtime/ffi_loader.o \
  $(OBJ_DIR)/runtime/gc.o \
  $(OBJ_DIR)/runtime/gc_struct.o \
  $(OBJ_DIR)/runtime/list_ASTArrayLiteral.o \
  $(OBJ_DIR)/runtime/list_ASTAssert.o \
  $(OBJ_DIR)/runtime/list_ASTBinaryOp.o \
  $(OBJ_DIR)/runtime/list_ASTBlock.o \
  $(OBJ_DIR)/runtime/list_ASTBool.o \
  $(OBJ_DIR)/runtime/list_ASTCall.o \
  $(OBJ_DIR)/runtime/list_ASTEnum.o \
  $(OBJ_DIR)/runtime/list_ASTFieldAccess.o \
  $(OBJ_DIR)/runtime/list_ASTFloat.o \
  $(OBJ_DIR)/runtime/list_ASTFor.o \
  $(OBJ_DIR)/runtime/list_ASTFunction.o \
  $(OBJ_DIR)/runtime/list_ASTIdentifier.o \
  $(OBJ_DIR)/runtime/list_ASTIf.o \
  $(OBJ_DIR)/runtime/list_ASTImport.o \
  $(OBJ_DIR)/runtime/list_ASTLet.o \
  $(OBJ_DIR)/runtime/list_ASTMatch.o \
  $(OBJ_DIR)/runtime/list_ASTModuleQualifiedCall.o \
  $(OBJ_DIR)/runtime/list_ASTNumber.o \
  $(OBJ_DIR)/runtime/list_ASTOpaqueType.o \
  $(OBJ_DIR)/runtime/list_ASTPrint.o \
  $(OBJ_DIR)/runtime/list_ASTReturn.o \
  $(OBJ_DIR)/runtime/list_ASTServiceDecl.o \
  $(OBJ_DIR)/runtime/list_ASTSet.o \
  $(OBJ_DIR)/runtime/list_ASTShadow.o \
  $(OBJ_DIR)/runtime/list_ASTStmtRef.o \
  $(OBJ_DIR)/runtime/list_ASTString.o \
  $(OBJ_DIR)/runtime/list_ASTStruct.o \
  $(OBJ_DIR)/runtime/list_ASTStructLiteral.o \
  $(OBJ_DIR)/runtime/list_ASTTupleIndex.o \
  $(OBJ_DIR)/runtime/list_ASTTupleLiteral.o \
  $(OBJ_DIR)/runtime/list_ASTUnion.o \
  $(OBJ_DIR)/runtime/list_ASTUnionConstruct.o \
  $(OBJ_DIR)/runtime/list_ASTUnsafeBlock.o \
  $(OBJ_DIR)/runtime/list_ASTWhile.o \
  $(OBJ_DIR)/runtime/list_CompilerDiagnostic.o \
  $(OBJ_DIR)/runtime/list_CompilerSourceLocation.o \
  $(OBJ_DIR)/runtime/list_LexerToken.o \
  $(OBJ_DIR)/runtime/list_int.o \
  $(OBJ_DIR)/runtime/list_string.o \
  $(OBJ_DIR)/runtime/list_token.o \
  $(OBJ_DIR)/runtime/module_build_dir.o \
  $(OBJ_DIR)/runtime/nl_string.o \
  $(OBJ_DIR)/runtime/regex.o \
  $(OBJ_DIR)/runtime/token_helpers.o \
  $(OBJ_DIR)/stdlib_runtime.o \
  $(OBJ_DIR)/toon_output.o \
  $(OBJ_DIR)/transpiler.o \
  $(OBJ_DIR)/typechecker.o \
  $(OBJ_DIR)/utf8.o
