/* Generated by nanolang self-hosted compiler */
#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE 1
#endif
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <time.h>
#include <ctype.h>
#include <sys/time.h>
#ifdef __MACH__
#include <mach/mach_time.h>
#endif
#include "nanolang.h"
#include "runtime/string_edges.h"
#include "collections/collections.h"
#include "json/json.h"
#include "runtime/hashmap_bootstrap.h"
#include "runtime/dyn_array.h"
#include "runtime/native_array_abi.h"
#include "runtime/list_int.h"
#include "runtime/list_string.h"
#include "runtime/list_token.h"
#include "runtime/list_LexerToken.h"
/* list_LexerToken compat aliases (unprefixed -> nl_ prefixed) */
#ifndef list_LexerToken_new
#define list_LexerToken_new  nl_list_LexerToken_new
#define list_LexerToken_push nl_list_LexerToken_push
#define list_LexerToken_get  nl_list_LexerToken_get
#define list_LexerToken_length nl_list_LexerToken_length
#endif
#include "runtime/list_CompilerDiagnostic.h"
#include "runtime/list_CompilerSourceLocation.h"
#include "runtime/token_helpers.h"
#include "runtime/list_ASTLet.h"
#include "runtime/list_ASTFunction.h"
#include "runtime/list_ASTNumber.h"
#include "runtime/list_ASTFloat.h"
#include "runtime/list_ASTString.h"
#include "runtime/list_ASTBool.h"
#include "runtime/list_ASTIdentifier.h"
#include "runtime/list_ASTBinaryOp.h"
#include "runtime/list_ASTCall.h"
#include "runtime/list_ASTArrayLiteral.h"
#include "runtime/list_ASTSet.h"
#include "runtime/list_ASTIf.h"
#include "runtime/list_ASTWhile.h"
#include "runtime/list_ASTFor.h"
#include "runtime/list_ASTReturn.h"
#include "runtime/list_ASTStmtRef.h"
#include "runtime/list_ASTBlock.h"
#include "runtime/list_ASTUnsafeBlock.h"
#include "runtime/list_ASTPrint.h"
#include "runtime/list_ASTAssert.h"
#include "runtime/list_ASTShadow.h"
#include "runtime/list_ASTStruct.h"
#include "runtime/list_ASTStructLiteral.h"
#include "runtime/list_ASTFieldAccess.h"
#include "runtime/list_ASTEnum.h"
#include "runtime/list_ASTUnion.h"
#include "runtime/list_ASTUnionConstruct.h"
#include "runtime/list_ASTMatch.h"
#include "runtime/list_ASTImport.h"
#include "runtime/list_ASTOpaqueType.h"
#include "runtime/list_ASTServiceDecl.h"
#include "runtime/list_ASTTupleLiteral.h"
#include "runtime/list_ASTModuleQualifiedCall.h"
#include "runtime/list_ASTTupleIndex.h"

/* Opaque type forward declarations */
#ifndef NL_OPAQUE_TYPES_DECLARED
#define NL_OPAQUE_TYPES_DECLARED
typedef void* NLStringBuilder;
typedef void* NLStringSet;
typedef void* NLHashMap;
typedef void* NlPeg;
typedef void* Peg2Grammar;
typedef void* Json;
typedef void* Regex;
typedef void* DateTime;
typedef void* HttpResponse;
typedef void* HttpServer;
typedef void* HttpRequest;
typedef void* NlQueue;
typedef void* NlQueueGroup;
#ifndef SDL_h_
typedef void* SDL_Window;
typedef void* SDL_Renderer;
typedef void* SDL_Texture;
typedef void* SDL_Surface;
typedef void* SDL_GLContext;
#endif
#ifndef SDL_TTF_H_
typedef void* TTF_Font;
#endif
#ifndef SDL_MIXER_H_
typedef void* Mix_Chunk;
typedef void* Mix_Music;
#endif
#endif

DynArray* fs_walkdir(const char* root);
const char* path_normalize(const char* path);
const char* path_canonical(const char* path);
int64_t file_compare_identity(const char* source, const char* candidate);
int64_t file_compare_destinations(const char* first, const char* second);
const char* path_join(const char* a, const char* b);
const char* path_basename(const char* path);
const char* path_dirname(const char* path);
const char* path_relpath(const char* target, const char* base);
const char* file_read(const char* path);
int64_t  file_write(const char* path, const char* content);
int64_t  file_append(const char* path, const char* content);
bool     file_exists(const char* path);
int64_t  file_delete(const char* path);
int64_t  fs_mkdir_p(const char* path);
int64_t  file_copy(const char* src, const char* dst);
int64_t  dir_copy(const char* src, const char* dst);
int64_t  nl_os_process_spawn(const char* command);
int64_t  nl_os_process_is_running(int64_t pid);
int64_t  nl_os_process_wait(int64_t pid);
DynArray* nl_os_process_spawn_with_pipes(const char* command);
const char* nl_os_fd_read_available(int64_t fd);
int64_t  nl_os_fd_close(int64_t fd);
extern int64_t nl_os_unsetenv(const char* name);

/* I canonicalize only scalar binary arithmetic results, never transported bits. */
#ifndef NANOLANG_BINARY64_ARITHMETIC_H
#define NANOLANG_BINARY64_ARITHMETIC_H
#include <float.h>
#include <stdint.h>
#include <string.h>

#if defined(__FAST_MATH__) || (defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__)
#error "I require ordinary IEEE arithmetic without fast-math."
#endif
#if FLT_RADIX != 2 || DBL_MANT_DIG != 53 || DBL_MAX_EXP != 1024 || DBL_MIN_EXP != -1021
#error "I require binary64 double arithmetic."
#endif
#if !defined(FLT_EVAL_METHOD) || FLT_EVAL_METHOD != 0
#error "I require operations evaluated in their binary64 type."
#endif
/* I retain a compile-time storage check in both C99 and C11 output. */
typedef char nano_rt_binary64_storage_guard[
    sizeof(double) == 8 && sizeof(uint64_t) == 8 ? 1 : -1];

/* I inspect a rounded result with integer operations, not another FP operation. */
static inline double nano_rt_f64_arithmetic_result(double value) {
    uint64_t bits;
    memcpy(&bits, &value, sizeof(bits));
    if ((bits & UINT64_C(0x7ff0000000000000)) == UINT64_C(0x7ff0000000000000) &&
        (bits & UINT64_C(0x000fffffffffffff)) != 0) {
        bits = UINT64_C(0x7ff8000000000000);
        memcpy(&value, &bits, sizeof(value));
    }
    return value;
}

/* Each volatile store/load is a binary64 rounding and noncontraction boundary. */
static inline double nano_rt_f64_add(double a, double b) {
    volatile double rounded = a + b;
    return nano_rt_f64_arithmetic_result(rounded);
}
static inline double nano_rt_f64_sub(double a, double b) {
    volatile double rounded = a - b;
    return nano_rt_f64_arithmetic_result(rounded);
}
static inline double nano_rt_f64_mul(double a, double b) {
    volatile double rounded = a * b;
    return nano_rt_f64_arithmetic_result(rounded);
}
static inline double nano_rt_f64_div(double a, double b) {
    uint64_t divisor;
    memcpy(&divisor, &b, sizeof(divisor));
    /* Either signed zero takes precedence even over a signaling NaN numerator. */
    if ((divisor & UINT64_C(0x7fffffffffffffff)) == 0) return 0.0;
    volatile double rounded = a / b;
    return nano_rt_f64_arithmetic_result(rounded);
}
#endif
/* I preserve nonfinite signs independently of host libc spelling. */
#ifndef NANOLANG_BINARY64_FORMAT_H
#define NANOLANG_BINARY64_FORMAT_H
#include <float.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#if FLT_RADIX != 2 || DBL_MANT_DIG != 53 || DBL_MAX_EXP != 1024 || DBL_MIN_EXP != -1021
#error "I require binary64 formatting storage."
#endif
#define NL_BINARY64_FORMAT_HELPERS \
typedef char nano_rt_f64_format_storage[(sizeof(double) == 8 && sizeof(uint64_t) == 8) ? 1 : -1]; \
static inline const char *nano_rt_f64_nonfinite(double value) { \
    uint64_t bits; memcpy(&bits, &value, sizeof bits); \
    if ((bits & UINT64_C(0x7ff0000000000000)) != UINT64_C(0x7ff0000000000000)) return NULL; \
    if (bits & UINT64_C(0x000fffffffffffff)) return bits >> 63 ? "-nan" : "nan"; \
    return bits >> 63 ? "-inf" : "inf"; \
} \
static inline int nano_rt_f64_format(char *out, size_t size, double value) { \
    const char *special = nano_rt_f64_nonfinite(value); \
    return special ? snprintf(out, size, "%s", special) : snprintf(out, size, "%g", value); \
} \
static inline int nano_rt_f64_print(FILE *out, double value) { \
    const char *special = nano_rt_f64_nonfinite(value); \
    return special ? fprintf(out, "%s", special) : fprintf(out, "%g", value); \
}
NL_BINARY64_FORMAT_HELPERS
#define NL_FORMAT_STRINGIFY_INNER(...) #__VA_ARGS__
#define NL_FORMAT_STRINGIFY(...) NL_FORMAT_STRINGIFY_INNER(__VA_ARGS__)
#define NL_BINARY64_FORMAT_SOURCE \
    "#ifndef NANOLANG_BINARY64_FORMAT_H\n#define NANOLANG_BINARY64_FORMAT_H\n" \
    "#include <float.h>\n#include <stdint.h>\n#include <stdio.h>\n#include <string.h>\n" \
    "#if FLT_RADIX != 2 || DBL_MANT_DIG != 53 || DBL_MAX_EXP != 1024 || DBL_MIN_EXP != -1021\n" \
    "#error \"I require binary64 formatting storage.\"\n#endif\n" \
    NL_FORMAT_STRINGIFY(NL_BINARY64_FORMAT_HELPERS) "\n#endif\n"
#endif
/* ========== Math and Utility Built-in Functions ========== */

#define nl_abs(x) _Generic((x), \
    double: (double)((x) < 0.0 ? -(x) : (x)), \
    default: (int64_t)((x) < 0 ? -(x) : (x)))

#define nl_min(a, b) _Generic((a), \
    double: (double)((a) < (b) ? (a) : (b)), \
    default: (int64_t)((a) < (b) ? (a) : (b)))

#define nl_max(a, b) _Generic((a), \
    double: (double)((a) > (b) ? (a) : (b)), \
    default: (int64_t)((a) > (b) ? (a) : (b)))

static DynArray* nl_array_slice(DynArray* arr, int64_t start, int64_t length) {
    if (!arr) return dyn_array_new(ELEM_INT);
    if (start < 0) start = 0;
    if (length < 0) length = 0;
    int64_t len = dyn_array_length(arr);
    if (start > len) start = len;
    if (length > len - start) length = len - start;
    int64_t end = start + length;
    if (end > len) end = len;
    ElementType t = dyn_array_get_elem_type(arr);
    DynArray* out = dyn_array_new(t);
    if (!out) return NULL;
    for (int64_t i = start; i < end; i++) {
        switch (t) {
            case ELEM_U8: dyn_array_push_u8(out, dyn_array_get_u8(arr, i)); break;
            case ELEM_INT: dyn_array_push_int(out, dyn_array_get_int(arr, i)); break;
            case ELEM_FLOAT: dyn_array_push_float(out, dyn_array_get_float(arr, i)); break;
            case ELEM_BOOL: dyn_array_push_bool(out, dyn_array_get_bool(arr, i)); break;
            case ELEM_STRING: dyn_array_push_string(out, dyn_array_get_string(arr, i)); break;
            case ELEM_ARRAY: dyn_array_push_array(out, dyn_array_get_array(arr, i)); break;
            case ELEM_STRUCT: dyn_array_push_struct(out, dyn_array_get_struct(arr, i), (size_t)arr->elem_size); break;
            default: assert(false && "nl_array_slice: unsupported element type");
        }
    }
    return out;
}

/* Math functions */
double nl_sqrt(double x) { return sqrt(x); }
double nl_pow(double base, double exp) { return pow(base, exp); }
double nl_floor(double x) { return floor(x); }
double nl_ceil(double x) { return ceil(x); }
double nl_round(double x) { return round(x); }
double nl_sin(double x) { return sin(x); }
double nl_cos(double x) { return cos(x); }
double nl_tan(double x) { return tan(x); }
double nl_atan2(double y, double x) { return atan2(y, x); }

/* Print functions */
void nl_print(const char* s) {
    printf("%s", s);
}

void nl_println(const char* s) {
    printf("%s\n", s);
}

void nl_print_float(double v) {
    nano_rt_f64_print(stdout, v);
}

void nl_println_float(double v) {
    nano_rt_f64_print(stdout, v); fputc('\n', stdout);
}

/* Type conversions */
char* nl_int_to_string(int64_t n) {
    char* buffer = malloc(32);
    if (!buffer) return "";
    snprintf(buffer, 32, "%lld", (long long)n);
    return buffer;
}

#ifndef NL_HAS_USER_FLOAT_TO_STRING
char* nl_float_to_string(double x) {
    char* buffer = malloc(64);
    if (!buffer) return "";
    nano_rt_f64_format(buffer, 64, x);
    if (!strchr(buffer, '.') && !strchr(buffer, 'e') && !strchr(buffer, 'n') && !strchr(buffer, 'i')) {
        size_t len = strlen(buffer);
        if (len + 2 < 64) { buffer[len] = '.'; buffer[len + 1] = '0'; buffer[len + 2] = '\0'; }
    }
    return buffer;
}
#endif

char* nl_bool_to_string(bool b) {
    return b ? "true" : "false";
}

int64_t nl_string_to_int(const char* s) {
    return strtoll(s, NULL, 10);
}

#include "runtime/binary64_parse.h"
double nl_string_to_float(const char* s) {
    return nl_binary64_prefix(s);
}

double nl_float_from_bits(int64_t value) { uint64_t bits = (uint64_t)value; double result; _Static_assert(sizeof(result) == sizeof(bits), "I require binary64 storage."); memcpy(&result, &bits, sizeof(result)); return result; }
int64_t nl_float_to_bits(double value) { uint64_t bits; _Static_assert(sizeof(value) == sizeof(bits), "I require binary64 storage."); memcpy(&bits, &value, sizeof(bits)); return bits <= INT64_MAX ? (int64_t)bits : -1 - (int64_t)(UINT64_MAX - bits); }
double nl_cast_float(int64_t x) { return (double)x; }
double nl_cast_float_from_float(double x) { return x; }
int64_t nl_cast_int(double x) { if (!(x >= -0x1p63 && x < 0x1p63)) { fputs("I cannot convert this float to int: I require a finite value in [-2^63, 2^63).\n", stderr); exit(EXIT_FAILURE); } return (int64_t)x; }
int64_t nl_cast_int_from_int(int64_t x) { return x; }
bool nl_cast_bool(int64_t x) { return x != 0; }
bool nl_cast_bool_from_float(double x) { return x != 0.0; }

/* String operations */
char* nl_str_concat(const char* a, const char* b) {
    size_t la = strlen(a);
    size_t lb = strlen(b);
    char* out = (char*)malloc(la + lb + 1);
    if (!out) return "";
    memcpy(out, a, la);
    memcpy(out + la, b, lb);
    out[la + lb] = 0;
    return out;
}

char* nl_str_substring(const char* s, int64_t start, int64_t len) {
    if (!s) return "";
    int64_t n = (int64_t)strlen(s);
    if (start < 0) start = 0;
    if (len < 0) len = 0;
    if (start > n) start = n;
    if (start + len > n) len = n - start;
    char* out = (char*)malloc((size_t)len + 1);
    if (!out) return "";
    memcpy(out, s + start, (size_t)len);
    out[len] = 0;
    return out;
}

bool nl_str_starts_with(const char* str, const char* prefix) {
    if (!str || !prefix) return false;
    while (*prefix) { if (*str++ != *prefix++) return false; }
    return true;
}

bool nl_str_contains(const char* str, const char* substr) {
    return strstr(str, substr) != NULL;
}

#include "runtime/string_search.h"
char* nl_str_slice(const char* s, int64_t start, int64_t end_pos) {
    if (!s) return "";
    int64_t len = end_pos - start;
    return nl_str_substring(s, start, len > 0 ? len : 0);
}

bool nl_str_equals(const char* s1, const char* s2) {
    return strcmp(s1, s2) == 0;
}

static DynArray* nl_bytes_from_string(const char* s) {
    DynArray* out = dyn_array_new(ELEM_U8);
    if (!out) return NULL;
    if (!s) return out;
    size_t len = strnlen(s, 64*1024*1024);
    for (size_t i = 0; i < len; i++) {
        dyn_array_push_u8(out, (uint8_t)(unsigned char)s[i]);
    }
    return out;
}

static const char* nl_string_from_bytes(DynArray* bytes) {
    if (!bytes) return "";
    if (dyn_array_get_elem_type(bytes) != ELEM_U8) return "";
    int64_t len = dyn_array_length(bytes);
    if (len < 0) return "";
    char* out = gc_alloc_string((size_t)len);
    if (!out) return "";
    for (int64_t i = 0; i < len; i++) {
        out[i] = (char)dyn_array_get_u8(bytes, i);
    }
    out[len] = '\0';
    return out;
}

static DynArray* nl_str_split(const char* str, const char* delim) {
    DynArray* result = dyn_array_new(ELEM_STRING);
    if (!result) { fprintf(stderr, "I cannot allocate a complete split-string result.\n"); abort(); }
    if (!str) return result;
    size_t delim_len = strlen(delim);
    if (delim_len == 0) {
        size_t str_len = strnlen(str, 64*1024*1024);
        for (size_t i = 0; i < str_len; i++) {
            char* ch = gc_alloc_string(1);
            if (!ch) { fprintf(stderr, "I cannot allocate a complete split-string result.\n"); abort(); }
            ch[0] = str[i]; ch[1] = '\0';
            dyn_array_push_string(result, ch);
        }
        return result;
    }
    const char* start = str;
    const char* found;
    while ((found = strstr(start, delim)) != NULL) {
        size_t seg_len = (size_t)(found - start);
        char* seg = gc_alloc_string(seg_len);
        if (!seg) { fprintf(stderr, "I cannot allocate a complete split-string result.\n"); abort(); }
        memcpy(seg, start, seg_len);
        seg[seg_len] = '\0';
        dyn_array_push_string(result, seg);
        start = found + delim_len;
    }
    size_t rest_len = strlen(start);
    char* seg = gc_alloc_string(rest_len);
    if (!seg) { fprintf(stderr, "I cannot allocate a complete split-string result.\n"); abort(); }
    {
        memcpy(seg, start, rest_len);
        seg[rest_len] = '\0';
        dyn_array_push_string(result, seg);
    }
    return result;
}

/* Character operations */
int64_t nl_char_at(const char* s, int64_t i) {
    return (int64_t)((unsigned char)s[i]);
}

char* nl_string_from_char(int64_t c) {
    char* buffer = malloc(2);
    if (!buffer) return "";
    buffer[0] = (char)c;
    buffer[1] = 0;
    return buffer;
}

/* Character classification */
bool nl_is_digit(int64_t c) {
    return c >= '0' && c <= '9';
}

bool nl_is_alpha(int64_t c) {
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
}

bool nl_is_alnum(int64_t c) {
    return nl_is_digit(c) || nl_is_alpha(c);
}

bool nl_is_whitespace(int64_t c) {
    return c == ' ' || c == '\t' || c == '\n' || c == '\r';
}

bool nl_is_upper(int64_t c) {
    return c >= 'A' && c <= 'Z';
}

bool nl_is_lower(int64_t c) {
    return c >= 'a' && c <= 'z';
}

int64_t nl_digit_value(int64_t c) {
    if (c >= '0' && c <= '9') {
        return c - '0';
    }
    return -1;
}

int64_t nl_char_to_lower(int64_t c) {
    if (c >= 'A' && c <= 'Z') {
        return c + 32;
    }
    return c;
}

int64_t nl_char_to_upper(int64_t c) {
    if (c >= 'a' && c <= 'z') {
        return c - 32;
    }
    return c;
}

/* fs wrappers */
static const char* nl_path_normalize(const char* p) { return path_normalize(p); }
static const char* nl_path_join(const char* a, const char* b) { return path_join(a, b); }
static const char* nl_path_basename(const char* p) { return path_basename(p); }
static const char* nl_path_dirname(const char* p) { return path_dirname(p); }
static const char* nl_path_relpath(const char* t, const char* b) { return path_relpath(t, b); }
static const char* nl_file_read(const char* p) { return file_read(p); }

static int64_t nl_fs_mkdir_p(const char* p) { return fs_mkdir_p(p); }
static int64_t nl_file_copy(const char* s, const char* d) { return file_copy(s, d); }
static int64_t nl_dir_copy(const char* s, const char* d) { return dir_copy(s, d); }

/* CLI and OS functions (defined in runtime/cli.c) */
int g_argc = 0;
char **g_argv = NULL;
extern int64_t get_argc(void);
extern const char* get_argv(int64_t index);
extern const char* nl_os_getenv(const char* name);
static const char* nl_get_argv(int64_t idx) { return get_argv(idx); }
static const char* nl_getenv(const char* name) { return nl_os_getenv(name); }
static const char* nl_env_get(const char* name) { return nl_os_getenv(name); }
extern int64_t nl_os_setenv(const char* name, const char* value, int64_t overwrite);
extern int64_t nl_os_system(const char* command);
static int64_t nl_exec_shell(const char* cmd) { return (int64_t)system(cmd); }

/* Capture stdout from a shell command (up to 65535 bytes) */
static const char* nl_exec_capture(const char* cmd) {
    FILE* pipe = popen(cmd, "r");
    if (!pipe) return "";
    char* out = (char*)malloc(65536);
    if (!out) { pclose(pipe); return ""; }
    size_t total = 0;
    char buf[1024];
    while (fgets(buf, sizeof(buf), pipe) && total < 65534) {
        size_t n = strlen(buf);
        if (total + n > 65534) n = 65534 - total;
        memcpy(out + total, buf, n);
        total += n;
    }
    out[total] = '\0';
    pclose(pipe);
    return out;
}

/* OS functions not in cli.c - static implementations */
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
static char* nl_os_getcwd(void) {
    char buf[4096];
    if (getcwd(buf, sizeof(buf))) {
        char* out = malloc(strlen(buf) + 1);
        if (out) { strcpy(out, buf); return out; }
    }
    return "";
}

static void nl_os_exit(int64_t code) { exit((int)code); }

static int64_t nl_os_chdir(const char* path) { return (int64_t)chdir(path); }

static bool nl_os_file_exists(const char* path) {
    struct stat st;
    return stat(path, &st) == 0;
}

static char* nl_os_tmp_dir(void) {
    const char* tmp = getenv("TMPDIR");
    if (!tmp || tmp[0] == '\0') tmp = "/tmp";
    size_t len = strlen(tmp);
    char* out = gc_alloc_string(len);
    if (!out) return gc_alloc_string(0);
    memcpy(out, tmp, len);
    out[len] = '\0';
    return out;
}

static char* nl_os_mktemp(const char* prefix) {
    const char* tmp = getenv("TMPDIR");
    if (!tmp || tmp[0] == '\0') tmp = "/tmp";
    const char* p = (prefix && prefix[0]) ? prefix : "nanolang_";
    char templ[1024];
    snprintf(templ, sizeof(templ), "%s/%sXXXXXX", tmp, p);
    int fd = mkstemp(templ);
    if (fd < 0) return gc_alloc_string(0);
    close(fd);
    size_t len = strlen(templ);
    char* out = gc_alloc_string(len);
    if (!out) return gc_alloc_string(0);
    memcpy(out, templ, len);
    out[len] = '\0';
    return out;
}

static char* nl_os_mktemp_dir(const char* prefix) {
    const char* tmp = getenv("TMPDIR");
    if (!tmp || tmp[0] == '\0') tmp = "/tmp";
    const char* p = (prefix && prefix[0]) ? prefix : "nanolang_dir_";
    char path[1024];
    for (int i = 0; i < 100; i++) {
        snprintf(path, sizeof(path), "%s/%s%lld_%d", tmp, p, (long long)time(NULL), i);
        if (mkdir(path, 0700) == 0) {
            size_t len = strlen(path);
            char* out = gc_alloc_string(len);
            if (!out) return gc_alloc_string(0);
            memcpy(out, path, len);
            out[len] = '\0';
            return out;
        }
    }
    return gc_alloc_string(0);
}

static const char* cast_string(int64_t v) { return nl_int_to_string(v); }
static const char* to_string(int64_t v) { return nl_int_to_string(v); }

/* Higher-order array functions */
static DynArray* nl_map(DynArray* arr, int64_t (*fn)(int64_t)) {
    DynArray* result = dyn_array_new(ELEM_INT);
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        dyn_array_push_int(result, fn(dyn_array_get_int(arr, i)));
    }
    return result;
}

static int64_t nano_rt_reduce_int(DynArray* arr, int64_t initial, int64_t (*fn)(int64_t, int64_t)) {
    int64_t acc = initial;
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        acc = fn(acc, dyn_array_get_int(arr, i));
    }
    return acc;
}

static DynArray* nl_filter(DynArray* arr, bool (*fn)(int64_t)) {
    DynArray* result = dyn_array_new(ELEM_INT);
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        int64_t val = dyn_array_get_int(arr, i);
        if (fn(val)) dyn_array_push_int(result, val);
    }
    return result;
}

static DynArray* nl_map_str(DynArray* arr, const char* (*fn)(const char*)) {
    DynArray* result = dyn_array_new(ELEM_STRING);
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        dyn_array_push_string(result, fn(dyn_array_get_string(arr, i)));
    }
    return result;
}

static const char* nano_rt_reduce_str(DynArray* arr, const char* initial, const char* (*fn)(const char*, const char*)) {
    const char* acc = initial;
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        acc = fn(acc, dyn_array_get_string(arr, i));
    }
    return acc;
}

static DynArray* nl_filter_str(DynArray* arr, bool (*fn)(const char*)) {
    DynArray* result = dyn_array_new(ELEM_STRING);
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        const char* val = dyn_array_get_string(arr, i);
        if (fn(val)) dyn_array_push_string(result, val);
    }
    return result;
}

static DynArray* nl_map_float(DynArray* arr, double (*fn)(double)) {
    DynArray* result = dyn_array_new(ELEM_FLOAT);
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        dyn_array_push_float(result, fn(dyn_array_get_float(arr, i)));
    }
    return result;
}

static double nano_rt_reduce_float(DynArray* arr, double initial, double (*fn)(double, double)) {
    double acc = initial;
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        acc = fn(acc, dyn_array_get_float(arr, i));
    }
    return acc;
}

static DynArray* nl_filter_float(DynArray* arr, bool (*fn)(double)) {
    DynArray* result = dyn_array_new(ELEM_FLOAT);
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        double val = dyn_array_get_float(arr, i);
        if (fn(val)) dyn_array_push_float(result, val);
    }
    return result;
}

static DynArray* nl_filter_bool(DynArray* arr, bool (*fn)(bool)) {
    DynArray* result = dyn_array_new(ELEM_BOOL);
    int64_t len = dyn_array_length(arr);
    for (int64_t i = 0; i < len; i++) {
        bool val = dyn_array_get_bool(arr, i);
        if (fn(val)) dyn_array_push_bool(result, val);
    }
    return result;
}

/* HashMap wrappers */
static inline HashMap_string_int* nl_map_new(void) { return nl_hashmap_string_int_alloc(16); }
static inline void nl_map_put(HashMap_string_int* hm, const char* key, int64_t val) { nl_hashmap_string_int_put(hm, key, val); }
static inline int64_t nl_map_get(HashMap_string_int* hm, const char* key) { return nl_hashmap_string_int_get(hm, key); }
static inline int nl_map_has(HashMap_string_int* hm, const char* key) { return nl_hashmap_string_int_has(hm, key); }
static inline int64_t nl_map_size(HashMap_string_int* hm) { return hm->size; }

/* Timing utilities */
static int64_t nl_timing_get_microseconds(void) {
#ifdef CLOCK_REALTIME
    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    return ((int64_t)ts.tv_sec * 1000000LL) + (int64_t)(ts.tv_nsec / 1000);
#else
    struct timeval tv;
    gettimeofday(&tv, NULL);
    return ((int64_t)tv.tv_sec * 1000000LL) + (int64_t)tv.tv_usec;
#endif
}

static int64_t nl_timing_get_nanoseconds(void) {
#ifdef __MACH__
    static mach_timebase_info_data_t timebase;
    static int initialized = 0;
    if (!initialized) {
        mach_timebase_info(&timebase);
        initialized = 1;
    }
    uint64_t mach_time = mach_absolute_time();
    return (int64_t)((mach_time * timebase.numer) / timebase.denom);
#elif defined(CLOCK_MONOTONIC)
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ((int64_t)ts.tv_sec * 1000000000LL) + (int64_t)ts.tv_nsec;
#else
    return nl_timing_get_microseconds() * 1000LL;
#endif
}

/* Convenience: current time in milliseconds */
static int64_t nl_get_time_ms(void) { return nl_timing_get_microseconds() / 1000LL; }

/* ========== End Math and Utility Built-in Functions ========== */


/* Extern function declarations (not covered by headers) */

/* Function prototypes */
int64_t __nl_declared_str_split(int64_t nl_value);
int64_t nl_probe();
int64_t nl_main();

/* User functions */
int64_t __nl_declared_str_split(int64_t nl_value) {
#line 1 "/tmp/nanolang-split-d1e41-puck-evidence/nano-split-primitive-oap66fib/refresh1-declared.nano"
    return ((nl_value) + (1));
}


int64_t nl_probe() {
#line 3 "/tmp/nanolang-split-d1e41-puck-evidence/nano-split-primitive-oap66fib/refresh1-declared.nano"
    assert((({ __auto_type _nl_push_fn_1 = __nl_declared_str_split; __auto_type _nl_push_arg_1_0 = 41; _nl_push_fn_1(_nl_push_arg_1_0); })) == (42));
#line 3 "/tmp/nanolang-split-d1e41-puck-evidence/nano-split-primitive-oap66fib/refresh1-declared.nano"
    return 0;
}


int64_t nl_main() {
#line 5 "/tmp/nanolang-split-d1e41-puck-evidence/nano-split-primitive-oap66fib/refresh1-declared.nano"
    return nl_probe();
}



/* C main() entry point - calls nanolang main */
int main(int argc, char **argv) {
    g_argc = argc;
    g_argv = argv;
    return (int)nl_main();
}
