#ifndef _GNU_SOURCE
#define _GNU_SOURCE 1
#endif
#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE 1
#endif
/* Generated by nvm2c from NanoISA. Not a VM wrapper. */
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
/* I preserve invariant termination while naming its generated source. */
#define NVM2C_ABORT() do { fprintf(stderr, "I stopped at a native invariant in %s at generated C line %d.\n", __func__, __LINE__); abort(); } while (0)
/* I reconstruct wrapped bits without an out-of-range signed cast. */
static inline int64_t ni64_from_bits(uint64_t bits) {
    return bits <= INT64_MAX ? (int64_t)bits : -INT64_C(1) - (int64_t)(UINT64_MAX - bits);
}
#include <string.h>
/* I retain binary64 bits in my existing 64-bit aggregate cells. */
static inline double nrec_f64(int64_t cell) {
    double value; memcpy(&value, &cell, sizeof value); return value;
}
#include <stdio.h>
static inline int64_t nf64_to_i64(double value) {
    if (!(value >= -0x1p63 && value < 0x1p63)) {
        fputs("I cannot convert this float to int: I require a finite value in [-2^63, 2^63).\n", stderr);
        exit(EXIT_FAILURE);
    }
    return (int64_t)value;
}
#include <string.h>
static inline double nl_float_from_bits(int64_t value) { uint64_t bits = (uint64_t)value; double result; (void)sizeof(char[sizeof(result) == sizeof(bits) ? 1 : -1]); __builtin___memcpy_chk (&result, &bits, sizeof(result), __builtin_object_size (&result, 0)); return result; }
static inline int64_t nl_float_to_bits(double value) { uint64_t bits; (void)sizeof(char[sizeof(value) == sizeof(bits) ? 1 : -1]); __builtin___memcpy_chk (&bits, &value, sizeof(bits), __builtin_object_size (&bits, 0)); return bits <= 9223372036854775807LL ? (int64_t)bits : -1 - (int64_t)(18446744073709551615ULL - bits); }
#include <stdlib.h>
#include <string.h>

typedef struct nmap_s *nmap_t;
typedef struct { int64_t *data; size_t len; struct narr_owner *owner; } narr_s;
typedef narr_s *narr_t;
typedef struct { const char **data; size_t len; struct nsarr_owner *owner; } nsarr_s;
typedef nsarr_s *nsarr_t;
static size_t nagg_live_bytes, nagg_peak_bytes, nagg_allocation_debt;
static inline void nagg_add(size_t bytes) {
    if (bytes > SIZE_MAX - nagg_live_bytes || bytes > SIZE_MAX - nagg_allocation_debt) NVM2C_ABORT();
    nagg_live_bytes += bytes; nagg_allocation_debt += bytes;
    if (nagg_live_bytes > nagg_peak_bytes) nagg_peak_bytes = nagg_live_bytes;
}
static inline void nagg_drop(size_t bytes) {
    if (bytes > nagg_live_bytes) NVM2C_ABORT();
    nagg_live_bytes -= bytes;
}
/* I canonicalize only scalar binary arithmetic results, never transported bits. */
#ifndef NANOLANG_BINARY64_ARITHMETIC_H
#define NANOLANG_BINARY64_ARITHMETIC_H
#include <float.h>
#include <stdint.h>
#include <string.h>

#if defined(__FAST_MATH__) || (defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__)
#error "I require ordinary IEEE arithmetic without fast-math."
#endif
#if FLT_RADIX != 2 || DBL_MANT_DIG != 53 || DBL_MAX_EXP != 1024 || DBL_MIN_EXP != -1021
#error "I require binary64 double arithmetic."
#endif
#if !defined(FLT_EVAL_METHOD) || FLT_EVAL_METHOD != 0
#error "I require operations evaluated in their binary64 type."
#endif
/* I retain a compile-time storage check in both C99 and C11 output. */
typedef char nano_rt_binary64_storage_guard[
    sizeof(double) == 8 && sizeof(uint64_t) == 8 ? 1 : -1];

/* I inspect a rounded result with integer operations, not another FP operation. */
static inline double nano_rt_f64_arithmetic_result(double value) {
    uint64_t bits;
    memcpy(&bits, &value, sizeof(bits));
    if ((bits & UINT64_C(0x7ff0000000000000)) == UINT64_C(0x7ff0000000000000) &&
        (bits & UINT64_C(0x000fffffffffffff)) != 0) {
        bits = UINT64_C(0x7ff8000000000000);
        memcpy(&value, &bits, sizeof(value));
    }
    return value;
}

/* Each volatile store/load is a binary64 rounding and noncontraction boundary. */
static inline double nano_rt_f64_add(double a, double b) {
    volatile double rounded = a + b;
    return nano_rt_f64_arithmetic_result(rounded);
}
static inline double nano_rt_f64_sub(double a, double b) {
    volatile double rounded = a - b;
    return nano_rt_f64_arithmetic_result(rounded);
}
static inline double nano_rt_f64_mul(double a, double b) {
    volatile double rounded = a * b;
    return nano_rt_f64_arithmetic_result(rounded);
}
static inline double nano_rt_f64_div(double a, double b) {
    uint64_t divisor;
    memcpy(&divisor, &b, sizeof(divisor));
    /* Either signed zero takes precedence even over a signaling NaN numerator. */
    if ((divisor & UINT64_C(0x7fffffffffffffff)) == 0) return 0.0;
    volatile double rounded = a / b;
    return nano_rt_f64_arithmetic_result(rounded);
}
#endif
#ifndef NANOISA_BINARY64_PARSE_H
#define NANOISA_BINARY64_PARSE_H
#include <stdint.h>
/* I parse closed C-locale binary64 values with fixed-capacity integer math.
 * My input is a valid byte view; NUL terminates its numeric prefix. */
typedef struct {
    uint32_t limb[128];
    unsigned used;
} NbpBig;
static inline void nbp_zero(NbpBig *a) { *a = (NbpBig){{0}, 0}; }
static inline void nbp_normalize(NbpBig *a) {
    while (a->used && !a->limb[a->used - 1])
        a->used--;
}
static inline int nbp_multiply(NbpBig *a, unsigned base, unsigned add) {
    uint64_t carry = add;
    for (unsigned i = 0; i < a->used; i++) {
        uint64_t value = (uint64_t)a->limb[i] * base + carry;
        a->limb[i] = (uint32_t)value;
        carry = value >> 32;
    }
    if (carry) {
        if (a->used == 128)
            return 0;
        a->limb[a->used++] = (uint32_t)carry;
    }
    return 1;
}
static inline unsigned nbp_bits(const NbpBig *a) {
    if (!a->used)
        return 0;
    uint32_t top = a->limb[a->used - 1];
    unsigned n = 0;
    while (top) {
        top >>= 1;
        n++;
    }
    return (a->used - 1) * 32 + n;
}
static inline int nbp_shift(NbpBig *a, unsigned shift) {
    if (!a->used || !shift)
        return 1;
    unsigned words = shift / 32, bits = shift % 32;
    unsigned carry = bits && (a->limb[a->used - 1] >> (32 - bits));
    if (words >= 128 || a->used + words + carry > 128)
        return 0;
    NbpBig result;
    nbp_zero(&result);
    result.used = a->used + words + carry;
    for (unsigned i = 0; i < a->used; i++) {
        uint64_t value = (uint64_t)a->limb[i] << bits;
        result.limb[i + words] |= (uint32_t)value;
        if (value >> 32)
            result.limb[i + words + 1] |= (uint32_t)(value >> 32);
    }
    *a = result;
    return 1;
}
static inline int nbp_compare(const NbpBig *a, const NbpBig *b) {
    if (a->used != b->used)
        return a->used > b->used ? 1 : -1;
    for (unsigned i = a->used; i > 0; i--)
        if (a->limb[i - 1] != b->limb[i - 1])
            return a->limb[i - 1] > b->limb[i - 1] ? 1 : -1;
    return 0;
}
static inline void nbp_subtract(NbpBig *a, const NbpBig *b) {
    uint64_t borrow = 0;
    for (unsigned i = 0; i < a->used; i++) {
        uint64_t sub = (i < b->used ? b->limb[i] : 0) + borrow, value = a->limb[i];
        a->limb[i] = (uint32_t)(value - sub);
        borrow = value < sub;
    }
    nbp_normalize(a);
}
static inline int nbp_rational(NbpBig numerator, NbpBig denominator, int sticky, uint64_t *out) {
    int exponent = (int)nbp_bits(&numerator) - (int)nbp_bits(&denominator);
    NbpBig probe = exponent < 0 ? numerator : denominator;
    if (!nbp_shift(&probe, (unsigned)(exponent < 0 ? -exponent : exponent)))
        return 0;
    if ((exponent < 0 ? nbp_compare(&probe, &denominator) : nbp_compare(&numerator, &probe)) < 0)
        exponent--;
    if (exponent > 1023) {
        *out = UINT64_C(0x7ff0000000000000);
        return 1;
    }
    int normal = exponent >= -1022, shift = normal ? 52 - exponent : 1074;
    if (!nbp_shift(shift >= 0 ? &numerator : &denominator, (unsigned)(shift >= 0 ? shift : -shift)))
        return 0;
    int bit = (int)nbp_bits(&numerator) - (int)nbp_bits(&denominator);
    if (bit >= 64)
        return 0;
    uint64_t quotient = 0;
    for (; bit >= 0; bit--) {
        probe = denominator;
        if (!nbp_shift(&probe, (unsigned)bit))
            return 0;
        if (nbp_compare(&numerator, &probe) >= 0) {
            nbp_subtract(&numerator, &probe);
            quotient |= UINT64_C(1) << bit;
        }
    }
    if (!nbp_shift(&numerator, 1))
        return 0;
    int half = nbp_compare(&numerator, &denominator);
    if (half > 0 || (half == 0 && (sticky || (quotient & 1))))
        quotient++;
    if (normal) {
        if (quotient == (UINT64_C(1) << 53)) {
            quotient >>= 1;
            exponent++;
        }
        if (exponent > 1023) {
            *out = UINT64_C(0x7ff0000000000000);
            return 1;
        }
        if (quotient < (UINT64_C(1) << 52) || quotient >= (UINT64_C(1) << 53))
            return 0;
        *out = ((uint64_t)(exponent + 1023) << 52) | (quotient - (UINT64_C(1) << 52));
    } else {
        if (quotient > (UINT64_C(1) << 52))
            return 0;
        *out = quotient;
    }
    return 1;
}
static inline unsigned char nbp_lower(unsigned char c) {
    return c >= 'A' && c <= 'Z' ? (unsigned char)(c + 32) : c;
}
static inline int nbp_digit(unsigned char c) {
    if (c >= '0' && c <= '9')
        return c - '0';
    c = nbp_lower(c);
    return c >= 'a' && c <= 'f' ? c - 'a' + 10 : -1;
}
static inline int nbp_word(const unsigned char *text, uint32_t length, uint32_t start,
                           const char *word, unsigned count) {
    if (start > length || length - start < count)
        return 0;
    for (unsigned i = 0; i < count; i++)
        if (nbp_lower(text[start + i]) != (unsigned char)word[i])
            return 0;
    return 1;
}
static inline uint64_t nbp_nan_payload(const unsigned char *text, uint32_t length, uint32_t start,
                                       uint32_t *consumed) {
    if (start >= length || text[start] != '(')
        return 0;
    uint32_t end = start + 1;
    while (end < length) {
        unsigned char c = nbp_lower(text[end]);
        if (!((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_'))
            break;
        end++;
    }
    if (end == length || text[end] != ')')
        return 0;
    *consumed = end + 1;
    uint32_t i = start + 1;
    unsigned base = 10;
    if (end - i >= 2 && text[i] == '0' && nbp_lower(text[i + 1]) == 'x') {
        base = 16;
        i += 2;
    } else if (end - i > 1 && text[i] == '0')
        base = 8;
    if (i == end)
        return 0;
    uint64_t value = 0;
    for (; i < end; i++) {
        int digit = nbp_digit(text[i]);
        if (digit < 0 || (unsigned)digit >= base)
            return 0;
        if (value > (UINT64_MAX - (unsigned)digit) / base)
            value = UINT64_MAX;
        else
            value = value * base + (unsigned)digit;
    }
    return value;
}
static inline int nbp_parse_impl(const unsigned char *text, uint32_t length, uint64_t *out,
                                 uint32_t *consumed) {
    if (!out || (!text && length))
        return 0;
    *consumed = 0;
    uint32_t i = 0;
    while (i < length && (text[i] == ' ' || text[i] == '\t' || text[i] == '\n' || text[i] == '\r' ||
                          text[i] == '\v' || text[i] == '\f'))
        i++;
    uint64_t sign = 0;
    if (i < length && (text[i] == '-' || text[i] == '+')) {
        if (text[i] == '-')
            sign = UINT64_C(1) << 63;
        i++;
    }
    if (nbp_word(text, length, i, "inf", 3)) {
        *consumed = i + (nbp_word(text, length, i, "infinity", 8) ? 8 : 3);
        *out = sign | UINT64_C(0x7ff0000000000000);
        return 1;
    }
    if (nbp_word(text, length, i, "nan", 3)) {
        *consumed = i + 3;
        *out = sign | UINT64_C(0x7ff8000000000000) |
               (nbp_nan_payload(text, length, i + 3, consumed) & UINT64_C(0xfffffffffffff));
        return 1;
    }
    unsigned radix = 10, cap = 800;
    if (length - i >= 3 && text[i] == '0' && nbp_lower(text[i + 1]) == 'x' &&
        (nbp_digit(text[i + 2]) >= 0 ||
         (length - i >= 4 && text[i + 2] == '.' && nbp_digit(text[i + 3]) >= 0))) {
        radix = 16;
        cap = 32;
        i += 2;
    }
    NbpBig numerator;
    nbp_zero(&numerator);
    unsigned kept = 0;
    int point = 0, saw_digit = 0, started = 0, sticky = 0;
    int64_t fractional = 0, omitted = 0;
    while (i < length) {
        int digit = nbp_digit(text[i]);
        if (digit >= 0 && (unsigned)digit < radix) {
            saw_digit = 1;
            if (point)
                fractional++;
            if (digit)
                started = 1;
            if (started) {
                if (kept < cap) {
                    if (!nbp_multiply(&numerator, radix, (unsigned)digit))
                        return 0;
                    kept++;
                } else {
                    omitted++;
                    sticky |= digit != 0;
                }
            }
            i++;
            continue;
        }
        if (text[i] == '.' && !point) {
            point = 1;
            i++;
            continue;
        }
        break;
    }
    if (!saw_digit) {
        *out = 0;
        return 1;
    }
    int64_t exponent = 0;
    if (i < length && nbp_lower(text[i]) == (radix == 16 ? 'p' : 'e')) {
        uint32_t next = i + 1;
        int minus = 0;
        if (next < length && (text[next] == '+' || text[next] == '-')) {
            minus = text[next] == '-';
            next++;
        }
        if (next < length && text[next] >= '0' && text[next] <= '9') {
            const int64_t cap_exponent = INT64_C(1) << 40;
            for (; next < length && text[next] >= '0' && text[next] <= '9'; next++) {
                if (exponent < cap_exponent) {
                    exponent = exponent * 10 + (text[next] - '0');
                    if (exponent > cap_exponent)
                        exponent = cap_exponent;
                }
            }
            i = next;
            if (minus)
                exponent = -exponent;
        }
    }
    *consumed = i;
    if (!started) {
        *out = sign;
        return 1;
    }
    int64_t scale = exponent + (omitted - fractional) * (radix == 16 ? 4 : 1);
    int64_t order = (radix == 16 ? (int64_t)nbp_bits(&numerator) - 1 : (int64_t)kept - 1) + scale;
    if (order > (radix == 16 ? 1023 : 308)) {
        *out = sign | UINT64_C(0x7ff0000000000000);
        return 1;
    }
    if (order < (radix == 16 ? -1075 : -324)) {
        *out = sign;
        return 1;
    }
    NbpBig denominator;
    nbp_zero(&denominator);
    denominator.used = 1;
    denominator.limb[0] = 1;
    NbpBig *scaled = scale < 0 ? &denominator : &numerator;
    unsigned power = (unsigned)(scale < 0 ? -scale : scale);
    if (radix == 16) {
        if (!nbp_shift(scaled, power))
            return 0;
    } else
        for (unsigned step = 0; step < power; step++)
            if (!nbp_multiply(scaled, 10, 0))
                return 0;
    uint64_t result;
    if (!nbp_rational(numerator, denominator, sticky, &result))
        return 0;
    *out = sign | result;
    return 1;
}
/* I publish both outputs only after checked parsing succeeds. An input with
 * no numeric prefix has endpoint zero; optional endpoints preserve values. */
static inline int nbp_parse_end(const unsigned char *text, uint32_t length, uint64_t *out,
                                uint32_t *consumed) {
    if (!out || (!text && length))
        return 0;
    uint64_t bits;
    uint32_t end;
    if (!nbp_parse_impl(text, length, &bits, &end))
        return 0;
    *out = bits;
    if (consumed)
        *consumed = end;
    return 1;
}
static inline int nbp_parse(const unsigned char *text, uint32_t length, uint64_t *out) {
    return nbp_parse_end(text, length, out, 0);
}
#endif
static inline double nparse_binary64(const char *text) {
    size_t length = text ? strlen(text) : 0; uint64_t bits = 0;
    if (length > UINT32_MAX || !nbp_parse((const unsigned char *)text, (uint32_t)length, &bits)) NVM2C_ABORT();
    double result; memcpy(&result, &bits, sizeof result); return result;
}
#include <string.h>
struct nsarr_owner { const char **data; size_t cap, bytes; nsarr_t handle; struct nsarr_owner *next; };
static struct nsarr_owner *nsarr_owners;
typedef struct nsarr_string { char *data; size_t bytes; struct nsarr_string *next; } nsarr_string;
static nsarr_string *nsarr_strings;
static inline struct nsarr_owner *nsarr_track(nsarr_t a, int own_handle) {
    struct nsarr_owner *owner = calloc(1, sizeof *owner);
    if (!owner) NVM2C_ABORT();
    owner->bytes = sizeof *owner + (own_handle ? sizeof *a : 0); nagg_add(owner->bytes);
    owner->handle = own_handle ? a : NULL; owner->next = nsarr_owners;
    nsarr_owners = owner; a->owner = owner; return owner;
}
static inline nsarr_t nsarr_new(void) {
    nsarr_t a = calloc(1, sizeof *a); if (!a) NVM2C_ABORT();
    nsarr_track(a, 1); return a;
}
static inline void nsarr_reserve(nsarr_t a, size_t n) {
    size_t limit = SIZE_MAX / sizeof *a->data;
    if (!a || n > limit || a->len > limit || (a->len && !a->data)) NVM2C_ABORT();
    struct nsarr_owner *owner = a->owner;
    if (owner && (owner->data != a->data || a->len > owner->cap)) NVM2C_ABORT();
    if (owner && n <= owner->cap) return;
    if (n < a->len) n = a->len;
    size_t cap = owner && owner->cap ? owner->cap : 8;
    while (cap < n) { if (cap > limit / 2) { cap = n; break; } cap *= 2; }
    if (!owner) {
        const char **data = malloc(cap * sizeof *data); if (!data) NVM2C_ABORT();
        if (a->len) memcpy(data, a->data, a->len * sizeof *data);
        owner = nsarr_track(a, 0); owner->data = data;
    } else {
        const char **data = realloc(owner->data, cap * sizeof *data);
        if (!data) { NVM2C_ABORT(); } owner->data = data;
    }
    size_t growth = (cap - owner->cap) * sizeof *owner->data;
    nagg_add(growth); owner->bytes += growth;
    owner->cap = cap; a->data = owner->data;
}
static inline const char *nsarr_copy_string(const char *value) {
    if (!value) { NVM2C_ABORT(); } size_t n = strlen(value); if (n == SIZE_MAX) NVM2C_ABORT();
    if (n > SIZE_MAX - sizeof(nsarr_string) - 1) NVM2C_ABORT();
    nsarr_string *owner = malloc(sizeof *owner); if (!owner) NVM2C_ABORT();
    owner->data = malloc(n + 1); if (!owner->data) NVM2C_ABORT();
    owner->bytes = sizeof *owner + n + 1; nagg_add(owner->bytes);
    memcpy(owner->data, value, n + 1); owner->next = nsarr_strings;
    nsarr_strings = owner; return owner->data;
}
static inline void nsarr_release_owned(void) {
    while (nsarr_owners) { struct nsarr_owner *owner = nsarr_owners;
        nsarr_owners = owner->next; nagg_drop(owner->bytes); free(owner->data); free(owner->handle); free(owner); }
    while (nsarr_strings) { nsarr_string *owner = nsarr_strings;
        nsarr_strings = owner->next; nagg_drop(owner->bytes); free(owner->data); free(owner); }
}
struct narr_owner { int64_t *data; const void **environments; size_t cap, bytes; narr_t handle; struct narr_owner *next; };
static struct narr_owner *narr_owners;
static inline struct narr_owner *narr_track(narr_t a, int own_handle) {
    struct narr_owner *owner = calloc(1, sizeof *owner); if (!owner) NVM2C_ABORT();
    owner->bytes = sizeof *owner + (own_handle ? sizeof *a : 0); nagg_add(owner->bytes);
    owner->handle = own_handle ? a : NULL; owner->next = narr_owners;
    narr_owners = owner; a->owner = owner; return owner;
}
static inline narr_t narr_new(void) {
    narr_t a = calloc(1, sizeof *a); if (!a) NVM2C_ABORT();
    narr_track(a, 1); return a;
}
static inline void narr_reserve(narr_t a, size_t n) {
    size_t limit = SIZE_MAX / sizeof *a->data;
    if (limit > SIZE_MAX / sizeof(void *)) limit = SIZE_MAX / sizeof(void *);
    if (!a || n > limit || a->len > limit || (a->len && !a->data)) NVM2C_ABORT();
    struct narr_owner *owner = a->owner;
    if (owner && (owner->data != a->data || a->len > owner->cap)) NVM2C_ABORT();
    if (owner && n <= owner->cap) return;
    if (n < a->len) n = a->len;
    size_t cap = owner && owner->cap ? owner->cap : 8;
    while (cap < n) { if (cap > limit / 2) { cap = n; break; } cap *= 2; }
    if (!owner) {
        int64_t *data = malloc(cap * sizeof *data); if (!data) NVM2C_ABORT();
        if (a->len) memcpy(data, a->data, a->len * sizeof *data);
        owner = narr_track(a, 0); owner->data = data;
    } else {
        int64_t *data = realloc(owner->data, cap * sizeof *data);
        if (!data) { NVM2C_ABORT(); } owner->data = data;
    }
    size_t growth = (cap - owner->cap) * sizeof *owner->data;
    if (owner->environments) {
        const void **environments = realloc(owner->environments, cap * sizeof *environments);
        if (!environments) NVM2C_ABORT();
        memset(environments + owner->cap, 0, (cap - owner->cap) * sizeof *environments);
        owner->environments = environments;
        size_t extra = (cap - owner->cap) * sizeof *environments;
        nagg_add(extra); owner->bytes += extra;
    }
    nagg_add(growth); owner->bytes += growth;
    owner->cap = cap; a->data = owner->data;
}
static inline const void *narr_environment(narr_t a, size_t at) {
    if (!a || at >= a->len) NVM2C_ABORT();
    return a->owner && a->owner->environments ? a->owner->environments[at] : NULL;
}
static inline void narr_release_owned(void) {
    while (narr_owners) { struct narr_owner *owner = narr_owners;
        narr_owners = owner->next; nagg_drop(owner->bytes); free(owner->environments); free(owner->data); free(owner->handle); free(owner); }
}
/* I count retained owned map storage, including API copies until release.
 * Bucket growth charges net capacity; temporary old/new overlap and allocator
 * overhead are not counted, so this is neither instantaneous allocation nor RSS. */
static size_t nmap_live_bytes, nmap_peak_bytes, nmap_allocation_debt;
static void nmap_bytes_add(size_t bytes) {
    if (bytes > SIZE_MAX - nmap_live_bytes || bytes > SIZE_MAX - nmap_allocation_debt) NVM2C_ABORT();
    nmap_live_bytes += bytes; nmap_allocation_debt += bytes;
    if (nmap_live_bytes > nmap_peak_bytes) nmap_peak_bytes = nmap_live_bytes;
}
static void nmap_bytes_drop(size_t bytes) {
    if (bytes > nmap_live_bytes) NVM2C_ABORT();
    nmap_live_bytes -= bytes;
}
static size_t nmap_text_bytes(const char *text) {
    if (!text) NVM2C_ABORT();
    size_t n = strlen(text); if (n == SIZE_MAX) NVM2C_ABORT(); return n + 1;
}
static void nmap_release_text(char *text) {
    nmap_bytes_drop(nmap_text_bytes(text)); free(text);
}
typedef struct { uint8_t kind; int64_t integer; char *text; } nmap_value;
typedef struct nmap_entry { uint64_t hash; char *key; nmap_value value; struct nmap_entry *next; } nmap_entry;
typedef struct nmap_s { nmap_entry **buckets; size_t capacity, count; uint8_t value_kind; } nmap_s;
typedef nmap_s *nmap_t;
static char *nmap_copy_text(const char *text) {
    if (!text) NVM2C_ABORT();
    size_t n = strlen(text); if (n == SIZE_MAX) NVM2C_ABORT();
    char *copy = malloc(n + 1); if (!copy) NVM2C_ABORT();
    nmap_bytes_add(n + 1); memcpy(copy, text, n + 1); return copy;
}
static nmap_value nmap_copy_value(nmap_value value) {
    if (value.kind == 5) value.text = nmap_copy_text(value.text);
    else if (value.kind == 1) value.text = NULL;
    else NVM2C_ABORT();
    return value;
}
static void nmap_release_value(nmap_value value) { if (value.kind == 5) nmap_release_text(value.text); }
static uint64_t nmap_hash(const char *key) {
    if (!key) NVM2C_ABORT();
    uint64_t h = UINT64_C(14695981039346656037);
    for (const unsigned char *p = (const unsigned char *)key; *p; ++p) {
        h ^= *p; h *= UINT64_C(1099511628211);
    } return h;
}
static nmap_t nmap_new(uint8_t value_kind) {
    if (value_kind != 1 && value_kind != 5) NVM2C_ABORT();
    nmap_t map = calloc(1, sizeof *map); if (!map) NVM2C_ABORT();
    map->capacity = 16; map->value_kind = value_kind;
    map->buckets = calloc(map->capacity, sizeof *map->buckets);
    if (!map->buckets) { free(map); NVM2C_ABORT(); }
    nmap_bytes_add(sizeof *map + map->capacity * sizeof *map->buckets);
    return map;
}
static nmap_entry *nmap_find(nmap_t map, const char *key, uint64_t hash) {
    if (!map) NVM2C_ABORT();
    for (nmap_entry *entry = map->buckets[hash & (map->capacity - 1)]; entry; entry = entry->next)
        if (entry->hash == hash && strcmp(entry->key, key) == 0) return entry;
    return NULL;
}
static void nmap_grow(nmap_t map) {
    if (map->capacity > SIZE_MAX / 2 / sizeof *map->buckets) NVM2C_ABORT();
    size_t capacity = map->capacity * 2;
    nmap_entry **buckets = calloc(capacity, sizeof *buckets); if (!buckets) NVM2C_ABORT();
    for (size_t i = 0; i < map->capacity; ++i) {
        nmap_entry *entry = map->buckets[i];
        while (entry) { nmap_entry *next = entry->next;
            size_t at = entry->hash & (capacity - 1);
            entry->next = buckets[at]; buckets[at] = entry; entry = next; }
    }
    nmap_bytes_add((capacity - map->capacity) * sizeof *buckets);
    free(map->buckets); map->buckets = buckets; map->capacity = capacity;
}
static nmap_t nmap_set(nmap_t map, const char *key, nmap_value value) {
    if (!map || value.kind != map->value_kind) NVM2C_ABORT();
    uint64_t hash = nmap_hash(key); nmap_entry *entry = nmap_find(map, key, hash);
    nmap_value owned = nmap_copy_value(value);
    if (entry) { nmap_release_value(entry->value); entry->value = owned; return map; }
    char *owned_key = nmap_copy_text(key);
    entry = malloc(sizeof *entry); if (!entry) NVM2C_ABORT();
    nmap_bytes_add(sizeof *entry);
    if (map->count >= map->capacity / 2) nmap_grow(map);
    size_t at = hash & (map->capacity - 1);
    *entry = (nmap_entry){hash, owned_key, owned, map->buckets[at]};
    map->buckets[at] = entry; ++map->count; return map;
}
static int nmap_has(nmap_t map, const char *key) { return nmap_find(map, key, nmap_hash(key)) != NULL; }
static nmap_value nmap_get(nmap_t map, const char *key) {
    nmap_entry *entry = nmap_find(map, key, nmap_hash(key));
    return entry ? nmap_copy_value(entry->value) : (nmap_value){0};
}
static size_t nmap_len(nmap_t map) { if (!map) NVM2C_ABORT(); return map->count; }
static nmap_t nmap_delete(nmap_t map, const char *key) {
    if (!map) NVM2C_ABORT();
    uint64_t hash = nmap_hash(key);
    nmap_entry **link = &map->buckets[hash & (map->capacity - 1)];
    while (*link) { nmap_entry *entry = *link;
        if (entry->hash == hash && strcmp(entry->key, key) == 0) {
            *link = entry->next; nmap_release_text(entry->key); nmap_release_value(entry->value);
            nmap_bytes_drop(sizeof *entry); free(entry); --map->count; break; }
        link = &entry->next;
    } return map;
}
static void nmap_destroy(nmap_t map) {
    if (!map) return;
    for (size_t i = 0; i < map->capacity; ++i) {
        nmap_entry *entry = map->buckets[i];
        while (entry) { nmap_entry *next = entry->next; nmap_release_text(entry->key);
            nmap_release_value(entry->value); nmap_bytes_drop(sizeof *entry); free(entry); entry = next; }
    } nmap_bytes_drop(sizeof *map + map->capacity * sizeof *map->buckets);
    free(map->buckets); free(map);
}
static size_t nmap_collection_budget = 65536;
typedef struct nmap_owned { nmap_t map; struct nmap_owned *next; unsigned marked; } nmap_owned;
static nmap_owned *nmap_owned_head;
typedef struct nvalue_owned { nmap_value value; struct nvalue_owned *next; unsigned marked; } nvalue_owned;
static nvalue_owned *nvalue_owned_head;
static size_t nmap_owned_live, nmap_owned_peak;
static nmap_value nmap_owned_get(nmap_t map, const char *key) {
    nmap_value value = nmap_get(map, key);
    if (value.kind == 5) { nvalue_owned *owner = malloc(sizeof *owner);
        if (!owner) { nmap_release_value(value); NVM2C_ABORT(); }
        *owner = (nvalue_owned){value, nvalue_owned_head, 0}; nvalue_owned_head = owner;
        nmap_bytes_add(sizeof *owner);
        if (++nmap_owned_live > nmap_owned_peak) nmap_owned_peak = nmap_owned_live; }
    return value;
}
static inline nmap_value nvalue_from_float(double value) {
    nmap_value result = {3, 0, NULL}; memcpy(&result.integer, &value, sizeof value); return result;
}
static inline double nvalue_require_float(nmap_value value) {
    if (value.kind != 3) NVM2C_ABORT();
    double result; memcpy(&result, &value.integer, sizeof result); return result;
}
static inline nmap_value nvalue_numeric(nmap_value a, nmap_value b, char op) {
    if (op != '~' && a.kind == 9) a.kind = 1;
    if (a.kind != 1 && a.kind != 3) NVM2C_ABORT();
    if (op == '~') return a.kind == 3 ? nvalue_from_float(-nvalue_require_float(a)) : (nmap_value){1, ni64_from_bits(UINT64_C(0) - (uint64_t)a.integer), NULL};
    if (b.kind == 9) b.kind = 1;
    if (b.kind != 1 && b.kind != 3) NVM2C_ABORT();
    if (a.kind == 1 && b.kind == 1) {
        int64_t x = a.integer, y = b.integer, value;
        if (op == '+') value = ni64_from_bits((uint64_t)x + (uint64_t)y);
        else if (op == '-') value = ni64_from_bits((uint64_t)x - (uint64_t)y);
        else if (op == '*') value = ni64_from_bits((uint64_t)x * (uint64_t)y);
        else if (op == '/') value = y == 0 ? 0 : (x == INT64_MIN && y == -1) ? INT64_MIN : x / y;
        else NVM2C_ABORT();
        return (nmap_value){1, value, NULL};
    }
    double x = a.kind == 3 ? nvalue_require_float(a) : (double)a.integer;
    double y = b.kind == 3 ? nvalue_require_float(b) : (double)b.integer;
    if (op == '+') return nvalue_from_float(nano_rt_f64_add(x, y));
    if (op == '-') return nvalue_from_float(nano_rt_f64_sub(x, y));
    if (op == '*') return nvalue_from_float(nano_rt_f64_mul(x, y));
    if (op == '/') return nvalue_from_float(nano_rt_f64_div(x, y));
    NVM2C_ABORT();
}
static inline int64_t nvalue_require_int(nmap_value value) {
    if (value.kind != 1) NVM2C_ABORT();
    return value.integer;
}
static inline int64_t nvalue_require_function(nmap_value value) {
    if (value.kind != 11) NVM2C_ABORT();
    return value.integer;
}
static inline int64_t nvalue_require_bool(nmap_value value) {
    if (value.kind != 4) NVM2C_ABORT();
    return value.integer;
}
static inline const char *nvalue_require_string(nmap_value value) {
    if (value.kind != 5) NVM2C_ABORT();
    return value.text;
}
static inline nmap_t nvalue_require_map(nmap_value value) {
    if (value.kind != 13 || !value.text) NVM2C_ABORT();
    return (nmap_t)value.text;
}
static inline double nvalue_cast_float(nmap_value value) {
    if (value.kind == 3) return nvalue_require_float(value);
    if (value.kind == 1 || value.kind == 2) return (double)value.integer;
    if (value.kind == 4) return value.integer ? 1.0 : 0.0;
    if (value.kind == 5) return nparse_binary64(value.text);
    return 0.0;
}
static inline uint8_t nvalue_cast_u8(nmap_value value) {
    if (value.kind != 1 && value.kind != 2) NVM2C_ABORT();
    return (uint8_t)value.integer;
}
static inline int64_t nvalue_cast_int(nmap_value value) {
    if (value.kind == 3) return nf64_to_i64(nvalue_require_float(value));
    return value.kind == 1 || value.kind == 2 || value.kind == 4 || value.kind == 9 ? value.integer : value.kind == 5 ? (int64_t)strtoll(value.text, NULL, 10) : 0;
}
static inline int64_t nvalue_require_byte(nmap_value value) {
    if (value.kind != 1 && value.kind != 2) NVM2C_ABORT();
    return (uint8_t)value.integer;
}
static inline void *nvalue_require_opaque(nmap_value value) {
    if (value.kind == 14) return (void *)value.text;
    if (value.kind == 1 && value.integer == 0) return NULL;
    NVM2C_ABORT();
}
static inline int nvalue_equal(nmap_value a, nmap_value b) {
    if (a.kind == 14 && b.kind == 1) return !a.text && b.integer == 0;
    if (a.kind == 1 && b.kind == 14) return a.integer == 0 && !b.text;
    if (a.kind == 14 && b.kind == 14) return a.text == b.text;
    if ((a.kind == 9 && b.kind == 1) || (a.kind == 1 && b.kind == 9)) return a.integer == b.integer;
    if (a.kind == 1 && b.kind == 3) return (double)a.integer == nvalue_require_float(b);
    if (a.kind == 3 && b.kind == 1) return nvalue_require_float(a) == (double)b.integer;
    if (a.kind != b.kind) return 0;
    if (a.kind == 7 || a.kind == 13 || a.kind == 15) return a.text == b.text;
    if (a.kind == 3) return nvalue_require_float(a) == nvalue_require_float(b);
    if (a.kind == 0) return 1;
    if (a.kind == 1 || a.kind == 2 || a.kind == 4 || a.kind == 9 || a.kind == 11) return a.integer == b.integer;
    if (a.text == b.text) return 1;
    if (!a.text || !b.text) return 0;
    return strcmp(a.text, b.text) == 0;
}
static inline int nvalue_compare(nmap_value a, nmap_value b) {
    if ((a.kind == 9 && b.kind == 1) || (a.kind == 1 && b.kind == 9)) return (a.integer > b.integer) - (a.integer < b.integer);
    if ((a.kind == 3 && (b.kind == 3 || b.kind == 1)) || (a.kind == 1 && b.kind == 3)) {
        double x = a.kind == 3 ? nvalue_require_float(a) : (double)a.integer;
        double y = b.kind == 3 ? nvalue_require_float(b) : (double)b.integer;
        return (x > y) - (x < y);
    }
    if (a.kind != b.kind) return (int)a.kind - (int)b.kind;
    if (a.kind == 1 || a.kind == 2 || a.kind == 4 || a.kind == 11) return (a.integer > b.integer) - (a.integer < b.integer);
    if (a.kind == 5) {
        if (a.text == b.text) return 0;
        if (!a.text) { return -1; } if (!b.text) { return 1; }
        return strcmp(a.text, b.text);
    }
    return 0;
}
static nmap_t nmap_owned_new(uint8_t kind) {
    nmap_t map = nmap_new(kind); nmap_owned *owner = malloc(sizeof *owner);
    if (!owner) { nmap_destroy(map); NVM2C_ABORT(); }
    *owner = (nmap_owned){map, nmap_owned_head, 0}; nmap_owned_head = owner;
    nmap_bytes_add(sizeof *owner);
    if (++nmap_owned_live > nmap_owned_peak) nmap_owned_peak = nmap_owned_live;
    return map;
}
static void nmap_release_owned(void) {
    while (nvalue_owned_head) { nvalue_owned *owner = nvalue_owned_head;
        nvalue_owned_head = owner->next; nmap_release_value(owner->value); nmap_bytes_drop(sizeof *owner); free(owner); --nmap_owned_live; }
    while (nmap_owned_head) { nmap_owned *owner = nmap_owned_head;
        nmap_owned_head = owner->next; nmap_destroy(owner->map); nmap_bytes_drop(sizeof *owner); free(owner); --nmap_owned_live; }
}
typedef struct nrarr_s nrarr_s;
typedef nrarr_s *nrarr_t;
typedef struct nrec_s nrec_t;
struct nrec_s { int64_t f[2]; const char *s[2]; narr_t a[2]; nsarr_t sa[2]; nrarr_t ra[2]; const nrec_t *rec[2]; uint8_t k[2], vk[2]; uint16_t n, tag; uint8_t kind; uint32_t callable_target; nmap_t m[2]; };
static inline int nrec_field_storage_matches(const nrec_t *a, const nrec_t *b, size_t field) {
    unsigned ak = a->k[field], bk = b->k[field];
    if (ak == bk) return 1;
    unsigned at = ak == 0 ? 1 : ak == 9 ? 4 : ak == 1 ? 5 : ak == 11 ? 3 : ak == 8 ? a->vk[field] : 255;
    unsigned bt = bk == 0 ? 1 : bk == 9 ? 4 : bk == 1 ? 5 : bk == 11 ? 3 : bk == 8 ? b->vk[field] : 255;
    return at == bt && (at == 1 || at == 3 || at == 4 || at == 5) &&
           (at != 5 || (a->s[field] && b->s[field]));
}
struct nrarr_s { nrec_t *data; size_t len; struct nrarr_owner *owner; };

typedef struct nrec_owned { nrec_t value; struct nrec_owned *next; } nrec_owned;
static nrec_owned *nrec_owned_head;
static inline const nrec_t *nrec_snapshot(nrec_t value) {
    nrec_owned *node = malloc(sizeof *node);
    if (!node) NVM2C_ABORT();
    nagg_add(sizeof *node);
    node->value = value; node->next = nrec_owned_head; nrec_owned_head = node;
    return &node->value;
}
static void nrec_release_snapshots(void) {
    while (nrec_owned_head) { nrec_owned *node = nrec_owned_head;
        nrec_owned_head = node->next; nagg_drop(sizeof *node); free(node); }
}
static inline nrec_t nvalue_require_record(nmap_value value) {
    if ((value.kind != 8 && value.kind != 10 && value.kind != 12) || !value.text) NVM2C_ABORT();
    return *(const nrec_t *)value.text;
}
#include <string.h>
struct nrarr_owner { nrec_t *data; size_t cap, bytes; nrarr_t handle; struct nrarr_owner *next; };
static struct nrarr_owner *nrarr_owners;
static inline struct nrarr_owner *nrarr_track(nrarr_t a, int own_handle) {
    struct nrarr_owner *owner = calloc(1, sizeof *owner);
    if (!owner) NVM2C_ABORT();
    owner->bytes = sizeof *owner + (own_handle ? sizeof *a : 0); nagg_add(owner->bytes);
    owner->handle = own_handle ? a : NULL; owner->next = nrarr_owners;
    nrarr_owners = owner; a->owner = owner; return owner;
}
static inline void nrarr_release_owned(void) {
    while (nrarr_owners) { struct nrarr_owner *owner = nrarr_owners;
        nrarr_owners = owner->next; nagg_drop(owner->bytes); free(owner->data); free(owner->handle); free(owner); }
}
static inline nrarr_t nrarr_new(void) {
    nrarr_t a = calloc(1, sizeof *a); if (!a) NVM2C_ABORT();
    nrarr_track(a, 1); return a;
}
static inline void nrarr_reserve(nrarr_t a, size_t n) {
    size_t limit = SIZE_MAX / sizeof(nrec_t);
    if (!a || n > limit || a->len > limit || (a->len && !a->data)) NVM2C_ABORT();
    struct nrarr_owner *owner = a->owner;
    if (owner && (owner->data != a->data || a->len > owner->cap)) NVM2C_ABORT();
    if (owner && n <= owner->cap) return;
    if (n < a->len) n = a->len;
    size_t cap = owner && owner->cap ? owner->cap : 8;
    while (cap < n) { if (cap > limit / 2) { cap = n; break; } cap *= 2; }
    if (!owner) {
        nrec_t *data = malloc(cap * sizeof *data); if (!data) NVM2C_ABORT();
        if (a->len) memcpy(data, a->data, a->len * sizeof *data);
        owner = nrarr_track(a, 0); owner->data = data;
    } else {
        nrec_t *data = realloc(owner->data, cap * sizeof *data);
        if (!data) NVM2C_ABORT();
        owner->data = data;
    }
    size_t growth = (cap - owner->cap) * sizeof *owner->data;
    nagg_add(growth); owner->bytes += growth;
    owner->cap = cap; a->data = owner->data;
}

static nrarr_t nrarr_push(nrarr_t a, nrec_t v) {
    if (!a || a->len >= SIZE_MAX / sizeof(nrec_t)) NVM2C_ABORT();
    nrarr_reserve(a, a->len + 1);
    a->data[a->len++] = v;
    return a;
}

static nrec_t nrarr_get(nrarr_t a, int64_t idx) {
    if (!a || idx < 0 || (uint64_t)idx >= a->len || !a->data) NVM2C_ABORT();
    return a->data[idx];
}

typedef struct { uint8_t kind; const void *ptr; } nroot_ref;
typedef struct { nroot_ref *items; size_t count, capacity; size_t *slots; size_t slot_count; } nroot_list;
typedef struct nroot_frame { nroot_list live; struct nroot_frame *prev; } nroot_frame;
static nroot_frame *nroot_head;
static size_t nroot_hash(uint8_t kind, const void *ptr) {
    uint64_t value = (uint64_t)(uintptr_t)ptr ^ kind;
    value = (value ^ (value >> 30)) * UINT64_C(0xbf58476d1ce4e5b9);
    value = (value ^ (value >> 27)) * UINT64_C(0x94d049bb133111eb);
    return (size_t)(value ^ (value >> 31));
}
static size_t nroot_slot(const nroot_list *list, uint8_t kind, const void *ptr) {
    size_t slot = nroot_hash(kind, ptr) & (list->slot_count - 1);
    while (list->slots[slot]) {
        size_t index = list->slots[slot] - 1;
        if (list->items[index].kind == kind && list->items[index].ptr == ptr) break;
        slot = (slot + 1) & (list->slot_count - 1);
    }
    return slot;
}
static int nroot_contains(const nroot_list *list, uint8_t kind, const void *ptr) {
    return list->slot_count && list->slots[nroot_slot(list, kind, ptr)] != 0;
}
static inline void nroot_reset(nroot_list *list) {
    list->count = 0;
    if (list->slot_count) memset(list->slots, 0, list->slot_count * sizeof *list->slots);
}
static void nroot_destroy(nroot_list *list) {
    free(list->items); free(list->slots); *list = (nroot_list){0};
}
static void nroot_add(nroot_list *list, uint8_t kind, const void *ptr) {
    if (!ptr || kind == 0 || kind == 2 || kind == 9 || kind == 11) return;
    if (nroot_contains(list, kind, ptr)) return;
    if (list->count >= list->slot_count / 2) {
        if (list->slot_count > SIZE_MAX / 2 / sizeof *list->slots) NVM2C_ABORT();
        size_t count = list->slot_count ? list->slot_count * 2 : 32;
        size_t *slots = calloc(count, sizeof *slots);
        if (!slots) NVM2C_ABORT();
        free(list->slots); list->slots = slots; list->slot_count = count;
        for (size_t i = 0; i < list->count; ++i)
            list->slots[nroot_slot(list, list->items[i].kind, list->items[i].ptr)] = i + 1;
    }
    if (list->count == list->capacity) {
        if (list->capacity > SIZE_MAX / 2 / sizeof *list->items) NVM2C_ABORT();
        size_t capacity = list->capacity ? list->capacity * 2 : 16;
        nroot_ref *items = realloc(list->items, capacity * sizeof *items);
        if (!items) NVM2C_ABORT();
        list->items = items; list->capacity = capacity;
    }
    size_t slot = nroot_slot(list, kind, ptr);
    list->items[list->count++] = (nroot_ref){kind, ptr};
    list->slots[slot] = list->count;
}
static void nroot_value(nroot_list *work, nmap_value value) {
    if (value.kind == 5) nroot_add(work, 1, value.text);
    else if (value.kind == 15 || value.kind == 8 || value.kind == 10 || value.kind == 12) nroot_add(work, 4, value.text);
    else if (value.kind == 13) nroot_add(work, 7, value.text);
    else if (value.kind == 7) nroot_add(work, (uint8_t)value.integer, value.text);
}
static void nroot_trace(nroot_list *work) {
    for (size_t cursor = 0; cursor < work->count; ++cursor) {
        nroot_ref root = work->items[cursor];
        if (root.kind == 8 || root.kind == 13) nroot_value(work, *(const nmap_value *)root.ptr);
        else if (root.kind == 3 || root.kind == 10 || root.kind == 12 || root.kind == 14 || root.kind == 15 || root.kind == 16) {
            const narr_s *a = root.ptr;
            nroot_add(work, 128, a->owner);
            if (root.kind == 14) for (size_t i = 0; i < a->len; ++i)
                nroot_add(work, 4, narr_environment((narr_t)a, i));
            if (root.kind == 16) for (size_t i = 0; i < a->len; ++i)
                nroot_add(work, (uint8_t)a->data[i], narr_environment((narr_t)a, i));
        }
        else if (root.kind == 5) {
            const nsarr_s *a = root.ptr;
            nroot_add(work, 128, a->owner);
            for (size_t i = 0; i < a->len; ++i) nroot_add(work, 1, a->data[i]);
        } else if (root.kind == 6) {
            const nrarr_s *a = root.ptr;
            nroot_add(work, 128, a->owner);
            if (a->len && !a->data) NVM2C_ABORT();
            for (size_t i = 0; i < a->len; ++i) nroot_add(work, 4, &a->data[i]);
        } else if (root.kind == 4) {
            const nrec_t *r = root.ptr;
            for (size_t i = 0; i < r->n; ++i) {
                if (r->k[i] == 1) nroot_add(work, 1, r->s[i]);
                else if (r->k[i] == 3 || r->k[i] == 10 || r->k[i] == 12 || r->k[i] == 14 || r->k[i] == 15 || r->k[i] == 16) nroot_add(work, r->k[i], r->a[i]);
                else if (r->k[i] == 4) nroot_add(work, 4, r->rec[i]);
                else if (r->k[i] == 5) nroot_add(work, 5, r->sa[i]);
                else if (r->k[i] == 6) nroot_add(work, 6, r->ra[i]);
                else if (r->k[i] == 7) nroot_add(work, 7, r->m[i]);
                else if (r->k[i] == 8 || r->k[i] == 13) nroot_value(work, (nmap_value){r->vk[i], r->f[i], (char *)r->s[i]});
            }
        }
    }
    /* I mark each owner once after closing the same reachable graph. */
    for (nvalue_owned *v = nvalue_owned_head; v; v = v->next)
        if (nroot_contains(work, 1, v->value.text)) v->marked = 1;
    for (nmap_owned *m = nmap_owned_head; m; m = m->next)
        if (nroot_contains(work, 7, m->map)) m->marked = 1;
}
static void nmap_sweep(void) {
    nmap_owned **maps = &nmap_owned_head;
    while (*maps) {
        nmap_owned *owner = *maps;
        if (owner->marked) { owner->marked = 0; maps = &owner->next; }
        else { *maps = owner->next; nmap_destroy(owner->map); nmap_bytes_drop(sizeof *owner); free(owner); --nmap_owned_live; }
    }
    nvalue_owned **values = &nvalue_owned_head;
    while (*values) {
        nvalue_owned *owner = *values;
        if (owner->marked) { owner->marked = 0; values = &owner->next; }
        else { *values = owner->next; nmap_release_value(owner->value); nmap_bytes_drop(sizeof *owner); free(owner); --nmap_owned_live; }
    }
}
static void nagg_sweep(const nroot_list *roots) {
    (void)roots;
    nrec_owned **records = &nrec_owned_head;
    while (*records) {
        nrec_owned *owner = *records;
        if (nroot_contains(roots, 4, &owner->value)) records = &owner->next;
        else { *records = owner->next; nagg_drop(sizeof *owner); free(owner); }
    }
    { struct narr_owner **link = &narr_owners;
      while (*link) { struct narr_owner *owner = *link;
        if (nroot_contains(roots, 128, owner)) link = &owner->next;
        else { *link = owner->next; nagg_drop(owner->bytes);
            free(owner->environments); free(owner->data); free(owner->handle); free(owner); }
      } }
    { struct nsarr_owner **link = &nsarr_owners;
      while (*link) { struct nsarr_owner *owner = *link;
        if (nroot_contains(roots, 128, owner)) link = &owner->next;
        else { *link = owner->next; nagg_drop(owner->bytes);
            free(owner->data); free(owner->handle); free(owner); }
      } }
    { struct nrarr_owner **link = &nrarr_owners;
      while (*link) { struct nrarr_owner *owner = *link;
        if (nroot_contains(roots, 128, owner)) link = &owner->next;
        else { *link = owner->next; nagg_drop(owner->bytes);
            free(owner->data); free(owner->handle); free(owner); }
      } }
    nsarr_string **strings = &nsarr_strings;
    while (*strings) { nsarr_string *owner = *strings;
        if (nroot_contains(roots, 1, owner->data)) strings = &owner->next;
        else { *strings = owner->next; nagg_drop(owner->bytes); free(owner->data); free(owner); }
    }
    nagg_allocation_debt = 0;
}
static inline size_t nheap_bytes_sum(size_t a, size_t z) {
    if (z > SIZE_MAX - a) NVM2C_ABORT();
    return a + z;
}
static void nmap_collect(void) {
    nroot_list work = {0};
    for (nroot_frame *f = nroot_head; f; f = f->prev)
        for (size_t i = 0; i < f->live.count; ++i)
            nroot_add(&work, f->live.items[i].kind, f->live.items[i].ptr);
    nroot_trace(&work);
    nagg_sweep(&work);
    nroot_destroy(&work); nmap_sweep();
    nmap_allocation_debt = 0;
    size_t retained = nheap_bytes_sum(0, nmap_live_bytes);
    retained = nheap_bytes_sum(retained, nagg_live_bytes);
    nmap_collection_budget = retained > 65536 ? retained : 65536;
}
/* I amortize a complete graph scan over all surviving owner storage.
 * Small owner families cannot independently trigger repeated scans of large ones.
 * Without allocation, dropped owners wait for the next allocating safepoint. */
static inline void nmap_collect_if_needed(void) {
    size_t debt = nheap_bytes_sum(0, nmap_allocation_debt);
    debt = nheap_bytes_sum(debt, nagg_allocation_debt);
    if (debt >= nmap_collection_budget) nmap_collect();
}
static narr_t narr_lit(const int64_t *elems, size_t n) {
    if (n > 0 && !elems) NVM2C_ABORT();
    narr_t a = narr_new(); narr_reserve(a, n);
    if (n) memcpy(a->data, elems, n * sizeof *a->data);
    a->len = n; return a;
}
static int64_t narr_get(narr_t a, int64_t idx) {
    if (!a || !a->data || idx < 0 || (size_t)idx >= a->len) NVM2C_ABORT();
    return a->data[idx];
}
static inline narr_t narr_push(narr_t a, int64_t v) {
    if (!a || a->len == SIZE_MAX) NVM2C_ABORT();
    narr_reserve(a, a->len + 1); a->data[a->len++] = v; return a;
}
static nsarr_t nsarr_lit(const char *const *elems, size_t n) {
    if (n > 0 && !elems) NVM2C_ABORT();
    nsarr_t a = nsarr_new();
    nsarr_reserve(a, n);
    if (n) memcpy(a->data, elems, n * sizeof *a->data);
    a->len = n;
    return a;
}

static const char *nsarr_get(nsarr_t a, int64_t idx) {
    if (!a || !a->data || idx < 0 || (size_t)idx >= a->len) NVM2C_ABORT();
    return a->data[idx] ? a->data[idx] : "";
}

static inline nsarr_t nsarr_push(nsarr_t a, const char *v) {
    if (!a || a->len == SIZE_MAX) NVM2C_ABORT();
    size_t n = a->len + 1;
    nsarr_reserve(a, n);
    a->data[a->len] = v ? v : "";
    a->len = n;
    return a;
}

static inline void narr_set_reference(narr_t a, size_t at, int64_t payload, const void *reference) {
    if (!a || at >= a->len) NVM2C_ABORT();
    narr_reserve(a, a->len);
    struct narr_owner *owner = a->owner;
    if (reference && !owner->environments) {
        owner->environments = calloc(owner->cap, sizeof *owner->environments);
        if (!owner->environments) NVM2C_ABORT();
        size_t bytes = owner->cap * sizeof *owner->environments;
        nagg_add(bytes); owner->bytes += bytes;
    }
    a->data[at] = payload;
    if (owner->environments) owner->environments[at] = reference;
}
static inline void ncall_array_set(narr_t a, size_t at, nmap_value value) {
    if ((value.kind != 11 && value.kind != 15) || (value.kind == 15 && !value.text)) NVM2C_ABORT();
    narr_set_reference(a, at, value.integer, value.kind == 15 ? value.text : NULL);
}
static inline void nchild_array_set(narr_t a, size_t at, nmap_value value) {
    if (value.kind != 7 || !value.text) NVM2C_ABORT();
    narr_set_reference(a, at, value.integer, value.text);
}
static inline narr_t nchild_array_push(narr_t a, nmap_value value) {
    if (!a || a->len == SIZE_MAX) NVM2C_ABORT();
    narr_reserve(a, a->len + 1);
    size_t at = a->len++; nchild_array_set(a, at, value); return a;
}
static inline narr_t ncall_array_push(narr_t a, nmap_value value) {
    if (!a || a->len == SIZE_MAX) NVM2C_ABORT();
    narr_reserve(a, a->len + 1);
    size_t at = a->len++; ncall_array_set(a, at, value); return a;
}
static inline narr_t nvalue_require_int_array(nmap_value a) {
    if (a.kind != 7 || a.integer != 3 || !a.text) NVM2C_ABORT();
    return (narr_t)a.text;
}
static inline int64_t nvalue_array_len(nmap_value a) {
    if (a.kind != 7 || !a.text) NVM2C_ABORT();
    if (a.integer == 3 || a.integer == 10 || a.integer == 12 || a.integer == 14 || a.integer == 15 || a.integer == 16) return (int64_t)((narr_t)a.text)->len;
    if (a.integer == 5) return (int64_t)((nsarr_t)a.text)->len;
    if (a.integer == 6) return (int64_t)((nrarr_t)a.text)->len;
    NVM2C_ABORT();
}
static inline nmap_value nvalue_array_get(nmap_value a, int64_t index) {
    int64_t length = nvalue_array_len(a);
    if (index < 0 || (uint64_t)index >= (uint64_t)length) return (nmap_value){0, 0, NULL};
    size_t at = (size_t)index;
    if (a.integer == 6) {
        const nrec_t *value = nrec_snapshot(((nrarr_t)a.text)->data[at]);
        return (nmap_value){value->kind == 0 ? 8 : value->kind == 1 ? 10 : 12, 0, (char *)value};
    }
    if (a.integer == 16) return (nmap_value){7, ((narr_t)a.text)->data[at], (char *)narr_environment((narr_t)a.text, at)};
    if (a.integer == 14) {
        narr_t array = (narr_t)a.text; const void *environment = narr_environment(array, at);
        return (nmap_value){environment ? 15 : 11, array->data[at], (char *)environment};
    }
    if (a.integer == 3 || a.integer == 10 || a.integer == 12 || a.integer == 15) return (nmap_value){a.integer == 15 ? 2 : a.integer == 12 ? 3 : a.integer == 10 ? 4 : 1, narr_get((narr_t)a.text, at), NULL};
    return (nmap_value){5, 0, (char *)nsarr_get((nsarr_t)a.text, at)};
}
static inline nmap_value nvalue_array_set(nmap_value a, int64_t index, nmap_value value) {
    if (a.integer == 6) NVM2C_ABORT();
    if (index < 0 || (uint64_t)index >= (uint64_t)nvalue_array_len(a)) NVM2C_ABORT();
    size_t at = (size_t)index;
    if (a.integer == 3) ((narr_t)a.text)->data[at] = nvalue_require_int(value);
    else if (a.integer == 14) {
        ncall_array_set((narr_t)a.text, at, value);
    }
    else if (a.integer == 16) {
        nchild_array_set((narr_t)a.text, at, value);
    }
    else if (a.integer == 15) ((narr_t)a.text)->data[at] = nvalue_require_byte(value);
    else if (a.integer == 10) ((narr_t)a.text)->data[at] = nvalue_require_bool(value);
    else if (a.integer == 12) ((narr_t)a.text)->data[at] = nvalue_from_float(nvalue_require_float(value)).integer;
    else ((nsarr_t)a.text)->data[at] = nvalue_require_string(value);
    return a;
}
static inline nmap_value nvalue_array_push(nmap_value a, nmap_value value) {
    (void)nvalue_array_len(a); (void)value;
    if (a.integer == 3) { narr_push((narr_t)a.text, nvalue_require_int(value)); return a; }
    if (a.integer == 16) { nchild_array_push((narr_t)a.text, value); return a; }
    if (a.integer == 15) { narr_push((narr_t)a.text, nvalue_require_byte(value)); return a; }
    if (a.integer == 14) { ncall_array_push((narr_t)a.text, value); return a; }
    if (a.integer == 10) { narr_push((narr_t)a.text, nvalue_require_bool(value)); return a; }
    if (a.integer == 12) { narr_push((narr_t)a.text, nvalue_from_float(nvalue_require_float(value)).integer); return a; }
    if (a.integer == 5) { nsarr_push((nsarr_t)a.text, nvalue_require_string(value)); return a; }
    NVM2C_ABORT();
}
static inline void nslice_bounds(size_t length, int64_t begin, int64_t end, size_t *start, size_t *count) {
    size_t lo = (uint32_t)begin, hi = (uint32_t)end;
    if (lo > length) lo = length;
    if (hi > length) hi = length;
    *start = lo; *count = hi > lo ? hi - lo : 0;
}
static inline narr_t narr_slice(narr_t input, int64_t begin, int64_t end) {
    if (!input) NVM2C_ABORT();
    size_t start, count; nslice_bounds(input->len, begin, end, &start, &count);
    narr_t result = narr_new(); narr_reserve(result, count);
    if (count) memcpy(result->data, input->data + start, count * sizeof *result->data);
    result->len = count;
    for (size_t i = 0; i < count; ++i) {
        const void *environment = narr_environment(input, start + i);
        if (environment) narr_set_reference(result, i, result->data[i], environment);
    }
    return result;
}
static inline nsarr_t nsarr_slice(nsarr_t input, int64_t begin, int64_t end) {
    if (!input) NVM2C_ABORT();
    size_t start, count; nslice_bounds(input->len, begin, end, &start, &count);
    nsarr_t result = nsarr_new(); nsarr_reserve(result, count);
    if (count) memcpy(result->data, input->data + start, count * sizeof *result->data);
    result->len = count;
    return result;
}
static inline nrarr_t nrarr_slice(nrarr_t input, int64_t begin, int64_t end) {
    if (!input) NVM2C_ABORT();
    size_t start, count; nslice_bounds(input->len, begin, end, &start, &count);
    nrarr_t result = nrarr_new(); nrarr_reserve(result, count);
    if (count) memcpy(result->data, input->data + start, count * sizeof *result->data);
    result->len = count;
    return result;
}
static inline nmap_value nvalue_array_slice(nmap_value a, int64_t begin, int64_t end) {
    if (a.kind != 7 || !a.text) NVM2C_ABORT();
    if (a.integer == 3 || a.integer == 10 || a.integer == 12 || a.integer == 14 || a.integer == 15 || a.integer == 16) { a.text = (char *)narr_slice((narr_t)a.text, begin, end); return a; }
    if (a.integer == 5) { a.text = (char *)nsarr_slice((nsarr_t)a.text, begin, end); return a; }
    if (a.integer == 6) { a.text = (char *)nrarr_slice((nrarr_t)a.text, begin, end); return a; }
    (void)begin; (void)end; NVM2C_ABORT();
}
static int64_t nl_main(void);

static int64_t nl_main(void) {
    (void)ni64_from_bits;
    nrec_t *rl = calloc(2, sizeof *rl);
    if (!rl) NVM2C_ABORT();
    narr_t l0 = {0};
    (void)l0;
    narr_t l1 = {0};
    (void)l1;
    narr_t l2 = {0};
    (void)l2;
    int64_t l3 = 0;
    (void)l3;
    int64_t l4 = 0;
    (void)l4;
    int64_t l5 = 0;
    (void)l5;
    narr_t l6 = {0};
    (void)l6;
    int64_t l7 = 0;
    (void)l7;
    int64_t l8 = 0;
    (void)l8;
    narr_t l9 = {0};
    (void)l9;
    narr_t l10 = {0};
    (void)l10;
    int64_t l11 = 0;
    (void)l11;
    int64_t l12 = 0;
    (void)l12;
    nmap_value l13 = {0};
    (void)l13;
    narr_t l14 = {0};
    (void)l14;
    narr_t l15 = {0};
    (void)l15;
    int64_t l16 = 0;
    (void)l16;
    int64_t l17 = 0;
    (void)l17;
    int64_t l18 = 0;
    (void)l18;
    narr_t l19 = {0};
    (void)l19;
    int64_t l20 = 0;
    (void)l20;
    int64_t l21 = 0;
    (void)l21;
    int64_t l22 = 0;
    (void)l22;
    narr_t l23 = {0};
    (void)l23;
    int64_t l24 = 0;
    (void)l24;
    int64_t l25 = 0;
    (void)l25;
    int64_t l26 = 0;
    (void)l26;
    narr_t l27 = {0};
    (void)l27;
    narr_t l28 = {0};
    (void)l28;
    int64_t l29 = 0;
    (void)l29;
    int64_t l30 = 0;
    (void)l30;
    int64_t l31 = 0;
    (void)l31;
    narr_t l32 = {0};
    (void)l32;
    narr_t l33 = {0};
    (void)l33;
    int64_t l34 = 0;
    (void)l34;
    int64_t l35 = 0;
    (void)l35;
    int64_t l36 = 0;
    (void)l36;
    narr_t l37 = {0};
    (void)l37;
    narr_t l38 = {0};
    (void)l38;
    int64_t l39 = 0;
    (void)l39;
    int64_t l40 = 0;
    (void)l40;
    int64_t l41 = 0;
    (void)l41;
    nsarr_t l42 = {0};
    (void)l42;
    nsarr_t l43 = {0};
    (void)l43;
    int64_t l44 = 0;
    (void)l44;
    int64_t l45 = 0;
    (void)l45;
    int64_t l46 = 0;
    (void)l46;
    narr_t l47 = {0};
    (void)l47;
    narr_t l48 = {0};
    (void)l48;
    int64_t l49 = 0;
    (void)l49;
    int64_t l50 = 0;
    (void)l50;
    int64_t l51 = 0;
    (void)l51;
    narr_t l52 = {0};
    (void)l52;
    nmap_value l53 = {0};
    (void)l53;
    nrarr_t l54 = {0};
    (void)l54;
    nrarr_t l55 = {0};
    (void)l55;
    int64_t l56 = 0;
    (void)l56;
    int64_t l57 = 0;
    (void)l57;
    int64_t l58 = 0;
    (void)l58;
    nrarr_t l59 = {0};
    (void)l59;
    int64_t t[358] = {0}; (void)t;
    double f[5] = {0}; (void)f;
    const char *s[2] = {0}; (void)s;
    narr_t a[65] = {0}; (void)a;
    nsarr_t sa[5] = {0}; (void)sa;
    nrec_t *r = 8 ? calloc(8, sizeof *r) : NULL;
    if (8 && !r) NVM2C_ABORT();
    nrarr_t ra[10] = {0}; (void)ra;
    nmap_t m[1] = {0}; (void)m;
    int64_t nresult = {0};
    nmap_value v[21] = {0}; (void)v;
    nroot_frame nroots = {0}; nroots.prev = nroot_head; nroot_head = &nroots;
    if (0) goto L_return;
    t[0] = (-9223372036854775807LL - 1LL);
    t[1] = 9221120237041090561LL;
    t[2] = 9218868437227405313LL;
    t[3] = 1LL;
    a[0] = 0;
    a[0] = narr_lit((int64_t[]){t[0], t[1], t[2], t[3]}, 4);
    l0 = a[0];
    a[1] = l0;
    t[4] = 0LL;
    v[0] = nvalue_array_get((nmap_value){7, 3, (char *)a[1]}, t[4]);
    t[5] = nvalue_require_int(v[0]);
    f[0] = nl_float_from_bits(t[5]);
    a[2] = l0;
    t[6] = 1LL;
    v[1] = nvalue_array_get((nmap_value){7, 3, (char *)a[2]}, t[6]);
    t[7] = nvalue_require_int(v[1]);
    f[1] = nl_float_from_bits(t[7]);
    a[3] = l0;
    t[8] = 2LL;
    v[2] = nvalue_array_get((nmap_value){7, 3, (char *)a[3]}, t[8]);
    t[9] = nvalue_require_int(v[2]);
    f[2] = nl_float_from_bits(t[9]);
    a[4] = l0;
    t[10] = 3LL;
    v[3] = nvalue_array_get((nmap_value){7, 3, (char *)a[4]}, t[10]);
    t[11] = nvalue_require_int(v[3]);
    f[3] = nl_float_from_bits(t[11]);
    a[5] = 0;
    a[5] = narr_lit((int64_t[]){nvalue_from_float(f[0]).integer, nvalue_from_float(f[1]).integer, nvalue_from_float(f[2]).integer, nvalue_from_float(f[3]).integer}, 4);
    l1 = a[5];
    a[6] = l1;
    l2 = a[6];
    t[12] = 0LL;
    l3 = t[12];
    t[13] = 4LL;
    l4 = t[13];
    a[7] = l2;
    t[14] = (int64_t)(a[7] ? a[7]->len : 0);
    l5 = t[14];
    t[15] = l3;
    t[16] = 0LL;
    t[17] = (t[15] < t[16]);
    if (!t[17]) {
    goto L_173;
    }
    t[18] = 0LL;
    l3 = t[18];
    {
    }
L_173: ;
    t[19] = l3;
    t[20] = l5;
    t[21] = (t[19] > t[20]);
    if (!t[21]) {
    goto L_191;
    }
    t[22] = l5;
    l3 = t[22];
    {
    }
L_191: ;
    t[23] = l5;
    t[24] = l3;
    t[25] = ni64_from_bits((uint64_t)t[23] - (uint64_t)t[24]);
    l5 = t[25];
    t[26] = l4;
    t[27] = 0LL;
    t[28] = (t[26] < t[27]);
    if (!t[28]) {
    goto L_231;
    }
    t[29] = 0LL;
    l4 = t[29];
    {
    }
L_231: ;
    t[30] = l4;
    t[31] = l5;
    t[32] = (t[30] > t[31]);
    if (!t[32]) {
    goto L_249;
    }
    t[33] = l5;
    l4 = t[33];
    {
    }
L_249: ;
    a[8] = l2;
    t[34] = l3;
    t[35] = l3;
    t[36] = l4;
    t[37] = ni64_from_bits((uint64_t)t[35] + (uint64_t)t[36]);
    a[9] = narr_slice(a[8], t[34], t[37]);
    l6 = a[9];
    t[38] = 0LL;
    t[39] = 4LL;
    l7 = t[39];
    l8 = t[38];
    a[10] = narr_new();
    l9 = a[10];
L_295: ;
    t[40] = l8;
    t[41] = l7;
    t[42] = (nvalue_compare((nmap_value){1, t[40], NULL}, (nmap_value){1, t[41], NULL}) < 0);
    if (!t[42]) {
    goto L_338;
    }
    a[11] = l9;
    t[43] = l8;
    a[12] = narr_push(a[11], t[43]);
    l9 = a[12];
    t[44] = l8;
    t[45] = 1LL;
    t[46] = ni64_from_bits((uint64_t)t[44] + (uint64_t)t[45]);
    l8 = t[46];
    nroot_reset(&nroots.live);
    nroot_add(&nroots.live, 3, l0);
    nroot_add(&nroots.live, 12, l1);
    nroot_add(&nroots.live, 12, l2);
    nroot_add(&nroots.live, 12, l6);
    nroot_add(&nroots.live, 3, l9);
    nroot_add(&nroots.live, 3, l10);
    nroot_add(&nroots.live, 8, &l13);
    nroot_add(&nroots.live, 3, l14);
    nroot_add(&nroots.live, 3, l15);
    nroot_add(&nroots.live, 3, l19);
    nroot_add(&nroots.live, 3, l23);
    nroot_add(&nroots.live, 3, l27);
    nroot_add(&nroots.live, 3, l28);
    nroot_add(&nroots.live, 15, l32);
    nroot_add(&nroots.live, 15, l33);
    nroot_add(&nroots.live, 10, l37);
    nroot_add(&nroots.live, 10, l38);
    nroot_add(&nroots.live, 5, l42);
    nroot_add(&nroots.live, 5, l43);
    nroot_add(&nroots.live, 16, l47);
    nroot_add(&nroots.live, 16, l48);
    nroot_add(&nroots.live, 16, l52);
    nroot_add(&nroots.live, 8, &l53);
    nroot_add(&nroots.live, 6, l54);
    nroot_add(&nroots.live, 6, l55);
    nroot_add(&nroots.live, 6, l59);
    nroot_add(&nroots.live, 4, &rl[0]);
    nroot_add(&nroots.live, 4, &rl[1]);
    nmap_collect_if_needed();
    {
    }
    goto L_295;
L_338: ;
    a[13] = l9;
    l10 = a[13];
    t[47] = 0LL;
    l11 = t[47];
    a[14] = l10;
    t[48] = (int64_t)(a[14] ? a[14]->len : 0);
    l12 = t[48];
L_363: ;
    t[49] = l11;
    t[50] = l12;
    t[51] = (nvalue_compare((nmap_value){1, t[49], NULL}, (nmap_value){1, t[50], NULL}) < 0);
    if (!t[51]) {
    goto L_423;
    }
    a[15] = l10;
    t[52] = l11;
    v[4] = nvalue_array_get((nmap_value){7, 3, (char *)a[15]}, t[52]);
    l13 = v[4];
    a[16] = l6;
    v[5] = l13;
    t[53] = nvalue_require_int(v[5]);
    v[6] = nvalue_array_get((nmap_value){7, 12, (char *)a[16]}, t[53]);
    f[4] = nvalue_require_float(v[6]);
    t[54] = nl_float_to_bits(f[4]);
    a[17] = l0;
    v[7] = l13;
    t[55] = nvalue_require_int(v[7]);
    v[8] = nvalue_array_get((nmap_value){7, 3, (char *)a[17]}, t[55]);
    if (v[8].kind != 1 && v[8].kind != 9) NVM2C_ABORT();
    t[56] = v[8].integer;
    t[57] = (t[54] == t[56]);
    if (!t[57]) NVM2C_ABORT();
    t[58] = l11;
    t[59] = 1LL;
    t[60] = ni64_from_bits((uint64_t)t[58] + (uint64_t)t[59]);
    l11 = t[60];
    nroot_reset(&nroots.live);
    nroot_add(&nroots.live, 3, l0);
    nroot_add(&nroots.live, 12, l1);
    nroot_add(&nroots.live, 12, l2);
    nroot_add(&nroots.live, 12, l6);
    nroot_add(&nroots.live, 3, l9);
    nroot_add(&nroots.live, 3, l10);
    nroot_add(&nroots.live, 8, &l13);
    nroot_add(&nroots.live, 3, l14);
    nroot_add(&nroots.live, 3, l15);
    nroot_add(&nroots.live, 3, l19);
    nroot_add(&nroots.live, 3, l23);
    nroot_add(&nroots.live, 3, l27);
    nroot_add(&nroots.live, 3, l28);
    nroot_add(&nroots.live, 15, l32);
    nroot_add(&nroots.live, 15, l33);
    nroot_add(&nroots.live, 10, l37);
    nroot_add(&nroots.live, 10, l38);
    nroot_add(&nroots.live, 5, l42);
    nroot_add(&nroots.live, 5, l43);
    nroot_add(&nroots.live, 16, l47);
    nroot_add(&nroots.live, 16, l48);
    nroot_add(&nroots.live, 16, l52);
    nroot_add(&nroots.live, 8, &l53);
    nroot_add(&nroots.live, 6, l54);
    nroot_add(&nroots.live, 6, l55);
    nroot_add(&nroots.live, 6, l59);
    nroot_add(&nroots.live, 4, &rl[0]);
    nroot_add(&nroots.live, 4, &rl[1]);
    nmap_collect_if_needed();
    {
    }
    goto L_363;
L_423: ;
    t[61] = 10LL;
    t[62] = 11LL;
    t[63] = 12LL;
    t[64] = 13LL;
    a[18] = 0;
    a[18] = narr_lit((int64_t[]){t[61], t[62], t[63], t[64]}, 4);
    l14 = a[18];
    a[19] = l14;
    l15 = a[19];
    t[65] = (-9223372036854775807LL - 1LL);
    l16 = t[65];
    t[66] = (-9223372036854775807LL - 1LL);
    l17 = t[66];
    a[20] = l15;
    t[67] = (int64_t)(a[20] ? a[20]->len : 0);
    l18 = t[67];
    t[68] = l16;
    t[69] = 0LL;
    t[70] = (t[68] < t[69]);
    if (!t[70]) {
    goto L_533;
    }
    t[71] = 0LL;
    l16 = t[71];
    {
    }
L_533: ;
    t[72] = l16;
    t[73] = l18;
    t[74] = (t[72] > t[73]);
    if (!t[74]) {
    goto L_551;
    }
    t[75] = l18;
    l16 = t[75];
    {
    }
L_551: ;
    t[76] = l18;
    t[77] = l16;
    t[78] = ni64_from_bits((uint64_t)t[76] - (uint64_t)t[77]);
    l18 = t[78];
    t[79] = l17;
    t[80] = 0LL;
    t[81] = (t[79] < t[80]);
    if (!t[81]) {
    goto L_591;
    }
    t[82] = 0LL;
    l17 = t[82];
    {
    }
L_591: ;
    t[83] = l17;
    t[84] = l18;
    t[85] = (t[83] > t[84]);
    if (!t[85]) {
    goto L_609;
    }
    t[86] = l18;
    l17 = t[86];
    {
    }
L_609: ;
    a[21] = l15;
    t[87] = l16;
    t[88] = l16;
    t[89] = l17;
    t[90] = ni64_from_bits((uint64_t)t[88] + (uint64_t)t[89]);
    a[22] = narr_slice(a[21], t[87], t[90]);
    t[91] = (int64_t)(a[22] ? a[22]->len : 0);
    t[92] = 0LL;
    t[93] = (t[91] == t[92]);
    if (!t[93]) NVM2C_ABORT();
    a[23] = l14;
    l19 = a[23];
    t[94] = (-9223372036854775807LL - 1LL);
    l20 = t[94];
    t[95] = 9223372036854775807LL;
    l21 = t[95];
    a[24] = l19;
    t[96] = (int64_t)(a[24] ? a[24]->len : 0);
    l22 = t[96];
    t[97] = l20;
    t[98] = 0LL;
    t[99] = (t[97] < t[98]);
    if (!t[99]) {
    goto L_702;
    }
    t[100] = 0LL;
    l20 = t[100];
    {
    }
L_702: ;
    t[101] = l20;
    t[102] = l22;
    t[103] = (t[101] > t[102]);
    if (!t[103]) {
    goto L_720;
    }
    t[104] = l22;
    l20 = t[104];
    {
    }
L_720: ;
    t[105] = l22;
    t[106] = l20;
    t[107] = ni64_from_bits((uint64_t)t[105] - (uint64_t)t[106]);
    l22 = t[107];
    t[108] = l21;
    t[109] = 0LL;
    t[110] = (t[108] < t[109]);
    if (!t[110]) {
    goto L_760;
    }
    t[111] = 0LL;
    l21 = t[111];
    {
    }
L_760: ;
    t[112] = l21;
    t[113] = l22;
    t[114] = (t[112] > t[113]);
    if (!t[114]) {
    goto L_778;
    }
    t[115] = l22;
    l21 = t[115];
    {
    }
L_778: ;
    a[25] = l19;
    t[116] = l20;
    t[117] = l20;
    t[118] = l21;
    t[119] = ni64_from_bits((uint64_t)t[117] + (uint64_t)t[118]);
    a[26] = narr_slice(a[25], t[116], t[119]);
    t[120] = (int64_t)(a[26] ? a[26]->len : 0);
    t[121] = 4LL;
    t[122] = (t[120] == t[121]);
    if (!t[122]) NVM2C_ABORT();
    a[27] = l14;
    l23 = a[27];
    t[123] = 1LL;
    l24 = t[123];
    t[124] = 9223372036854775807LL;
    l25 = t[124];
    a[28] = l23;
    t[125] = (int64_t)(a[28] ? a[28]->len : 0);
    l26 = t[125];
    t[126] = l24;
    t[127] = 0LL;
    t[128] = (t[126] < t[127]);
    if (!t[128]) {
    goto L_871;
    }
    t[129] = 0LL;
    l24 = t[129];
    {
    }
L_871: ;
    t[130] = l24;
    t[131] = l26;
    t[132] = (t[130] > t[131]);
    if (!t[132]) {
    goto L_889;
    }
    t[133] = l26;
    l24 = t[133];
    {
    }
L_889: ;
    t[134] = l26;
    t[135] = l24;
    t[136] = ni64_from_bits((uint64_t)t[134] - (uint64_t)t[135]);
    l26 = t[136];
    t[137] = l25;
    t[138] = 0LL;
    t[139] = (t[137] < t[138]);
    if (!t[139]) {
    goto L_929;
    }
    t[140] = 0LL;
    l25 = t[140];
    {
    }
L_929: ;
    t[141] = l25;
    t[142] = l26;
    t[143] = (t[141] > t[142]);
    if (!t[143]) {
    goto L_947;
    }
    t[144] = l26;
    l25 = t[144];
    {
    }
L_947: ;
    a[29] = l23;
    t[145] = l24;
    t[146] = l24;
    t[147] = l25;
    t[148] = ni64_from_bits((uint64_t)t[146] + (uint64_t)t[147]);
    a[30] = narr_slice(a[29], t[145], t[148]);
    l27 = a[30];
    a[31] = l27;
    a[32] = l14;
    t[149] = !nvalue_equal((nmap_value){7, 3, (char *)a[31]}, (nmap_value){7, 3, (char *)a[32]});
    if (!t[149]) NVM2C_ABORT();
    a[33] = l27;
    t[150] = (int64_t)(a[33] ? a[33]->len : 0);
    t[151] = 3LL;
    t[152] = (t[150] == t[151]);
    if (!t[152]) NVM2C_ABORT();
    a[34] = l27;
    t[153] = 0LL;
    v[9] = nvalue_array_get((nmap_value){7, 3, (char *)a[34]}, t[153]);
    t[154] = 11LL;
    if (v[9].kind != 1 && v[9].kind != 9) NVM2C_ABORT();
    t[155] = v[9].integer;
    t[156] = (t[155] == t[154]);
    if (!t[156]) NVM2C_ABORT();
    a[35] = l27;
    t[157] = 0LL;
    t[158] = 99LL;
    if (!a[35] || t[157] < 0 || (uint64_t)t[157] >= a[35]->len) NVM2C_ABORT();
    a[35]->data[t[157]] = t[158];
    a[36] = l14;
    t[159] = 1LL;
    v[10] = nvalue_array_get((nmap_value){7, 3, (char *)a[36]}, t[159]);
    t[160] = 11LL;
    if (v[10].kind != 1 && v[10].kind != 9) NVM2C_ABORT();
    t[161] = v[10].integer;
    t[162] = (t[161] == t[160]);
    if (!t[162]) NVM2C_ABORT();
    a[37] = l14;
    l28 = a[37];
    t[163] = 9223372036854775807LL;
    l29 = t[163];
    t[164] = 9223372036854775807LL;
    l30 = t[164];
    a[38] = l28;
    t[165] = (int64_t)(a[38] ? a[38]->len : 0);
    l31 = t[165];
    t[166] = l29;
    t[167] = 0LL;
    t[168] = (t[166] < t[167]);
    if (!t[168]) {
    goto L_1125;
    }
    t[169] = 0LL;
    l29 = t[169];
    {
    }
L_1125: ;
    t[170] = l29;
    t[171] = l31;
    t[172] = (t[170] > t[171]);
    if (!t[172]) {
    goto L_1143;
    }
    t[173] = l31;
    l29 = t[173];
    {
    }
L_1143: ;
    t[174] = l31;
    t[175] = l29;
    t[176] = ni64_from_bits((uint64_t)t[174] - (uint64_t)t[175]);
    l31 = t[176];
    t[177] = l30;
    t[178] = 0LL;
    t[179] = (t[177] < t[178]);
    if (!t[179]) {
    goto L_1183;
    }
    t[180] = 0LL;
    l30 = t[180];
    {
    }
L_1183: ;
    t[181] = l30;
    t[182] = l31;
    t[183] = (t[181] > t[182]);
    if (!t[183]) {
    goto L_1201;
    }
    t[184] = l31;
    l30 = t[184];
    {
    }
L_1201: ;
    a[39] = l28;
    t[185] = l29;
    t[186] = l29;
    t[187] = l30;
    t[188] = ni64_from_bits((uint64_t)t[186] + (uint64_t)t[187]);
    a[40] = narr_slice(a[39], t[185], t[188]);
    t[189] = (int64_t)(a[40] ? a[40]->len : 0);
    t[190] = 0LL;
    t[191] = (t[189] == t[190]);
    if (!t[191]) NVM2C_ABORT();
    t[192] = 255LL;
    v[11] = (nmap_value){1, t[192], NULL};
    a[41] = 0;
    a[41] = narr_lit((int64_t[]){nvalue_require_byte(v[11])}, 1);
    l32 = a[41];
    a[42] = l32;
    l33 = a[42];
    t[193] = 0LL;
    l34 = t[193];
    t[194] = 1LL;
    l35 = t[194];
    a[43] = l33;
    t[195] = (int64_t)(a[43] ? a[43]->len : 0);
    l36 = t[195];
    t[196] = l34;
    t[197] = 0LL;
    t[198] = (t[196] < t[197]);
    if (!t[198]) {
    goto L_1310;
    }
    t[199] = 0LL;
    l34 = t[199];
    {
    }
L_1310: ;
    t[200] = l34;
    t[201] = l36;
    t[202] = (t[200] > t[201]);
    if (!t[202]) {
    goto L_1328;
    }
    t[203] = l36;
    l34 = t[203];
    {
    }
L_1328: ;
    t[204] = l36;
    t[205] = l34;
    t[206] = ni64_from_bits((uint64_t)t[204] - (uint64_t)t[205]);
    l36 = t[206];
    t[207] = l35;
    t[208] = 0LL;
    t[209] = (t[207] < t[208]);
    if (!t[209]) {
    goto L_1368;
    }
    t[210] = 0LL;
    l35 = t[210];
    {
    }
L_1368: ;
    t[211] = l35;
    t[212] = l36;
    t[213] = (t[211] > t[212]);
    if (!t[213]) {
    goto L_1386;
    }
    t[214] = l36;
    l35 = t[214];
    {
    }
L_1386: ;
    a[44] = l33;
    t[215] = l34;
    t[216] = l34;
    t[217] = l35;
    t[218] = ni64_from_bits((uint64_t)t[216] + (uint64_t)t[217]);
    a[45] = narr_slice(a[44], t[215], t[218]);
    t[219] = 0LL;
    v[12] = nvalue_array_get((nmap_value){7, 15, (char *)a[45]}, t[219]);
    t[220] = nvalue_cast_int(v[12]);
    t[221] = 255LL;
    t[222] = (t[220] == t[221]);
    if (!t[222]) NVM2C_ABORT();
    t[223] = 1LL;
    a[46] = 0;
    a[46] = narr_lit((int64_t[]){t[223]}, 1);
    l37 = a[46];
    a[47] = l37;
    l38 = a[47];
    t[224] = 0LL;
    l39 = t[224];
    t[225] = 1LL;
    l40 = t[225];
    a[48] = l38;
    t[226] = (int64_t)(a[48] ? a[48]->len : 0);
    l41 = t[226];
    t[227] = l39;
    t[228] = 0LL;
    t[229] = (t[227] < t[228]);
    if (!t[229]) {
    goto L_1498;
    }
    t[230] = 0LL;
    l39 = t[230];
    {
    }
L_1498: ;
    t[231] = l39;
    t[232] = l41;
    t[233] = (t[231] > t[232]);
    if (!t[233]) {
    goto L_1516;
    }
    t[234] = l41;
    l39 = t[234];
    {
    }
L_1516: ;
    t[235] = l41;
    t[236] = l39;
    t[237] = ni64_from_bits((uint64_t)t[235] - (uint64_t)t[236]);
    l41 = t[237];
    t[238] = l40;
    t[239] = 0LL;
    t[240] = (t[238] < t[239]);
    if (!t[240]) {
    goto L_1556;
    }
    t[241] = 0LL;
    l40 = t[241];
    {
    }
L_1556: ;
    t[242] = l40;
    t[243] = l41;
    t[244] = (t[242] > t[243]);
    if (!t[244]) {
    goto L_1574;
    }
    t[245] = l41;
    l40 = t[245];
    {
    }
L_1574: ;
    a[49] = l38;
    t[246] = l39;
    t[247] = l39;
    t[248] = l40;
    t[249] = ni64_from_bits((uint64_t)t[247] + (uint64_t)t[248]);
    a[50] = narr_slice(a[49], t[246], t[249]);
    t[250] = 0LL;
    v[13] = nvalue_array_get((nmap_value){7, 10, (char *)a[50]}, t[250]);
    t[251] = ((v[13].kind == 3 && nvalue_require_float(v[13]) != 0.0) || v[13].kind == 5 || v[13].kind == 7 || v[13].kind == 13 || ((v[13].kind == 1 || v[13].kind == 2 || v[13].kind == 4 || v[13].kind == 9) && v[13].integer != 0));
    if (!t[251]) NVM2C_ABORT();
    s[0] = "retained";
    sa[0] = 0;
    sa[0] = nsarr_lit((const char *[]){s[0]}, 1);
    l42 = sa[0];
    sa[1] = l42;
    l43 = sa[1];
    t[252] = 0LL;
    l44 = t[252];
    t[253] = 1LL;
    l45 = t[253];
    sa[2] = l43;
    t[254] = (int64_t)(sa[2] ? sa[2]->len : 0);
    l46 = t[254];
    t[255] = l44;
    t[256] = 0LL;
    t[257] = (t[255] < t[256]);
    if (!t[257]) {
    goto L_1678;
    }
    t[258] = 0LL;
    l44 = t[258];
    {
    }
L_1678: ;
    t[259] = l44;
    t[260] = l46;
    t[261] = (t[259] > t[260]);
    if (!t[261]) {
    goto L_1696;
    }
    t[262] = l46;
    l44 = t[262];
    {
    }
L_1696: ;
    t[263] = l46;
    t[264] = l44;
    t[265] = ni64_from_bits((uint64_t)t[263] - (uint64_t)t[264]);
    l46 = t[265];
    t[266] = l45;
    t[267] = 0LL;
    t[268] = (t[266] < t[267]);
    if (!t[268]) {
    goto L_1736;
    }
    t[269] = 0LL;
    l45 = t[269];
    {
    }
L_1736: ;
    t[270] = l45;
    t[271] = l46;
    t[272] = (t[270] > t[271]);
    if (!t[272]) {
    goto L_1754;
    }
    t[273] = l46;
    l45 = t[273];
    {
    }
L_1754: ;
    sa[3] = l43;
    t[274] = l44;
    t[275] = l44;
    t[276] = l45;
    t[277] = ni64_from_bits((uint64_t)t[275] + (uint64_t)t[276]);
    sa[4] = nsarr_slice(sa[3], t[274], t[277]);
    t[278] = 0LL;
    v[14] = nvalue_array_get((nmap_value){7, 5, (char *)sa[4]}, t[278]);
    s[1] = "retained";
    t[279] = nvalue_equal(v[14], (nmap_value){5, 0, (char *)s[1]});
    if (!t[279]) NVM2C_ABORT();
    a[51] = l14;
    v[15] = (nmap_value){7, 3, (char *)a[51]};
    a[52] = narr_new();
    narr_reserve(a[52], 1); a[52]->len = 1;
    nchild_array_set(a[52], 0, v[15]);
    l47 = a[52];
    a[53] = l47;
    l48 = a[53];
    t[280] = 0LL;
    l49 = t[280];
    t[281] = 1LL;
    l50 = t[281];
    a[54] = l48;
    t[282] = (int64_t)(a[54] ? a[54]->len : 0);
    l51 = t[282];
    t[283] = l49;
    t[284] = 0LL;
    t[285] = (t[283] < t[284]);
    if (!t[285]) {
    goto L_1862;
    }
    t[286] = 0LL;
    l49 = t[286];
    {
    }
L_1862: ;
    t[287] = l49;
    t[288] = l51;
    t[289] = (t[287] > t[288]);
    if (!t[289]) {
    goto L_1880;
    }
    t[290] = l51;
    l49 = t[290];
    {
    }
L_1880: ;
    t[291] = l51;
    t[292] = l49;
    t[293] = ni64_from_bits((uint64_t)t[291] - (uint64_t)t[292]);
    l51 = t[293];
    t[294] = l50;
    t[295] = 0LL;
    t[296] = (t[294] < t[295]);
    if (!t[296]) {
    goto L_1920;
    }
    t[297] = 0LL;
    l50 = t[297];
    {
    }
L_1920: ;
    t[298] = l50;
    t[299] = l51;
    t[300] = (t[298] > t[299]);
    if (!t[300]) {
    goto L_1938;
    }
    t[301] = l51;
    l50 = t[301];
    {
    }
L_1938: ;
    a[55] = l48;
    t[302] = l49;
    t[303] = l49;
    t[304] = l50;
    t[305] = ni64_from_bits((uint64_t)t[303] + (uint64_t)t[304]);
    a[56] = narr_slice(a[55], t[302], t[305]);
    l52 = a[56];
    a[57] = l52;
    t[306] = 0LL;
    v[16] = nvalue_array_get((nmap_value){7, 16, (char *)a[57]}, t[306]);
    l53 = v[16];
    v[17] = l53;
    a[58] = l14;
    t[307] = nvalue_equal(v[17], (nmap_value){7, 3, (char *)a[58]});
    if (!t[307]) NVM2C_ABORT();
    t[308] = 42LL;
    a[59] = l14;
    r[0].n = 2;
    r[0].kind = 0; r[0].tag = 0;
    r[0].k[0] = 0;
    r[0].f[0] = t[308];
    r[0].k[1] = 3;
    r[0].a[1] = a[59];
    ra[0] = nrarr_new();
    ra[0] = nrarr_push(ra[0], r[0]);
    l54 = ra[0];
    ra[1] = l54;
    l55 = ra[1];
    t[309] = 0LL;
    l56 = t[309];
    t[310] = 1LL;
    l57 = t[310];
    ra[2] = l55;
    t[311] = (int64_t)(ra[2] ? ra[2]->len : 0);
    l58 = t[311];
    t[312] = l56;
    t[313] = 0LL;
    t[314] = (t[312] < t[313]);
    if (!t[314]) {
    goto L_2075;
    }
    t[315] = 0LL;
    l56 = t[315];
    {
    }
L_2075: ;
    t[316] = l56;
    t[317] = l58;
    t[318] = (t[316] > t[317]);
    if (!t[318]) {
    goto L_2093;
    }
    t[319] = l58;
    l56 = t[319];
    {
    }
L_2093: ;
    t[320] = l58;
    t[321] = l56;
    t[322] = ni64_from_bits((uint64_t)t[320] - (uint64_t)t[321]);
    l58 = t[322];
    t[323] = l57;
    t[324] = 0LL;
    t[325] = (t[323] < t[324]);
    if (!t[325]) {
    goto L_2133;
    }
    t[326] = 0LL;
    l57 = t[326];
    {
    }
L_2133: ;
    t[327] = l57;
    t[328] = l58;
    t[329] = (t[327] > t[328]);
    if (!t[329]) {
    goto L_2151;
    }
    t[330] = l58;
    l57 = t[330];
    {
    }
L_2151: ;
    ra[3] = l55;
    t[331] = l56;
    t[332] = l56;
    t[333] = l57;
    t[334] = ni64_from_bits((uint64_t)t[332] + (uint64_t)t[333]);
    ra[4] = nrarr_slice(ra[3], t[331], t[334]);
    l59 = ra[4];
    ra[5] = l59;
    ra[6] = l54;
    t[335] = !nvalue_equal((nmap_value){7, 6, (char *)ra[5]}, (nmap_value){7, 6, (char *)ra[6]});
    if (!t[335]) NVM2C_ABORT();
    ra[7] = l59;
    t[336] = 0LL;
    r[1] = nrarr_get(ra[7], t[336]);
    rl[0] = r[1];
    a[60] = l14;
    t[337] = 0LL;
    t[338] = 99LL;
    if (!a[60] || t[337] < 0 || (uint64_t)t[337] >= a[60]->len) NVM2C_ABORT();
    a[60]->data[t[337]] = t[338];
    r[2] = rl[0];
    if (1 >= r[2].n) NVM2C_ABORT();
    if (r[2].k[1] != 3) NVM2C_ABORT();
    a[61] = r[2].a[1];
    t[339] = 0LL;
    v[18] = nvalue_array_get((nmap_value){7, 3, (char *)a[61]}, t[339]);
    t[340] = 99LL;
    if (v[18].kind != 1 && v[18].kind != 9) NVM2C_ABORT();
    t[341] = v[18].integer;
    t[342] = (t[341] == t[340]);
    if (!t[342]) NVM2C_ABORT();
    r[3] = rl[0];
    if (1 >= r[3].n) NVM2C_ABORT();
    if (r[3].k[1] != 3) NVM2C_ABORT();
    a[62] = r[3].a[1];
    a[63] = l14;
    t[343] = nvalue_equal((nmap_value){7, 3, (char *)a[62]}, (nmap_value){7, 3, (char *)a[63]});
    if (!t[343]) NVM2C_ABORT();
    v[19] = l53;
    t[344] = 0LL;
    v[20] = nvalue_array_get(v[19], t[344]);
    t[345] = 99LL;
    if (v[20].kind != 1 && v[20].kind != 9) NVM2C_ABORT();
    t[346] = v[20].integer;
    t[347] = (t[346] == t[345]);
    if (!t[347]) NVM2C_ABORT();
    ra[8] = l59;
    t[348] = 0LL;
    t[349] = 7LL;
    a[64] = l14;
    r[4].n = 2;
    r[4].kind = 0; r[4].tag = 0;
    r[4].k[0] = 0;
    r[4].f[0] = t[349];
    r[4].k[1] = 3;
    r[4].a[1] = a[64];
    if (!ra[8] || t[348] < 0 || (uint64_t)t[348] >= ra[8]->len) NVM2C_ABORT();
    if (!ra[8]->data) NVM2C_ABORT();
    if (ra[8]->data[t[348]].n != r[4].n || ra[8]->data[t[348]].kind != r[4].kind) NVM2C_ABORT();
    for (size_t f = 0; f < r[4].n; ++f) if (!nrec_field_storage_matches(&ra[8]->data[t[348]], &r[4], f)) NVM2C_ABORT();
    ra[8]->data[t[348]] = r[4];
    ra[9] = l54;
    t[350] = 0LL;
    r[5] = nrarr_get(ra[9], t[350]);
    rl[1] = r[5];
    r[6] = rl[1];
    if (0 >= r[6].n) NVM2C_ABORT();
    if (r[6].k[0] != 0 && !(r[6].k[0] == 8 && r[6].vk[0] == 1)) NVM2C_ABORT();
    t[351] = r[6].f[0];
    t[352] = 42LL;
    t[353] = (t[351] == t[352]);
    if (!t[353]) NVM2C_ABORT();
    r[7] = rl[0];
    if (0 >= r[7].n) NVM2C_ABORT();
    if (r[7].k[0] != 0 && !(r[7].k[0] == 8 && r[7].vk[0] == 1)) NVM2C_ABORT();
    t[354] = r[7].f[0];
    t[355] = 42LL;
    t[356] = (t[354] == t[355]);
    if (!t[356]) NVM2C_ABORT();
    t[357] = 0LL;
    nresult = t[357];
    goto L_return;
L_return:
    nroot_head = nroots.prev; nroot_destroy(&nroots.live);
    free(r);
    free(rl);
    return nresult;
}

int main(void) {
    (void)nf64_to_i64;
    (void)nvalue_array_slice;
    (void)nvalue_require_record;
    (void)nparse_binary64;
    (void)nano_rt_f64_add; (void)nano_rt_f64_sub; (void)nano_rt_f64_mul; (void)nano_rt_f64_div;
    (void)nl_float_from_bits; (void)nl_float_to_bits;
    (void)nrec_f64;
    (void)nl_main;
    (void)nmap_owned_new; (void)nmap_set; (void)nmap_get; (void)nmap_owned_get;
    (void)nvalue_numeric; (void)nvalue_from_float; (void)nvalue_require_int; (void)nvalue_require_bool; (void)nvalue_require_function; (void)nvalue_require_string; (void)nvalue_require_map; (void)nvalue_cast_int; (void)nvalue_cast_u8; (void)nvalue_cast_float; (void)nvalue_equal; (void)nvalue_require_byte; (void)nvalue_require_opaque;
    (void)nvalue_compare;
    (void)nvalue_require_int_array; (void)nvalue_array_len; (void)nvalue_array_get; (void)nvalue_array_set; (void)nvalue_array_push;
    (void)nmap_has; (void)nmap_len; (void)nmap_delete; (void)nmap_collect;
    (void)nroot_reset; (void)nmap_collect_if_needed;
    (void)nagg_add; (void)nagg_drop;
    (void)nsarr_new; (void)nsarr_reserve; (void)nsarr_copy_string;
    (void)narr_new; (void)narr_reserve;
    (void)nrarr_new; (void)nrarr_reserve;
    (void)nrarr_get;
    (void)nsarr_push;
    (void)narr_push;
    (void)nrec_snapshot;
    (void)nrec_field_storage_matches;
    (void)nrarr_push;
    int result = (int)nl_main();
    nrec_release_snapshots();
    nmap_release_owned();
    nrarr_release_owned();
    nsarr_release_owned();
    narr_release_owned();
    return result;
}
