#!/usr/bin/env python3
"""
gen_ringbuf.py — Generate a typed ringbuf header from a YAML or JSON schema.

Usage:
    python3 tools/gen_ringbuf.py schema.yaml        # writes <name>_ringbuf.h
    python3 tools/gen_ringbuf.py schema.json -o out.h

Schema format (YAML example):
    name: ipc_msg          # ringbuf name prefix  → ipc_msg_t, ipc_msg_push …
    entry_type: ipc_msg_t  # C type stored in each slot
    capacity: 128          # must be power-of-2; default 64
    fields:                # optional: if present, the entry struct is emitted
      - name: src_pd
        type: uint32_t
      - name: dst_pd
        type: uint32_t
      - name: opcode
        type: uint16_t
      - name: payload
        type: uint8_t
        array: 56          # → uint8_t payload[56];

Equivalent JSON:
    {
      "name": "ipc_msg",
      "entry_type": "ipc_msg_t",
      "capacity": 128,
      "fields": [
        {"name": "src_pd", "type": "uint32_t"},
        {"name": "dst_pd", "type": "uint32_t"}
      ]
    }
"""

import argparse
import json
import sys
import os
from pathlib import Path


# ---------------------------------------------------------------------------
# Optional YAML support (stdlib only: json always available)
# ---------------------------------------------------------------------------

def _load_schema(path: str) -> dict:
    text = Path(path).read_text()
    if path.endswith((".yaml", ".yml")):
        try:
            import yaml  # type: ignore
            return yaml.safe_load(text)
        except ImportError:
            # Minimal hand-rolled YAML parser for simple key-value / list docs
            return _parse_simple_yaml(text)
    return json.loads(text)


def _parse_simple_yaml(text: str) -> dict:
    """
    Tiny YAML subset parser: handles top-level key: value and
    a single list of mappings under one key.  Good enough for the schema above.
    """
    result: dict = {}
    current_list_key: str | None = None
    current_item: dict | None = None

    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue

        stripped = line.lstrip()
        indent = len(line) - len(stripped)

        if indent == 0:
            if stripped.endswith(":"):
                # start of a list block
                key = stripped[:-1].strip()
                result[key] = []
                current_list_key = key
                current_item = None
            elif ":" in stripped:
                key, _, val = stripped.partition(":")
                result[key.strip()] = _coerce(val.strip())
                current_list_key = None
        elif indent == 2 and stripped.startswith("- "):
            if current_list_key is None:
                raise ValueError("Unexpected list item")
            if current_item is not None:
                result[current_list_key].append(current_item)
            rest = stripped[2:]
            current_item = {}
            if ":" in rest:
                k, _, v = rest.partition(":")
                current_item[k.strip()] = _coerce(v.strip())
        elif indent >= 4 and current_item is not None:
            if ":" in stripped:
                k, _, v = stripped.partition(":")
                current_item[k.strip()] = _coerce(v.strip())

    if current_item is not None and current_list_key is not None:
        result[current_list_key].append(current_item)

    return result


def _coerce(val: str):
    if val.isdigit():
        return int(val)
    if val.lower() in ("true", "yes"):
        return True
    if val.lower() in ("false", "no"):
        return False
    return val


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

_HEADER_TEMPLATE = """\
/*
 * {out_filename} — auto-generated typed ring buffer
 * Generated by tools/gen_ringbuf.py — DO NOT EDIT
 */

#ifndef {guard}
#define {guard}

#include <stdint.h>
#include "ringbuf.h"
{struct_block}
RINGBUF_DEFINE({name}, {entry_type}, {capacity})

#endif /* {guard} */
"""

_STRUCT_TEMPLATE = """\

typedef struct {{
{fields}}} {entry_type};
"""


def _is_pow2(n: int) -> bool:
    return n > 0 and (n & (n - 1)) == 0


def _render_fields(fields: list) -> str:
    lines = []
    for f in fields:
        fname = f["name"]
        ftype = f["type"]
        arr = f.get("array")
        if arr:
            lines.append(f"    {ftype} {fname}[{arr}];")
        else:
            lines.append(f"    {ftype} {fname};")
    return "\n".join(lines) + "\n"


def generate(schema: dict, out_path: str | None = None) -> str:
    name = schema.get("name")
    if not name:
        raise ValueError("Schema missing required 'name' field")

    entry_type = schema.get("entry_type", f"{name}_entry_t")
    capacity = int(schema.get("capacity", 64))
    fields = schema.get("fields")

    if not _is_pow2(capacity):
        raise ValueError(f"capacity {capacity} is not a power-of-2")

    if out_path is None:
        out_path = f"{name}_ringbuf.h"

    out_filename = os.path.basename(out_path)
    guard = out_filename.upper().replace(".", "_").replace("-", "_")

    struct_block = ""
    if fields:
        struct_block = _STRUCT_TEMPLATE.format(
            fields=_render_fields(fields),
            entry_type=entry_type,
        )

    code = _HEADER_TEMPLATE.format(
        out_filename=out_filename,
        guard=guard,
        name=name,
        entry_type=entry_type,
        capacity=capacity,
        struct_block=struct_block,
    )
    return code


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a typed ringbuf header from a YAML/JSON schema"
    )
    parser.add_argument("schema", help="Path to schema (.yaml/.yml/.json)")
    parser.add_argument(
        "-o", "--output",
        default=None,
        help="Output header path (default: <name>_ringbuf.h in current dir)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print to stdout instead of writing a file",
    )
    args = parser.parse_args()

    schema = _load_schema(args.schema)
    code = generate(schema, args.output)

    if args.stdout:
        sys.stdout.write(code)
    else:
        out = args.output or f"{schema['name']}_ringbuf.h"
        Path(out).write_text(code)
        print(f"Written: {out}")


if __name__ == "__main__":
    main()
