#!/usr/bin/env python3
"""
Generate modules/index.json from all module.manifest.json files.

This creates a searchable index of all modules with their capabilities,
keywords, and metadata for LLM agent discovery.
"""

import json
import os
from pathlib import Path
from typing import List, Dict, Any

def find_manifests(modules_dir: Path) -> List[Path]:
    """Find all module.manifest.json files in modules/"""
    manifests = []
    for root, dirs, files in os.walk(modules_dir):
        if 'module.manifest.json' in files:
            manifests.append(Path(root) / 'module.manifest.json')
    return sorted(manifests)

def load_manifest(path: Path) -> Dict[str, Any]:
    """Load and validate a module manifest"""
    try:
        with open(path, 'r') as f:
            data = json.load(f)
        
        # Validate required fields
        required = ['name', 'version', 'stability', 'summary', 'use_when', 'capabilities']
        for field in required:
            if field not in data:
                print(f"Warning: {path} missing required field '{field}'")
                return None
        
        return data
    except json.JSONDecodeError as e:
        print(f"Error parsing {path}: {e}")
        return None
    except Exception as e:
        print(f"Error loading {path}: {e}")
        return None

def build_capabilities_index(modules: List[Dict[str, Any]]) -> Dict[str, List[str]]:
    """Build reverse index: capability -> [module names]"""
    index = {}
    for module in modules:
        for cap in module.get('capabilities', []):
            if cap not in index:
                index[cap] = []
            index[cap].append(module['name'])
    return dict(sorted(index.items()))

def build_keywords_index(modules: List[Dict[str, Any]]) -> Dict[str, List[str]]:
    """Build reverse index: keyword -> [module names]"""
    index = {}
    for module in modules:
        for kw in module.get('keywords', []):
            if kw not in index:
                index[kw] = []
            index[kw].append(module['name'])
    return dict(sorted(index.items()))

def build_io_surface_index(modules: List[Dict[str, Any]]) -> Dict[str, List[str]]:
    """Build reverse index: io_surface -> [module names]"""
    index = {}
    for module in modules:
        for surface in module.get('io_surfaces', []):
            if surface not in index:
                index[surface] = []
            index[surface].append(module['name'])
    return dict(sorted(index.items()))

def generate_index(modules_dir: Path) -> Dict[str, Any]:
    """Generate complete module index"""
    manifests = find_manifests(modules_dir)
    
    if not manifests:
        print(f"Warning: No module.manifest.json files found in {modules_dir}")
        return {
            "version": "1.0.0",
            "generated_at": "",
            "modules": [],
            "indices": {}
        }
    
    print(f"Found {len(manifests)} module manifests")
    
    # Load all manifests
    modules = []
    for path in manifests:
        manifest = load_manifest(path)
        if manifest:
            modules.append(manifest)
            print(f"  ✓ {manifest['name']} v{manifest['version']} ({manifest['stability']})")
    
    # Build reverse indices
    capabilities_idx = build_capabilities_index(modules)
    keywords_idx = build_keywords_index(modules)
    io_surface_idx = build_io_surface_index(modules)
    
    # Count modules by stability
    stability_counts = {}
    for module in modules:
        stability = module['stability']
        stability_counts[stability] = stability_counts.get(stability, 0) + 1
    
    print(f"\nIndex statistics:")
    print(f"  Total modules: {len(modules)}")
    for stability, count in sorted(stability_counts.items()):
        print(f"  {stability}: {count}")
    print(f"  Capabilities: {len(capabilities_idx)}")
    print(f"  Keywords: {len(keywords_idx)}")
    print(f"  IO surfaces: {len(io_surface_idx)}")
    
    return {
        "version": "1.0.0",
        "generated_at": "auto-generated by tools/generate_module_index.py",
        "total_modules": len(modules),
        "modules": modules,
        "indices": {
            "capabilities": capabilities_idx,
            "keywords": keywords_idx,
            "io_surfaces": io_surface_idx
        }
    }

def main():
    # Find repo root
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    modules_dir = repo_root / 'modules'
    output_file = modules_dir / 'index.json'
    
    if not modules_dir.exists():
        print(f"Error: {modules_dir} does not exist")
        return 1
    
    print(f"Scanning {modules_dir} for module manifests...")
    index = generate_index(modules_dir)
    
    # Write index
    with open(output_file, 'w') as f:
        json.dump(index, f, indent=2, sort_keys=False)
    
    print(f"\n✓ Generated {output_file}")
    print(f"  {index['total_modules']} modules indexed")
    
    return 0

if __name__ == '__main__':
    exit(main())

