/* I generate this from binary64_arithmetic.h; do not edit. SHA256 49f450e9eabbd64dc837660e5c893d1c658775b2b8aa86bd5380a5b09a42aa4e */
#ifndef NANOLANG_BINARY64_ARITHMETIC_SOURCE_H
#define NANOLANG_BINARY64_ARITHMETIC_SOURCE_H
static const char nl_binary64_arithmetic_source[] =
"/* I canonicalize only scalar binary arithmetic results, never transported bits. */\n"
"#ifndef NANOLANG_BINARY64_ARITHMETIC_H\n"
"#define NANOLANG_BINARY64_ARITHMETIC_H\n"
"#include <float.h>\n"
"#include <stdint.h>\n"
"#include <string.h>\n"
"\n"
"#if defined(__FAST_MATH__) || (defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__)\n"
"#error \"I require ordinary IEEE arithmetic without fast-math.\"\n"
"#endif\n"
"#if FLT_RADIX != 2 || DBL_MANT_DIG != 53 || DBL_MAX_EXP != 1024 || DBL_MIN_EXP != -1021\n"
"#error \"I require binary64 double arithmetic.\"\n"
"#endif\n"
"#if !defined(FLT_EVAL_METHOD) || FLT_EVAL_METHOD != 0\n"
"#error \"I require operations evaluated in their binary64 type.\"\n"
"#endif\n"
"/* I retain a compile-time storage check in both C99 and C11 output. */\n"
"typedef char nano_rt_binary64_storage_guard[\n"
"    sizeof(double) == 8 && sizeof(uint64_t) == 8 ? 1 : -1];\n"
"\n"
"#if defined(__GNUC__) || defined(__clang__)\n"
"#define NL_BINARY64_ARITHMETIC_OPTIONAL __attribute__((unused))\n"
"#else\n"
"#define NL_BINARY64_ARITHMETIC_OPTIONAL\n"
"#endif\n"
"\n"
"/* I inspect a rounded result with integer operations, not another FP operation. */\n"
"static inline NL_BINARY64_ARITHMETIC_OPTIONAL double nano_rt_f64_arithmetic_result(double value) {\n"
"    uint64_t bits;\n"
"    memcpy(&bits, &value, sizeof(bits));\n"
"    if ((bits & UINT64_C(0x7ff0000000000000)) == UINT64_C(0x7ff0000000000000) &&\n"
"        (bits & UINT64_C(0x000fffffffffffff)) != 0) {\n"
"        bits = UINT64_C(0x7ff8000000000000);\n"
"        memcpy(&value, &bits, sizeof(value));\n"
"    }\n"
"    return value;\n"
"}\n"
"\n"
"/* Each volatile store/load is a binary64 rounding and noncontraction boundary. */\n"
"static inline NL_BINARY64_ARITHMETIC_OPTIONAL double nano_rt_f64_add(double a, double b) {\n"
"    volatile double rounded = a + b;\n"
"    return nano_rt_f64_arithmetic_result(rounded);\n"
"}\n"
"static inline NL_BINARY64_ARITHMETIC_OPTIONAL double nano_rt_f64_sub(double a, double b) {\n"
"    volatile double rounded = a - b;\n"
"    return nano_rt_f64_arithmetic_result(rounded);\n"
"}\n"
"static inline NL_BINARY64_ARITHMETIC_OPTIONAL double nano_rt_f64_mul(double a, double b) {\n"
"    volatile double rounded = a * b;\n"
"    return nano_rt_f64_arithmetic_result(rounded);\n"
"}\n"
"static inline NL_BINARY64_ARITHMETIC_OPTIONAL double nano_rt_f64_div(double a, double b) {\n"
"    uint64_t divisor;\n"
"    memcpy(&divisor, &b, sizeof(divisor));\n"
"    /* Either signed zero takes precedence even over a signaling NaN numerator. */\n"
"    if ((divisor & UINT64_C(0x7fffffffffffffff)) == 0) return 0.0;\n"
"    volatile double rounded = a / b;\n"
"    return nano_rt_f64_arithmetic_result(rounded);\n"
"}\n"
"#undef NL_BINARY64_ARITHMETIC_OPTIONAL\n"
"#endif\n"
;
#endif
