/* I generate this from binary64_arithmetic.h; do not edit. SHA256 8d0423fb3536a8f77216bab3749341eb536b485121d41111b33cda752cf53e97 */
#ifndef NANOLANG_BINARY64_ARITHMETIC_SOURCE_H
#define NANOLANG_BINARY64_ARITHMETIC_SOURCE_H
static const char nl_binary64_arithmetic_source[] =
"/* I canonicalize only scalar binary arithmetic results, never transported bits. */\n"
"#ifndef NANOLANG_BINARY64_ARITHMETIC_H\n"
"#define NANOLANG_BINARY64_ARITHMETIC_H\n"
"#include <float.h>\n"
"#include <stdint.h>\n"
"#include <string.h>\n"
"\n"
"#if defined(__FAST_MATH__) || (defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__)\n"
"#error \"I require ordinary IEEE arithmetic without fast-math.\"\n"
"#endif\n"
"#if FLT_RADIX != 2 || DBL_MANT_DIG != 53 || DBL_MAX_EXP != 1024 || DBL_MIN_EXP != -1021\n"
"#error \"I require binary64 double arithmetic.\"\n"
"#endif\n"
"#if !defined(FLT_EVAL_METHOD) || FLT_EVAL_METHOD != 0\n"
"#error \"I require operations evaluated in their binary64 type.\"\n"
"#endif\n"
"_Static_assert(sizeof(double) == 8 && sizeof(uint64_t) == 8, \"I require eight-byte binary64 storage.\");\n"
"\n"
"/* I inspect a rounded result with integer operations, not another FP operation. */\n"
"static inline double nano_rt_f64_arithmetic_result(double value) {\n"
"    uint64_t bits;\n"
"    memcpy(&bits, &value, sizeof(bits));\n"
"    if ((bits & UINT64_C(0x7ff0000000000000)) == UINT64_C(0x7ff0000000000000) &&\n"
"        (bits & UINT64_C(0x000fffffffffffff)) != 0) {\n"
"        bits = UINT64_C(0x7ff8000000000000);\n"
"        memcpy(&value, &bits, sizeof(value));\n"
"    }\n"
"    return value;\n"
"}\n"
"\n"
"/* Each volatile store/load is a binary64 rounding and noncontraction boundary. */\n"
"static inline double nano_rt_f64_add(double a, double b) {\n"
"    volatile double rounded = a + b;\n"
"    return nano_rt_f64_arithmetic_result(rounded);\n"
"}\n"
"static inline double nano_rt_f64_sub(double a, double b) {\n"
"    volatile double rounded = a - b;\n"
"    return nano_rt_f64_arithmetic_result(rounded);\n"
"}\n"
"static inline double nano_rt_f64_mul(double a, double b) {\n"
"    volatile double rounded = a * b;\n"
"    return nano_rt_f64_arithmetic_result(rounded);\n"
"}\n"
"static inline double nano_rt_f64_div(double a, double b) {\n"
"    uint64_t divisor;\n"
"    memcpy(&divisor, &b, sizeof(divisor));\n"
"    /* Either signed zero takes precedence even over a signaling NaN numerator. */\n"
"    if ((divisor & UINT64_C(0x7fffffffffffffff)) == 0) return 0.0;\n"
"    volatile double rounded = a / b;\n"
"    return nano_rt_f64_arithmetic_result(rounded);\n"
"}\n"
"#endif\n"
;
#endif
