/*
 * c_backend.c — nanolang C source emit backend
 *
 * Emits readable, self-contained C99 source from the nanolang AST.
 * Supports: numeric types, strings, arithmetic, comparisons, logical ops,
 * function definitions, let/set bindings, if/else, while, for, return,
 * print/println, structs, enums, unions, match, and basic effect stubs.
 *
 * Generated output is C99/C11-compliant and compiles with:
 *   gcc -std=c11 output.c -o output
 *
 * Usage:
 *   nanoc --target c input.nano [-o output.c]
 */

#include "c_backend.h"
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* ── Symbol table for local type tracking ───────────────────────────────── */
#define CB_MAX_SYMS   512
#define CB_MAX_SCOPES  64

typedef struct {
    const char *name;
    Type        type;
} CBSym;

/* ── Emit context ────────────────────────────────────────────────────────── */
typedef struct {
    FILE       *out;
    int         indent;
    bool        verbose;
    const char *error;

    /* Scoped symbol table */
    CBSym syms[CB_MAX_SYMS];
    int   sym_count;
    int   scope_marks[CB_MAX_SCOPES];
    int   scope_depth;
} CBCtx;

/* ── Helpers ─────────────────────────────────────────────────────────────── */

static void ctx_push_scope(CBCtx *c) {
    if (c->scope_depth < CB_MAX_SCOPES)
        c->scope_marks[c->scope_depth++] = c->sym_count;
}

static void ctx_pop_scope(CBCtx *c) {
    if (c->scope_depth > 0)
        c->sym_count = c->scope_marks[--c->scope_depth];
}

static void ctx_add_sym(CBCtx *c, const char *name, Type t) {
    if (c->sym_count < CB_MAX_SYMS) {
        c->syms[c->sym_count].name = name;
        c->syms[c->sym_count].type = t;
        c->sym_count++;
    }
}

static Type ctx_lookup_type(CBCtx *c, const char *name) {
    for (int i = c->sym_count - 1; i >= 0; i--) {
        if (strcmp(c->syms[i].name, name) == 0)
            return c->syms[i].type;
    }
    return TYPE_UNKNOWN;
}

/* Emit n*2 spaces of indentation */
static void emit_indent(CBCtx *c) {
    for (int i = 0; i < c->indent * 2; i++)
        fputc(' ', c->out);
}

/* Map nanolang Type → C type string */
static const char *c_type(Type t) {
    switch (t) {
        case TYPE_INT:    return "int64_t";
        case TYPE_U8:     return "uint8_t";
        case TYPE_FLOAT:  return "double";
        case TYPE_BOOL:   return "int";
        case TYPE_STRING: return "const char*";
        case TYPE_VOID:   return "void";
        default:          return "int64_t";
    }
}

/* Infer expression type for format string selection */
static Type infer_expr_type(CBCtx *c, ASTNode *node) {
    if (!node) return TYPE_INT;
    switch (node->type) {
        case AST_NUMBER:     return TYPE_INT;
        case AST_FLOAT:      return TYPE_FLOAT;
        case AST_BOOL:       return TYPE_BOOL;
        case AST_STRING:     return TYPE_STRING;
        case AST_IDENTIFIER: return ctx_lookup_type(c, node->as.identifier);
        case AST_LET:        return node->as.let.var_type;
        case AST_CALL:
            /* Heuristic: calls returning strings usually have "string" in name */
            if (node->as.call.name) {
                const char *n = node->as.call.name;
                if (strstr(n, "to_string") || strstr(n, "string_of") ||
                    strstr(n, "int_to_str") || strcmp(n, "nano_strcat") == 0)
                    return TYPE_STRING;
            }
            return TYPE_INT;
        case AST_PREFIX_OP: {
            TokenType op = node->as.prefix_op.op;
            if (op == TOKEN_EQ || op == TOKEN_NE || op == TOKEN_LT ||
                op == TOKEN_GT || op == TOKEN_LE || op == TOKEN_GE ||
                op == TOKEN_AND || op == TOKEN_OR || op == TOKEN_NOT)
                return TYPE_BOOL;
            /* For arithmetic, check lhs */
            if (node->as.prefix_op.arg_count > 0)
                return infer_expr_type(c, node->as.prefix_op.args[0]);
            return TYPE_INT;
        }
        default: return TYPE_INT;
    }
}

/* Return printf format specifier for a type */
static const char *fmt_for_type(Type t) {
    switch (t) {
        case TYPE_FLOAT:  return "%f";
        case TYPE_BOOL:   return "%d";
        case TYPE_STRING: return "%s";
        default:          return "%lld";
    }
}

/* Forward declarations */
static int emit_expr(CBCtx *c, ASTNode *node);
static int emit_stmt(CBCtx *c, ASTNode *node);
static int emit_block_body(CBCtx *c, ASTNode *node);

/* ── Preamble ─────────────────────────────────────────────────────────────── */
static void emit_preamble(CBCtx *c, const char *source_file) {
    fprintf(c->out, "/* Generated by nanolang --target c");
    if (source_file) fprintf(c->out, " from %s", source_file);
    fprintf(c->out, " */\n");
    fprintf(c->out, "#include <stdio.h>\n");
    fprintf(c->out, "#include <stdlib.h>\n");
    fprintf(c->out, "#include <stdint.h>\n");
    fprintf(c->out, "#include <string.h>\n");
    fprintf(c->out, "#include <setjmp.h>\n\n");

    /* nano_strcat helper */
    fprintf(c->out,
        "static const char* nano_strcat(const char* a, const char* b) {\n"
        "    size_t la = strlen(a), lb = strlen(b);\n"
        "    char* r = (char*)malloc(la + lb + 1);\n"
        "    memcpy(r, a, la); memcpy(r+la, b, lb); r[la+lb] = 0;\n"
        "    return (const char*)r;\n"
        "}\n\n");

    /* nano_bool_to_string helper */
    fprintf(c->out,
        "static const char* nano_bool_to_string(int b) {\n"
        "    return b ? \"true\" : \"false\";\n"
        "}\n\n");

    /* Effect stub support */
    fprintf(c->out,
        "/* Effect handler stubs */\n"
        "static jmp_buf _nano_effect_jmp;\n"
        "static int64_t _nano_effect_val;\n\n");
}

/* ── Expression emitter ───────────────────────────────────────────────────── */
static int emit_expr(CBCtx *c, ASTNode *node) {
    if (!node) {
        if (c->verbose)
            fprintf(stderr, "[c_backend] null AST node in expression\n");
        c->error = "null AST node";
        return -1;
    }

    switch (node->type) {
    case AST_NUMBER:
        fprintf(c->out, "%lldLL", (long long)node->as.number);
        return 0;

    case AST_FLOAT:
        fprintf(c->out, "%g", node->as.float_val);
        return 0;

    case AST_BOOL:
        fprintf(c->out, "%d", node->as.bool_val ? 1 : 0);
        return 0;

    case AST_STRING: {
        /* Emit as a C string literal with escaping */
        fputc('"', c->out);
        const char *s = node->as.string_val;
        for (; s && *s; s++) {
            switch (*s) {
                case '"':  fputs("\\\"", c->out); break;
                case '\\': fputs("\\\\", c->out); break;
                case '\n': fputs("\\n",  c->out); break;
                case '\r': fputs("\\r",  c->out); break;
                case '\t': fputs("\\t",  c->out); break;
                default:   fputc(*s, c->out);     break;
            }
        }
        fputc('"', c->out);
        return 0;
    }

    case AST_IDENTIFIER:
        fputs(node->as.identifier, c->out);
        return 0;

    case AST_PREFIX_OP: {
        int argc = node->as.prefix_op.arg_count;
        TokenType op = node->as.prefix_op.op;

        /* Unary not */
        if (argc == 1 && op == TOKEN_NOT) {
            fputc('!', c->out);
            fputc('(', c->out);
            if (emit_expr(c, node->as.prefix_op.args[0])) return -1;
            fputc(')', c->out);
            return 0;
        }

        /* Unary minus */
        if (argc == 1 && op == TOKEN_MINUS) {
            fputc('(', c->out);
            fputc('-', c->out);
            if (emit_expr(c, node->as.prefix_op.args[0])) return -1;
            fputc(')', c->out);
            return 0;
        }

        /* Binary op: check for string concatenation */
        if (argc == 2 && op == TOKEN_PLUS) {
            Type lt = infer_expr_type(c, node->as.prefix_op.args[0]);
            Type rt = infer_expr_type(c, node->as.prefix_op.args[1]);
            if (lt == TYPE_STRING || rt == TYPE_STRING) {
                fputs("nano_strcat(", c->out);
                if (emit_expr(c, node->as.prefix_op.args[0])) return -1;
                fputs(", ", c->out);
                if (emit_expr(c, node->as.prefix_op.args[1])) return -1;
                fputc(')', c->out);
                return 0;
            }
        }

        if (argc != 2) {
            c->error = "unsupported arity for prefix op";
            return -1;
        }

        const char *op_str = NULL;
        switch (op) {
            case TOKEN_PLUS:    op_str = "+";  break;
            case TOKEN_MINUS:   op_str = "-";  break;
            case TOKEN_STAR:    op_str = "*";  break;
            case TOKEN_SLASH:   op_str = "/";  break;
            case TOKEN_PERCENT: op_str = "%";  break;
            case TOKEN_EQ:      op_str = "=="; break;
            case TOKEN_NE:      op_str = "!="; break;
            case TOKEN_LT:      op_str = "<";  break;
            case TOKEN_LE:      op_str = "<="; break;
            case TOKEN_GT:      op_str = ">";  break;
            case TOKEN_GE:      op_str = ">="; break;
            case TOKEN_AND:     op_str = "&&"; break;
            case TOKEN_OR:      op_str = "||"; break;
            default:
                c->error = "unsupported binary operator";
                return -1;
        }

        fputc('(', c->out);
        if (emit_expr(c, node->as.prefix_op.args[0])) return -1;
        fprintf(c->out, " %s ", op_str);
        if (emit_expr(c, node->as.prefix_op.args[1])) return -1;
        fputc(')', c->out);
        return 0;
    }

    case AST_CALL: {
        const char *name = node->as.call.name;
        /* Handle built-in print/println */
        if (name && (strcmp(name, "println") == 0 || strcmp(name, "print") == 0) &&
            node->as.call.arg_count == 1) {
            bool is_println = (strcmp(name, "println") == 0);
            Type t = infer_expr_type(c, node->as.call.args[0]);
            if (t == TYPE_STRING) {
                fprintf(c->out, "printf(\"%%s%s\", ", is_println ? "\\n" : "");
            } else if (t == TYPE_FLOAT) {
                fprintf(c->out, "printf(\"%%g%s\", ", is_println ? "\\n" : "");
            } else if (t == TYPE_BOOL) {
                fprintf(c->out, "printf(\"%%d%s\", ", is_println ? "\\n" : "");
            } else {
                fprintf(c->out, "printf(\"%%lld%s\", (long long)(", is_println ? "\\n" : "");
            }
            if (emit_expr(c, node->as.call.args[0])) return -1;
            if (t != TYPE_STRING && t != TYPE_FLOAT && t != TYPE_BOOL)
                fputc(')', c->out);
            fputc(')', c->out);
            return 0;
        }
        /* Handle built-in int_to_string → snprintf pattern */
        if (name && strcmp(name, "int_to_string") == 0 &&
            node->as.call.arg_count == 1) {
            fputs("({ static char _ibuf[32]; snprintf(_ibuf,sizeof(_ibuf),\"%lld\",(long long)(", c->out);
            if (emit_expr(c, node->as.call.args[0])) return -1;
            fputs(")); _ibuf; })", c->out);
            return 0;
        }
        if (name && strcmp(name, "float_to_string") == 0 &&
            node->as.call.arg_count == 1) {
            fputs("({ static char _fbuf[64]; snprintf(_fbuf,sizeof(_fbuf),\"%g\",(double)(", c->out);
            if (emit_expr(c, node->as.call.args[0])) return -1;
            fputs(")); _fbuf; })", c->out);
            return 0;
        }
        if (name && strcmp(name, "bool_to_string") == 0 &&
            node->as.call.arg_count == 1) {
            fputs("nano_bool_to_string(", c->out);
            if (emit_expr(c, node->as.call.args[0])) return -1;
            fputc(')', c->out);
            return 0;
        }
        if (name && strcmp(name, "str_length") == 0 &&
            node->as.call.arg_count == 1) {
            fputs("(int64_t)strlen(", c->out);
            if (emit_expr(c, node->as.call.args[0])) return -1;
            fputc(')', c->out);
            return 0;
        }
        /* Regular function call */
        if (name) {
            fputs(name, c->out);
        } else if (node->as.call.func_expr) {
            fputc('(', c->out);
            if (emit_expr(c, node->as.call.func_expr)) return -1;
            fputc(')', c->out);
        } else {
            c->error = "call with no name or func_expr";
            return -1;
        }
        fputc('(', c->out);
        for (int i = 0; i < node->as.call.arg_count; i++) {
            if (i > 0) fputs(", ", c->out);
            if (emit_expr(c, node->as.call.args[i])) return -1;
        }
        fputc(')', c->out);
        return 0;
    }

    case AST_MODULE_QUALIFIED_CALL: {
        /* Emit as alias_function(args) */
        if (node->as.module_qualified_call.module_alias &&
            node->as.module_qualified_call.function_name) {
            fprintf(c->out, "%s_%s",
                    node->as.module_qualified_call.module_alias,
                    node->as.module_qualified_call.function_name);
        } else if (node->as.module_qualified_call.function_name) {
            fputs(node->as.module_qualified_call.function_name, c->out);
        }
        fputc('(', c->out);
        for (int i = 0; i < node->as.module_qualified_call.arg_count; i++) {
            if (i > 0) fputs(", ", c->out);
            if (emit_expr(c, node->as.module_qualified_call.args[i])) return -1;
        }
        fputc(')', c->out);
        return 0;
    }

    case AST_IF: {
        /* Ternary for expression contexts */
        fputc('(', c->out);
        if (emit_expr(c, node->as.if_stmt.condition)) return -1;
        fputs(" ? (", c->out);
        if (emit_expr(c, node->as.if_stmt.then_branch)) return -1;
        fputs(") : (", c->out);
        if (node->as.if_stmt.else_branch) {
            if (emit_expr(c, node->as.if_stmt.else_branch)) return -1;
        } else {
            fputs("0", c->out);
        }
        fputs("))", c->out);
        return 0;
    }

    case AST_BLOCK: {
        /* Inline block (GNU statement expression) */
        fputs("({\n", c->out);
        c->indent++;
        ctx_push_scope(c);
        for (int i = 0; i < node->as.block.count; i++) {
            emit_indent(c);
            if (emit_stmt(c, node->as.block.statements[i])) {
                ctx_pop_scope(c);
                c->indent--;
                return -1;
            }
        }
        ctx_pop_scope(c);
        c->indent--;
        emit_indent(c);
        fputs("})", c->out);
        return 0;
    }

    case AST_RETURN:
        /* Should be handled as a statement; if used as expr: */
        if (node->as.return_stmt.value) {
            return emit_expr(c, node->as.return_stmt.value);
        }
        fputs("0", c->out);
        return 0;

    case AST_STRUCT_LITERAL: {
        /* Emit: (NanoStruct_Name){ .field = val, ... } */
        fprintf(c->out, "(NanoStruct_%s){", node->as.struct_literal.struct_name);
        for (int i = 0; i < node->as.struct_literal.field_count; i++) {
            if (i > 0) fputs(", ", c->out);
            fprintf(c->out, ".%s = ", node->as.struct_literal.field_names[i]);
            if (emit_expr(c, node->as.struct_literal.field_values[i])) return -1;
        }
        fputc('}', c->out);
        return 0;
    }

    case AST_FIELD_ACCESS: {
        if (emit_expr(c, node->as.field_access.object)) return -1;
        fprintf(c->out, ".%s", node->as.field_access.field_name);
        return 0;
    }

    case AST_UNION_CONSTRUCT: {
        fprintf(c->out, "(NanoUnion_%s){ .tag = NanoUnion_%s_TAG_%s",
                node->as.union_construct.union_name,
                node->as.union_construct.union_name,
                node->as.union_construct.variant_name);
        if (node->as.union_construct.field_count > 0) {
            fprintf(c->out, ", .as.%s = {",
                    node->as.union_construct.variant_name);
            for (int i = 0; i < node->as.union_construct.field_count; i++) {
                if (i > 0) fputs(", ", c->out);
                fprintf(c->out, ".%s = ",
                        node->as.union_construct.field_names[i]);
                if (emit_expr(c, node->as.union_construct.field_values[i]))
                    return -1;
            }
            fputc('}', c->out);
        }
        fputc('}', c->out);
        return 0;
    }

    case AST_ARRAY_LITERAL: {
        fputc('{', c->out);
        for (int i = 0; i < node->as.array_literal.element_count; i++) {
            if (i > 0) fputs(", ", c->out);
            if (emit_expr(c, node->as.array_literal.elements[i])) return -1;
        }
        fputc('}', c->out);
        return 0;
    }

    case AST_TUPLE_LITERAL: {
        /* Tuples not fully supported; emit first element as fallback */
        if (node->as.tuple_literal.element_count > 0) {
            return emit_expr(c, node->as.tuple_literal.elements[0]);
        }
        fputs("0", c->out);
        return 0;
    }

    case AST_EFFECT_OP: {
        /* Simplified stub: longjmp to nearest handler */
        fputs("(longjmp(_nano_effect_jmp, 1), 0)", c->out);
        return 0;
    }

    case AST_AWAIT: {
        /* Simplified stub: just evaluate the inner expression */
        return emit_expr(c, node->as.await_expr.expr);
    }

    case AST_TRY_OP: {
        /* Simplified stub: evaluate operand */
        return emit_expr(c, node->as.try_op.operand);
    }

    default:
        if (c->verbose)
            fprintf(stderr, "[c_backend] unsupported expr node type %d\n",
                    node->type);
        c->error = "unsupported expression AST node";
        return -1;
    }
}

/* ── Statement emitter ────────────────────────────────────────────────────── */
static int emit_stmt(CBCtx *c, ASTNode *node) {
    if (!node) return 0;

    switch (node->type) {
    case AST_LET: {
        Type t = node->as.let.var_type;
        ctx_add_sym(c, node->as.let.name, t);

        if (t == TYPE_STRUCT && node->as.let.type_name) {
            fprintf(c->out, "NanoStruct_%s %s", node->as.let.type_name,
                    node->as.let.name);
        } else if (t == TYPE_UNION && node->as.let.type_name) {
            fprintf(c->out, "NanoUnion_%s %s", node->as.let.type_name,
                    node->as.let.name);
        } else if (t == TYPE_ARRAY) {
            fprintf(c->out, "%s* %s", c_type(node->as.let.element_type),
                    node->as.let.name);
        } else {
            fprintf(c->out, "%s %s", c_type(t), node->as.let.name);
        }
        if (node->as.let.value) {
            fputs(" = ", c->out);
            if (emit_expr(c, node->as.let.value)) return -1;
        }
        fputs(";\n", c->out);
        return 0;
    }

    case AST_SET: {
        fputs(node->as.set.name, c->out);
        fputs(" = ", c->out);
        if (emit_expr(c, node->as.set.value)) return -1;
        fputs(";\n", c->out);
        return 0;
    }

    case AST_RETURN:
        fputs("return", c->out);
        if (node->as.return_stmt.value) {
            fputc(' ', c->out);
            if (emit_expr(c, node->as.return_stmt.value)) return -1;
        }
        fputs(";\n", c->out);
        return 0;

    case AST_BREAK:
        fputs("break;\n", c->out);
        return 0;

    case AST_CONTINUE:
        fputs("continue;\n", c->out);
        return 0;

    case AST_PRINT: {
        Type t = infer_expr_type(c, node->as.print.expr);
        const char *fmt = fmt_for_type(t);
        (void)fmt;
        if (node->as.print.is_println) {
            if (t == TYPE_STRING)
                fprintf(c->out, "printf(\"%%s\\n\", ");
            else if (t == TYPE_FLOAT)
                fprintf(c->out, "printf(\"%%g\\n\", ");
            else if (t == TYPE_BOOL)
                fprintf(c->out, "printf(\"%%d\\n\", ");
            else
                fprintf(c->out, "printf(\"%%lld\\n\", (long long)(");
        } else {
            if (t == TYPE_STRING)
                fprintf(c->out, "printf(\"%%s\", ");
            else if (t == TYPE_FLOAT)
                fprintf(c->out, "printf(\"%%g\", ");
            else if (t == TYPE_BOOL)
                fprintf(c->out, "printf(\"%%d\", ");
            else
                fprintf(c->out, "printf(\"%%lld\", (long long)(");
        }
        if (emit_expr(c, node->as.print.expr)) return -1;
        if (t != TYPE_STRING && t != TYPE_FLOAT && t != TYPE_BOOL)
            fputc(')', c->out);
        fputs(");\n", c->out);
        return 0;
    }

    case AST_ASSERT: {
        fputs("if (!(", c->out);
        if (emit_expr(c, node->as.assert.condition)) return -1;
        fprintf(c->out,
                ")) { fprintf(stderr, \"Assertion failed at line %d\\n\"); exit(1); }\n",
                node->line);
        return 0;
    }

    case AST_IF: {
        fputs("if (", c->out);
        if (emit_expr(c, node->as.if_stmt.condition)) return -1;
        fputs(") {\n", c->out);
        c->indent++;
        ctx_push_scope(c);
        if (emit_block_body(c, node->as.if_stmt.then_branch)) {
            ctx_pop_scope(c); c->indent--;
            return -1;
        }
        ctx_pop_scope(c);
        c->indent--;
        emit_indent(c);
        fputc('}', c->out);
        if (node->as.if_stmt.else_branch) {
            fputs(" else {\n", c->out);
            c->indent++;
            ctx_push_scope(c);
            if (emit_block_body(c, node->as.if_stmt.else_branch)) {
                ctx_pop_scope(c); c->indent--;
                return -1;
            }
            ctx_pop_scope(c);
            c->indent--;
            emit_indent(c);
            fputc('}', c->out);
        }
        fputc('\n', c->out);
        return 0;
    }

    case AST_WHILE: {
        fputs("while (", c->out);
        if (emit_expr(c, node->as.while_stmt.condition)) return -1;
        fputs(") {\n", c->out);
        c->indent++;
        ctx_push_scope(c);
        if (emit_block_body(c, node->as.while_stmt.body)) {
            ctx_pop_scope(c); c->indent--;
            return -1;
        }
        ctx_pop_scope(c);
        c->indent--;
        emit_indent(c);
        fputs("}\n", c->out);
        return 0;
    }

    case AST_FOR: {
        ASTNode *range = node->as.for_stmt.range_expr;
        const char *var = node->as.for_stmt.var_name;
        ctx_add_sym(c, var, TYPE_INT);

        if (range && range->type == AST_PREFIX_OP &&
            range->as.prefix_op.op == TOKEN_RANGE &&
            range->as.prefix_op.arg_count == 2) {
            fprintf(c->out, "for (int64_t %s = ", var);
            if (emit_expr(c, range->as.prefix_op.args[0])) return -1;
            fprintf(c->out, "; %s < ", var);
            if (emit_expr(c, range->as.prefix_op.args[1])) return -1;
            fprintf(c->out, "; %s++) {\n", var);
        } else {
            fprintf(c->out, "for (int64_t %s = 0; %s < ", var, var);
            if (emit_expr(c, range)) return -1;
            fprintf(c->out, "; %s++) {\n", var);
        }
        c->indent++;
        ctx_push_scope(c);
        if (emit_block_body(c, node->as.for_stmt.body)) {
            ctx_pop_scope(c); c->indent--;
            return -1;
        }
        ctx_pop_scope(c);
        c->indent--;
        emit_indent(c);
        fputs("}\n", c->out);
        return 0;
    }

    case AST_BLOCK: {
        fputs("{\n", c->out);
        c->indent++;
        ctx_push_scope(c);
        for (int i = 0; i < node->as.block.count; i++) {
            emit_indent(c);
            if (emit_stmt(c, node->as.block.statements[i])) {
                ctx_pop_scope(c); c->indent--;
                return -1;
            }
        }
        ctx_pop_scope(c);
        c->indent--;
        emit_indent(c);
        fputs("}\n", c->out);
        return 0;
    }

    case AST_MATCH: {
        ASTNode *expr = node->as.match_expr.expr;
        fprintf(c->out, "/* match */ {\n");
        c->indent++;
        emit_indent(c);
        const char *utype = node->as.match_expr.union_type_name;
        if (utype) {
            fprintf(c->out, "NanoUnion_%s _match_val = ", utype);
        } else {
            fputs("int64_t _match_val = ", c->out);
        }
        if (emit_expr(c, expr)) { c->indent--; return -1; }
        fputs(";\n", c->out);

        for (int i = 0; i < node->as.match_expr.arm_count; i++) {
            emit_indent(c);
            if (i == 0) fputs("if (", c->out);
            else        fputs("} else if (", c->out);

            if (utype) {
                fprintf(c->out, "_match_val.tag == NanoUnion_%s_TAG_%s",
                        utype, node->as.match_expr.pattern_variants[i]);
            } else {
                fprintf(c->out, "1 /* %s */",
                        node->as.match_expr.pattern_variants[i]);
            }

            if (node->as.match_expr.guard_exprs &&
                node->as.match_expr.guard_exprs[i]) {
                fputs(" && (", c->out);
                if (emit_expr(c, node->as.match_expr.guard_exprs[i]))
                    { c->indent--; return -1; }
                fputc(')', c->out);
            }

            fputs(") {\n", c->out);
            c->indent++;
            ctx_push_scope(c);

            if (node->as.match_expr.pattern_bindings &&
                node->as.match_expr.pattern_bindings[i] &&
                utype) {
                emit_indent(c);
                fprintf(c->out, "__typeof__(_match_val.as.%s) %s = _match_val.as.%s;\n",
                        node->as.match_expr.pattern_variants[i],
                        node->as.match_expr.pattern_bindings[i],
                        node->as.match_expr.pattern_variants[i]);
                ctx_add_sym(c, node->as.match_expr.pattern_bindings[i], TYPE_STRUCT);
            }

            emit_indent(c);
            if (emit_stmt(c, node->as.match_expr.arm_bodies[i])) {
                ctx_pop_scope(c); c->indent -= 2;
                return -1;
            }
            ctx_pop_scope(c);
            c->indent--;
        }
        if (node->as.match_expr.arm_count > 0) {
            emit_indent(c);
            fputs("}\n", c->out);
        }
        c->indent--;
        emit_indent(c);
        fputs("}\n", c->out);
        return 0;
    }

    case AST_HANDLE_EXPR: {
        fputs("/* handle */ if (setjmp(_nano_effect_jmp) == 0) {\n", c->out);
        c->indent++;
        if (emit_block_body(c, node->as.handle_expr.body)) {
            c->indent--;
            return -1;
        }
        c->indent--;
        emit_indent(c);
        fputs("}\n", c->out);
        return 0;
    }

    case AST_EFFECT_DECL:
        fputs("/* effect declaration (stub) */\n", c->out);
        return 0;

    case AST_SHADOW:
        fputs("/* shadow test (skipped) */\n", c->out);
        return 0;

    case AST_IMPORT:
    case AST_MODULE_DECL:
    case AST_OPAQUE_TYPE:
        return 0;

    case AST_PAR_BLOCK: {
        ASTNode **bindings = node->as.par_block.bindings;
        int cnt = node->as.par_block.count;
        for (int i = 0; i < cnt; i++) {
            emit_indent(c);
            if (emit_stmt(c, bindings[i])) return -1;
        }
        return 0;
    }
    case AST_PAR_LET: {
        /* par-let: emit each binding value as a statement, then the body */
        int cnt = node->as.par_let.count;
        for (int i = 0; i < cnt; i++) {
            emit_indent(c);
            if (emit_stmt(c, node->as.par_let.values[i])) return -1;
        }
        if (node->as.par_let.body) {
            emit_indent(c);
            if (emit_stmt(c, node->as.par_let.body)) return -1;
        }
        return 0;
    }

    case AST_UNSAFE_BLOCK: {
        fputs("/* unsafe */ {\n", c->out);
        c->indent++;
        ctx_push_scope(c);
        for (int i = 0; i < node->as.unsafe_block.count; i++) {
            emit_indent(c);
            if (emit_stmt(c, node->as.unsafe_block.statements[i])) {
                ctx_pop_scope(c); c->indent--;
                return -1;
            }
        }
        ctx_pop_scope(c);
        c->indent--;
        emit_indent(c);
        fputs("}\n", c->out);
        return 0;
    }

    case AST_COND: {
        for (int i = 0; i < node->as.cond_expr.clause_count; i++) {
            emit_indent(c);
            if (i == 0) fputs("if (", c->out);
            else        fputs("} else if (", c->out);
            if (emit_expr(c, node->as.cond_expr.conditions[i])) return -1;
            fputs(") {\n", c->out);
            c->indent++;
            ctx_push_scope(c);
            emit_indent(c);
            fputs("return ", c->out);
            if (emit_expr(c, node->as.cond_expr.values[i])) {
                ctx_pop_scope(c); c->indent--;
                return -1;
            }
            fputs(";\n", c->out);
            ctx_pop_scope(c);
            c->indent--;
        }
        if (node->as.cond_expr.clause_count > 0) {
            emit_indent(c);
            fputs("} else {\n", c->out);
            c->indent++;
            emit_indent(c);
            fputs("return ", c->out);
            if (emit_expr(c, node->as.cond_expr.else_value)) {
                c->indent--;
                return -1;
            }
            fputs(";\n", c->out);
            c->indent--;
            emit_indent(c);
            fputs("}\n", c->out);
        }
        return 0;
    }

    /* Expressions used as statements */
    default: {
        if (emit_expr(c, node)) return -1;
        fputs(";\n", c->out);
        return 0;
    }
    }
}

/*
 * emit_block_body — emit the contents of a block node (or single statement)
 * without surrounding braces.
 */
static int emit_block_body(CBCtx *c, ASTNode *node) {
    if (!node) return 0;
    if (node->type == AST_BLOCK) {
        for (int i = 0; i < node->as.block.count; i++) {
            emit_indent(c);
            if (emit_stmt(c, node->as.block.statements[i])) return -1;
        }
        return 0;
    }
    emit_indent(c);
    return emit_stmt(c, node);
}

/* ── Type definitions ─────────────────────────────────────────────────────── */
static void emit_struct_def(CBCtx *c, ASTNode *node) {
    if (node->as.struct_def.is_extern) return;
    fprintf(c->out, "typedef struct {\n");
    for (int i = 0; i < node->as.struct_def.field_count; i++) {
        Type ft = node->as.struct_def.field_types[i];
        const char *fname = node->as.struct_def.field_names[i];
        fputs("  ", c->out);
        if (ft == TYPE_STRUCT && node->as.struct_def.field_type_names &&
            node->as.struct_def.field_type_names[i]) {
            fprintf(c->out, "NanoStruct_%s %s;\n",
                    node->as.struct_def.field_type_names[i], fname);
        } else if (ft == TYPE_ARRAY) {
            Type et = node->as.struct_def.field_element_types
                    ? node->as.struct_def.field_element_types[i]
                    : TYPE_INT;
            fprintf(c->out, "%s* %s;\n", c_type(et), fname);
        } else {
            fprintf(c->out, "%s %s;\n", c_type(ft), fname);
        }
    }
    fprintf(c->out, "} NanoStruct_%s;\n\n", node->as.struct_def.name);
}

static void emit_enum_def(CBCtx *c, ASTNode *node) {
    if (node->as.enum_def.is_extern) return;
    fprintf(c->out, "typedef enum {\n");
    for (int i = 0; i < node->as.enum_def.variant_count; i++) {
        fputs("  ", c->out);
        fprintf(c->out, "NanoEnum_%s_%s",
                node->as.enum_def.name, node->as.enum_def.variant_names[i]);
        if (node->as.enum_def.variant_values) {
            fprintf(c->out, " = %d", node->as.enum_def.variant_values[i]);
        }
        if (i < node->as.enum_def.variant_count - 1) fputc(',', c->out);
        fputc('\n', c->out);
    }
    fprintf(c->out, "} NanoEnum_%s;\n\n", node->as.enum_def.name);
}

static void emit_union_def(CBCtx *c, ASTNode *node) {
    if (node->as.union_def.is_extern) return;
    const char *uname = node->as.union_def.name;
    /* Tag enum */
    fprintf(c->out, "typedef enum {\n");
    for (int i = 0; i < node->as.union_def.variant_count; i++) {
        fprintf(c->out, "  NanoUnion_%s_TAG_%s%s\n",
                uname, node->as.union_def.variant_names[i],
                (i < node->as.union_def.variant_count - 1) ? "," : "");
    }
    fprintf(c->out, "} NanoUnion_%s_Tag;\n\n", uname);

    fprintf(c->out, "typedef struct {\n");
    fprintf(c->out, "  NanoUnion_%s_Tag tag;\n", uname);
    fprintf(c->out, "  union {\n");
    for (int v = 0; v < node->as.union_def.variant_count; v++) {
        int fc = node->as.union_def.variant_field_counts[v];
        if (fc == 0) continue;
        fprintf(c->out, "    struct {\n");
        for (int f = 0; f < fc; f++) {
            Type ft = node->as.union_def.variant_field_types[v][f];
            const char *fn = node->as.union_def.variant_field_names[v][f];
            fprintf(c->out, "      %s %s;\n", c_type(ft), fn);
        }
        fprintf(c->out, "    } %s;\n", node->as.union_def.variant_names[v]);
    }
    fprintf(c->out, "  } as;\n");
    fprintf(c->out, "} NanoUnion_%s;\n\n", uname);
}

/* ── Function emitter ─────────────────────────────────────────────────────── */
static int emit_function(CBCtx *c, ASTNode *node) {
    if (node->as.function.is_extern) return 0;

    Type ret = node->as.function.return_type;
    const char *ret_type_str;
    static char struct_ret[128];
    if (ret == TYPE_STRUCT && node->as.function.return_struct_type_name) {
        snprintf(struct_ret, sizeof(struct_ret), "NanoStruct_%s",
                 node->as.function.return_struct_type_name);
        ret_type_str = struct_ret;
    } else {
        ret_type_str = c_type(ret);
    }

    fprintf(c->out, "%s %s(", ret_type_str, node->as.function.name);
    for (int i = 0; i < node->as.function.param_count; i++) {
        if (i > 0) fputs(", ", c->out);
        Parameter *p = &node->as.function.params[i];
        if (p->type == TYPE_STRUCT && p->struct_type_name) {
            fprintf(c->out, "NanoStruct_%s %s", p->struct_type_name, p->name);
        } else if (p->type == TYPE_UNION && p->struct_type_name) {
            fprintf(c->out, "NanoUnion_%s %s", p->struct_type_name, p->name);
        } else {
            fprintf(c->out, "%s %s", c_type(p->type), p->name);
        }
    }
    fputs(") {\n", c->out);

    ctx_push_scope(c);
    for (int i = 0; i < node->as.function.param_count; i++) {
        Parameter *p = &node->as.function.params[i];
        ctx_add_sym(c, p->name, p->type);
    }

    c->indent = 1;
    if (node->as.function.body) {
        if (node->as.function.body->type == AST_BLOCK) {
            for (int i = 0; i < node->as.function.body->as.block.count; i++) {
                emit_indent(c);
                if (emit_stmt(c, node->as.function.body->as.block.statements[i])) {
                    ctx_pop_scope(c);
                    return -1;
                }
            }
        } else {
            emit_indent(c);
            if (emit_stmt(c, node->as.function.body)) {
                ctx_pop_scope(c);
                return -1;
            }
        }
    }

    ctx_pop_scope(c);
    c->indent = 0;
    fputs("}\n\n", c->out);
    return 0;
}

/* ── Forward declarations ─────────────────────────────────────────────────── */
static void emit_forward_decls(CBCtx *c, ASTNode *root) {
    if (!root) return;
    ASTNode **items = NULL;
    int count = 0;
    if (root->type == AST_PROGRAM) {
        items = root->as.program.items;
        count = root->as.program.count;
    } else {
        items = &root;
        count = 1;
    }
    for (int i = 0; i < count; i++) {
        ASTNode *n = items[i];
        if (!n || n->type != AST_FUNCTION) continue;
        if (n->as.function.is_extern) continue;
        Type ret = n->as.function.return_type;
        const char *ret_str;
        static char sbuf[128];
        if (ret == TYPE_STRUCT && n->as.function.return_struct_type_name) {
            snprintf(sbuf, sizeof(sbuf), "NanoStruct_%s",
                     n->as.function.return_struct_type_name);
            ret_str = sbuf;
        } else {
            ret_str = c_type(ret);
        }
        fprintf(c->out, "%s %s(", ret_str, n->as.function.name);
        for (int j = 0; j < n->as.function.param_count; j++) {
            if (j > 0) fputs(", ", c->out);
            Parameter *p = &n->as.function.params[j];
            if (p->type == TYPE_STRUCT && p->struct_type_name)
                fprintf(c->out, "NanoStruct_%s %s", p->struct_type_name, p->name);
            else if (p->type == TYPE_UNION && p->struct_type_name)
                fprintf(c->out, "NanoUnion_%s %s", p->struct_type_name, p->name);
            else
                fprintf(c->out, "%s %s", c_type(p->type), p->name);
        }
        fputs(");\n", c->out);
    }
    if (count > 0) fputc('\n', c->out);
}

/* ── Top-level program emitter ───────────────────────────────────────────── */
static int emit_program(CBCtx *c, ASTNode *root) {
    ASTNode **items = NULL;
    int count = 0;

    if (root->type == AST_PROGRAM) {
        items = root->as.program.items;
        count = root->as.program.count;
    } else {
        items = &root;
        count = 1;
    }

    /* Pass 1: type definitions */
    for (int i = 0; i < count; i++) {
        ASTNode *n = items[i];
        if (!n) continue;
        switch (n->type) {
            case AST_STRUCT_DEF: emit_struct_def(c, n); break;
            case AST_ENUM_DEF:   emit_enum_def(c, n);   break;
            case AST_UNION_DEF:  emit_union_def(c, n);  break;
            default: break;
        }
    }

    /* Pass 2: forward declarations */
    emit_forward_decls(c, root);

    /* Pass 3: function definitions */
    for (int i = 0; i < count; i++) {
        ASTNode *n = items[i];
        if (!n) continue;
        switch (n->type) {
            case AST_ASYNC_FN:
                if (n->as.async_fn.function)
                    n = n->as.async_fn.function;
                /* fall through */
            case AST_FUNCTION:
                if (emit_function(c, n)) return -1;
                break;
            default:
                break;
        }
    }
    return 0;
}

/* ── Public API ──────────────────────────────────────────────────────────── */
int c_backend_emit_fp(ASTNode *root, FILE *out, const char *source_file,
                      const CBOptions *opts) {
    CBCtx c;
    memset(&c, 0, sizeof(c));
    c.out     = out;
    c.verbose = opts ? opts->verbose : false;
    c.indent  = 0;

    emit_preamble(&c, source_file);
    return emit_program(&c, root);
}

int c_backend_emit(ASTNode *root, const char *output_path,
                   const char *source_file, const CBOptions *opts) {
    FILE *fp = fopen(output_path, "w");
    if (!fp) {
        fprintf(stderr, "[c_backend] error: cannot open %s for writing\n",
                output_path);
        return 1;
    }

    CBCtx c;
    memset(&c, 0, sizeof(c));
    c.out     = fp;
    c.verbose = opts ? opts->verbose : false;
    c.indent  = 0;

    emit_preamble(&c, source_file);
    int rc = emit_program(&c, root);

    fclose(fp);
    if (rc != 0) {
        fprintf(stderr, "[c_backend] error: %s\n",
                c.error ? c.error : "unknown error");
    }
    return rc;
}
