/*
 * c_backend.c — nanolang C transpiler backend
 *
 * Emits readable, self-contained C source from the nanolang AST.
 * Designed for embedding nanolang logic in agentOS PD binaries on seL4
 * without a WASM interpreter or LLVM toolchain dependency.
 *
 * Type mapping:
 *   int     → int64_t
 *   float   → double
 *   bool    → int  (C11 _Bool / stdbool.h)
 *   string  → const char*
 *   struct  → typedef struct { ... } Name;
 *   array   → nano_array_t (simple fat pointer: ptr + len)
 *
 * Generated output is C11-compliant and compiles with:
 *   gcc -std=c11 output.c -o output
 */

#include "c_backend.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdarg.h>

/* ── Emit context ──────────────────────────────────────────────────────── */

typedef struct {
    FILE       *out;
    int         indent;
    const char *source_file;
    bool        verbose;
    bool        error;
    bool        in_function;    /* true while emitting a function body */
    bool        has_string;     /* emitted at least one string op — need runtime? */
} CCtx;

static void cctx_init(CCtx *ctx, FILE *out, const char *source_file, bool verbose) {
    ctx->out         = out;
    ctx->indent      = 0;
    ctx->source_file = source_file;
    ctx->verbose     = verbose;
    ctx->error       = false;
    ctx->in_function = false;
    ctx->has_string  = false;
}

/* ── Indented printf ──────────────────────────────────────────────────── */

static void iprintf(CCtx *ctx, const char *fmt, ...) {
    for (int i = 0; i < ctx->indent; i++) fputs("    ", ctx->out);
    va_list ap;
    va_start(ap, fmt);
    vfprintf(ctx->out, fmt, ap);
    va_end(ap);
}

static void emit(CCtx *ctx, const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    vfprintf(ctx->out, fmt, ap);
    va_end(ap);
}

/* ── Type name ──────────────────────────────────────────────────────────── */

static const char *c_type_name(Type t, const char *struct_name) {
    switch (t) {
        case TYPE_INT:      return "int64_t";
        case TYPE_U8:       return "uint8_t";
        case TYPE_FLOAT:    return "double";
        case TYPE_BOOL:     return "bool";
        case TYPE_STRING:   return "const char*";
        case TYPE_VOID:     return "void";
        case TYPE_STRUCT:   return struct_name ? struct_name : "nano_record_t";
        case TYPE_ENUM:     return struct_name ? struct_name : "int";
        case TYPE_ARRAY:    return "nano_array_t";
        case TYPE_UNKNOWN:  return "nano_val_t";
        default:            return "nano_val_t";
    }
}

/* ── Forward declaration ─────────────────────────────────────────────── */
static void emit_node(CCtx *ctx, ASTNode *node);
static void emit_expr(CCtx *ctx, ASTNode *node);

/* ── Preamble ─────────────────────────────────────────────────────────── */

static void emit_preamble(CCtx *ctx) {
    fprintf(ctx->out,
        "/* Generated by nanoc --target c from: %s */\n"
        "/* Do not edit — regenerate with: nanoc --target c %s */\n\n"
        "#include <stdint.h>\n"
        "#include <stdbool.h>\n"
        "#include <string.h>\n"
        "#include <stdio.h>\n"
        "#include <stdlib.h>\n\n"
        "/* ── nanolang runtime shims ──────────────────────────────────── */\n\n"
        "/* Untyped value (for generic/unknown types) */\n"
        "typedef union { int64_t i; double f; bool b; const char *s; void *p; } nano_val_t;\n\n"
        "/* Fat-pointer array */\n"
        "typedef struct { void *data; int64_t len; int64_t cap; } nano_array_t;\n\n"
        "/* Dynamic record (row-polymorphic, heap allocated) */\n"
        "typedef struct nano_record nano_record_t;\n"
        "struct nano_record { int field_count; const char **field_names; nano_val_t *field_vals; };\n\n"
        "static inline nano_val_t nano_record_get(nano_record_t *r, const char *name) {\n"
        "    for (int i = 0; i < r->field_count; i++)\n"
        "        if (strcmp(r->field_names[i], name) == 0) return r->field_vals[i];\n"
        "    nano_val_t v = {0}; return v;\n"
        "}\n\n",
        ctx->source_file ? ctx->source_file : "<unknown>",
        ctx->source_file ? ctx->source_file : "<unknown>"
    );
}

/* ── Token → C operator ──────────────────────────────────────────────── */

static const char *token_op_str(TokenType op) {
    switch (op) {
        case TOKEN_PLUS:    return "+";
        case TOKEN_MINUS:   return "-";
        case TOKEN_STAR:    return "*";
        case TOKEN_SLASH:   return "/";
        case TOKEN_PERCENT: return "%";
        case TOKEN_EQ:      return "==";
        case TOKEN_NE:      return "!=";
        case TOKEN_LT:      return "<";
        case TOKEN_LE:      return "<=";
        case TOKEN_GT:      return ">";
        case TOKEN_GE:      return ">=";
        case TOKEN_AND:     return "&&";
        case TOKEN_OR:      return "||";
        case TOKEN_NOT:     return "!";
        case TOKEN_PIPE:    return "|";
        case TOKEN_BAR:     return "|";
        default:            return "/* op */";
    }
}

/* ── Emit expression ─────────────────────────────────────────────────── */

static void emit_expr(CCtx *ctx, ASTNode *node) {
    if (!node) { emit(ctx, "0"); return; }

    switch (node->type) {
        case AST_NUMBER:
            emit(ctx, "%lld", (long long)node->as.number);
            break;

        case AST_FLOAT:
            emit(ctx, "%g", node->as.float_val);
            break;

        case AST_BOOL:
            emit(ctx, node->as.bool_val ? "true" : "false");
            break;

        case AST_STRING:
            ctx->has_string = true;
            emit(ctx, "\"");
            /* Escape special chars */
            for (const char *p = node->as.string_val; *p; p++) {
                switch (*p) {
                    case '"':  emit(ctx, "\\\""); break;
                    case '\\': emit(ctx, "\\\\"); break;
                    case '\n': emit(ctx, "\\n");  break;
                    case '\t': emit(ctx, "\\t");  break;
                    default:   fputc(*p, ctx->out); break;
                }
            }
            emit(ctx, "\"");
            break;

        case AST_IDENTIFIER:
            emit(ctx, "%s", node->as.identifier);
            break;

        case AST_PREFIX_OP: {
            /* Binary ops have 2 args; unary ops have 1 */
            if (node->as.prefix_op.arg_count == 2) {
                emit(ctx, "(");
                emit_expr(ctx, node->as.prefix_op.args[0]);
                emit(ctx, " %s ", token_op_str(node->as.prefix_op.op));
                emit_expr(ctx, node->as.prefix_op.args[1]);
                emit(ctx, ")");
            } else if (node->as.prefix_op.arg_count == 1) {
                emit(ctx, "(%s", token_op_str(node->as.prefix_op.op));
                emit_expr(ctx, node->as.prefix_op.args[0]);
                emit(ctx, ")");
            }
            break;
        }

        case AST_CALL: {
            const char *fn = node->as.call.name;
            if (!fn && node->as.call.func_expr) {
                emit(ctx, "(");
                emit_expr(ctx, node->as.call.func_expr);
                emit(ctx, ")(");
            } else {
                emit(ctx, "%s(", fn ? fn : "unknown");
            }
            for (int i = 0; i < node->as.call.arg_count; i++) {
                if (i > 0) emit(ctx, ", ");
                emit_expr(ctx, node->as.call.args[i]);
            }
            emit(ctx, ")");
            break;
        }

        case AST_MODULE_QUALIFIED_CALL: {
            emit(ctx, "%s_%s(", node->as.module_qualified_call.module_alias,
                                node->as.module_qualified_call.function_name);
            for (int i = 0; i < node->as.module_qualified_call.arg_count; i++) {
                if (i > 0) emit(ctx, ", ");
                emit_expr(ctx, node->as.module_qualified_call.args[i]);
            }
            emit(ctx, ")");
            break;
        }

        case AST_FIELD_ACCESS:
            emit_expr(ctx, node->as.field_access.object);
            emit(ctx, ".%s", node->as.field_access.field_name);
            break;

        case AST_STRUCT_LITERAL: {
            /* Emit as designated initializer: (TypeName){ .f1=v1, .f2=v2 } */
            emit(ctx, "(%s){ ", node->as.struct_literal.struct_name
                                 ? node->as.struct_literal.struct_name : "nano_record_t");
            for (int i = 0; i < node->as.struct_literal.field_count; i++) {
                if (i > 0) emit(ctx, ", ");
                emit(ctx, ".%s = ", node->as.struct_literal.field_names[i]);
                emit_expr(ctx, node->as.struct_literal.field_values[i]);
            }
            emit(ctx, " }");
            break;
        }

        case AST_ARRAY_LITERAL: {
            /* Emit as compound literal wrapped in nano_array_t */
            emit(ctx, "(nano_array_t){ .data = (nano_val_t[]){");
            for (int i = 0; i < node->as.array_literal.element_count; i++) {
                if (i > 0) emit(ctx, ", ");
                emit(ctx, "(nano_val_t){.i = (int64_t)(");
                emit_expr(ctx, node->as.array_literal.elements[i]);
                emit(ctx, ")}");
            }
            emit(ctx, "}, .len = %d, .cap = %d }",
                 node->as.array_literal.element_count,
                 node->as.array_literal.element_count);
            break;
        }

        case AST_IF: {
            emit(ctx, "(");
            emit_expr(ctx, node->as.if_stmt.condition);
            emit(ctx, " ? (");
            if (node->as.if_stmt.then_branch)
                emit_expr(ctx, node->as.if_stmt.then_branch);
            else
                emit(ctx, "0");
            emit(ctx, ") : (");
            if (node->as.if_stmt.else_branch)
                emit_expr(ctx, node->as.if_stmt.else_branch);
            else
                emit(ctx, "0");
            emit(ctx, "))");
            break;
        }

        case AST_MATCH: {
            /* Match as chained ternary (simplified) */
            ASTNode *expr = node->as.match_expr.expr;
            emit(ctx, "/* match */ (");
            for (int i = 0; i < node->as.match_expr.arm_count; i++) {
                emit(ctx, "(");
                emit_expr(ctx, expr);
                emit(ctx, ".tag == %d) ? (", i);
                emit_expr(ctx, node->as.match_expr.arm_bodies[i]);
                emit(ctx, ") : ");
            }
            if (node->as.match_expr.arm_count > 0)
                emit(ctx, "(__builtin_unreachable(), (int64_t)0)");
            else
                emit(ctx, "0");
            emit(ctx, ")");
            break;
        }

        case AST_TUPLE_LITERAL: {
            /* Tuples as anonymous struct literal */
            ASTNode **elems = node->as.struct_literal.field_values; /* reuse field */
            int count = node->as.struct_literal.field_count;
            emit(ctx, "(nano_val_t[%d]){", count);
            for (int i = 0; i < count; i++) {
                if (i > 0) emit(ctx, ", ");
                emit(ctx, "{.i = (int64_t)(");
                emit_expr(ctx, elems[i]);
                emit(ctx, ")}");
            }
            emit(ctx, "}");
            break;
        }

        default:
            /* Fallback: emit statement form */
            emit(ctx, "/* unsupported-expr(%d) */0", (int)node->type);
            break;
    }
}

/* ── Emit statement ──────────────────────────────────────────────────── */

static void emit_node(CCtx *ctx, ASTNode *node) {
    if (!node) return;

    switch (node->type) {
        case AST_PROGRAM:
            for (int i = 0; i < node->as.program.count; i++)
                emit_node(ctx, node->as.program.items[i]);
            break;

        case AST_STRUCT_DEF: {
            if (node->as.struct_def.is_extern) break; /* skip extern decls */
            fprintf(ctx->out, "\ntypedef struct {\n");
            for (int i = 0; i < node->as.struct_def.field_count; i++) {
                const char *ft = c_type_name(node->as.struct_def.field_types[i],
                                             node->as.struct_def.field_type_names
                                                 ? node->as.struct_def.field_type_names[i]
                                                 : NULL);
                fprintf(ctx->out, "    %s %s;\n", ft, node->as.struct_def.field_names[i]);
            }
            fprintf(ctx->out, "} %s;\n", node->as.struct_def.name);
            break;
        }

        case AST_ENUM_DEF: {
            if (node->as.enum_def.is_extern) break;
            fprintf(ctx->out, "\ntypedef enum {\n");
            for (int i = 0; i < node->as.enum_def.variant_count; i++) {
                fprintf(ctx->out, "    %s_%s",
                        node->as.enum_def.name,
                        node->as.enum_def.variant_names[i]);
                if (node->as.enum_def.variant_values)
                    fprintf(ctx->out, " = %d", node->as.enum_def.variant_values[i]);
                fprintf(ctx->out, "%s\n", i + 1 < node->as.enum_def.variant_count ? "," : "");
            }
            fprintf(ctx->out, "} %s;\n", node->as.enum_def.name);
            break;
        }

        case AST_UNION_DEF: {
            if (node->as.union_def.is_extern) break;
            /* Tagged union: struct { int tag; union { ... } as; } */
            fprintf(ctx->out, "\ntypedef struct {\n    int tag;\n    union {\n");
            for (int i = 0; i < node->as.union_def.variant_count; i++) {
                int fc = node->as.union_def.variant_field_counts[i];
                if (fc == 0) continue;
                fprintf(ctx->out, "        struct {\n");
                for (int j = 0; j < fc; j++) {
                    const char *ft = c_type_name(node->as.union_def.variant_field_types[i][j],
                                                 node->as.union_def.variant_field_type_names
                                                     ? node->as.union_def.variant_field_type_names[i][j]
                                                     : NULL);
                    fprintf(ctx->out, "            %s %s;\n", ft,
                            node->as.union_def.variant_field_names[i][j]);
                }
                fprintf(ctx->out, "        } %s;\n", node->as.union_def.variant_names[i]);
            }
            fprintf(ctx->out, "    } as;\n} %s;\n", node->as.union_def.name);
            break;
        }

        case AST_FUNCTION: {
            if (node->as.function.is_extern) {
                /* Emit extern declaration only */
                const char *rt = c_type_name(node->as.function.return_type,
                                             node->as.function.return_struct_type_name);
                fprintf(ctx->out, "\nextern %s %s(", rt, node->as.function.name);
                for (int i = 0; i < node->as.function.param_count; i++) {
                    if (i > 0) fprintf(ctx->out, ", ");
                    const char *pt = c_type_name(node->as.function.params[i].type,
                                                  node->as.function.params[i].struct_type_name);
                    const char *pn = node->as.function.params[i].name;
                    fprintf(ctx->out, "%s %s", pt, pn ? pn : "_");
                }
                fprintf(ctx->out, ");\n");
                break;
            }

            const char *rt = c_type_name(node->as.function.return_type,
                                         node->as.function.return_struct_type_name);
            fprintf(ctx->out, "\n%s %s(", rt, node->as.function.name);
            for (int i = 0; i < node->as.function.param_count; i++) {
                if (i > 0) fprintf(ctx->out, ", ");
                const char *pt = c_type_name(node->as.function.params[i].type,
                                              node->as.function.params[i].struct_type_name);
                const char *pn = node->as.function.params[i].name;
                fprintf(ctx->out, "%s %s", pt, pn ? pn : "_");
            }
            fprintf(ctx->out, ") {\n");
            ctx->indent++;
            ctx->in_function = true;
            if (node->as.function.body)
                emit_node(ctx, node->as.function.body);
            ctx->in_function = false;
            ctx->indent--;
            fprintf(ctx->out, "}\n");
            break;
        }

        case AST_BLOCK:
            for (int i = 0; i < node->as.block.count; i++)
                emit_node(ctx, node->as.block.statements[i]);
            break;

        case AST_LET: {
            const char *ct = c_type_name(node->as.let.var_type, node->as.let.type_name);
            /* Use auto if type is unknown to let compiler infer */
            if (node->as.let.var_type == TYPE_UNKNOWN)
                ct = "__auto_type";
            iprintf(ctx, "%s %s", ct, node->as.let.name);
            if (node->as.let.value) {
                emit(ctx, " = ");
                emit_expr(ctx, node->as.let.value);
            }
            emit(ctx, ";\n");
            break;
        }

        case AST_SET:
            iprintf(ctx, "%s = ", node->as.set.name);
            emit_expr(ctx, node->as.set.value);
            emit(ctx, ";\n");
            break;

        case AST_RETURN:
            iprintf(ctx, "return");
            if (node->as.return_stmt.value) {
                emit(ctx, " ");
                emit_expr(ctx, node->as.return_stmt.value);
            }
            emit(ctx, ";\n");
            break;

        case AST_IF: {
            iprintf(ctx, "if (");
            emit_expr(ctx, node->as.if_stmt.condition);
            emit(ctx, ") {\n");
            ctx->indent++;
            if (node->as.if_stmt.then_branch)
                emit_node(ctx, node->as.if_stmt.then_branch);
            ctx->indent--;
            if (node->as.if_stmt.else_branch) {
                iprintf(ctx, "} else {\n");
                ctx->indent++;
                emit_node(ctx, node->as.if_stmt.else_branch);
                ctx->indent--;
            }
            iprintf(ctx, "}\n");
            break;
        }

        case AST_WHILE: {
            iprintf(ctx, "while (");
            emit_expr(ctx, node->as.while_stmt.condition);
            emit(ctx, ") {\n");
            ctx->indent++;
            if (node->as.while_stmt.body)
                emit_node(ctx, node->as.while_stmt.body);
            ctx->indent--;
            iprintf(ctx, "}\n");
            break;
        }

        case AST_FOR: {
            /* for var in range_expr { body } — emit as C for with counter */
            iprintf(ctx, "/* for %s in */ {\n", node->as.for_stmt.var_name);
            ctx->indent++;
            iprintf(ctx, "nano_array_t _nano_range_ = ");
            emit_expr(ctx, node->as.for_stmt.range_expr);
            emit(ctx, ";\n");
            iprintf(ctx, "for (int64_t _i_ = 0; _i_ < _nano_range_.len; _i_++) {\n");
            ctx->indent++;
            iprintf(ctx, "nano_val_t %s = ((nano_val_t*)_nano_range_.data)[_i_];\n",
                    node->as.for_stmt.var_name);
            if (node->as.for_stmt.body)
                emit_node(ctx, node->as.for_stmt.body);
            ctx->indent--;
            iprintf(ctx, "}\n");
            ctx->indent--;
            iprintf(ctx, "}\n");
            break;
        }

        case AST_PRINT: {
            iprintf(ctx, "printf(");
            if (node->as.print.is_println) {
                emit(ctx, "\"%%s\\n\", (const char*)(");
                emit_expr(ctx, node->as.print.expr);
                emit(ctx, ")");
            } else {
                emit(ctx, "\"%%s\", (const char*)(");
                emit_expr(ctx, node->as.print.expr);
                emit(ctx, ")");
            }
            emit(ctx, ");\n");
            break;
        }

        case AST_ASSERT:
            iprintf(ctx, "if (!(");
            emit_expr(ctx, node->as.assert.condition);
            emit(ctx, ")) { fprintf(stderr, \"assertion failed (line %d)\\n\"); __builtin_trap(); }\n",
                 node->line);
            break;

        case AST_IMPORT:
            /* Imports become comments in C output — types/functions must be linked externally */
            iprintf(ctx, "/* import \"%s\" */\n",
                    node->as.import_stmt.module_path ? node->as.import_stmt.module_path : "?");
            break;

        case AST_MODULE_DECL:
            iprintf(ctx, "/* module %s */\n",
                    node->as.module_decl.name ? node->as.module_decl.name : "?");
            break;

        default:
            /* For expression statements at top level */
            iprintf(ctx, "");
            emit_expr(ctx, node);
            emit(ctx, ";\n");
            break;
    }
}

/* ── Public API ─────────────────────────────────────────────────────────── */

int c_backend_emit_fp(ASTNode *root, FILE *out, const char *source_file, bool verbose) {
    if (!root || !out) return 1;

    CCtx ctx;
    cctx_init(&ctx, out, source_file, verbose);

    emit_preamble(&ctx);
    emit_node(&ctx, root);

    /* Emit main() stub if no main function was found */
    /* (detection would require a pre-pass — omit for now) */

    if (verbose)
        fprintf(stderr, "[c_backend] emitted C source from %s\n",
                source_file ? source_file : "<input>");

    return ctx.error ? 1 : 0;
}

int c_backend_emit(ASTNode *root, const char *output_path, const char *source_file, bool verbose) {
    FILE *out;
    bool close_out = false;

    if (output_path) {
        out = fopen(output_path, "w");
        if (!out) {
            fprintf(stderr, "[c_backend] cannot open output: %s\n", output_path);
            return 1;
        }
        close_out = true;
    } else {
        out = stdout;
    }

    int rc = c_backend_emit_fp(root, out, source_file, verbose);

    if (close_out) fclose(out);
    return rc;
}
