/* I expose counters only to my separately built diagnostic provider closure. */
#ifndef NANOLANG_EVALUATOR_TIMING_PRIVATE_H
#define NANOLANG_EVALUATOR_TIMING_PRIVATE_H
#ifdef NANO_EVALUATOR_LIFETIME_TIMING
#include <stdint.h>
enum NanoLifetimeCounter {
    LIFE_GRAPH_ALLOC, LIFE_CLONE_NODES, LIFE_CLONE_NS,
    LIFE_RETIREMENTS, LIFE_ROOTS, LIFE_LOOKUPS, LIFE_LOOKUP_HITS, LIFE_LOOKUP_NS,
    LIFE_INDEX_CALLS, LIFE_INDEX_PROBES, LIFE_INDEX_HITS,
    LIFE_VIEW_CALLS, LIFE_VIEW_NS, LIFE_VIEW_COPIES, LIFE_VIEW_WRAP_ALLOC,
    LIFE_CHECKED_METADATA_ALLOC, LIFE_LEGACY_METADATA_ALLOC,
    LIFE_LIST_CALLS, LIFE_LIST_VISITS, LIFE_LIST_HITS, LIFE_LIST_NS,
    LIFE_PUBLICATION_CALLS, LIFE_PUBLICATION_NS, LIFE_DISCARD_NODES, LIFE_DISCARD_NS,
    LIFE_SCOPE_EXPR_CALLS, LIFE_SCOPE_EXPR_NS,
    LIFE_SCOPE_STMT_CALLS, LIFE_SCOPE_STMT_NS,
    LIFE_SCOPE_CALL_CALLS, LIFE_SCOPE_CALL_NS,
    LIFE_SCOPE_NAMED_CALL_CALLS, LIFE_SCOPE_NAMED_CALL_NS,
    LIFE_SCOPE_RELEASE_CALLS, LIFE_SCOPE_RELEASE_NS,
    LIFE_SCOPE_FUNCTION_CALLS, LIFE_SCOPE_FUNCTION_NS,
    LIFE_SCOPE_SYMBOL_CALLS, LIFE_SCOPE_SYMBOL_NS,
    LIFE_SCOPE_VISIBLE_CALLS, LIFE_SCOPE_VISIBLE_NS,
    LIFE_SCOPE_DEFINE_CALLS, LIFE_SCOPE_DEFINE_NS,
    LIFE_SCOPE_SET_CALLS, LIFE_SCOPE_SET_NS,
    LIFE_SCOPE_SYNC_CALLS, LIFE_SCOPE_SYNC_NS,
    LIFE_SCOPE_OUTSIDE_NS,
    LIFE_COUNTER_COUNT
};
enum NanoLifetimeScope { SCOPE_EXPR, SCOPE_STMT, SCOPE_CALL, SCOPE_NAMED_CALL, SCOPE_RELEASE, SCOPE_FUNCTION, SCOPE_SYMBOL, SCOPE_VISIBLE, SCOPE_DEFINE, SCOPE_SET, SCOPE_SYNC, SCOPE_COUNT };
void nano_lifetime_scope_enter(enum NanoLifetimeScope);
void nano_lifetime_scope_exit(enum NanoLifetimeScope);
void nano_lifetime_add(enum NanoLifetimeCounter, uint64_t);
uint64_t nano_lifetime_now(void);
void nano_lifetime_elapsed(enum NanoLifetimeCounter, uint64_t);
void nano_evaluator_lifetime_marker(const char *, const char *);
#define LIFE_COUNT(counter) nano_lifetime_add(counter, 1)
#else
#define LIFE_COUNT(counter) ((void)0)
#endif
#endif
