#ifndef NL_NSI_BINDING_H
#define NL_NSI_BINDING_H
/* I share parsing limits and status codes, not service authority. */
#define NL_BINDING_MAX_BYTES 1048576u
#define NL_BINDING_MAX_TOKENS 8192u
#define NL_BINDING_MAX_DEPTH 64u
#define NL_BINDING_MAX_OBJECTS 256u
#define NL_BINDING_MAX_MEMBERS 64u
#define NL_BINDING_MAX_ELEMENTS 256u
#define NL_BINDING_MAX_LEXEME 4096u
#define NL_BINDING_MAX_ALLOCATION 16777216u

typedef enum {
    NL_BINDING_OK, NL_BINDING_INVALID, NL_BINDING_LIMIT,
    NL_BINDING_MEMORY, NL_BINDING_UNRESOLVED,
    NL_BINDING_IO, NL_BINDING_EXISTS, NL_BINDING_UNSUPPORTED
} NlBindingStatus;

#endif
