#ifndef NANOLANG_VERSION_H
#define NANOLANG_VERSION_H

#define NANOLANG_VERSION_MAJOR 5
#define NANOLANG_VERSION_MINOR 0
#define NANOLANG_VERSION_PATCH 1
#define NANOLANG_VERSION_SUFFIX ""

#define NANOLANG_VERSION "5.0.1"
#define NANOLANG_BUILD_DATE __DATE__
#define NANOLANG_BUILD_TIME __TIME__

#endif /* NANOLANG_VERSION_H */
